### ISSUE TITLE
同步时间间隔以及是否同步admin表

### ISSUE THREAD

**Issue by Roarain** [alibaba/MongoShake#10]
在测试过程中又两个疑惑。
1：src端在admin上createUser，src的oplog中有记录，但是没有同步到dst端，是否因为mongoshake不同步admin DB？

2：src到dst的oplog传输间隔。参数checkpoint.interval = 20还是batch_size控制。
根据bin/mongoshake-stat --port=9100获取到的数据，大概是凑够255条数据在dst端统一应用oplog。能否设置成3秒同步一次，无论是否到255条数据

Contributor的回答：
1：admin表不同步
2：checkpoint.interval单位是ms，默认5000ms也就是5s。也就是说最小的同步checkpoint是5s。batch数据是批量传送的，存在缓存机制，batch数据传送后才会触发刷新操作。目前没法做到固定时间刷一次。

**Comment by shiftyman** [comment]
”大概是凑够255条数据在dst端统一应用oplog”是什么意思？ shake在源处获取到255条oplog才会应用到目标？否则一直等待？不会延迟太久吗？

**Comment by vinllen** [comment]
这个机制在1.4.3中已经修改
