### ISSUE TITLE
为什么我的mongoshake同步这么慢？

### ISSUE THREAD

**Issue by julyxiong** [alibaba/MongoShake#102]
环境如下：
1，mongoshake部署在mongodb副本集的服务器上。
2，服务器是32核的，内存64G，mongod占用40G。
3，运行collector后，collector占用虚拟内存7G多，实际内存一致保持3G。
4，源库实例中，有140多个数据库。

mongoshake配置：
1，版本 1.4.5
2，配置文件参数除了黑名单，源库，目标库设置外，其他都为默认选项。
3，黑名单设置了43个 库.表，  1个库

collector部分日志如下：
![2](https://user-images.githubusercontent.com/32185365/50532655-3b82d100-0b57-11e9-9027-500f60a1b27b.png)

![3](https://user-images.githubusercontent.com/32185365/50532657-40e01b80-0b57-11e9-8577-74f42352f5bc.png)

mongo-state输出：
![1](https://user-images.githubusercontent.com/32185365/50532617-e0e97500-0b56-11e9-8659-17959df5f23a.png)

**Comment by vinllen** [comment]
同步变慢有很多原因
1. 源mongodb写入qps有多少？同步不上导致存量lag在慢慢变大？
2. 你把黑白名单放开，看看qps有多少
3. 源端读性能排查一下
4. 目的端写入性能排查一下，也可能是目的端写入瓶颈导致同步变慢。
5. 如果以上都没问题，shake有提供[pprof接口](https://github.com/aliyun/mongo-shake/wiki/FAQ#q-how-to-monitor-the-mongoshake)，深度定位一下

**Comment by vinllen** [comment]
https://github.com/aliyun/mongo-shake/wiki/FAQ#q-how-to-debug-the-mongoshake

**Comment by vinllen** [comment]
如果没有反馈，这个问题我先关了，如果有问题再进行reopen.

**Comment by vinllen** [comment]
可能还是有一个问题导致，参考：https://github.com/alibaba/MongoShake/issues/150
