### ISSUE TITLE
logs_get logs_repl logs_success

### ISSUE THREAD

**Issue by xzshinan** [alibaba/MongoShake#106]
mongo-shake 版本，使用的当前的master分支.

配置：
除了变更 源库、目标库、监控的port、增加了黑名单 以及 修改了context.start_position的时间。
别的都是默认配置

问题：
![2 pic](https://user-images.githubusercontent.com/7299894/51819619-090ef400-230e-11e9-8e53-de00a89b090f.jpg)

总是  logs_get  先拿到，貌似并没有及时  logs_repl

logs_repl  以及 logs_success  总会延迟个 两分钟以内。然后一次接受前面的logs_get。

我的理解是  等了个 时间周期 一起 logs_repl ？是 queue处理的时间么？

另外ps: 求问是否有命令可以查看当前mongo-shake的版本~~

**Comment by vinllen** [comment]
版本多少？在1.4后续的版本应该是修改了这个缓存策略

**Comment by vinllen** [comment]
你自己测试也是写一条同步延迟很大？

**Comment by xzshinan** [comment]
> 版本多少？在1.4后续的版本应该是修改了这个缓存策略

呃，当时build的时候没留意。上周五down的master的分支。应该是最新版本吧

**Comment by vinllen** [comment]
再build下不就看到了

**Comment by xzshinan** [comment]
> 再build下不就看到了

[ BUILD RELEASE ]
Build collector
master,b77b21e19f4cf465d1eed9d9775df4168d63c80c,release,go1.11,2019-01-28_16:40:07
Build receiver
master,b77b21e19f4cf465d1eed9d9775df4168d63c80c,release,go1.11,2019-01-28_16:40:07



> 你自己测试也是写一条同步延迟很大？

是的，延迟很大。

**Comment by xzshinan** [comment]
> 贴下配置文件

# connect source mongodb, set username and password if enable authority.
# split by comma(,) if use multiple instance in one replica-set.
# split by semicolon(;) if sharding enable.
mongo_urls = mongodb://***:***@***:***

# collector name
collector.id = mongoshake-beijing

# save checkpoint interval if necessary. 
# the checkpoint will be checked and stored after starting 3 minutes.
checkpoint.interval = 5000

# http api interface. Users can use this api to monitor mongoshake.
# We also provide a restful tool named "mongoshake-stat" to 
# print ack, lsn, checkpoint and qps information based on this api.
# usage: `./mongoshake-stat --port=9100`
http_profile = ***
# profiling on net/http/profile
system_profile = ***


# global log level. lower level message
# will be filter
log_level = info
# log file name. use logs/ prefix folder path
log_file = collector-beijing.log
# log buffer or unbuffer. If set true, logs may not be print when exit. If
# set false, performance will be decreased extremely
log_buffer = true


# filter db or collection namespace. at most one of these two parameters can be given.
# if the filter.namespace.black is not empty, the given namespace will be
# filtered while others namespace passed. 
# if the filter.namespace.white is not empty, the given namespace will be
# passed while others filtered. 
# all the namespace will be passed if no condition given.
# db and collection connected by the dot(.).
# different namespaces are splitted by the semicolon(;).
filter.namespace.black = **;**
filter.namespace.white = 

# this parameter is not supported in current opensouce version.
# oplog namespace and global id. others oplog in 
# mongo cluster that has distinct global id will 
# be discard. Query without gid (means getting all
# oplog out) if no oplog.gid set
oplog.gids =   


# [auto] 		decide by if there has uniq index in collections. 
# 		 		use `collection` with uniqu index set otherwise `id`
# [id] 			shard by ObjectId. handle oplogs in sequence by unique _id 
# [collection] 	shard by ns. handle oplogs in sequence by unique ns 
shard_key = auto


# syncer send time interval, unit is second.
# time interval of flushing the syncer reader buffer.
syncer.reader.buffer_time = 3


# oplog transmit worker concurrent
worker = 8
# memory queue configuration, plz visit FAQ document to see more details.
# do not modify these variables if the performance and resource usage can
# meet your needs.
worker.batch_queue_size = 64
adaptive.batching_max_size = 16384
fetcher.buffer_capacity = 256

# batched oplogs have block level checksum value using 
# crc32 algorithm. and compressor for compressing content
# of oplog entry. 
# supported compressor are : gzip,zlib,deflate
# Do not enable this option when tunnel type is "direct"
worker.oplog_compressor = none


# tunnel pipeline type. now we support rpc,file,kafka,mock,direct
tunnel = direct
# tunnel target resource url
# for rpc. this is remote receiver socket address
# for tcp. this is remote receiver socket address
# for file. this is the file path, for instance "data"
# for kafka. this is the topic and brokers address which split by comma, for
# instance: topic@brokers1,brokers2, default topic is "mongoshake"
# for mock. this is uesless
# for direct. this is target mongodb address
tunnel.address = mongodb://***:***@***:***



# collector context storage mainly including store checkpoint
# type include : database, api
# for api storage, address is http url
# for database storage, address is collection name while db name is "mongoshake" by default.
# if source database is replica, context will store in the source mongodb.
# if source database is sharding, context must be given to point the config server address.
# context.storage.url is only used in sharding. When source mongodb type is replicaSet, 
# checkpoint will write into source mongodb as default.
context.storage = database
#context.storage.url = mongodb://127.0.0.1:20070
context.address = ckpt_default
# pay attention: this is UTC time which is 8 hours latter than CST time. this 
# variable will only be used when checkpoint is not exist.
context.start_position = 2019-01-27T08:19:01Z


# high availabity option.
# enable master election if set true. only one mongoshake can become master
# and do sync, the others will wait and at most one of them become master once 
# previous master die. The master information stores in the `mongoshake` db in the source 
# database by default.
# This option is useless when there is only one mongoshake running.
master_quorum = false


# ----------------------splitter----------------------
# if tunnel type is direct, all the below variable should be set

# only transfer oplog commands for syncing. represent
# by oplog.op are "i","d","u". also include applyOps
replayer.dml_only = true

# executors in single worker
replayer.executor = 1

# oplog changes to Insert while Update found non-exist (_id or unique-index)
replayer.executor.upsert = false
# oplog changes to Update while Insert found duplicated key (_id or unique-index)
replayer.executor.insert_on_dup_update = false
# db. write duplicated logs to mongoshake_conflict
# sdk. write duplicated logs to sdk.
replayer.conflict_write_to = none

# replayer duration mode. drop oplogs and take
# no any action(only for debugging enviroment) if 
# set to false. otherwise write to ${mongo_url} instance
replayer.durable = true

**Comment by vinllen** [comment]
这个问题需要进一步定位下，最近有点忙，有空我看下。

**Comment by xzshinan** [comment]
> 这个问题需要进一步定位下，最近有点忙，有空我看下。

好的~ tks~~

**Comment by vinllen** [comment]
协助定位下问题吧，你写入一条消息后，打印这个metric看看是多少。
`curl 127.0.0.1:9100/worker | python -m json.tool | grep jobs_in_queue`
另外，是不是开了啥限速？
`curl 127.0.0.1:9100/sentinel`

**Comment by vinllen** [comment]
完了把操作时间久的日志也发我下吧

**Comment by vinllen** [comment]
拉develop或者feature-1.4分支吧

**Comment by vinllen** [comment]
尝试一下把shake部署到离目的mongodb近一些

**Comment by vinllen** [comment]
@xzshinan 这个问题现在怎么样了？

**Comment by vinllen** [comment]
这个问题先行关闭，如果后续还有同样的问题请再打开
