### ISSUE TITLE
pymongo.errors.ServerSelectionTimeoutError: admin:27017: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by supersujj** [alibaba/MongoShake#107]
when used comparision.py it issue error:pymongo.errors.ServerSelectionTimeoutError: admin:27017: [Errno -2] Name or service not known

my command is :
python comparision.py --src="mongodb://admin/password@IP:27021/admin" --dest=mongodb://sync:password@IP:27017/admin  --count=1000  --excludeDbs=admin,local  --excludeCollections=system.profile      

what is wrong?

**Comment by vinllen** [comment]
Can you log in your MongoDB with these two URLs?

**Comment by supersujj** [comment]
yes,i use these two urls sync normal.

**Comment by supersujj** [comment]
this format is it correct?

**Comment by vinllen** [comment]
The URL format is "mongodb://username:password@ip:port/auth_db"

**Comment by supersujj** [comment]
yes，is it must add double quotation marks？

**Comment by supersujj** [comment]
#python mongodb-schema.py --src=mongodb://admin/password@IP:27021/admin --dest=mongodb://sync:password@IP:27017/admin --excludeDbs=admin,local --excludeCollections=system.profile
INFO  [2019-02-21 09:46:17] configuration : excludeDbs=['admin', 'local', 'admin', 'local'], excludeColls=['system.profile', 'system.profile'] 
Traceback (most recent call last):
  File "mongodb-schema.py", line 179, in <module>
    if check(src, dst):
  File "mongodb-schema.py", line 68, in check
    srcDbNames = src.conn.database_names()
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 1493, in list_database_names
    for doc in self.list_databases(session, nameOnly=True)]
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 1473, in list_databases
    "admin").command(cmd, session=session)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 529, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 979, in _socket_for_reads
    server = topology.select_server(read_preference)
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 224, in select_server
    address))
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: admin:27017: [Errno -2] Name or service not known

**Comment by vinllen** [comment]
the source URL looks incorrect: "admin/password". plz check again

**Comment by supersujj** [comment]
# mongo 192.168.XXX.XX:27021/admin -uadmin -p
MongoDB shell version v3.4.9
Enter password: 
connecting to: mongodb://192.168.XXX.XX:27021/admin
MongoDB server version: 3.4.9
shard1_zxl:SECONDARY> rs.status()
{
        "set" : "shard1_zxl",
        "date" : ISODate("2019-02-22T01:20:22.067Z"),
        "myState" : 2,
        "term" : NumberLong(56),
        "syncingTo" : "192.168.XXX.XX:27021",
        "heartbeatIntervalMillis" : NumberLong(2000),
        "optimes" : {
                "lastCommittedOpTime" : {
                        "ts" : Timestamp(1550798392, 6),
                        "t" : NumberLong(56)
                },
                "appliedOpTime" : {
                        "ts" : Timestamp(1550798392, 12),
                        "t" : NumberLong(56)
                },
                "durableOpTime" : {
                        "ts" : Timestamp(1550798392, 12),
                        "t" : NumberLong(56)
                }
        },
        "members" : [
                {
                        "_id" : 7,
                        "name" : "192.168.XXX.XX:27021",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 4274515,
                        "optime" : {
                                "ts" : Timestamp(1550798392, 12),
                                "t" : NumberLong(56)
                        },
                        "optimeDate" : ISODate("2019-02-22T01:19:52Z"),
                        "syncingTo" : "192.168..XXX.XX:27021",
                        "configVersion" : 18,
                        "self" : true
                },
                {
                        "_id" : 9,
                        "name" : "192.168.XXX.XX:27030",
                        "health" : 1,
                        "state" : 7,
                        "stateStr" : "ARBITER",
                        "uptime" : 4274498,
                        "lastHeartbeat" : ISODate("2019-02-22T01:20:20.230Z"),
                        "lastHeartbeatRecv" : ISODate("2019-02-22T01:20:20.006Z"),
                        "pingMs" : NumberLong(0),
                        "configVersion" : 18
                },
                {
                        "_id" : 10,
                        "name" : "192.168.XXX.XX:27021",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 4274498,
                        "optime" : {
                                "ts" : Timestamp(1550798390, 25),
                                "t" : NumberLong(56)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(1550798390, 23),
                                "t" : NumberLong(56)
                        },
                        "optimeDate" : ISODate("2019-02-22T01:19:50Z"),
                        "optimeDurableDate" : ISODate("2019-02-22T01:19:50Z"),
                        "lastHeartbeat" : ISODate("2019-02-22T01:20:20.452Z"),
                        "lastHeartbeatRecv" : ISODate("2019-02-22T01:20:20.224Z"),
                        "pingMs" : NumberLong(0),
                        "electionTime" : Timestamp(1527560523, 1),
                        "electionDate" : ISODate("2018-05-29T02:22:03Z"),
                        "configVersion" : 18
                }
        ],
        "ok" : 1
}

**Comment by vinllen** [comment]
is this problem solved?
