### ISSUE TITLE
从配置的时间点来同步，不想按checkpoint，应该怎么配?

### ISSUE THREAD

**Issue by rickicui** [alibaba/MongoShake#121]
关于context.start_position配置项的说明
# pay attention: this is UTC time which is 8 hours latter than CST time. this
# variable will only be used when checkpoint is not exist.

我现在想从配置的时间点来同步，不想从checkpoint来同步，应该怎么配？

**Comment by vinllen** [comment]
请参考这个：
https://github.com/alibaba/MongoShake/wiki/FAQ#q-how-can-i-configure-checkpoint
https://github.com/alibaba/MongoShake/wiki/FAQ#q-if-i-both-have-the-checkpointstores-in-mongoshakeckpt_default-by-default-and-contextstart_position-which-one-will-be-used
删除源端的checkpoint即可。
