### ISSUE TITLE
[BSONObj size: 41789902 (0x27DA9CE) is invalid

### ISSUE THREAD

**Issue by lynch0227** [alibaba/MongoShake#122]
Today we meet the below error message:
[2019/04/12 10:20:27 CST] [CRIT] [executor.(*Executor).execute:109] Replayer-3, executor-3, oplog for [recurrent_voice.file.chunks] op[i] failed. (*mgo.BulkError) [BSONObj size: 41789902 (0x27DA9CE) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "file.chunks"], logs 160. firstLog &{6678590951763476484 i  xxxx.file.chunks map[_id:ObjectIdHex("5caf1f168a5da5000125816e") data:[................]

Here is the collector.conf:
mongo_urls = mongodb://user:pwd@xx.xx.xx.xx:27017
collector.id = mongoshake
checkpoint.interval = 5000
http_profile = 9100
system_profile = 9200
log_level = WARN
log_file = collector.log
log_buffer = true
filter.namespace.black = 
filter.namespace.white =
oplog.gids =   
shard_key = auto
syncer.reader.buffer_time = 3
worker = 8
worker.batch_queue_size = 64
adaptive.batching_max_size = 16384
fetcher.buffer_capacity = 256
worker.oplog_compressor = none
tunnel = direct
tunnel.address = mongodb://user:pwd@xx.xx.xx.xx:27017/db
context.storage = database
context.address = ckpt
context.start_position = 2019-04-11T11:00:00Z
master_quorum = false
replayer.dml_only = true
replayer.executor = 1
replayer.executor.upsert = true
replayer.executor.insert_on_dup_update = true
replayer.conflict_write_to = none
replayer.durable = true

**Comment by vinllen** [comment]
this is a bug that `shake` gathers too much oplogs so that overpass the 16 MB threshold.
please checkout v1.4.6(the binaries aren't the newest, you should rebuild it yourself).

**Comment by vinllen** [comment]
@lynch0227 贴一下最新的Log，报错的那条

**Comment by vinllen** [comment]
v2.0.4 fixes this issue, plan to release before 7.22
