### ISSUE TITLE
关于mongo_urls 分片如何配置

### ISSUE THREAD

**Issue by GuoWei2019** [alibaba/MongoShake#124]
bugfix-1.4.6 配置mongo_urls 多个分片 分好分割报错如下:
Conf.Options check failed: storage server should be configured while mongo shard servers

**Comment by vinllen** [comment]
请仔细看下配置文件的说明，关于context的部分，需要配置context.storage.url

**Comment by GuoWei2019** [comment]
是不是这样子配置？
mongo_urls = mongodb://127.0.0.1:27001,127.0.0.2:27001;127.0.0.1:27002,127.0.0.2:27002

**Comment by GuoWei2019** [comment]
> 请仔细看下配置文件的说明，关于上下文的部分，需要配置context.storage.url

是不是这样子配置？
mongo_urls = mongodb：//127.0.0.1：27001,127.0.0.2：27001; 127.0.0.1：27002,127.0.0.2：27002

**Comment by vinllen** [comment]
哥，我说了是context.storage.url

**Comment by GuoWei2019** [comment]
> 哥，我说了是context.storage.url

大哥，context.storage.url=mongodb：//127.0.0.1：27001,127.0.0.2：27001; 127.0.0.1:27002,127.0.0.2:27002    也还是不行

**Comment by vinllen** [comment]
你配的是cs吗

**Comment by GuoWei2019** [comment]
> 你配的是cs吗
配置分片mongodb
增加配置context.storage.url后报如下错误
Conf.Options check failed: storage server should not be configured while single mongo server

**Comment by vinllen** [comment]
context.storage.url这个只有在源端是sharding的时候才配置的，你这个mongo_url明显不是shard
