### ISSUE TITLE
对比脚本开发

### ISSUE THREAD

**Issue by vinllen** [alibaba/MongoShake#130]
对比两端mongodb的数据是否位于一致状态，初期可以采用全量对比，后续增加增量对比，目前script目录下面的comparison.py脚本没办法进行精准校验。
大家谁有精力的可以帮助开发，在comparison.py脚本基础上进行改进。

**Comment by cocoakekeyu** [comment]
这个脚本是独立于 MongoShake 运行的，一次全量对比可以，增量对比的化需要增加 start_position 的参数。 不如直接接收 MongoShake 的配置文件？

**Comment by vinllen** [comment]
增量对比开发成本比较高，此需要暂时延期
