### ISSUE TITLE
如何配置collector的内存

### ISSUE THREAD

**Issue by zeusYi** [alibaba/MongoShake#136]
目前collector.conf 参数文件中只配置了以一个worker:
# executors in single worker
replayer.executor = 1

但是启动了collector进程以后，发现内存耗尽，并且top load负载达到70，cpus=2，请问怎么优化配置？

**Comment by vinllen** [comment]
你这个不是worker，有个专门worker的参数，可以调小一些worker = xxx，另外以下三个参数也可以适当调小：
worker.batch_queue_size = 64
adaptive.batching_max_size = 16384
fetcher.buffer_capacity = 256

**Comment by vinllen** [comment]
参考一下这个wiki：https://github.com/alibaba/MongoShake/wiki/FAQ#q-mongoshake-crashed-because-of-oomout-of-memory-how-can-i-estimate-memory-usage
