### ISSUE TITLE
kafka 生产的数据是乱码是什么原因导致的

### ISSUE THREAD

**Issue by newluhuibiao** [alibaba/MongoShake#138]

**Comment by vinllen** [comment]
kafka中的数据是有控制信息在里面的，需要进行剥离。可以用receiver：
https://github.com/alibaba/MongoShake/wiki/FAQ#q-how-to-connect-to-different-tunnel-except-direct

**Comment by newluhuibiao** [comment]
下面哪个参数是用来剥离kafka  控制信息的？
# global log level. lower level message
# will be filter
log_level = info
# log file name. use logs/ prefix folder path
log_file = reeciver.log
# log buffer or unbuffer. If set true, logs may not be print when exit. If
# set false, performance will be decreased
log_buffer = true


# profiling on net/http/profile
system_profile = 9500


# tunnel pipeline type. now we support rpc,tcp,file,mock,kafka
tunnel = rpc
# tunnel target resource url
# for rpc. this is receiver socket address
# for tcp. this is receiver socket address
# for file. this is the file path, for instance "data"
# for mock. this is useless. mongoshake will generate random data including "i", "d", "u", "n"
# for kafka. this is the topic and brokers address which split by comma, for
# instance: topic@brokers1,brokers2, default topic is "mongoshake"
tunnel.address = 127.0.0.1:30033


# replayer worker concurrency. must equal to the collector worker number
replayer = 8

**Comment by vinllen** [comment]
剥离不了，控制信息是必须带的。你看下我上面发你的wiki文档，启动receiver进行读取就会剥离

**Comment by newluhuibiao** [comment]
那现在乱码怎么处理。改源码嘛。

**Comment by vinllen** [comment]
请仔细阅读我上面的回复和文档

**Comment by newluhuibiao** [comment]
好的。我试试。

**Comment by zlklink** [comment]
兄弟  你使用kafka结果如何？

**Comment by zlklink** [comment]
我也遇到了同样的问题  目前不知道怎么解决
