### ISSUE TITLE
Mongo shake 新版本中全量同步怎么设计的   能透露下吗   ？  

### ISSUE THREAD

**Issue by himura-kenshin** [alibaba/MongoShake#139]
全量数据抓取和 增量同步 怎么衔接呢？
把全量数据做更新 然后 写入oplog 吗

**Comment by vinllen** [comment]
全量数据按snapshot拉取，并记录拉取位点，后续增量在这个位点基础上增量oplog同步。具体的实现内部细节可以参考[这个pr](https://github.com/alibaba/MongoShake/pull/133)

**Comment by himura-kenshin** [comment]
mongodb有全局一致性快照吗 ？ 不太理解   利用的是 oplog的位点吗 ?
我们在搞MySQL这块功能的时候用过两种方案
1、从节点加全局读锁阻塞更新 记录binlog位点 在从节点进行全量同步，全量同步结束 后 释放锁 通过binlog 进行增量部分同步
2、全量数据执行变更操作（实际上不改变值得内容），记录到临时表中  通过binlog同步  到目标端解析binlog的时候  应用到 原表

**Comment by vinllen** [comment]
@lydarkforest 回答一下吧

**Comment by vinllen** [comment]
拉的时候是按表拉的，所以打的是表级别的快照，由于mongodb本身oplog幂等，所以不同表的位点不一致，采用统一的位点往前拉一点问题不大，如果这个很短的时间窗口内（往前拉的一点到真实的位点之间）操作了ddl，那么需要报错退出
