### ISSUE TITLE
在哪个版本可以实现mongodb全量加增量同步？这个有计划吗？

### ISSUE THREAD

**Issue by wwwwwwchun** [alibaba/MongoShake#140]
您好，咱们现在有没有规划在哪个版本可以实现全量加增量的同步的方式？方便透露一下吗？谢谢啦

**Comment by vinllen** [comment]
feature-1.5版本会进行支持，目前分支已经出来了，但是我们还在持续测试中。

**Comment by vinllen** [comment]
请关注：https://github.com/alibaba/MongoShake/issues/120
