### ISSUE TITLE
"bson.Unmarshal(raw, &oplogs[i])" is  invalid in replayer.go

### ISSUE THREAD

**Issue by marknewmail** [alibaba/MongoShake#142]
line:"bson.Unmarshal(raw, &oplogs[i])"  at   "ExampleReplayer.handle" in replayer.go 
will raise "Document is corrupted" error
er.Ack  will return timestamp 0 to server,if set  AckRequired=true in tcp/rpc channel,this could result in a loss of data

**Comment by vinllen** [comment]
Did you modify the replayer code? Please show me the code if so.
Please add the detailed error log information.

**Comment by marknewmail** [comment]
only add catch error info code
err:=bson.Unmarshal(raw, &oplogs[i])
if err!=nil{
        LOG.Error("bson.Unmarshal:",err)
}
the original error message is:
[2019/05/05 09:54:32 CST] [EROR] [receiver.(*ExampleReplayer).handler:123] bson.Unmarshal:%!(EXTRA string=Document is corrupted)

**Comment by vinllen** [comment]
It looks like the input oplog is broken, which tunnel type do you use? Kafka? 
Under normal circumstances, this is unlikely to happen.
If you are free, please contacts me in WeChat so we can better focus on this question.

**Comment by marknewmail** [comment]
tcp or rpc

**Comment by vinllen** [comment]
You can try to print the raw log and compare the field to the [bson spec](http://bsonspec.org/spec.html) to find the reason that oplog is corrupt

**Comment by vinllen** [comment]
This is a problem introduced by the user himself that modify the source code.
