### ISSUE TITLE
Questions about a two way sync of mongodb between two instances

### ISSUE THREAD

**Issue by mymmoonoa** [alibaba/MongoShake#147]
想实现 a two way sync of mongodb between two instances in different DC. 由于时间等原因使用了类似multi-master的模式，没用sharded database模式。(https://www.mongodb.com/blog/post/active-active-application-architectures-with-mongodb)

所以需要借助像MongoShake, mongo-connector这样的Tool

我看到https://github.com/alibaba/MongoShake/issues/93 里说 ` can't keep a collection in sync if I make changes on both servers to this collection?` 是指两边的数据库都修改了同一个collction的情况下，就没法sync的意思吗？我们两边的DataCenter都会有app不断地往local的mongo写数据，这样肯定会出现大家在write相同的collection，但是write的内容能保证不一样。这种情况能用mongoshake吗？

**Comment by vinllen** [comment]
这里我只是给了一个例子，介绍可以怎么进行双写。双活需要面临的两个问题：

1. 数据双写
2. 数据环形复制。

对于双写问题，主要问题在于复制通道是异步的，如果同时对一条数据进行操作，如何保证最终一致性。两边的数据不一致。如果可以避免这种双写同个key的操作，那么双写是没有问题的。但是数据环形复制问题还是避免不了。

**Comment by mymmoonoa** [comment]
> 这里我只是给了一个例子，介绍可以怎么进行双写。双活需要面临的两个问题：
> 
> 1. 数据双写
> 2. 数据环形复制。
> 
> 对于双写问题，主要问题在于复制通道是异步的，如果同时对一条数据进行操作，如何保证最终一致性。两边的数据不一致。如果可以避免这种双写同个key的操作，那么双写是没有问题的。但是数据环形复制问题还是避免不了。

谢谢提示
