### ISSUE TITLE
我看使用介绍说1.5版本支持全量+增量同步，所以我想知道我的版本是哪个版本，该怎么查，

### ISSUE THREAD

**Issue by 15029836736** [alibaba/MongoShake#148]
RT，直接在github上clone的代码，分支是refs/heads/develop。 求大神，问题比较愚蠢，还请见笑哈

**Comment by vinllen** [comment]
有个-version参数可以查看版本号：`./collector -version`。

另外，目前1.5版本还没有正式发布，对于表过滤、重启后位点的衔接等一些功能考虑不完备。但整体功能目前是可以用的。

**Comment by 15029836736** [comment]
好的大神。1.5版本有计划什么时候正式发布吗

**Comment by vinllen** [comment]
人力问题，现在还不能敲定，请关注。

**Comment by Dushibing** [comment]
Now, you should place the completed version 1.5  is your first KPI now, please complete it ASAP, for most user, if you don't provide the full+cdc data migration, the tool doesn't have wide use situation.

**Comment by vinllen** [comment]
@Dushibing thx for your advice, this version is coming soon.

**Comment by vinllen** [comment]
v2.0 is released
