### ISSUE TITLE
[Found $id field without a $ref before it, which is invalid.]

### ISSUE THREAD

**Issue by ChenNengNeng** [alibaba/MongoShake#149]
mongoshake使用direct模式
mongshake版本：1.4.4
mongodb源版本：RDS For mongodb 3.4
mongodb目标版本：mongodb 3.4.18
首先使用mongodump导出源库数据，然后在目标库mongorestore恢复数据。恢复后开启mongoshake进行实时同步，同步时出现以下错误。

错误日志：
[14:26:56 CST 2019/05/17] [CRIT] (mongoshake/executor.(*Executor).execute:109) Replayer-5, executor-5, oplog for [bbd.usdc] op[i] failed. (*errors.errorString) [doUpdateOn
Insert run upsert/update[true] failed[Found $id field without a $ref before it, which is invalid.]], logs 1. firstLog &{6688440192241500196 i  bbd.usdc map[createdTime:155
7273835 deletedTime:0 userId:5281c476 enable:true click:false updatedTime:1557273835 version:0 advertisementDO:map[$ref:advertisement $id:ObjectIdHex("5cc80c2e0afc45
420757c39b")] _id:ObjectIdHex("5cd21ceb0afc4572976d30fe") _class:com.tzx.sp.sz.ea.zweas] map[] map[] map[] 0 0}

mongoshake配置：
mongo_urls = mongodb://test:123456@dds-x.mongodb.rds.aliyuncs.com:3717/test
collector.id = mongoshake
checkpoint.interval = 5000
http_profile = 9100
system_profile = 9200
log_level = info
log_file = collector.log
log_buffer = true
filter.namespace.black =
filter.namespace.white = 
oplog.gids =   
shard_key = auto
syncer.reader.buffer_time = 3
worker = 8
worker.batch_queue_size = 64
adaptive.batching_max_size = 16384
fetcher.buffer_capacity = 256
worker.oplog_compressor = none
tunnel = direct
tunnel.address = mongodb://t:123456@192.168.1.1:27017/admin?replicaSet=rs0
context.storage = database
context.address = ckpt_default
context.start_position = 2019-05-08T00:00:01Z
master_quorum = true
replayer.dml_only = true
replayer.executor = 1
replayer.executor.upsert = true
replayer.executor.insert_on_dup_update = true
replayer.conflict_write_to = none
replayer.durable = true

**Comment by vinllen** [comment]
advertisement表中$id:ObjectIdHex("5cc80c2e0afc45420757c39b")这条文档存在吗？

https://jira.mongodb.org/browse/SERVER-14024

增量开始同步的位点需要小于等于全量开始的位点。

**Comment by ChenNengNeng** [comment]
在表中通过db.advertisement.find({"_id": ObjectId("5cc80c2e0afc45420757c39b")})查找数据是存在的。
 数据导出开始时间是2019-05-08 16:00 之后，所以我设置context.start_position = 2019-05-08T00:00:01Z 这样是否可行？

**Comment by ChenNengNeng** [comment]
源库版本号：MongoDB server version: 3.4.6

**Comment by ChenNengNeng** [comment]
源库权限为：mongoshake库可读写，local库可读。其他库无权限。

**Comment by vinllen** [comment]
你看看报错这条语句是否可以手动update插入:
`db.xxx.update({query}, {update}, {"upsert": true})`
目的库中间操作过写入吗？理论上全量操作后进行增量拉取不应该会有这个
`replayer.executor.upsert`和`replayer.executor.insert_on_dup_update`参数的启用是因为一开始报错导致的？

**Comment by ChenNengNeng** [comment]
尝试手动update插入是成功的。
目标库在准备完成后修改过admin库用户信息，删除过local库。
replayer.executor.upsert和replayer.executor.insert_on_dup_update，开启这两个参数前就出现了同样的问题，所以尝试开启，结果还是有问题。

我排查了源库和目标库的oplog，发现mongshake没有按照源库的oplog顺序执行。
过程如下：

在源库种找到某条失败的记录，找到oplog，有1条insert，3条update记录。
数据中有一个version字段，会在每次数据更新时自增
按照记录ts字段排序：version的值分别为0,1,2,3
version 为0的记录是一条insert记录

同样在目标库中查找记录，找到9条update记录。
因为开启了replayer.executor.upsert = true，所以源库的一条insert变为了update
按照记录ts字段排序：version的值分别为1,2,0,1,3,0,1,2,3
目标库对比源库oplog的执行顺序发生变化，且存在多次执行的情况

怀疑$ref中关联表的数据是在update之后写入的，所以导致报了Found $id field without a $ref before it, which is invalid.异常。

检查了源库和目标库中的最终数据是一致的

**Comment by vinllen** [comment]
由于多表并发操作，而$ref涉及跨表协同，所以此处是一个bug。
解决方式需要类似1.5分支中DDL卡全局barrier的操作：一旦发现$ref语句，且引用的语句在当前batcher内出现，则对batcher进行拆分。对于编码的代价需要记录出现的_id以及对$ref的过滤，对于性能的代价是如果$ref频繁出现对同步性能会有一定的降低。但考虑到目的shake同步性能很高，此部分目前可控。
该部分修改在目前1.4分支下不好操作，请等待2.0分支。

**Comment by vinllen** [comment]
这个问题应该不是$ref引用的不存在，而是因为写入的mgo driver中的bson.M没有控制顺序 导致$ref可能在$id之前。而$ref相关的语句是有顺序要求的：$ref, $id, $db这顺序。
另外，帮忙确认下是否有”Duplicated document found. reinsert or update to “相关日志

```
rszz-0:PRIMARY> db.zzz.update({"b":7}, {"b": 7, "user": {"$id": ObjectId("40b6d79e507b2c613615f15d"), "$ref": "xxx"}})
WriteResult({
	"nMatched" : 0,
	"nUpserted" : 0,
	"nModified" : 0,
	"writeError" : {
		"code" : 55,
		"errmsg" : "Found $id field without a $ref before it, which is invalid."
	}
})
rszz-0:PRIMARY> db.zzz.update({"b":7}, {"b": 7, "user": {"$ref":"xxx", "$id": ObjectId("40b6d79e507b2c613615f15d")}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
```

**Comment by vinllen** [comment]
v2.0.0版本已经修复
