### ISSUE TITLE
当持续写入数据时，source 已写入很多条，target 没有实时同步的困惑

### ISSUE THREAD

**Issue by gegeyan** [alibaba/MongoShake#150]
大神好，mongoshake 使用过程中发现，source这边儿已经写入好多条了， 
target 这边儿没实时同步上。

持续写入的时候，不会立即同步。
当没有持续写入的时候，会立即同步。

还有一种情况：就是 持续写入的时候，这个延迟时间和 fetcher.buffer_capacity 的配置有关。
（源库和目标库都在我本地做的，其他配置项均默认）

附：
    mongoshake    version: 1.4.6 
source mongodb version: 3.6.6
target mongodb  version: 3.0.2

collector.conf 内容如下：

# connect source mongodb, set username and password if enable authority.
# split by comma(,) if use multiple instance in one replica-set.
# split by semicolon(;) if sharding enable.
#mongo_urls = mongodb://username:password@127.0.0.1:20040,127.0.0.1:20041
mongo_urls = mongodb://192.168.8.198:27017

# collector name
collector.id = mongoshake

# save checkpoint interval if necessary. 
# the checkpoint will be checked and stored after starting 3 minutes.
checkpoint.interval = 5000

# http api interface. Users can use this api to monitor mongoshake.
# We also provide a restful tool named "mongoshake-stat" to 
# print ack, lsn, checkpoint and qps information based on this api.
# usage: `./mongoshake-stat --port=9100`
http_profile = 9100
# profiling on net/http/profile
system_profile = 9200

# global log level: debug, info, warning, error. lower level message will be filter
log_level = warning
# log file name. use logs/ prefix folder path
log_file = collector.log
# log buffer or unbuffer. If set true, logs may not be print when exit. If
# set false, performance will be decreased extremely
log_buffer = true

# filter db or collection namespace. at most one of these two parameters can be given.
# if the filter.namespace.black is not empty, the given namespace will be
# filtered while others namespace passed. 
# if the filter.namespace.white is not empty, the given namespace will be
# passed while others filtered. 
# all the namespace will be passed if no condition given.
# db and collection connected by the dot(.).
# different namespaces are splitted by the semicolon(;).
#filter.namespace.black = filterDbName1.filterCollectionName1;filterDbName2
filter.namespace.white = yapi 

# this parameter is not supported in current opensouce version.
# oplog namespace and global id. others oplog in 
# mongo cluster that has distinct global id will 
# be discard. Query without gid (means getting all
# oplog out) if no oplog.gid set
oplog.gids =   

# [auto] 		decide by if there has uniq index in collections. 
# 		 		use `collection` with uniqu index set otherwise `id`
# [id] 			shard by ObjectId. handle oplogs in sequence by unique _id 
# [collection] 	shard by ns. handle oplogs in sequence by unique ns 
shard_key = auto

# syncer send time interval, unit is second.
# time interval of flushing the syncer reader buffer.
syncer.reader.buffer_time = 3

# oplog transmit worker concurrent
worker = 8
# memory queue configuration, plz visit FAQ document to see more details.
# do not modify these variables if the performance and resource usage can
# meet your needs.
worker.batch_queue_size = 64
adaptive.batching_max_size = 16384
fetcher.buffer_capacity = 256

# batched oplogs have block level checksum value using 
# crc32 algorithm. and compressor for compressing content
# of oplog entry. 
# supported compressor are : gzip,zlib,deflate
# Do not enable this option when tunnel type is "direct"
worker.oplog_compressor = none

# tunnel pipeline type. now we support rpc,file,kafka,mock,direct
tunnel = direct
# tunnel target resource url
# for rpc. this is remote receiver socket address
# for tcp. this is remote receiver socket address
# for file. this is the file path, for instance "data"
# for kafka. this is the topic and brokers address which split by comma, for
# instance: topic@brokers1,brokers2, default topic is "mongoshake"
# for mock. this is uesless
# for direct. this is target mongodb address
#tunnel.address = mongodb://127.0.0.1:20080
tunnel.address = mongodb://192.168.8.189:27018 

# collector context storage mainly including store checkpoint
# type include : database, api
# for api storage, address is http url
# for database storage, address is collection name while db name is "mongoshake" by default.
# if source database is replica, context will store in the source mongodb.
# if source database is sharding, context must be given to point the config server address.
# context.storage.url is only used in sharding. When source mongodb type is replicaSet, 
# checkpoint will write into source mongodb as default.
context.storage = database
#context.storage.url = mongodb://127.0.0.1:20070
context.address = ckpt_default
# pay attention: this is UTC time which is 8 hours latter than CST time. this 
# variable will only be used when checkpoint is not exist.
#context.start_position = 2000-01-01T00:00:01Z

# high availabity option.
# enable master election if set true. only one mongoshake can become master
# and do sync, the others will wait and at most one of them become master once 
# previous master die. The master information stores in the `mongoshake` db in the source 
# database by default.
# This option is useless when there is only one mongoshake running.
master_quorum = false

#sync_mode = all  #all代表全量+增量，document代表仅全量，oplog代表仅增量。

# ----------------------splitter----------------------
# if tunnel type is direct, all the below variable should be set

# only transfer oplog commands for syncing. represent
# by oplog.op are "i","d","u". also include applyOps
replayer.dml_only = true
#replayer.dml_only = false  #false 代表启用DDL同步，包括建索引、建表、删库、事务等

# executors in single worker
replayer.executor = 1

# oplog changes to Insert while Update found non-exist (_id or unique-index)
replayer.executor.upsert = false
# oplog changes to Update while Insert found duplicated key (_id or unique-index)
replayer.executor.insert_on_dup_update = false
# db. write duplicated logs to mongoshake_conflict
# sdk. write duplicated logs to sdk.
replayer.conflict_write_to = none

# replayer duration mode. drop oplogs and take
# no any action(only for debugging enviroment) if 
# set to false. otherwise write to ${mongo_url} instance
replayer.durable = true

**Comment by vinllen** [comment]
请帮忙确认下：
1. ”延迟时间和 fetcher.buffer_capacity 的配置“的关系是正相关吗？
2. 前后是否有报错日志？
3. 延迟大是通过什么进行确认的？mongo-stat吗？
4. 将syncer.reader.buffer_time调低到1看下效果
5. 再确认一下源端写入的速率

**Comment by vinllen** [comment]
原因已确定，由于目前用户写入的qps过低，但是没有触发syncer.reader.buffer_time的阈值，也就是说，默认的3秒阈值内一直有数据写入，但是写入的量一直没有堆积到fetcher.buffer_capacity，所以会有这个问题。
目前的机制是：数据在发送端会有缓存，堆积到fetcher.buffer_capacity会进行发送，或者syncer.reader.buffer_time发送阈值内没有数据，也会强刷发送缓存。但如果用户的数据写入量很少，但是也在3秒内一直有写入，那么就会触发用户所说的问题。
解决方式：
1. syncer.reader.buffer_time调低至0
2. fetcher.buffer_capacity调低。对于qps很低的情况，这个调低影响不大。

**Comment by vinllen** [comment]
https://github.com/alibaba/MongoShake/wiki/FAQ#q-why-data-synchronization-is-slow
