### ISSUE TITLE
同步的时候MoveChunk会有什么问题

### ISSUE THREAD

**Issue by tlightsky** [alibaba/MongoShake#154]
https://github.com/alibaba/MongoShake/wiki/第一次使用，如何进行配置？#31-如果是分片sharding该如何配置

同步的时候MoveChunk会有什么问题？
如果自己写工具读取oplog进行同步也有这个问题吗？

**Comment by tlightsky** [comment]
怎么跟云Mongo的Balancer配合呢，
是每次同步之前关掉，然后同步完再打开Balancer吗

**Comment by vinllen** [comment]
跟是否是云mongodb没有关系，目前mongodb sharding情况下没办法处理move chunk，分片可能发生变更，这对于mongo-shake通道没办法感知，主要是维护分片数据迁移的happened-before关系。这个方案我们还在研究。
目前只能关balancer迁移，完成后打开。

**Comment by tlightsky** [comment]
好的，我目前理解的是mongo-shake也是分析oplog来进行同步的，
所以另外再写go去解析oplog也一样会碰到这个move chunk无感知的问题对吧

**Comment by vinllen** [comment]
是的。目前单单通过同步通道层面应该没有方法可以解决move chunk的问题。
