### ISSUE TITLE
mongoshake1.5版本什么时候出来？

### ISSUE THREAD

**Issue by UNXshell** [alibaba/MongoShake#156]
请问2个问题：
1、源端3.2版本，目标端为4.0版本是否支持？
2、支持全量同步的1.5版本，大概预计什么时候能够出？

**Comment by vinllen** [comment]
1. 支持
2. 1.5版本已经可以使用了，不过需要自己编译，1.5是非稳定版本，稳定版本是2.0。

**Comment by vinllen** [comment]
2.0已经发布

**Comment by UNXshell** [comment]
github上吗
________________________________
发件人: Vinllen Chen <notifications@github.com>
发送时间: 2019年6月24日 11:22:40
收件人: alibaba/MongoShake
抄送: UNXshell; Author
主题: Re: [alibaba/MongoShake] mongoshake1.5版本什么时候出来？ (#156)


2.0已经发布

―

**Comment by vinllen** [comment]
嗯 代码请拉取feature-2.0分支，二进制下载可以在这：https://github.com/alibaba/MongoShake/releases
