### ISSUE TITLE
希望新增几个配置选项

### ISSUE THREAD

**Issue by cocoakekeyu** [alibaba/MongoShake#157]
1. 可以配置强制同步源端集群为 Primary。
   - 因为某些源集群的 Oplog 同步有延迟， 直接同步 Primary 到新集群可以减少延迟

2. 可以配置 checkpoint 在额外的数据库
   - 目前虽然有提供 API 方法，但是搭建另外一个 mongodb 作为 checkpoint 存储更为方便。现 checkpoint 保存在源集群数据库，如果想要删除或者修改 checkpoint ，可能需要登录源集群手动操作，比较危险。

3. 提供额外配置可以用启动的 checkpoint 参数 overwrite 存储在数据库的 checkpoint。
    - 原因同 2 。目前如果需要重新从某个时间点同步，需要手动登录源端数据库删除或者修改 checkpoint ，因为数据库的 checkpoint 优先级比配置的高。

**Comment by vinllen** [comment]
感谢建议，需求合理，我们会进行考虑支持

**Comment by vinllen** [comment]
1. 支持三种模式：
Primary：从primary读取
SecondaryPreferred：优先secondary
Standalone: 支持从单节点，比如hidden读取
2. 副本集也启用context.storage.url，没有配置则默认打到源端，配置则打到配置的库
3. 这个不合适，如果添加了发生了重启，将会再次覆盖源端导致数据重放。此功能暂不支持

**Comment by vinllen** [comment]
https://github.com/alibaba/MongoShake/issues/20

**Comment by vinllen** [comment]
v2.0.1版本已经支持
