### ISSUE TITLE
mongo-shake2.0 全量导入的数据有的字段或整个doc缺失，但是整体的count没错

### ISSUE THREAD

**Issue by lixj1103** [alibaba/MongoShake#173]
源库：Mongodb3.2.4 cluster（有3个分片）
目的库： Mongodb3.2.10 复制集；
同步模式：全量+增量
同步结果：目的库的所有collectio的count与源库相同
 但是有一些doc的缺少字段，或者整个doc缺失

**Comment by hesy007** [comment]
我也遇到了，新增和删除可以，但是更新DOC的话，会导致整个DOC只留下一个 _id 字段，其他字段都丢失了。

**Comment by vinllen** [comment]
@hesy007 增量阶段出现的？update语句导致？

**Comment by hesy007** [comment]
@vinllen  是的，增量阶段的 update 语句

**Comment by hesy007** [comment]
我尝试了多次，会出现以下两个结果：

- 只保留 _id 字段
- 被更新到字段丢失，其他字段都在

**Comment by vinllen** [comment]
@hesy007 ok, 晚上我看下

**Comment by vinllen** [comment]
@hesy007 该问题与标题不符合，移步https://github.com/alibaba/MongoShake/issues/183

**Comment by vinllen** [comment]
@hesy007 对应bug已修复 v2.0.3
