### ISSUE TITLE
not support update set?

### ISSUE THREAD

**Issue by rafael-0317** [alibaba/MongoShake#174]
I having the same problem...
It seems to be the problem describes below.

db.test.update(
   { "_id": ObjectId("5d1b1acad2d8328d32781b89") },
   {
      "i": 84,
      "username": "user84",
      "age": 2000,
      "created": ISODate("2019-07-02T08:50:18.968Z")
   }
)
>> okay. no problem.

db.test.update(
   { "_id": ObjectId("5d1b1acad2d8328d32781b89") },
   { $set:  {  <<<<
      "i": 84,
      "username": "user84",
      "age": 2001,
      "created": ISODate("2019-07-02T08:50:18.968Z")
   }
   },
   { multi: true }
)
>> removed the all fields....., this is not support update set?
(mongod-3.4.20)[PRIMARY:beta] test> db.test.find( { "_id": ObjectId("5d1b1acad2d8328d32781b89") } )
{
  "_id": ObjectId("5d1b1acad2d8328d32781b89")
}
Fetched 1 record(s) in 1ms

Best Regards,
Park

**Comment by vinllen** [comment]
What you ask is MongoDB problem about `$set`, right? It's unrelated with MongoShake.
But, I'm sure you did something wrong with the sentence, `$set` can modify the result.
```
rszz-4.0:PRIMARY> db.y.insert({"i": 84, "username": "user84", "age": 2000})
WriteResult({ "nInserted" : 1 })
rszz-4.0:PRIMARY> db.y.find()
{ "_id" : ObjectId("5cb6e756507b2c613615f160"), "qwe" : 2 }
{ "_id" : ObjectId("5d1b5417fdffc4cdbd4b5329"), "i" : 84, "username" : "user84", "age" : 2000 }
rszz-4.0:PRIMARY> db.y.update({"_id" : ObjectId("5d1b5417fdffc4cdbd4b5329")}, {"i": 86, "username": "user85", "age": 2002})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
rszz-4.0:PRIMARY> db.y.find()
{ "_id" : ObjectId("5cb6e756507b2c613615f160"), "qwe" : 2 }
{ "_id" : ObjectId("5d1b5417fdffc4cdbd4b5329"), "i" : 86, "username" : "user85", "age" : 2002 }
rszz-4.0:PRIMARY> db.y.update({"_id" : ObjectId("5d1b5417fdffc4cdbd4b5329")}, {$set: {"i": 86, "username": "user85", "age": 2000000}}, {multi: true})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
rszz-4.0:PRIMARY> db.y.find()
{ "_id" : ObjectId("5cb6e756507b2c613615f160"), "qwe" : 2 }
{ "_id" : ObjectId("5d1b5417fdffc4cdbd4b5329"), "i" : 86, "username" : "user85", "age" : 2000000 }
rszz-4.0:PRIMARY> db.y.update({"_id" : ObjectId("5d1b5417fdffc4cdbd4b5329")}, {$set: {"i": 86, "username": "user85", "age": 3000000}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
rszz-4.0:PRIMARY> db.y.find()
{ "_id" : ObjectId("5cb6e756507b2c613615f160"), "qwe" : 2 }
{ "_id" : ObjectId("5d1b5417fdffc4cdbd4b5329"), "i" : 86, "username" : "user85", "age" : 3000000 }
```
