### ISSUE TITLE
sharding迁移遇到duplicate key error报错

### ISSUE THREAD

**Issue by MaxLinyun** [alibaba/MongoShake#186]
duplicate key是源库在move chunk时由于move chunk失败产生的orphaned document，也就是说同一个_id在源库多个shard节点中存在，那样用mongoshake迁移时现在肯定会失败，需要把源库的orphaned document给清理掉才行。清理orphaned document可以参考https://docs.mongodb.com/manual/reference/command/cleanupOrphaned/

**Comment by MaxLinyun** [comment]
可以考虑：利用config库里的数据区分出来自不同shard的两个_id哪个是对的，哪个是错的

**Comment by vinllen** [comment]
@lydarkforest 这个加到faq里面吧：https://github.com/alibaba/MongoShake/wiki/FAQ

**Comment by jadegold** [comment]
这个功能sharding很需要

**Comment by MaxLinyun** [comment]
@jadegold 这个问题在feature-2.1-unstable分支里已经解决了，把配置文件的filter.orphan_document设为true就可以使用了
