### ISSUE TITLE
复制集迁移报错 

### ISSUE THREAD

**Issue by xiaolongyuan** [alibaba/MongoShake#187]
![image](https://user-images.githubusercontent.com/3142363/61021630-e1e84280-a3d4-11e9-9386-df69790be68a.png)
![image](https://user-images.githubusercontent.com/3142363/61021635-e4e33300-a3d4-11e9-89eb-7f77b783598b.png)

**Comment by vinllen** [comment]
用户深度报错日志：
![image](https://user-images.githubusercontent.com/6987398/61030506-17e6f000-a3f0-11e9-8676-3ffed59875a7.png)

**Comment by vinllen** [comment]
类似问题：https://github.com/alibaba/MongoShake/issues/122

**Comment by vinllen** [comment]
v2.0.4版本已修复，计划7.14前发布
