### ISSUE TITLE
复制集全量复制objects不一致

### ISSUE THREAD

**Issue by afei263** [alibaba/MongoShake#190]
- (mongodb3.2 并且 都是单节点复制集, mongoshake为2.0.3版本)
- 源mongodb全量同步到目标库,通过comparision.py比对报以下错误.
```
|># python3 comparision.py --src=xxx --dest=xxx --count=500000 --excludeDbs=admin,local,mongoshake --excludeCollections=system.profile
INFO  [2019-07-12 11:28:43] Configuration [sample=True, count=500000, excludeDbs=['admin', 'local', 'mongoshake', 'admin', 'local'], excludeColls=['system.profile', 'system.profile']] 
[src = 172.16.31.1:30411]
[dst = 172.16.31.92:32038]
INFO  [2019-07-12 11:28:43] EQUL => database count equals 
ERROR [2019-07-12 11:28:43] DIFF => database [hari] stats not equals src[{'db': 'hari', 'collections': 1, 'objects': 2369253, 'numExtents': 0, 'indexes': 1, 'ok': 1.0}], dst[{'db': 'hari', 'collections': 1, 'objects': 2369262, 'numExtents': 0, 'indexes': 1, 'ok': 1.0}] 
```

- 操作过程为(多次测试都是采用此流程):
   - 关闭mongoshake
   - 停止目标mongodb并删除目标mongodb /data/db中的文件及文件夹
   - 重启目标mongodb,将新启的目标mongodb初始化为单节点复制集
   - 删除源mongodb的mongoshake库.
   - 开启mongoshake(sync_mode=all)

- 个人检测
  - 可以看到比对结果为目标库比源库数据多几条(多次操作,此bug恒定出现)
  - 使用下面个人比对数据脚本运行后,却发现目标库的所有数据都能在源库找到

```
# !/usr/bin/python3

import pymongo


dest_client = pymongo.MongoClient("mongodb://xxx/")
dest_db = dest_client["hari"]
dest_col = dest_db["item"]


src_client = pymongo.MongoClient("mongodb://xxx/")
src_db = src_client["hari"]
src_col = src_db["item"]


dest_list = dest_col.find()
count = 0
for x in dest_list:
    y = src_col.find_one({"_id": "%s" % x["_id"]})
    if not y:
        print("not %s in 31" % str(x))
    if not len(x.keys()) == len(y.keys()):
        print("----------------not keys len equal")
        print(x)
        print(y)
    count += 1
    if count % 10000 == 0:
        print(count)
```

**Comment by afei263** [comment]
2019-07-17
- 今天对生产环境的mongodb做了调整.
  - 关闭源mongodb
  - 关闭目标mongodb,并删除目标mongodb  /data/db目录中的文件和文件夹
  - 将源mongodb /data/db中的内容rsync到目标mongodb /data/db中
  - 开启源mongodb和目标mongo'db,并对目标mongodb复制集重新初始化
  - 开始mongoshake的oplog模式
  - 数据比对,一致.

所以mongoshake的全量同步可能是有点问题的.

**Comment by vinllen** [comment]
@lydarkforest 支持看下

**Comment by lydarkforest** [comment]
用sync_mode=document光跑全量同步，测一下

**Comment by MaxLinyun** [comment]
还有多出来的那几条数据有什么特征没有，看下这几条数据的oplog

**Comment by vinllen** [comment]
@lydarkforest 用户数据太多了，多的数据diff没有比对出来。
全量+增量 数据反馈有10条不一致
然后用户自己拷贝全量 + 增量 数据没有不一致
所以问题 要么全量问题 要么是增量位点的问题

**Comment by vinllen** [comment]
@afei263 DDL是否有开启？

**Comment by afei263** [comment]
@lydarkforest @vinllen 每次检测 目标库都是多的,但是我查询出目标库的所有数据,去源库找都是能找到的(上面已经有解释). 我看了下也可能是比对脚本的问题.因为我07-17虽然比对一致了,现在比对又不一致.从我两边的count的数据来看,目标库的数据是一直追着走的.  总起来说,好像也可能不是全量同步的问题,是比对脚本的问题. 热同步的情况下,你们的这个比对脚本应该不符合要求的,你们是怎么去校验两边数据是否一致呢?(假设源库一直是在往目标库同步数据的情况下,好像是肯定不一致的)

**Comment by vinllen** [comment]
这个脚本本身是用于全量对比的，这种增量场景的确适用有局限
