### ISSUE TITLE
sharding配置时，work数量报错

### ISSUE THREAD

**Issue by tangchuanming** [alibaba/MongoShake#198]
mongo_urls=mongodb://zb:aaaa@192.168.20.191:30002,192.168.20.192:30002,192.168.20.193:30002;mongodb://zb:aaaa@192.168.20.194:30002,192.168.20.195:30002,192.168.20.196:30002;mongodb://zb:aaaa@192.168.20.197:30002,192.168.20.198:30002,192.168.20.199:30002

work=9

我配置了9个mongod，work也是设置的9，但是运行的时候，提示Conf.Options check failed: replication worker should be equal to count of mongo_urls while multi sources (shard)。说shardding 的数量要和work相等。
我的mongo_urls写法有误吗？

**Comment by tangchuanming** [comment]
如果源端是sharding，目的端也必须是sharding吗？而且分片数相同？

**Comment by vinllen** [comment]
worker个数需要等同于源端的shard的个数，目的端没有要求，分片数可以不同。
你配置的是3个shard，应该是3。
这个后续版本将会强行修改worker个数。

**Comment by tangchuanming** [comment]
Conf.Options check failed: unknown mongo_connect_mode[]，这个是指连接方式配置错了吧，已下是我的配置，但不知道是哪错了。
tunnel = direct
tunnel.address=mongodb://zb:aaaa@192.168.22.103:27001,192.168.22.103:27002,192.168.22.103:27003;mongodb://zb:aaaa@192.168.22.103:27004,192.168.22.103:27005,192.168.22.103:27006;mongodb://zb:aaaa@192.168.22.103:27007,192.168.22.103:27008,192.168.22.103:27009
context.storage = database
context.storage.url=mongodb://zb:aaaa@192.168.20.200:30001,192.168.20.201:30001,192.168.20.202:30001      #这个地址是源的config服务器
context.address = ckpt_default。

**Comment by vinllen** [comment]
你配置文件不是最新的吧，最新的配置文件有个mongo_connect_mode选项，这个应该是在v2.0某个小版本里面添加的

**Comment by tangchuanming** [comment]
[root@localhost bin]# ./collector --version
develop,6a76cc5a5ece513a642c7d3dce0678029b4ca3c2,release,go1.11.5,2019-07-22_09:17:09

**Comment by vinllen** [comment]
你在release上下载二进制包看下吧，有个配置选项的。你应该没拉最新代码

**Comment by tangchuanming** [comment]
下了新包，可以同步了。但是有选项可以把服务放在后台运行吗？

**Comment by vinllen** [comment]
加上"&"运行。
