### ISSUE TITLE
shake tunnel连接kafka出错

### ISSUE THREAD

**Issue by zlklink** [alibaba/MongoShake#209]
配置：
tunnel = kafka
tunnel.address = mongoshake@127.0.0.1:9092
kafka版本2.11-2.3.0
zookeeper采用单实例部署
执行报错：start writer error[kafka: client has run out of available brokers to talk to (Is your cluster reachable?)]

**Comment by zlklink** [comment]
[CRIT] (mongoshake/tunnel.(*KafkaWriter).Prepare:24) KafkaWriter prepare[mongoshake@127.0.0.1:9092] start writer error[kafka: client has run out of available brokers to talk to (Is your cluster reachable?)]

**Comment by vinllen** [comment]
检查一下kafka集群的状态，这个应该是本身kafka集群状态的问题

**Comment by zlklink** [comment]
有没有可能和kafka的版本有关系
此外目前处于技术调研阶段，kafka是单实例部署的，会不会也有问题？
希望能给予解答，谢谢


------------------ 原始邮件 ------------------
发件人: "Vinllen Chen"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 上午10:08
收件人: "alibaba/MongoShake"<MongoShake@noreply.github.com>;
抄送: "云和山的彼端"<1067176522@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/MongoShake] shake tunnel连接kafka出错 (#209)




检查一下kafka集群的状态，这个应该是本身kafka集群状态的问题

**Comment by vinllen** [comment]
你可以搞个client对接写入看看有没有问题，先看看集群状态吧，单实例应该也可以的

**Comment by woshihepengyu** [comment]
请问您解决了吗？

**Comment by SuperChrisliu** [comment]
我用的是cdh版本 KAFKA 4.1.0-1.4.1.0.p0.4，`(mongoshake/common.NewMongoConn:48) Connect to mongosync@hadoop001:9092 failed. no reachable servers`
kafka broker提示：
`org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 973078528 larger than 104857600)`
是不是对kafka版本有要求啊

**Comment by SuperChrisliu** [comment]
@vinllen

**Comment by SuperChrisliu** [comment]
用kafka-console-producer是可以写入的

**Comment by SuperChrisliu** [comment]
(mongoshake/common.NewMongoConn:48) Connect to mongosync@hadoop001:9092 failed. no reachable servers看提示怎么是NewMongoConn报错呢，好像是用卡夫卡的地址连了mongo？
我的tunnel 配置如下
`tunnel = kafka
tunnel.address = topic_test@127.0.0.1:9092
tunnel.message = json`

**Comment by vinllen** [comment]
#424
