### ISSUE TITLE
document同步链路可以关闭，进程一直存在的问题

### ISSUE THREAD

**Issue by jackyu86** [alibaba/MongoShake#210]
同步完成的日志截图
![image](https://user-images.githubusercontent.com/11902949/62508548-9e012580-b83a-11e9-8113-92e52ce00769.png)
同步完成后进程截图
![image](https://user-images.githubusercontent.com/11902949/62508572-b96c3080-b83a-11e9-92db-cc531d71ae8c.png)

CTRL+C强制关闭
![image](https://user-images.githubusercontent.com/11902949/62508600-d7399580-b83a-11e9-8e7e-2c046c3be7fc.png)

**Comment by vinllen** [comment]
目前全量同步完的确没有退出机制，会一直block住，这个后续支持掉，正常的话下个版本吧

**Comment by vinllen** [comment]
v2.0.6版本已经支持，请等待发布

**Comment by vinllen** [comment]
v2.0.6版本已发布
