### ISSUE TITLE
mongodb sharding集群之间同步数据过程中有孤儿数据也可以进行同步

### ISSUE THREAD

**Issue by jadegold** [alibaba/MongoShake#214]
背景：两个mongodb sharding集群，并且balance会打开active window，可能会存在孤儿数据
目的：集群之间之间进行数据同步
需求：mongoshake在进行数据同步时，在存在孤儿数据的时候也可以正常进行数据同步，不会退出失败

**Comment by jadegold** [comment]
![image](https://user-images.githubusercontent.com/53553715/62541870-3c1ddb80-b88d-11e9-8f63-01404e5f8c24.png)

**Comment by vinllen** [comment]
需求待评估。

**Comment by vinllen** [comment]
v2.1已经计划支持，本issue关闭，请移步 #186 。
