### ISSUE TITLE
开源模式下支持双活

### ISSUE THREAD

**Issue by vinllen** [alibaba/MongoShake#221]
TODO

**Comment by xiaolongyuan** [comment]
@vinllen 开源版本Mongodb 实现双活有具体方案么？

**Comment by vinllen** [comment]
具体方案暂未敲定，v3.6版本之后添加了一个uuid字段，这个字段应该包括了集群、db和collection的信息，如果可以剥离出集群字段，那么可以根据这个实现双活策略。
最近没有时间，这个后面有时间了会再仔细调研一下。

**Comment by jianhuihi** [comment]
vinllen加油，武汉加油

**Comment by vinllen** [comment]
@jianhuihi 感谢支持~继续关注mongoshake，开工大吉~~
