### ISSUE TITLE
白名单设置到collection报database不存在-分片集群到分片集群

### ISSUE THREAD

**Issue by jackyu86** [alibaba/MongoShake#222]
如题:
collections:
![image](https://user-images.githubusercontent.com/11902949/62924354-7f72cf80-bde2-11e9-83da-42609ffe46fc.png)
报错:
![image](https://user-images.githubusercontent.com/11902949/62924362-84d01a00-bde2-11e9-8734-cd2f338f169f.png)
配置信息:
![image](https://user-images.githubusercontent.com/11902949/62924368-8863a100-bde2-11e9-97df-afb5db3d7650.png)

**Comment by MaxLinyun** [comment]
这是代码bug，最新的2.0代码已经修复了，你可以下载下来再试下

**Comment by jackyu86** [comment]
我用的已经是最新版了，2.0.6

**Comment by MaxLinyun** [comment]
![image](https://user-images.githubusercontent.com/5073309/63033233-ddd6a580-bee9-11e9-808b-eefc5019a64e.png)
我晚上刚提交的更新，你用这个feature-2.0分支的最新代码

**Comment by vinllen** [comment]
@lydarkforest 今天我rebase一下发个版本好了：v2.0.7

**Comment by vinllen** [comment]
时间问题，推迟到周末release

**Comment by vinllen** [comment]
v2.0.7版本已发布
