### ISSUE TITLE
需要加一个开关，支持admin数据库的同步

### ISSUE THREAD

**Issue by erwzqsdsdsf** [alibaba/MongoShake#223]
新手不知道如何创建数据库，经常容易用教程提供的mongo url。也就是admin数据库。

然后业务上就一天天的都存在admin上了。

现在需要提供支持，admin的导出。admin的同步到其他地方。

**Comment by vinllen** [comment]
需求评估中，计划v2.0.7支持

**Comment by vinllen** [comment]
v2.0.7版本已发布
