### ISSUE TITLE
没关闭balance,导致MongoShake  move chunk oplog found

### ISSUE THREAD

**Issue by gao13993335271** [alibaba/MongoShake#224]
以前集群也没有关闭Balance 没出过问题
今天突然发现很多错误信息   move chunk oplog found XXXXX
手动关闭Mongo的Balancer之后，重启MongoShake还是不能恢复
目前应该清除checkPoint 然后重新设置时间点启动么 避免过这个问题
还是？  求指点

**Comment by vinllen** [comment]
对，清除checkpoint，重新全量+增量同步就行，全量完毕会记录新的checkpoint，增量会从这个位点开始拉取。
目前不支持源端不关闭balancer同步，之前没事应该是没有触发move chunk操作。

**Comment by gao13993335271** [comment]
@vinllen   问题解决了  多谢

**Comment by hsiven** [comment]
> 对，清除checkpoint，重新全量+增量同步就行，全量完毕会记录新的checkpoint，增量会从这个位点开始拉取。
> 目前不支持源端不关闭balancer同步，之前没事应该是没有触发move chunk操作。

@vinllen 请教一下，这里为什么不支持 源端不不关闭balancer 同步啊。如果还要支持，会有什么问题吗？

**Comment by hsiven** [comment]
> > 对，清除checkpoint，重新全量+增量同步就行，全量完毕会记录新的checkpoint，增量会从这个位点开始拉取。
> > 目前不支持源端不关闭balancer同步，之前没事应该是没有触发move chunk操作。
> 
> @vinllen 请教一下，这里为什么不支持 源端不不关闭balancer 同步啊。如果还要支持，会有什么问题吗？

我的别的 issue 中找到了答案了，多谢

**Comment by vinllen** [comment]
@hsiven 2.4最新版本可以通过change stream对接支持不关闭balancer，不过要求mongodb的最低版本是4.0
