### ISSUE TITLE
Fix typo in wiki

### ISSUE THREAD

**Issue by AshutoshBharti** [alibaba/MongoShake#226]
Hey, I noticed in the MongoShake-Detailed-Documentation.md, at two places, 'Syncer' has been written as 'Synder' twice. 

```
 # 4. Architecture & Data Flow
... 
-Syncer is responsible for fetching data from the source database. If the source is a Mongod or a ReplicaSet, then there is only one **Synder**. If it is a Sharding mode, then there need to be multiple "syncers" connecting to each shard. Inside **Synder**, 

```
I have fixed this in wiki at `https://github.com/AshutoshBharti/MongoShake/wiki`

**Comment by vinllen** [comment]
@AshutoshBharti thanks for your modification, but I haven't received your Pull Request. Did you submit your PR?

**Comment by AshutoshBharti** [comment]
@vinllen I don't think a Pull request can be opened to wiki. But in case you would like to merge it: https://github.com/AshutoshBharti/MongoShake.wiki.git
