### ISSUE TITLE
分布式环境下时间如何同步呢？

### ISSUE THREAD

**Issue by JerryJavaCoding** [alibaba/MongoShake#231]
多地多机房的情况下，比如我的生产在俄罗斯和印尼，最终一致性要按照时间来确定，请问如何保证多个机房之间时间的同步呢？望解答

**Comment by vinllen** [comment]
你说的最终一致性是指的单向同步还是双向同步？

**Comment by JerryJavaCoding** [comment]
双向的，多地多机房都可以写且互相同步，现在假设机房A，机房B在脑裂时候先后写入同一条数据，理论上B后写应该采用B的数据，这时候要根据时间来进行判断，而这个时间，如何确保多地机房保持一致呢

**Comment by vinllen** [comment]
没办法保证，最终一致性这里也只取决于最后同步写入的时间，并没有根据时钟来判断。如果要保证最终一致性，需要CRDT+全局时钟或者全局统一的时钟序
