### ISSUE TITLE
direct tunnel不支持同时往多个mongodb实例复制?

### ISSUE THREAD

**Issue by liunianjie** [alibaba/MongoShake#235]
测试发现,tunnel.address配置多个mongodb实例(不同的副本集群实例)时,有些实例没有同步到数据.
尝试通过启动两个collector进程来完成,但是只能启动一个.
http://yqfile.alicdn.com/1d2f004feeab709055cf043b7a49f25b9c4536ed.png
但从这张图来看是支持往多个实例做复制的,想请问下目前开源版本是只支持单个吗,还是我这边用法有问题?

**Comment by vinllen** [comment]
目前一个mongoshake对于direct通道只能对接一个mongodb，别的通道灵活一些，不过需要自己实现receiver。如果direct想要多个，可以启动多个，改一下checkpoint的地址，context.address 对应的名字改一下，不要使用同一个checkpoint就行。
