### ISSUE TITLE
两机房双写，集群数据一致性问题咨询

### ISSUE THREAD

**Issue by y123456yz** [alibaba/MongoShake#240]
场景1. 
机房A集群更新数据为A，同时机房B更新数据为B，最终是数据用A还是用B，如何保持一直，根据什么确定

场景2.
开始总库存假设100，机房A更新商品库存dec 4, 同时机房B用户更新商品库存 dec 5,  由于Oplog幂等性，机房A集群最后的oplog是库存100-4=96，机房B集群最后oplog是库存100-5=95，同步结束后最终要么是95，要么是96。但是正常的库存量应该是100-5-4=91，这个你们如何保证最终的一致性的。

谢谢回答
@vinllen  vinllen

**Comment by vinllen** [comment]
场景一：目前没做，做的话也是最终一致性。
场景二：典型双写问题。
同时操作key肯定要做CRDT的，直接修改内核，这种现在云上也没有处理，需求决定，后面可能会考虑进行内核层面的支持。

**Comment by y123456yz** [comment]
@vinllen  我看你们开源了个mongodb版本，和官方的版本改动不大啊，有打算这些功能也一起开源吗

**Comment by vinllen** [comment]
短期内没有计划。开源的Mongodb是比较早的版本了，这些功能没有包括

**Comment by y123456yz** [comment]
好勒，收到，感谢。
