### ISSUE TITLE
/repl接口里面没有看到TPS值

### ISSUE THREAD

**Issue by windyzhousir** [alibaba/MongoShake#241]
{"who":"mongoshake","tag":"improve-2.0.1,505565265f370a57452189a0f5272ee118fa8524,release,go1.10.3,2019-06-24_11:12:35","replset":"default-0","logs_get":7558849,"logs_repl":6371042,"logs_success":6371042,"lsn":{"unix":1568190687,"time":"2019-09-11 16:31:27","ts":"6735327714556773425"},"lsn_ack":{"unix":1568187598,"time":"2019-09-11 15:39:58","ts":"6735314447402795184"},"lsn_ckpt":{"unix":1568187598,"time":"2019-09-11 15:39:58","ts":"6735314447402795184"},"now":{"unix":1568191034,"time":"2019-09-11 16:37:14"}}

输出只看到当前的各种日志总量，没有tps值

**Comment by vinllen** [comment]
v2.0.8版本计划近期发布进行支持，请等待。此外，你用的v2.0.1版本存在bug可能会导致数据同步错乱，建议升级2.0.4以后版本。

**Comment by vinllen** [comment]
v2.0.8版本已经发布
