### ISSUE TITLE
关于oplog collection capped error

### ISSUE THREAD

**Issue by ranyuanyuan** [alibaba/MongoShake#242]
两个mongo复制集之间双向同步，出现如下信息：
[EROR] [collector.(*OplogSyncer).next:374] oplog collection capped error, users should fix it manually
我无法确定是哪个collection的数据有冲突，有没有什么办法可以查出来？

**Comment by vinllen** [comment]
capped error指的是拉取位点的mongodb的oplog丢了，mongodb是实时拉取同步的，如果出现capped error肯定说明之前同步卡住了，然后oplog被Purge掉了就出现这个。你翻一下之前的shake日志，看看有没有具体的报错信息。

**Comment by ranyuanyuan** [comment]
> capped error指的是拉取位点的mongodb的oplog丢了，mongodb是实时拉取同步的，如果出现capped error肯定说明之前同步卡住了，然后oplog被Purge掉了就出现这个。你翻一下之前的shake日志，看看有没有具体的报错信息。



> capped error指的是拉取位点的mongodb的oplog丢了，mongodb是实时拉取同步的，如果出现capped error肯定说明之前同步卡住了，然后oplog被Purge掉了就出现这个。你翻一下之前的shake日志，看看有没有具体的报错信息。

是不是因为数据库中有很多的collection没有数据，只有索引才导致出现这种提示
[executor.(*Executor).execute:97] Replayer-7, executor-7, oplog for namespace[xxx.$cmd] op[c] failed. error type[*mgo.QueryError] error[a collection 'xxx.PSMemberGroupRole' already exists], logs number[1], firstLog: [{ts 6735195378024448010} {op c} {g } {ns xxx.$cmd} {o [{create PSMemberGroupRole} {idIndex [{v 2} {key [{_id 1}]} {name _id_} {ns xxx.PSMemberGroupRole}]}]} {o2 map[]} {uk map[]} {lsid <nil>} {fromMigrate false}]

**Comment by vinllen** [comment]
如果有报错是会一直报错的，你们需要自己加点监控监控一下日志的内容，看看是不是有报错。
你这个是写的时候目的端表存在了，`a collection 'xxx.PSMemberGroupRole' already exists`。
中间如果重启过，有DDL语句是可能会有这个错误的，表被反复重建。或者你们自己在目的库已经有这个表或者创建了这个表，源端同步过来就有问题了。

**Comment by ranyuanyuan** [comment]
> 如果有报错是会一直报错的，你们需要自己加点监控监控一下日志的内容，看看是不是有报错。
> 你这个是写的时候目的端表存在了，`a collection 'xxx.PSMemberGroupRole' already exists`。
> 中间如果重启过，有DDL语句是可能会有这个错误的，表被反复重建。或者你们自己在目的库已经有这个表或者创建了这个表，源端同步过来就有问题了。

A拉取B上的数据，这些数据中有一部分collection只有索引没有数据；在双向同步的环境中，B再去拉取A上的这部分空的collection时就提示错误了，所谓的冲突数据应该就是指这部分空数据库的collection吧？

**Comment by vinllen** [comment]
你这种场景A->B可以做全量同步，B->A只能做增量，而且位点得是A到B全量同步完的位点。

**Comment by ranyuanyuan** [comment]
> 你这种场景A->B可以做全量同步，B->A只能做增量，而且位点得是A到B全量同步完的位点。

听起来应该能解决我的问题了，但还是希望能在后续版本加上空collection的兼容。

**Comment by vinllen** [comment]
这个没办法兼容，双向同步全量导致。即使是空的collection，有索引也是等于有表。
