### ISSUE TITLE
报错：Locked by other process

### ISSUE THREAD

**Issue by CuteBull** [alibaba/MongoShake#245]
环境：复制了一个配置文件collector.conf改名后，修改里面的源数据库地址、http_profile和system_profile端口号、context.address。目标数据库地址跟之前的配置文件一致。

调用./collector -conf=新配置文件  后报错如下：(mongoshake/common.WritePidById:160) Process write pid and lock file failed : Locked by other process

请问怎么解决，非常感谢~

**Comment by vinllen** [comment]
这表示机器上现在已经有进程启动了，如果你是只启动一个，那么应该先kill原来的，如果是做主备，那么应该不同目录启动。

**Comment by CuteBull** [comment]
好的，已经解决了。
collector.id= 这个配置改成一个别的名字，不跟之前配置文件中的重复就可以了
