### ISSUE TITLE
Query: Transaction support

### ISSUE THREAD

**Issue by sguptara** [alibaba/MongoShake#249]
As per FAQ page, mongodb transactions are supported in mongoshake version 1.6.x.
Is it supported in 2.x, I tried with mongodb 4.2.0 on both source and destination mongodbs and replayer.dml_only is set to false, executed a transaction on source, the collections modified as part of transaction are not reflected onto destination. 

Could you please clarify if transactions are supported in mongoshake 2.x

**Comment by vinllen** [comment]
Transaction is supported in mongoshake 2.x, could you show me the transaction commands and oplog?
