### ISSUE TITLE
单实例同步到mongos sharding

### ISSUE THREAD

**Issue by liuqy95** [alibaba/MongoShake#251]
请教下，我从单实例mongodb同步到mongos，tunnel.address配置的是mongos集群地址，shard_key=id，先在mongos建好了片键，同步完之后数据，数据都在其中一个shard里面，没有均匀分配，还需要注意哪里的配置呢

**Comment by vinllen** [comment]
这是因为分片键信息没有设置。解决方法有2：
1. 同步之前先在目的库创建好表，并建好分片键信息。mongoshake参数有个replayer.collection_drop置为false。再开启同步
2. 同步后，再创建分片键，开启balancer进行数据的迁移均衡。

**Comment by liuqy95** [comment]
创建好分片之后，全量同步的时候提示目标库已存在，退出了；但是删除库之后，分片键也一起删除了，无法达到分片的目的，是为何呢

**Comment by vinllen** [comment]
你用2.0.8应该没这个问题，这个逻辑后面版本修改了，drop置为false不会退出。

**Comment by liuqy95** [comment]
非常感谢，已解决
