### ISSUE TITLE
密码带加号时会导致报错: server returned error on SASL authentication step: Authentication failed

### ISSUE THREAD

**Issue by benamazing** [alibaba/MongoShake#253]
当mongodb的用户密码里有加号时，会导致认证报错

![image](https://user-images.githubusercontent.com/7868153/67387187-f7baf580-f5c8-11e9-9c54-6a964bcc0536.png)

后来把密码随机中的加号去掉之后，就可以了。

**Comment by vinllen** [comment]
这个应该是mgo本身驱动的限制了，修改一下密码吧
