### ISSUE TITLE
全量同步启动后，目标库同步完成后 数据不再更新

### ISSUE THREAD

**Issue by itcam** [alibaba/MongoShake#255]
mongo_urls = mongodb://xxx:xxxx@xxxxx:27017
mongo_connect_mode = standalone
collector.id = mongoshake
sync_mode = all
http_profile = 9100
system_profile = 9200
log.level = info
log.dir =
log.file = collector.log
log.buffer = true
filter.namespace.black =
filter.namespace.white = db1.col1
filter.pass.special.db =
oplog.gids =
shard_key = collection
worker = 8
worker.batch_queue_size = 64
adaptive.batching_max_size = 1024
fetcher.buffer_capacity = 256
worker.oplog_compressor = none
tunnel = direct
tunnel.address = mongodb://xxx:xxx@127.0.0.1:27017
context.storage = database
context.storage.url =
context.address = ckpt_default
context.start_position = 2000-01-01T00:00:01Z
master_quorum = false
transform.namespace = db1.col1:db2.col1
dbref = false
replayer.dml_only = false
replayer.executor.upsert = false
replayer.executor.insert_on_dup_update = false
replayer.conflict_write_to = none
replayer.durable = true
replayer.collection_parallel = 6
replayer.document_parallel = 8
replayer.document_batch_size = 256
replayer.collection_drop = false

[12:09:22 CST 2019/11/04] [INFO] (mongoshake/common.(*ReplicationMetric).startup.func1:137) [name=default-0, filter=0, get=0, consume=0, apply=0, failed_times=0, success=0, tps=0, ckpt_times=0, retransimit_times=0, tunnel_traffic=0B, lsn_ckpt={0,1970-01-01 08:00:00}, lsn_ack={0,1970-01-01 08:00:00}]

**Comment by vinllen** [comment]
确认下源库的版本，如果源库是单节点，没有oplog，全量同步完是不会增量同步的。

**Comment by vinllen** [comment]
问题无反馈，暂时关闭，如果还有问题请重新打开或者新建issue
