### ISSUE TITLE
源库是主从方式部署，目标库是主从方式部署，使用mongoshake如何同步

### ISSUE THREAD

**Issue by python8384** [alibaba/MongoShake#257]
源库版本：
mongodb 3.0.12   部署方式为： 主从
目标库：
mongodb 3.0.12   部署方式：  主从
mongoshake 版本： 2.0.8
使用 oplog 或者 all 同步模式，启动时都会报错，报错信息为：[CRIT] (mongoshake/collector.(*ReplicationCoordinator).sanitizeMongoDB:136) There has no oplog collection in mongo db server Oplog Tailer initialize failed: no oplog ns in mongo.
根据报错信息，查看源码，发现 session.go 源文件中，OplogNS = oplog.rs 
使用主从方式部署，生成oplog的集合名称为： oplog.$main  所以，修改 OplogNS = oplog.$main 
然后，重新编译生成可执行文件，可以正常启动和同步。
现在不太确定，这种修改方式是否就支持主从方式部署的MongoDB集群之间的同步，稳定性如何？

**Comment by vinllen** [comment]
这个报错得找下原因，看看是不是源端权限不够，或者mongo_connect_mode配置出错，导致读取Oplog失败了。

**Comment by vinllen** [comment]
问题无反馈，暂时关闭，如果还有问题请重新打开或者新建issue

**Comment by cloudufull** [comment]
我也遇到 相同的问题了
