### ISSUE TITLE
MongoDB 4.2 删除了OP_COMMAND(2010), 导致同步异常

### ISSUE THREAD

**Issue by luoffei** [alibaba/MongoShake#259]
https://jira.mongodb.org/browse/SERVER-33135

**Comment by vinllen** [comment]
你同步异常报错发出来看下，op_command是内部的命令，但是正常同步都是直接直接走的普通命令，不会用到这个

**Comment by luoffei** [comment]
MongoShake日志

> [2019/11/09 19:08:24 CST] [CRIT] [executor.(*Executor).execute:97] Replayer-2, executor-2, oplog for namespace[ngiam-db.user] op[i] failed. error type[*errors.errorString] error[EOF], logs number[1], firstLog: [{ts 6757368554711941121} {op i} {g cq} {ns test.user} {o [{_id ObjectIdHex("5dc6fee610a9e179874b2b0f")} {user zhangsan}]} {o2 map[]} {uk map[]} {lsid <nil>} {fromMigrate false}]

MongoDB日志

> 2019-11-11T11:13:33.241+0800 E  -        [conn58] Assertion: Location34348: cannot translate opcode 2010 \src\src\mongo/rpc/message.h 120

**Comment by vinllen** [comment]
MongoDB是什么版本？云上的吗？

**Comment by luoffei** [comment]
> MongoDB是什么版本？云上的吗？

MongoDB 4.2.1   本地的

**Comment by vinllen** [comment]
你能在oplog表里面找一下报错的这条原始日志吗？

**Comment by vinllen** [comment]
```
use local;
db.oplog.rs.find({"o._id": ObjectId("5dc6fee610a9e179874b2b0f")})
```

**Comment by luoffei** [comment]
`{
    "ts" : Timestamp(1573322470, 1),
    "t" : NumberLong(1),
    "g" : "cq",
    "h" : NumberLong(0),
    "v" : 2,
    "op" : "i",
    "ns" : "test.user",
    "ui" : UUID("f87d77b5-b8d8-4978-99fe-fc1b953ca1be"),
    "wall" : ISODate("2019-11-10T02:01:10.985+08:00"),
    "o" : {
        "_id" : ObjectId("5dc6fee610a9e179874b2b0f"),
        "user" : "lynnrowe"
    }
}`

**Comment by vinllen** [comment]
你这个mongoshake同步的跟mongodb的日志时间点对不上，确定是这个报错吗？

**Comment by luoffei** [comment]
> 你这个mongoshake同步的跟mongodb的日志时间点对不上，确定是这个报错吗？

清库重试了很多次, mongoshake是之前的

> [11:13:32 CST 2019/11/11] [CRIT] (mongoshake/executor.(*Executor).execute:97) Replayer-2, executor-2, oplog for namespace[ngiam-db.user] op[i] failed. error type[*errors.errorString] error[EOF], logs number[1], firstLog: [{ts 6757368554711941121} {op i} {g cq} {ns test.user} {o [{_id ObjectIdHex("5dc6fee610a9e179874b2b0f")} {user lynnrowe}]} {o2 map[]} {uk map[]} {lsid <nil>} {fromMigrate false}]

**Comment by vinllen** [comment]
`{g: cq}`你这个是有gid，代码你们自己改过吧？有g字段的话是会默认走op_command的

**Comment by luoffei** [comment]
嗯

**Comment by vinllen** [comment]
这个可以到3.x或者4.0版本，4.2版本抛弃op_command，后面可能需要换种方式进行支持

**Comment by luoffei** [comment]
> 这个可以到3.x或者4.0版本，4.2版本抛弃op_command，后面可能需要换种方式进行支持

嗯 准备切换到4.0版本了
