### ISSUE TITLE
shake自动重启问题？

### ISSUE THREAD

**Issue by flykingmz** [alibaba/MongoShake#263]
: { name: "soapa-rs", ackTs: Timestamp 1575457254000|1, syncTs: Timestamp 1575457254000|1 }, upsert: true } ], writeConcern: { getLastError: 1, w: "majority" }, ordered: true }
- **child process[29661] terminated .**
- read zero from pipe of children.
- extra info: - normal termination, exit status = 250

- **process: "./collector.linux" exit, restart it**
- execute: "./collector.linux"
[19:00:54 CST 2019/12/04] [CRIT] (mongoshake/collector/docsyncer.LoadCheckpoint:42) CheckpointManager close iterator failed. not authorized on mongoshake to execute command { find: "ckpt_default", filter: {}, skip: 0 }
Oplog Tailer initialize failed: CheckpointManager upsert map[ackTs:6766537382175965185 name:soapa-rs syncTs:6766537382175965185] error. not authorized on mongoshake to execute command { update: "ckpt_default", updates: [ { q: { name: "soapa-rs" }, 

mongodb版本：3.4.2
mongoshake版本：2.2.0
同步模式：all
使用Hypervisor启动，每过一段时间进程就中断，被Hypervisor重新拉起

**Comment by vinllen** [comment]
使用hypervisor启动的，如果中间shake挂了，是会被不断拉起的。你这个错误挺明显了，权限不够。
