### ISSUE TITLE
v2.2 sharding cluster sync to sharding cluster : [CRIT] [docsyncer.(*DBSyncer).Start.func2:310]

### ISSUE THREAD

**Issue by bagechashu** [alibaba/MongoShake#265]
insert docs with length[5120] into ns {db collection} of dest mongo failed[read tcp source ip:tcp -> dest mongos ip:tcp: i/o timeout]. first doc: &{0    [] map[] map[] <nil> false map[] 0 0}

```collector.conf
replayer.collection_parallel = 6
replayer.document_parallel = 32
replayer.document_batch_size = 5120
```

**Comment by bagechashu** [comment]
source and dest mongo sharding cluster version on aliyun  v4.0.4 

I alse test anther config
```
replayer.collection_parallel = 6
replayer.document_parallel = 32
replayer.document_batch_size = 8192
```
```
replayer.collection_parallel = 6
replayer.document_parallel = 64
replayer.document_batch_size = 5120
```
```
replayer.collection_parallel = 6
replayer.document_parallel = 48
replayer.document_batch_size = 8192
```

After the above error is reported several times, the full synchronization is interrupted

**Comment by vinllen** [comment]
It looks like the connection is timeout, please decrease the "document_batch_size" less than 1024 and retry. This problem maybe caused by the batch size too larger.
