### ISSUE TITLE
"load illegal record map"

### ISSUE THREAD

**Issue by burnsjake** [alibaba/MongoShake#267]
I am able to connect to my mongo 3.6.3 source and my mongo 4.2 target. When I try to run mongoshake it errors out with:

Oplog Tailer initialize failed: LoadCheckpoint load illegal record map[_id:ObjectIdHex("5d82e23f47922a3bb5ce81d4") ckpt:6768908414576755093 name:rs01]. ok1[true] ok2[false]
[20:21:46 UTC 2019/12/10] [WARN] (mongoshake/common.Goodbye:214)

**Comment by vinllen** [comment]
Do you upgrade your MongoShake version from less than or equal to 2.0 to 2.2?

**Comment by coderw184** [comment]
I ran into the same situation where the source and destination versions were both 3.4.2

**Comment by coderw184** [comment]
It has been solved.https://www.codeleading.com/article/97702603032/

**Comment by vinllen** [comment]
Yes, mongoshake v2.2 is not compatible with older versions.
