### ISSUE TITLE
修改同步模式后启动报错

### ISSUE THREAD

**Issue by joe-luolk** [alibaba/MongoShake#268]
原来sync_mode是oplog模式运行正常，修改成all模式后无法启动，报server returned error on SASL authentication step: Authentication failed，其他参数配置没变,详细信息如下：
[17:58:04 CST 2019/12/11] [INFO] (mongoshake/common.NewMongoConn:89) New session to mongodb://192.168.0.181:27017 successfully
[17:58:04 CST 2019/12/11] [INFO] (mongoshake/common.(*MongoConn).Close:94) Close session with mongodb://192.168.0.181:27017
Oplog Tailer initialize failed: server returned error on SASL authentication step: Authentication failed.
[17:58:04 CST 2019/12/11] [WARN] (mongoshake/common.Goodbye:214)

**Comment by vinllen** [comment]
server returned error on SASL authentication step: Authentication failed
看下账号的权限，集群版有读config server的权限

**Comment by joe-luolk** [comment]
> server returned error on SASL authentication step: Authentication failed
> 看下账号的权限，集群版有读config server的权限
账号是root权限，复制集架构没有分片

**Comment by vinllen** [comment]
@joe-luolk 发下版本号和配置信息 @lydarkforest 看下这个问题

**Comment by joe-luolk** [comment]
> @joe-luolk 发下版本号和配置信息 @lydarkforest 看下这个问题
测试的单节点副本,版本：mongoshake-v2.2.0
collector.conf:
mongo_urls = mongodb://repl:123456@192.168.1.105:27017
mongo_cs_url =
mongo_connect_mode = standalone
collector.id = mongoshake
sync_mode = all
http_profile = 9100
system_profile = 9200
log.level = info
log.dir =
log.file = collector.log
log.buffer = true
filter.namespace.black =
filter.namespace.white = test.daily_log;test.all_log
filter.pass.special.db =
oplog.gids =
shard_key = collection
worker = 8
worker.batch_queue_size = 64
adaptive.batching_max_size = 1024
fetcher.buffer_capacity = 256
worker.oplog_compressor = none
tunnel = direct
tunnel.address = mongodb://127.0.0.1:27017
context.storage = database
context.storage.url = mongodb://127.0.0.1:27017
context.storage.db = mongoshake
context.storage.collection = ckpt_default
context.start_position = 1970-01-01T00:00:00Z
master_quorum = false
transform.namespace = test1.daily_log;test1.all_log
dbref = false
movechunk.enable = false
movechunk.interval = 1000
replayer.dml_only = true
replayer.executor.upsert = false
replayer.executor.insert_on_dup_update = false
replayer.conflict_write_to = none
replayer.durable = true
replayer.collection_parallel = 6
replayer.document_parallel = 8
replayer.document_batch_size = 256
replayer.collection_drop = false
filter.orphan_document = false
