### ISSUE TITLE
是否支持多个单独副本集表同步到一个表

### ISSUE THREAD

**Issue by joe-luolk** [alibaba/MongoShake#269]
当前mongoshake版本是否支持部署有多个独立的副本集，需要将不同源里的相同表或不同表同步到本地同一个表中进行数据的聚合的场景

**Comment by MaxLinyun** [comment]
支持的，细节可以参考wiki的内容

**Comment by joe-luolk** [comment]
> 支持的，细节可以参考wiki的内容
已验证，支持
