### ISSUE TITLE
receiver只有一个协程在跑，receiver.conf中replayer参数不起作用

### ISSUE THREAD

**Issue by 474199332** [alibaba/MongoShake#275]
receiver.go 92行
	/*
	 * create re-players, the number of re-players number is equal to the
	 * collector worker number to fulfill load balance. The tunnel that message
	 * sent to is determined in the collector side: `TMessage.Shard`.
	 */
	repList := make([]tunnel.Replayer, conf.Options.ReplayerNum)
	for i := range repList {
		repList[i] = replayer.NewExampleReplayer(i)
	}

replayer.go  43行（我加了id进去，打印发现全部是0）
func NewExampleReplayer(id int) *ExampleReplayer {
	LOG.Info("ExampleReplayer start. pending queue capacity %d", PendingQueueCapacity)
	er := &ExampleReplayer{
		pendingQueue: make(chan *MessageWithCallback, PendingQueueCapacity),
		id:           id,
	}
	go er.handler(id)
	return er
}

**Comment by vinllen** [comment]
默认一个表只会hash到一个replayer，修改shard_key为id可以hash到多个replayer，但不能保证表内顺序

**Comment by TIMPLIN** [comment]
麻烦问下老哥，最后是怎么解析raw中的信息的，这个receiver源码你是怎么改的呀，receiver是要部署在接收kafka数据的服务中吗
