### ISSUE TITLE
怎么增大mongodb logs_get的获取速度

### ISSUE THREAD

**Issue by 474199332** [alibaba/MongoShake#277]
目前最大速度是28000，还不够，我希望增大到60000以上

**Comment by 474199332** [comment]
![image](https://user-images.githubusercontent.com/18642139/71404168-cca65e00-266c-11ea-94a6-944eee5e04e7.png)

**Comment by 474199332** [comment]
![image](https://user-images.githubusercontent.com/18642139/71404334-3a528a00-266d-11ea-9af0-53b443dccfec.png)

**Comment by vinllen** [comment]
可以考虑部署离源端近一些，修改驱动的参数也可以一定程度提高，不过单表6w的qps？有这么大的写入量？

**Comment by 327** [comment]
哥们，你 26940 的速度怎么配置的，我不管怎么修改配置，拉取速度都是 8192。

**Comment by 474199332** [comment]
@327 collector中的oplog_reader修改源码，如果你的模式是oplog的话
![image](https://user-images.githubusercontent.com/18642139/71510373-a7faf200-28c9-11ea-8c64-1c762a25efa6.png)

**Comment by bolongsir** [comment]
![image](https://user-images.githubusercontent.com/18642139/71510350-91ed3180-28c9-11ea-84c6-45527dcfabbe.png)

**Comment by bolongsir** [comment]
![image](https://user-images.githubusercontent.com/18642139/71510379-af220000-28c9-11ea-87f6-fdd94b1df81a.png)

**Comment by 327** [comment]
我是通过 oplog。
你是试了改配置项不行后，才想改源码的吗？
还是一开始就知道配置项不起作用

**Comment by 474199332** [comment]
要修改源码的，这个写死了，我是因为有其他的业务需求，我是直接在collector改造然后自己写完同步逻辑的，并不需要receiver
修改源码的地方是
collecotr =》 oplogsyncer =》 oplog_reader.go的212行

	reader.firstRead = false

	// rebuild syncerGroup condition statement with current checkpoint timestamp
	reader.conn.Session.SetBatch(15360) //
	reader.conn.Session.SetPrefetch(0.25)
	reader.oplogsIterator = reader.conn.Session.DB(LocalDB).C(utils.OplogNS).
		Find(reader.query).LogReplay().Tail(time.Second * tailTimeout) // this timeout is useless
	return

**Comment by 474199332** [comment]
@327 我之前试过一次拉取102400的速度

**Comment by 327** [comment]
非常感谢了。我之前增量同步有问题，导致目的端和源端，始终有 3 个小时的时间差。
