### ISSUE TITLE
版本和curl的问题

### ISSUE THREAD

**Issue by digitzone** [alibaba/MongoShake#281]
您好：
咨询2个问题
1 1.X 和 2.X 版本是什么关系，线上环境建议用哪个？
2 我现在用的1.4.5版本，curl里会带出密码，怎么才能屏蔽这个curl的功能？或者把curl里的密码隐藏？

谢谢！

**Comment by vinllen** [comment]
1. 1.x版本目前只支持增量的同步，2.0开始支持了全量同步，如果你们只是增量同步的需求，可以用1.4的最新版本，如果希望用到全量同步，可以使用2.0版本，2.2版本目前有缺陷，我们将会进行更新到2.4版本。
2. 你是说info里面的配置信息，感谢反馈信息，后面我们会进行修改，你说的这个问题目前这块的确考虑不全。目前暂时没办法禁用。

**Comment by digitzone** [comment]
> 1. 1.x版本目前只支持增量的同步，2.0开始支持了全量同步，如果你们只是增量同步的需求，可以用1.4的最新版本，如果希望用到全量同步，可以使用2.0版本，2.2版本目前有缺陷，我们将会进行更新到2.4版本。
> 2. 你是说info里面的配置信息，感谢反馈信息，后面我们会进行修改，你说的这个问题目前这块的确考虑不全。目前暂时没办法禁用。

感谢您的回答！！！

**Comment by vinllen** [comment]
关于info里面密码的屏蔽完成修改，将会release在v2.4版本
