### ISSUE TITLE
指定库同步

### ISSUE THREAD

**Issue by zlgwarm** [alibaba/MongoShake#282]
你好。如果我只需要同步指定的库，如何修改配置文件，源实例指定库同步到目标实例中，怎么修改配置文件

**Comment by vinllen** [comment]
有个filter.namespace.whitelist的选项，指定你的同步的库即可

**Comment by yhydev** [comment]
我这边用 filter.namespace.whitelist 指定源库的namespace，但是同步后，把全部的数据库给同步了，请问还需要其他的配置吗？
