### ISSUE TITLE
mongodb同步时出错of dest mongo failed[no progress was made executing batch write op in datacore.riskengine_io after 5 rounds (0 ops completed in 6 rounds total)]. first doc: &{0    [] map[] map[] <nil> false map[] 0 0}

### ISSUE THREAD

**Issue by 463419442** [alibaba/MongoShake#283]
mongodb的同步源版本是3.4.6复制集合，目标版本是4.2.2的mongodb版本。mongoshake的版本是mongoshake-v2.2.0的二进制版本

**Comment by vinllen** [comment]
relate: 
* https://jira.mongodb.org/browse/SERVER-22971
* https://jira.mongodb.org/browse/SERVER-39296

这个看起来是本身目的端集群状态存在问题了，建议排查一下，普通的insert写入失败。从源码上看，是batch写入，从mongos到mongod的尝试超过5次了。
![image](https://user-images.githubusercontent.com/6987398/72638780-244f9500-399f-11ea-8db7-d61211c28b89.png)
