### ISSUE TITLE
能提供一下最新的movechunk的处理逻辑吗？

### ISSUE THREAD

**Issue by huntlyroad** [alibaba/MongoShake#284]
看见最新的2.2.0版本中添加了支持movechunk操作的代码，不过貌似没找到相关的wiki，不太理解这个改动具体的处理逻辑是什么，如果能加入wiki就最好了

**Comment by vinllen** [comment]
2.2关于move chunk的处理目前还没有稳定，现在逻辑比较繁琐而且存在一些corner case，我们会年后升级到2.4版本，修改为更加容易处理的方式。2.2的细节目前可以不用过多关注
