### ISSUE TITLE
请问基于开源mongodb的双活方案中提到的proxy有相关的开源项目吗

### ISSUE THREAD

**Issue by monkeyWie** [alibaba/MongoShake#286]
我看架构介绍中有介绍到，但是比较模糊。
![image](https://user-images.githubusercontent.com/13160176/74095427-6ea1dd00-4b2b-11ea-8989-415e645e1e44.png)

**Comment by vinllen** [comment]
这部分没有提供，这个proxy需要自己去构建，目前来说这个方案比较困难，需要用户自己参与进行proxy层面的开发。后面我们会给MongoDB提交关于gid内核的patch，MongoDB review可以后才会合入，不过人力问题，这部分提交可能会比较晚。

**Comment by monkeyWie** [comment]
好的，谢谢大佬回复 😊
