### ISSUE TITLE
全量同步完之后没有进行增量同步

### ISSUE THREAD

**Issue by monkeyWie** [alibaba/MongoShake#287]
```
sync_mode = all
transform.namespace = db1:db2
```
在`transform.namespace`选项开启时会出现不增量同步的情况，不设置这个选项的时候是没问题的，作者大大帮忙看看是否正常？

还有个疑问，增量同步好像并不是实时的，是隔一小段时间同步一次吗？

**Comment by vinllen** [comment]
1. `transform.namespace`开启出现不增量同步的情况。日志层面是否有报错？不同步是如何确定的，查看db2的表是否有数据进行修改？
2. 增量同步是实时的，只要源端有数据就会同步，最大间隔默认是1秒钟

**Comment by monkeyWie** [comment]
@vinllen 1. 日志没有发现什么异常，db2的表数据总数在全量同步完之后就不再新增了，db1那边还在一直在写数据

![image](https://user-images.githubusercontent.com/13160176/74498585-059bda00-4f1c-11ea-8522-510356f51e29.png)

**Comment by vinllen** [comment]
@monkeyWie 钉钉加我私聊下，readme上有钉钉群的加入方式

**Comment by monkeyWie** [comment]
跟大佬私聊之后，发现改用2.0.7版本就可以了。
