### ISSUE TITLE
通过mongoshake做全量同步的时候报错E11000 duplicate key error collection 调整参数后不奏效

### ISSUE THREAD

**Issue by amber-one** [alibaba/MongoShake#288]
数据源端为副本集，目的端也是副本集，在利用mongoshake对10张表进行数据同步时有一张表在全量同步阶段报E11000 duplicate key error collection，之后同步进程停止。查看详细日志：
insert docs with length[256] into ns { } of dest mongo failed[E11000 duplicate key error collection:  index: _id_ dup key: { : }]. first doc: &{0    [] map[] map[] <nil> false map[] 0 0} ，然后查看操作文档调整了相关参数  replayer.executor.upsert = true
replayer.executor.insert_on_dup_update = true  并将数据清除重新同步，错误依旧。

**Comment by vinllen** [comment]
确认下是否的确目的端_id或者unique key重复了

**Comment by y123456yz** [comment]
@vinllen  建议这个问题向mongorestore一样，重复了报个错就好，不要crash。
或者增加个配置，我这遇到同样的情况，mongoSharke同步多次crash。后面还是用mongodump mongorestore恢复同步的

**Comment by vinllen** [comment]
@y123456yz  全量阶段，v2.4版本已经进行改进，近期会release
