### ISSUE TITLE
开启命名空间转换，导致全量同步后不会增量同步

### ISSUE THREAD

**Issue by yhydev** [alibaba/MongoShake#289]
版本是2.2.1 release

配置文件是基于默认配置文件的基础下，修改了以下内容
源地址
通道地址
白名单
命名空间转换

源地址是复制集，通道是分片

**Comment by yhydev** [comment]
好像是命名空间转换不起作用。

**Comment by vinllen** [comment]
2.2的命名空间转换存在bug，问题还没有修复

**Comment by 327** [comment]
现在哪个版本的命名空间转换能起作用？

**Comment by vinllen** [comment]
@327 2.0的最新版本。

**Comment by 327** [comment]
> @327 2.0的最新版本。

https://github.com/alibaba/MongoShake/tree/release-v2.0.8-20190930
你是指上面这个版本？

**Comment by 327** [comment]
另外，当我们需要对全局的 namespace 做转换时，比如源库叫 linde_db，目的库叫 linde_db_backup, 以下写法可行？
transform.namespace = linde_db:linde_db_backup

**Comment by vinllen** [comment]
@327 是2.0.8。可以

**Comment by 327** [comment]
由于 2.2.1 命名空间bug ,我们切换回 2.0.8，但配置文件继续使用 2.2.1 的，启动 mongoshake，报错如下：
collector.conf parse failed. couldn't found structure key's tag 'mongo_cs_url'. one must be tagged
