### ISSUE TITLE
启动mongoshake,然后停止一段时间,再次启动报错[oplog syncer default-0 load checkpoint queryTs[Timestamp(1582304516, 305)] is less than oldTs[Timestamp(1582304698, 152)], this error means user's oplog collection size is too small or document replication continues too long]

### ISSUE THREAD

**Issue by 13430647361** [alibaba/MongoShake#292]
这是详细的报错日志`(mongoshake/collector.(*OplogSyncer).LoadByDoc:420) oplog syncer default-0 load checkpoint queryTs[Timestamp(1582304516, 305)] is less than oldTs[Timestamp(1582304698, 152)], this error means user's oplog collection size is too small or document replication continues too long
panic: oplog syncer default-0 load checkpoint queryTs[Timestamp(1582304516, 305)] is less than oldTs[Timestamp(1582304698, 152)], this error means user's oplog collection size is too small or document replication continues too long [recovered]
        panic: oplog syncer default-0 load checkpoint queryTs[Timestamp(1582304516, 305)] is less than oldTs[Timestamp(1582304698, 152)], this error means user's oplog collection size is too small or document replication continues too long

goroutine 1 [running]:
main.handleExit()
        /home/zhuzhao.cx/MongoShake/src/mongoshake/collector/main/collector.go:299 +0x89
panic(0x995340, 0xc4201f3fb0)
        /home/zhuzhao.cx/go/src/runtime/panic.go:502 +0x229
vendor/github.com/vinllen/log4go.Crashf(0xaad9b9, 0xa9, 0xc420459160, 0x3, 0x3)
        /home/zhuzhao.cx/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector.(*OplogSyncer).LoadByDoc(0xc4200f8c30, 0xc420388f60, 0xbf8cf7b739bb83d2, 0x148961be22, 0xfc8e40, 0xc42035e301, 0x12)
        /home/zhuzhao.cx/MongoShake/src/mongoshake/collector/syncer.go:420 +0xfa0
mongoshake/collector.(*CheckpointManager).Load(0xc420260980, 0xc4202564cd, 0xc, 0xa809bc, 0x1)
        /home/zhuzhao.cx/MongoShake/src/mongoshake/collector/checkpoint.go:203 +0x451
mongoshake/collector.(*CheckpointManager).loadAll(0xc420260980, 0x0, 0x0)
        /home/zhuzhao.cx/MongoShake/src/mongoshake/collector/checkpoint.go:169 +0x8a3
mongoshake/collector.(*ReplicationCoordinator).startOplogReplication(0xc4201be460, 0xc420362b40, 0xc420362b70, 0x9, 0xc4200f8be8)
        /home/zhuzhao.cx/MongoShake/src/mongoshake/collector/replication.go:443 +0x832
mongoshake/collector.(*ReplicationCoordinator).Run(0xc4201be460, 0xc4201be460, 0x1)
        /home/zhuzhao.cx/MongoShake/src/mongoshake/collector/replication.go:100 +0x598
main.startup()
        /home/zhuzhao.cx/MongoShake/src/mongoshake/collector/main/collector.go:102 +0x2d2
main.main()
        /home/zhuzhao.cx/MongoShake/src/mongoshake/collector/main/collector.go:83 +0x621`

**Comment by vinllen** [comment]
你用的是v2.2.1的版本吧，这个报错表示停止这段时间，源端Oplog已经被清掉了。上一次拉取的位点是1582304516，再次启动拉取的最老的位点是1582304698。

**Comment by 13430647361** [comment]
是的,用的mongo-shake-v2.2.1.tar.gz版本,这里的意思就是我目前能获取的位点的最小值已经比我上一次存放的位点值更大了,所以我应该删除上次checkpoint信息,让它重新运行

**Comment by vinllen** [comment]
重新同步的话，上一次位点到本次开始位点中间的数据就已经丢失了。
比如上一次同步到10点，然后中断了，本次重启最老的Oplog是11点，那么10-11点中间产生的增量数据就会丢失了。
