### ISSUE TITLE
主从架构用keyfile认证的模式，需要设置什么样的用户权限来同步到副本集？

### ISSUE THREAD

**Issue by rainhan99** [alibaba/MongoShake#295]
同步一直提示[17:47:24 CST 2020/02/27] [CRIT] (mongoshake/collector.(*ReplicationCoordinator).sanitizeMongoDB:220) no oplog ns in mongo. See https://github.com/alibaba/MongoShake/wiki/FAQ#q-how-to-solve-the-oplog-tailer-initialize-failed-no-oplog-ns-in-mongo-error，

**Comment by vinllen** [comment]
wiki上说的方式都试过还是不行吗？
账号权限问题，连接串是否配置正确。

**Comment by rainhan99** [comment]
测试过了，都一样的提示，配置文件如下：
mongo_urls = mongodb://root:123456@172.16.20.61:27017  //主从mongodb
mongo_connect_mode = standalone
sync_mode = all
tunnel.address = mongodb://root:test123u@172.16.20.206:27017  //副本集mongodb
其他都是默认配置

**Comment by rainhan99** [comment]
源库是mongodb主从的,配置文件
bind_ip = 0.0.0.0
fork = true
pidfilepath = /var/run/mongodb/mongod.pid
logpath = /var/log/mongodb/mongod.log
unixSocketPrefix = /var/run/mongodb
dbpath = /var/lib/mongodb
journal = true
keyFile = /opt/keyfile
auth = true
oplogSize = 2048
master = true

**Comment by vinllen** [comment]
keyfile认证的现在还没支持，SSL这部分会在2.4（2.4.0，计划3月中发布）或者2.4.1进行支持。大概率是2.4.1版本里面做掉，排期可能要到4月差不多。

**Comment by rainhan99** [comment]
感谢，希望工具越来越强大

**Comment by vinllen** [comment]
#236
