### ISSUE TITLE
在做全量同步后发现在做前台建索引

### ISSUE THREAD

**Issue by GDkunban** [alibaba/MongoShake#296]
前几天在迁移几张数千万的表格时发现：这个工具是在数据迁移完全备份之后才开始前台建索引？
前端建索引会引起数据库无法提供服务，中信希望作者后续可以改进这个点吧，谢谢~
目前我的思路是这两个：
一是全量同步数据表之前建好索引，但这恐怕会影响同步效率；
二是在全量完成后在后台创建建索引。

**Comment by vinllen** [comment]
感谢反馈，目前的确是全量同步结束以后在前台建索引，这块也是一个权衡的结果，如果全量同步之前，同步的整体效率会变低。后台建索引这个思路值得思考，后面我会评估一下这个方案。

**Comment by GDkunban** [comment]
> 感谢反馈，目前的确是全量同步结束以后在前台建索引，这块也是一个权衡的结果，如果全量同步之前，同步的整体效率会变低。幕后索引这个想法值得思考，后面我会评估一下这个方案。

生产中更希望能够实时进行使用而不锁库。最后：感谢有这款工具，怒赞100个。

**Comment by ipcpu** [comment]
我也发现这个问题，全量同步后，目标库建索引会导致无法连接，mongo-shake进程会退出。

**Comment by vinllen** [comment]
@ipcpu 是建索引导致连接超时退出？

**Comment by vinllen** [comment]
2.4已经增加了后台建索引选项
