### ISSUE TITLE
源和目的都是同一数据库是同步表出现的疑问

### ISSUE THREAD

**Issue by GDkunban** [alibaba/MongoShake#300]
具体场景：
transform: fromDbName1.fromCollectionName1:toDbName1.toCollectionName1
transform.namespace =A.B:A.C    # 其中A是数据库，B是源表名，C是目的表名（）
程序运行报错：目标库已经存在，实际上C表在数据库中不存在

**Comment by vinllen** [comment]
1. 你用的是哪个版本？
2. 这种db到自身db的只能支持全量同步，sync_mode是否选择了全量？

**Comment by vinllen** [comment]
IMPROVE: v2.4添加强校验，自身到自身的同步，sync_mode强制只能为全量。
