### ISSUE TITLE
建议源集群的url地址配置增加通过mongos自动识别的功能，线上一个集群几十个分片，上百个节点，每次配置过程比较心累

### ISSUE THREAD

**Issue by y123456yz** [alibaba/MongoShake#301]
建议源集群的url地址配置增加通过mongos自动识别的功能，线上一个集群几十个分片，上百个节点，每次配置过程比较心累

是否可以支持只配置一个源集群mongos，就可以自动识别到所有节点，不用人肉配置，分片太多，有点累

**Comment by vinllen** [comment]
分片的地址可以通过mongos或者cs拿到，账号密码可能每个分片都不一样，这个不配置分片你有什么好的建议吗？

**Comment by y123456yz** [comment]
@vinllen  我们这默认搭建集群所有分片都是一样的，可能忽略了有些集群分片账号密码不一样的情况。
