### ISSUE TITLE
mongoshake oom 问题

### ISSUE THREAD

**Issue by Robert87666** [alibaba/MongoShake#303]
想同步阿里云副本集云数据库mongodb到本地ECS自建单实例mongodb数据库时，
启动 ./collector.linux -conf=collector.conf 后，没多久就因oom中断了。dmesg有相信信息。

云数据库mongodb3.4版本 
本地mongodb 3.4.24版本

collector.conf
mongo_urls = 云数据库连接地址
tunnel.address = mongodb://127.0.0.1:14823  （因为是同一台ECS机器）
sync_mode = oplog  只想增量同步
replayer.dml_only = false    想同步DDL操作

mongoshake 是最新版本V2.2.1

希望能在这里得到帮助。

**Comment by vinllen** [comment]
![image](https://user-images.githubusercontent.com/6987398/76616973-32b1cb80-6560-11ea-86d9-4474509b552f.png)
![image](https://user-images.githubusercontent.com/6987398/76616747-a99a9480-655f-11ea-957b-96646a204ce5.png)
看这个火焰图使用的确是不合理，oom的的时候内存使用超过了20G。定位发现是用户的oplog巨大无比导致的。
降低fetcher.buffer_capacity的参数，调到1再试一下。

**Comment by Robert87666** [comment]
@vinllen 经过修改参数后，mongoshake进程内存消耗会维持在几G到20G之间，是不会oom了，但是目标库会oom
