### ISSUE TITLE
4.2版本的分布式功能当前支持吗？单向同步场景

### ISSUE THREAD

**Issue by y123456yz** [alibaba/MongoShake#306]
4.2版本的分布式功能当前支持吗？单向同步场景，谢谢

@vinllen

**Comment by vinllen** [comment]
分布式事务当前还不支持

**Comment by zkl94** [comment]
`如果目的端是sharding，暂时不支持applyOps命令，包括事务`

@vinllen 请问有提供 目的端是 sharding 的事务支持的roadmap吗？谢谢

**Comment by vinllen** [comment]
这个可能会放到2.6版本进行支持，具体的时间排期还没有定
