### ISSUE TITLE
有计划新增直接往ES 写入的tunnel吗？

### ISSUE THREAD

**Issue by yilezhu** [alibaba/MongoShake#308]
有计划新增直接往ES 写入的tunnel吗？这块场景还是挺多的，在MongoDB分片集群场景中，在MongoDB查询出现瓶颈的时候，有时候会需要把MongoDB数据实时备份到ES中来优化查询性能，这时候对于不熟悉go的人员来说，如果通过重写源码来新增这个tunnel有一定的门槛。当然kafka也能满足，但是这增加了额外部署kafka的成本。所以想问下，官方有计划新增直接往ES 写入的tunnel吗？

**Comment by vinllen** [comment]
该需求我们会评估一下

**Comment by dengdongshan** [comment]
hbase也想要。
用phoneix写入

**Comment by vinllen** [comment]
hbase是什么场景？拉mongodb的oplog进行分析吗？还是做ap计算的场景？

**Comment by dengdongshan** [comment]
> hbase是什么场景？拉mongodb的oplog进行分析吗？还是做ap计算的场景？

地区系统的数据汇总到云数据中心，把monggodb的表数据同步过来就OK。

**Comment by vinllen** [comment]
同步到hbase后的数据是用于做实时分析的？
