### ISSUE TITLE
实时限速调整，能否支持？ 数据同步过程中发现速度太快，主压力过大，从跟不上

### ISSUE THREAD

**Issue by y123456yz** [alibaba/MongoShake#310]
1. 这时候是否可以在线实时调整同步速度，当前配置文件可以通过线程数来解决，但是每次需要重启，感觉无法实时在线调整。
@vinllen

**Comment by vinllen** [comment]
增量阶段有限速，可以看下restful的sentinel接口，全量阶段目前还没有，后面会加上。

**Comment by y123456yz** [comment]
增量压力一般不大，主要是在全量的时候

**Comment by vinllen** [comment]
2.4.1版本已经支持先建后台索引，再进行全量同步https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E#22-%E7%BB%93%E6%9E%84%E5%8C%96%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0
