### ISSUE TITLE
主从架构的master mongodb同步到另外一个主从架构的master mongodb不成功

### ISSUE THREAD

**Issue by steedyu** [alibaba/MongoShake#312]
两个主从架构都是开启auth=true，
都创建了一个root和{role:"dbOwner", db:"local"}的权限用户

mongo_urls = mongodb://username:password@10.1.1.1:1001 #源端连接串信息，逗号分隔不同的mongod
sync_mode = all # all 表示全量+增量，document表示仅全量，oplog表示仅增量
tunnel.address = mongodb://username:password@10.5.5.5:5005, #目的端连接串信息，逗号分隔不同的mongod
mongo_connect_mode = standalone

采用如上配置
启动即报错
Oplog Tailer initialize failed: no oplog ns in mongo. See https://github.com/alibaba/MongoShake/wiki/FAQ#q-how-to-solve-the-oplog-tailer-initialize-failed-no-oplog-ns-in-mongo-error

检查权限没有问题，是不是不支持 主从架构的主往另一个主从架构的主进行同步数据？

**Comment by vinllen** [comment]
oplog是否真实存在？单节点没有oplog。

**Comment by steedyu** [comment]
单节点 local表中又oplog数据，但是 就是直接报上面哪个错，我看了下你们源码，看着你们只支持repel set的方式吧？

**Comment by vinllen** [comment]
支持副本集形态的单节点，纯粹的单节点不应该有oplog表
