### ISSUE TITLE
是否可以考虑先同步索引，然后在开始做全量数据同步，这样在某些情况下更加稳定，如原集群索引没有加backgroud

### ISSUE THREAD

**Issue by y123456yz** [alibaba/MongoShake#316]
是否可以考虑先同步索引，然后在开始做全量数据同步，这样在某些情况下更加稳定，如原集群索引没有加backgroud

早期部分源集群索引添加在数据写入前，所以没有backgroud参数。
全量数据同步完后，同步索引目的集群全部阻塞了

@vinllen

**Comment by vinllen** [comment]
索引类型在2.4版本里面支持了none和foreground类型，background类型会在后续小版本加上，不过先同步索引，再全量；还是先全量，再同步索引有待进一步商榷

**Comment by vinllen** [comment]
2.4.1版本将会提供选项支持先创建background索引，再同步全量数据的策略，防止block

**Comment by vinllen** [comment]
2.4.1版本已发布
