### ISSUE TITLE
v2.4.1 github.com/vinllen/go-diskqueue

### ISSUE THREAD

**Issue by Aload** [alibaba/MongoShake#327]
go: github.com/vinllen/go-diskqueue@v1.0.0: parsing go.mod: unexpected module path "github.com/nsqio/go-diskqueue"
go: error loading module requirements

**Comment by vinllen** [comment]
currently, the library should compile by `govendor` but not `gomod`.

**Comment by Aload** [comment]
> currently, the library should compile by `govendor` but not `gomod`.

Ok mod的编译会出么？

**Comment by vinllen** [comment]
@Aload 后续可能会有计划
