### ISSUE TITLE
开启同步后，导致源mongodb cpu开销大增。

### ISSUE THREAD

**Issue by clanet** [alibaba/MongoShake#332]
源数据库大概有50个库，每秒总计500update左右的数量级。没有使用mongoshake同步时，cpu开销一般在30-50%之间波动。开启monoshake的all 同步，源库的cpu占用飙到了250%左右。这一般会是什么问题？还是说，这种开销是需要的？其他的配置大概如下
worker = 8
worker.batch_queue_size = 64
adaptive.batching_max_size = 1024
fetcher.buffer_capacity = 256
worker.oplog_compressor = none
tunnel = direct

master_quorum = false
transform.namespace =
dbref = false
replayer.dml_only = true
replayer.executor.upsert = false
replayer.executor.insert_on_dup_update = false
replayer.conflict_write_to = none
replayer.durable = true
replayer.collection_parallel = 6
replayer.document_parallel = 8
replayer.document_batch_size = 256
replayer.collection_drop = false

**Comment by vinllen** [comment]
全量阶段还是增量阶段？全量来说，是扫表操作，并发度越高对源目的端的性能消耗会越大。增量来说，是拉取增量oplog，写入的qps越大这个cpu消耗也会越大。

**Comment by clanet** [comment]
在增量阶段有这样的开销增加。
这个和update的qps是线性关系吗？但是增加的感觉太夸张了。。。源数据库的cpu开销能增加个5倍。

**Comment by vinllen** [comment]
5倍是有点多，别的业务量都正常吗？有整体启动同步前后的监控曲线吗？包括内存，cache等开销。mongostat看过吗？

**Comment by clanet** [comment]
mogostat看没什么异常。
就是command会大幅飙升，正常业务command数在0-10之间。开了同步之后，command大概到200左右。

**Comment by vinllen** [comment]
有没有调用链或者火焰图之类的，能看到调用开销的
