### ISSUE TITLE
mongodb+srv 不能连接

### ISSUE THREAD

**Issue by jren2019** [alibaba/MongoShake#333]
mongodb+srv://admin:password@userle-xnrav.gcp.mongodb.net/TEST

我想同步这样的数据库，mongoshake连接不上？应该怎样处理，求指点

**Comment by vinllen** [comment]
目前driver层面还不支持这种模式

**Comment by keidrych** [comment]
mongo+srv URI support for mgo driver
https://github.com/globalsign/mgo/pull/393/files
