### ISSUE TITLE
全量同步过程中，mongoshake i/o timeout, 进程down了，重启启动报错

### ISSUE THREAD

**Issue by uxun** [alibaba/MongoShake#335]
mongoshake2.0.7
mongodb 4.0.12

进程i/o timeout
[2020/04/30 20:01:51 CST] [CRIT] 
[collector.(*ReplicationCoordinator).startDocumentReplication.func1:257] 
document replication for url=mongodb://tcpxx/tb failed. document syncer sync ns {tb sync_order} to {tb sync_order} failed.
Get next document from ns {TmsTracking sync_order} of src mongodb failed.get next doc failed. release oplogsIterator, 
read tcp ip1:46964->ip2:63101: i/o timeout

重启后
[docsyncer.IsShardingToSharding:46] replication from replica to replica
[docsyncer.StartDropDestCollection:63] ns {db tb} to be synced already exists in dest mongodb

**Comment by vinllen** [comment]
你是全量阶段中断的，重启后因为表之前已经复制过了，所以重启会报错已经存在。
参考：https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E6%8A%A5%E9%94%99ns-xx-yy-to-be-synced-already-exists-in-dest-mongodb

**Comment by uxun** [comment]
@vinllen 你好，这类报错有出现过嘛  i/o timeout,指的是目标库的i/o, 还是源库的i/o 问题
panic: splitter reader[DocumentReader src[mongodb://use:***@ip:port/] ns[{db tb}] query[map[]]] get next document failed: read tcp 目标库:port->源库:port: i/o timeout

goroutine 491 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xcc7e0b, 0x2, 0xc42273bf98, 0x1, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1(0xc4202c36e0, 0xc4202501b0, 0xc4203c8780, 0xc42014f840, 0xc420440050)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:417 +0xeb
created by mongoshake/collector/docsyncer.(*DBSyncer).collectionSync
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:409 +0x2cc

**Comment by vinllen** [comment]
reader是读相关的，属于源库的。写相关的是目的库。
看下网络，源库mongodb日志确认下原因

**Comment by yuwei43** [comment]
请问下现在全量同步支持断点续传了嘛~  我们也遇到了这个问题。
因为海外到国内的网络IO会出现问题，在全量同步的时候会报这个问题，就会自动停止当前进程，这就导致了同步无法进行。有什么方法或配置能避免mongoShake down掉嘛？

**Comment by vinllen** [comment]
断点续传还没有支持，4.4版本的MongoDB后面会考虑支持
