### ISSUE TITLE
副本集同步到分片集群

### ISSUE THREAD

**Issue by chenxy807** [alibaba/MongoShake#336]
1.配置db的分片功能
sh.enableSharding("xxx")
设置片键
sh.shardCollection("xxx.table",{"field":1})

2.开始mongoShake 开始同步

3.同步结果
xxx.table 的数据全部到同一个shard，没有分片

请问下，这个怎么解决？

**Comment by vinllen** [comment]
是按hash还是range的？你这个是数据量少吧，chunk没写满吧？
