### ISSUE TITLE
How to find-out replication lag ! 

### ISSUE THREAD

**Issue by k-nuhdim** [alibaba/MongoShake#337]
Hello Team,

We're planning to implement mongoshake for our Production to DR syncing , so can someone please guide how we can get the replication lag , any inbuild method is there to find the lag ?

Thanks !

**Comment by vinllen** [comment]
You can call the restful API to find the result: `curl 127.0.0.1:9100/repl`.
The `lsn_ack` field means the current checkpoint position which also means all the data before this position(timestamp) has applied successfully. `now` means current time. So the gap between `now` and `lsn_ack` means the replication lag. This info can also be found on the log.

**Comment by k-nuhdim** [comment]
@vinllen  - Thanks ! it will helps a lot , I'll create a custom script using this details for monitoring replication lag. 

+ One more question - What minimum permission need to set for the mongodb user for accessing logs from source replicaset ?

user with read access on local + all other db is ok ? [Planning to use full sync + oplog ] 


Sorry for continues questions! just need to ensure all requirement is matching before implement on our production servers.

**Comment by vinllen** [comment]
If the source is replica, the minimum permission for source MongoDB is: 

- read permission of `local`
- write permission of `mongoshake`

If the source is sharding, mongoshake needs more:

- read/write permission of `config` db on config server.

**Comment by k-nuhdim** [comment]
@vinllen  Thanks for confirmation.

**Comment by k-nuhdim** [comment]
@vinllen  - 

> So the gap between now and lsn_ack means the replication lag

If there is no new write in source database then ideally this gap also will increase,right ? so we cant calculate the exact replication lag using this parameters , do we have any other options to findout the exact replication gap while we are using mongoshake for replicaset sync ?

**Comment by vinllen** [comment]
If there is no new write in source database then ideally this gap also will increase,right ?
----------
Actually, the answer is **No**. Since v3.4, MongoDB writes **noop** oplog periodically to advance the oplog Optime.
