### ISSUE TITLE
开启主备模式就卡住不走了

### ISSUE THREAD

**Issue by dx8439** [alibaba/MongoShake#338]
我用的2.4.2版本，从shard导入到副本集。两个mongoshake节点，master_quorum都设置为true，但是两个节点都是从一开始就卡住不动。但是我只运行一个节点，配置成false就运行正常。

**Comment by vinllen** [comment]
应该是抢主失败了，日志有什么报错信息吗？

**Comment by dx8439** [comment]
> 应该是抢主失败了，日志有什么报错信息吗？

没有报错，就是提示连接config成功，然后就不动了
日志就这一句
[14:52:16 CST 2020/05/07] [INFO] (mongoshake/common.NewMongoConn:73) New session to mongodb://172.17.143.93:27018 successfully

**Comment by vinllen** [comment]
打一下堆栈我看一下：
```
curl http://127.0.0.1:9100/debug/pprof/goroutine?debug=2
```

**Comment by dx8439** [comment]
> curl http://127.0.0.1:9100/debug/pprof/goroutine?debug=2

[{"Uri":"/queue","Method":"GET"},{"Uri":"/sentinel/options","Method":"POST"},{"Uri":"/sentinel","Method":"GET"},{"Uri":"/executor","Method":"GET"},{"Uri":"/conf","Method":"GET"},{"Uri":"/repl","Method":"GET"},{"Uri":"/worker","Method":"GET"},{"Uri":"/persist","Method":"GET"}]

**Comment by vinllen** [comment]
问题无反馈，暂时关闭，如果还有问题请重新打开或者新建issue
