### ISSUE TITLE
MongoShake支持多个mongodb数据源向一个mongodb数据源同步数据吗?

### ISSUE THREAD

**Issue by zhangtong123** [alibaba/MongoShake#342]

**Comment by vinllen** [comment]
支持，如果db/collection没有冲突没有问题，如果有冲突的话，全量期间，请设置`full_sync.collection_exist_no_drop = false`。此外，增量期间如果多个源对同一个文档都有修改，不保证最终一致性

**Comment by zhangtong123** [comment]
那我是否需要启动多个MongoShake去进行同步数据，单个MongoShake里面配置里面好像是不支持配置多个不同的数据源吧

**Comment by zhangtong123** [comment]
> 支持，如果db / collection没有冲突没有问题，如果有冲突的话，全量期间，请设置`full_sync.collection_exist_no_drop = false`。结果，增量期间如果多个源对同一个文档都有修改，不保证最终一致

那我是否需要启动多个MongoShake去进行同步数据，单个MongoShake里面配置里面好像是不支持配置多个不同的数据源吧

**Comment by vinllen** [comment]
需要启动多个

**Comment by zhangtong123** [comment]
> 需要启动多个

感谢解惑！
