### ISSUE TITLE
希望增加一个配置，设置更新的时候抓取整个文档还是抓取更新的字段

### ISSUE THREAD

**Issue by Raydy** [alibaba/MongoShake#350]
目前更新某个字段，抓取的json信息里面只包含变更的字段。
我想要抓取的时候，拿到变更的整个文档

**Comment by vinllen** [comment]
如果是$set，$unset更新，的确是只有变更的字段，目前没有提供更新前的整个文档。你这个需求后面我可以考虑在change stream对接的时候，添加配置项进行支持

**Comment by Raydy** [comment]
嗯嗯，好的，了解了，感谢回复。

我的需求有配置可以设置，输出变更后的整个文档。

**Comment by lanmaodage** [comment]
兄弟 我这边测试时没有在shard上加权限，这样在kafka里面看到就是更新后的整个文档，但是在生产上看到的只是更新的字段，请问一下这个是权限的问题么

**Comment by lanmaodage** [comment]
@vinllen 希望可以完善这个功能呀

**Comment by Raydy** [comment]
临时方案：

更改文件：mongoshake\common\change_stream.go
csHandler, err := client.Watch(ctx, mongo.Pipeline{}, ops.SetFullDocument(options.UpdateLookup))

更改文件：mongoshake\oplog\changestram_event.go
case "update":
oplog.Namespace = fmt.Sprintf("%s.%s", ns["db"], ns["coll"])
oplog.Operation = "u"
oplog.Query = event.DocumentKey
oplog.Object = event.FullDocument

**Comment by lanmaodage** [comment]
这个是要mongo版本>=4.0才可以的吧

**Comment by Raydy** [comment]
> 这个是要mongo版本>=4.0才可以的吧

是的
我已经做了调整，可以参考：
https://github.com/alibaba/MongoShake/pull/354

**Comment by vinllen** [comment]
感谢PR，最近休假了，下下周我review一下，大概6.4前后

**Comment by lanmaodage** [comment]
https://github.com/alibaba/MongoShake/issues/371#issuecomment-644567463
@vinllen 感谢回复。
