### ISSUE TITLE
只看到更新的字段是否是同步所用的帐号权限问题？

### ISSUE THREAD

**Issue by lanmaodage** [alibaba/MongoShake#351]
测试时没有在shard上加相应的权限，这样在kafka里面看到就是更新后的整个文档记录，但是在生产上（有授权）看到的$set $v只是更新的字段，请问一下这个是权限的问题么

确定了是用sql语句来更新值是不会打印完整文档，用robo来手动改是有完整记录
还希望可以完善这个功能呀

**Comment by vinllen** [comment]
不是更新问题，你用update $set更新产生的oplog就是增量部分，而不是全部。
问题跟 #350 重复了，先关了。

**Comment by lanmaodage** [comment]
好的，感谢感谢！
