### ISSUE TITLE
MongoShake支持集群容灾吗?

### ISSUE THREAD

**Issue by vega0707** [alibaba/MongoShake#353]
目前看源码和配置似乎没有集群的方案,如果长期运行可能会有单点故障是否有方案解决?

**Comment by vinllen** [comment]
有HA模式，关注master_quorum参数，看下文档
https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E

**Comment by vega0707** [comment]
嗯嗯,我后面看到了就关闭了,没想到大佬还特地回复一下,感谢
