### ISSUE TITLE
请问下CheckpointStartPosition是从什么地方获取到的？

### ISSUE THREAD

**Issue by srui** [alibaba/MongoShake#355]
在启动的时候，
[INFO] [coordinator.(*ReplicationCoordinator).Run:49] Collector configuration
的配置选项中，CheckpointStartPosition是从什么地方获取到的？

**Comment by vinllen** [comment]
如果给定的地址（副本集默认源库的mongoshake.ckpt_default，集群版默认cs的admin.ckpt_default）里面有checkpoint，则从给定的地址获取；如果没有，则从配置文件里面获取。
