### ISSUE TITLE
使用full_sync.reader.oplog_store_disk同步问题

### ISSUE THREAD

**Issue by maKeane** [alibaba/MongoShake#359]
场景描述：
1、源端阿里托管分片集群，目的端ECS自建单机Mongo（跨区域）
2、使用了sync_mode = all模式进行少量表测试，正常
3、使用了sync_mode = all模式进行超大表测试，全量同步(10小时)完报错，Oplog已经被覆盖
4、托管分片集群不支持修改Oplog Size，因此增加了full_sync.reader.oplog_store_disk参数为true
5、再次进行超大表测试，全量同步(10小时)完不报错，mongo shake进程持续运行，后台日志也有输出，但是增量数据没有追加
问题：
mongo shake 使用最新的2.4的版本，这个参数是否有版本限制？
full_sync.reader.oplog_store_disk设置后，拉取的oplog写入到什么地方？

**Comment by maKeane** [comment]
在mongo shake的目录下有4个文件，但是大小一直没有变化
-rw------- 1 root root      114 Jun  2 09:45 diskqueue-mgset-500463488-20200602-094516.000000.dat
-rw------- 1 root root      240 Jun  2 09:45 diskqueue-mgset-500463488-20200602-094516.meta.dat
-rw------- 1 root root      114 Jun  2 09:45 diskqueue-mgset-500463489-20200602-094516.000000.dat
-rw------- 1 root root      240 Jun  2 09:45 diskqueue-mgset-500463489-20200602-094516.meta.dat

**Comment by vinllen** [comment]
2.4版本 这个落盘选项临时关闭了，change log里面有说明。后面版本会考虑放开

**Comment by maKeane** [comment]
谢谢，那可以用2.2.1来实现嘛

**Comment by vinllen** [comment]
如果单纯使用这个落盘，2.2.1版本是可以的

**Comment by maKeane** [comment]
非常感谢，我用2.2.1可以启用这个功能了，但是请问落盘的具体位置是哪里呢？

**Comment by vinllen** [comment]
log目录

**Comment by maKeane** [comment]
我在Mongoshake的logs没有找到，我自己再仔细看下，谢谢帮忙

**Comment by maKeane** [comment]
落盘文件找到了，实在mongoshake的logs目录，主要是增量追完了文件就删除看不到了 
@vinllen    多谢

**Comment by maKeane** [comment]
@vinllen   有个问题，2.2.1 通过replayer.oplog_store_disk做持久化
diskqueue-mgset-500467859-20200603-055120.000000.dat这些文件为什么会被删除了，后续mongoshake就报错了 
[2020/06/03 06:05:49 UTC] [CRIT] [common.(*DiskQueue).ioLoop:653] DISKQUEUE(diskqueue-mgset-500467859-20200603-055120) reading at 160261 of logs/diskqueue-mgset-500467859-20200603-055120.000001.dat - EOF

**Comment by vinllen** [comment]
全量期间发生的问题的话，看起来是边界处理存在问题了。2.2版本是测试版本，暂时不考虑修复这个问题了。2.4的代码进行了调整，实现原理有所修改，目前还没有开放。

**Comment by maKeane** [comment]
2.4大概什么时候能把full_sync.reader.oplog_store_disk落盘功能开放呢？

**Comment by vinllen** [comment]
至少7月之后了

**Comment by solemnpending** [comment]
> 

您好，这个功能现在修复了吗...
