### ISSUE TITLE
同步功能中需要有重试机制，减少重启带来的影响

### ISSUE THREAD

**Issue by dishytianxiang** [alibaba/MongoShake#362]
1.  源请求超时重启问题：同步遇到源端压力大导致超时，Mongahske自动重启重新全量同步，对于大数据量的同步代价太大，需要有连接重试机制
2. 源请求client可以做成线程池，有可能单个连接以外崩坏

**Comment by vinllen** [comment]
cursor没办法重试，全量版本后面会支持断点续传的功能。
