### ISSUE TITLE
mongo-shake-v2.4.2/comparison.py  执行偶尔报错pymongo.errors.OperationFailure

### ISSUE THREAD

**Issue by kkltkklt** [alibaba/MongoShake#365]
mongo-shake-v2.4.2执行comparison.py (python版本2.7.9)偶尔会报如下错误:
pymongo.errors.OperationFailure: $sample stage could not find a non-duplicate document after 100 while using a random cursor. This is likely a sporadic failure, please try again.

**Comment by vinllen** [comment]
这是mongodb的Bug，看起来还没有完全修复：
https://jira.mongodb.org/browse/SERVER-29446
https://jira.mongodb.org/browse/SERVER-43525

**Comment by kkltkklt** [comment]
收到，谢谢！
