### ISSUE TITLE
mongo-shake-v2.4.2同步kafka报错消息过大,请教如何设置mongoshake的最大发送消息大小(Producer端的max.request.size)

### ISSUE THREAD

**Issue by wuhaopengpm** [alibaba/MongoShake#369]
1.mongo-shake-v2.4.2同步kafka报错消息过大,报错信息如下:
> [2020/06/15 11:17:20 CST] [EROR] [tunnel.(*KafkaWriter).Send:59] KafkaWriter send [mongo_test1@xxx] with type[json] error[kafka server: Message was too large, server rejected it to avoid allocation error.]

2.自测对比验证,设置kafka的broker端max.message.size = 16MB, producer端发送6MB数据,报错如下:

> [2020-06-15 10:53:50,402] ERROR Error when sending message to topic mongo_test1 with key: null, value: 5974001 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.RecordTooLargeException: The request included a message 
larger than the max message size the server will accept.

3.producer端发送时指定 max.request.size = 16MB,测试发送成功

对此,想问下mongoshake端哪里可以指定发送消息最大值,单独设置kafka的broker端参数无法解决此问题,谢谢。

**Comment by wuhaopengpm** [comment]
像Flume发数据到kafka可以设置参数kafka.producer.max.request.size = 5271988
mongoshake默认是发送多大,在哪里修改呢

**Comment by vinllen** [comment]
目前是写死的1MB，这里我直接写死配到最大的16MB吧，下个版本2.4.6开始生效

**Comment by wuhaopengpm** [comment]
2.4.6版本预计什么时候上呢

**Comment by vinllen** [comment]
正常情况下，本周内

**Comment by wuhaopengpm** [comment]
还有个问题请教,oplog最大16M,但是mongoshake本身会进行一次transform,包装后的消息体肯定会比16M大,那么producer端的消息发送最大值会考虑往大再调整吗?

**Comment by vinllen** [comment]
设置比16M大一点就可以，比如17M的样子。不过json序列化后跟原来的大小可能也不一样，预留gap的话设置到20M。

**Comment by vinllen** [comment]
2.4.6版本已经发布
