### ISSUE TITLE
增加延迟同步

### ISSUE THREAD

**Issue by vinllen** [alibaba/MongoShake#371]
类似MongoDB主从同步的slaveDelay，增加延迟同步功能，目的端可以落后于源端给定的时间阈值。计划2.4.6版本发布。

**Comment by lanmaodage** [comment]
你好vinllen，issues 350这个有打算增加吗？让mongo>=3.6都支持

**Comment by vinllen** [comment]
@lanmaodage 支持>=4.0的版本，release在v2.4.6。
此外，你的回复跟这个issue没有关系，请回复到对应issue里面。

**Comment by vinllen** [comment]
2.4.6版本已经发布
