### ISSUE TITLE
MongoShake :  GetColShardType meet unknown ShakeKey type [{@id 1}]

### ISSUE THREAD

**Issue by Surge01** [alibaba/MongoShake#376]
Source : shard cluster
target : replica set
MongoShake version: 2.0.10
-------------------
sync_mode = all
shard_key = auto
replayer.executor.upsert = true
replayer.executor.insert_on_dup_update = true
filter.namespace.white = public.weather_data
--------------------
The namespace public.weather_data is sharded by field "@id : hashed"，when I start MongoShake, it prints the following error message:
`Oplog Tailer initialize failed: GetColShardType meet unknown ShakeKey type [{@id 1}]`

The following command is executed on the source mongodb cluster. Can someone give me some advice? 
```
mongos> use config
mongos> db.collections.find({"_id":"public.weather_data"})
{ "_id" : "public.weather_data", "lastmodEpoch" : ObjectId("5df1b5a3f2b410c42edc0175"), "lastmod" : ISODate("1970-02-19T17:02:47.304Z"), "dropped" : false, "key" : { "@id" : "hashed" }, "unique" : false }
mongos> use public
mongos> db.weather_data.getIndexes()
[
	{
		"v" : 2,
		"key" : {
			"@id" : "hashed"
		},
		"name" : "@id_hashed",
		"ns" : "public.weather_data"
	},
	{
		"v" : 2,
		"unique" : true,
		"key" : {
			"@id" : 1
		},
		"name" : "@id_1",
		"ns" : "public.weather_data",
		"background" : true
	},
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "public.weather_data"
	}
]
```

**Comment by vinllen** [comment]
I guess your MongoShake version isn't 2.0 but greater than 2.1 or 2.2. This bug has been fixed, please upgrade to the newest version and retry.

**Comment by Surge01** [comment]
> I guess your MongoShake version isn't 2.0 but greater than 2.1 or 2.2. This bug has been fixed, please upgrade to the newest version and retry.

Thanks for your reply!    It works when I upgrade MongoShake version to release-v2.4.6-20200617.
