### ISSUE TITLE
集群场景下，代码在构造batch数据时，如下场景下，代码会自动构造成applyOps的oplog数据，导致MongoShake执行挂住

### ISSUE THREAD

**Issue by ytwork** [alibaba/MongoShake#383]
BatchMore函数，没有判断是否为集群场景，当两个shard插入的时间戳相同，会通过事务构造成相同applyOps数据，但Sharding场景下，又不支持applyOps，导致执行挂住，这个问题在如下操作方式下必现。
创建两个sharding。
1、给一个sharding 的表不断插入数据，中间不停；
2、登录另一个sharding，并创建collection，问题出现；
发现问题的代码：
![image](https://user-images.githubusercontent.com/25236642/86570569-b4f84c80-bfa2-11ea-8614-8b2ff7922c90.png)

**Comment by vinllen** [comment]
是的，这个后面会进行修改，请跟这个issue： #370

**Comment by vinllen** [comment]
2.4.10版本进行优化以提高性能：细化事务合并的判断逻辑，对于源端原来就是事务或者applyOps写入的，包括单机事务和分布式事务，目前还是会继续沿用applyOps进行写入；对于其他情况，不会采用applyOps写入。
该issue先关闭，类似问题请跟 #370
