### ISSUE TITLE
增量场景下的权限问题以及相应的报错信息不明显

### ISSUE THREAD

**Issue by muyunziyue** [alibaba/MongoShake#385]
源mongo为副本集模式，在配置了增量采集数据到kafka的场景下，只配置了local库读权限和mongoshake库的读写权限，启动mongoshake报错如下：
![image](https://user-images.githubusercontent.com/41473162/86935804-d5293680-c16f-11ea-8fde-fb1f3df66e1d.png)

**Comment by muyunziyue** [comment]
![lALPGojJ88daV7HM_M0GfA_1660_252](https://user-images.githubusercontent.com/41473162/86935932-f558f580-c16f-11ea-805a-74b1a50c584c.png)

**Comment by muyunziyue** [comment]
上面问题解决了，缺少listDatabases权限。但是增量场景应该是不需要这个权限的。

**Comment by muyunziyue** [comment]
![image](https://user-images.githubusercontent.com/41473162/87167833-2b2ce400-c300-11ea-8d14-e56d08d63a3a.png)
然后就又报了这个错误，没有任务报错信息弹出

**Comment by muyunziyue** [comment]
![image](https://user-images.githubusercontent.com/41473162/87167998-65968100-c300-11ea-9bdb-7f9775a3dace.png)
log日志也没有报错

**Comment by muyunziyue** [comment]
上面的问题也解决了，我让运维同学给我开的权限，他少给我开了一个mongoshake的读写权限。。。就很气。但是mongoshake的日志里也没有详细的报错日志信息弹出，希望可以补充一下这块导致的报错。

**Comment by muyunziyue** [comment]
最后这里贴一下，我配置的mongo用户的详细权限，对应于mongodb为副本集，incr方式同步oplog到kafka:  { role: "read", db: "local" },
        { role: "listDatabases", db: "admin" },
        { role: "readWrite", db: "mongoshake" }

**Comment by vinllen** [comment]
感谢反馈

**Comment by vinllen** [comment]
第一个问题已经修复，将会release在下个小版本。第二个问题，应该是你checkpoint格式不对，这个能否复现？

**Comment by vinllen** [comment]
2.4.8版本已发布，减少对源端mongodb的权限依赖。本issue暂时close，如果后面还有问题请再reopen
