### ISSUE TITLE
mongoshake 集群下, 主节点变成从节点后, 还是会刷新checkpoint

### ISSUE THREAD

**Issue by luoffei** [alibaba/MongoShake#388]
mongoshake版本: 2.2.0

mongoshake主从模式, 三个节点, 主节点在变更为从节点后, 会继续刷新数据库的checkpoint, 新的主节点也会刷新, checkpoint会在两个时间来回切换

![image](https://user-images.githubusercontent.com/10286864/87525296-e0beb500-c6bb-11ea-8133-b6f6cb8b8ab9.png)

**Comment by vinllen** [comment]
下个小版本进行修复

**Comment by vinllen** [comment]
2.4.8版本已发布
