### ISSUE TITLE
mongodb副本集通过mongoshake无法同步到mongos集群

### ISSUE THREAD

**Issue by BcnJcaicai** [alibaba/MongoShake#391]
线上副本集版本3.4.19希望通过mongoshake同步到目标的mongos 4.0.12中。

同步用户monitor，权限
![mrepl_img](https://user-images.githubusercontent.com/57022395/88241427-a73e0900-ccbc-11ea-88f7-2ba5e252c386.png)
![ms_pri](https://user-images.githubusercontent.com/57022395/88241430-a9a06300-ccbc-11ea-8b5e-501952fa4915.png)

mongoshake 版本 2.4.6以及 2.4.7  在原有配置文件基础上只修改了sync_mode=all 要做全量以及增量。 

后期显示全量同步完成，增量始终报错：

[08:11:33 CST 2020/07/23] [CRIT] (mongoshake/executor.(*Executor).execute:111) Replayer-1, executor-1, oplog for namespace[360monitor.inserttable7697] op[i] failed. error type[*mgo.BulkError] error[index[0], msg[command insert requires authentication], dup[false]], logs number[1], firstLog: {"ts":6852210417679204732,"op":"i","g":"","ns":"360monitor.inserttable7697","o":[{"Name":"_id","Value":1595404562},{"Name":"n","Value":"360mongomonitor"}],"o2":null,"uk":null,"lsid":null,"fromMigrate":false}

请问是不支持副本集跨版本升级到mongos么？

**Comment by vinllen** [comment]
你mongoshake权限没给够吧？是哪个账号？有给到写权限？

**Comment by BcnJcaicai** [comment]
用的monitor 这权限还不够？

**Comment by BcnJcaicai** [comment]
![image](https://user-images.githubusercontent.com/57022395/88276544-d03cb900-cd11-11ea-8c1a-bd5726ade19c.png)
![image](https://user-images.githubusercontent.com/57022395/88276561-d6cb3080-cd11-11ea-90bf-23c46139d46b.png)

**Comment by BcnJcaicai** [comment]
副本集之间3.4---->4.0 以及 4.0---->3.4 同样权限都是可以的。 到mongos就不行了

**Comment by vinllen** [comment]
权限问题你可以手动确认下，你看看手动用这个权限mongoshell连接，能否正常插入

**Comment by BcnJcaicai** [comment]
手动是可以插入的用这个用户。

**Comment by BcnJcaicai** [comment]
![image](https://user-images.githubusercontent.com/57022395/88358624-3e30c100-cda2-11ea-88f6-486f1a52925a.png)

**Comment by BcnJcaicai** [comment]
![image](https://user-images.githubusercontent.com/57022395/88358690-8c45c480-cda2-11ea-9706-3f1bd4b543b6.png)

**Comment by vinllen** [comment]
看起来有点奇怪，全量如果可以的，增量没道理不可以。

**Comment by BcnJcaicai** [comment]
我也是纳闷，而且我测试副本集同样权限，增量稳稳的，就算版本差异也没报错过。但是到了mongos就不行，副本集的全量过来后，增量就开始报错。。。。。。

**Comment by vzardlloo** [comment]
我这也遇到了一样的问题
