### ISSUE TITLE
第一个release 包发布时间

### ISSUE THREAD

**Issue by qiudao767** [alibaba/MongoShake#4]
想问下第一个release包的发布有计划吗

**Comment by vinllen** [comment]
这个会尽快release，最近有点忙，计划下周吧。目前这个master应该是稳定版本，功能上是齐备的。

**Comment by iamyangjy** [comment]
赞，这边有业务场景需要做mongo的异地数据中心同步，会先做个可行性评估。到时期待能有个quickstart。
