### ISSUE TITLE
请问同步模式选择all  全量+增量同步时，能使用restful监控端口查看统计情况吗？我这边试好像只有full或者incr才行

### ISSUE THREAD

**Issue by yuwei43** [alibaba/MongoShake#401]

**Comment by vinllen** [comment]
可以的。all模式如果是全量同步，则看全量同步对应的接口 默认应该是9101，增量是9100

**Comment by yuwei43** [comment]
可是我在all模式的时候，还在全量同步阶段，  访问对应的接口显示的是 No JSON object could be decoded

**Comment by vinllen** [comment]
什么版本？刚启动是没有的 过个几秒钟应该就有了

**Comment by yuwei43** [comment]
mongodb3.6  mongoshakev2.4.6  我之前怀疑可能是checkpoint的问题，我现在把配置都清空了一遍重新开始all同步
不管访问9100还是9101(和配置文件中一致)都是返回 No JSON object could be decoded

**Comment by vinllen** [comment]
@yuwei43  这个有现场吗？方便的话加我钉钉私聊下，暴露一下restful接口到公网，我看下。
