### ISSUE TITLE
Connect checkpointStorageUrl[] error

### ISSUE THREAD

**Issue by supanwoc** [alibaba/MongoShake#410]
Connect checkpointStorageUrl[] error[<nil>]. Please add primary node into 'mongo_urls' if 'context.storage.url' is empty

run replication failed: select sync mode failed: server returned error on SASL authentication step: Authentication failed.

**Comment by supanwoc** [comment]
这俩提示是啥意思哦   我就单点mongo 同步另一个单点mongo 。密码账号没有错，也没特殊字符

**Comment by vinllen** [comment]
你secondaryPreferred是配置的standalone吗？

**Comment by supanwoc** [comment]
有secondaryPreferred这个配置吗，那就是没配置 secondaryPreferred；倒是倒是配置了个 mongo_connect_mode=primary

**Comment by vinllen** [comment]
对 就是这个，你配置primary 肯定是要连接primary的，单节点只能配置standalone
https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E6%8A%A5%E9%94%99connect-checkpointstorageurl-error-please-add-primary-node-into-mongo_urls-if-contextstorageurl-is-empty
