### ISSUE TITLE
是否支持源为公有云mongodb集群的迁移？

### ISSUE THREAD

**Issue by tttacit** [alibaba/MongoShake#411]
公有云的mongodb集群是只给一个访问url地址，没有具体分片地址、config server地址。

**Comment by vinllen** [comment]
你说的是阿里云的吧，默认给定的url就是mongos地址，另外控制台是可以额外申请地址分片、cs地址的，不会的话可以找下售后同学

**Comment by tttacit** [comment]
> 你说的是阿里云的吧，默认给定的url就是mongos地址，另外控制台是可以额外申请地址分片、cs地址的，不会的话可以找下售后同学

其他的云。。。我看看能不能申请分片和config server地址。
