### ISSUE TITLE
what is hypervisor mechanism and how to use it

### ISSUE THREAD

**Issue by hiep1097** [alibaba/MongoShake#415]
@vinllen High Availability feature in the document talk that Hypervisor mechanism is also supported so that it will restart immediately when dies. What it is and how to use? Is it configurable? or it auto? Can you explain more detail about it? I cannot find any tutorial.

**Comment by vinllen** [comment]
Hypervisor is a process that watches the MongoShake running, if MongoShake dies, it'll restart it immediately. 
About the details, I'll add it to the documentation recently.
You can use the `start.sh` script to start which will including the hypervisor.
