### ISSUE TITLE
请问下能否使用mongoShake将数据同步到该复制集从节点下的另一个库中？

### ISSUE THREAD

**Issue by yuwei43** [alibaba/MongoShake#417]
复制集中：主节点A  从节点B 裁决C
需要同步的数据库database1  
可否将数据同步到从节点B下的数据库database2中呢？我好像没有在配置中只看到tunnel.address，没有目的库的配置

**Comment by vinllen** [comment]
首先，一个副本集下面表的集合是一定的，主节点A有什么db，从节点B就有什么db，不可能存在，主节点A多了db1，而从二节点没有db1，反之亦然。
其次，你可能想要的是一个rename的功能，比如副本集中的db1，重命名为db2。这个是可以的，不过应该只能做全量同步，增量可能不行。
