### ISSUE TITLE
使用mongoshake 同步到kfaka  出现数据不全的现象是为什么？

### ISSUE THREAD

**Issue by wgq1134711420** [alibaba/MongoShake#420]
同步出来的结果 有一部分是全的mongo信息  有一部分只有id字段没有其他数据信息    我使用的是2.4.6
conf.version = 4
id = mongoshake_a
master_quorum = false

full_sync.http_port = 9201
incr_sync.http_port = 9200
system_profile_port = 9300
log.level = info
log.dir =
log.file = collector_a.log
log.flush = false
sync_mode = incr
tunnel = kafka
tunnel.address 
tunnel.message = bson
mongo_connect_mode = secondaryPreferred

filter.namespace.black =
filter.namespace.white =  ***.**
filter.pass.special.db =
filter.ddl_enable = false
checkpoint.storage.url =
checkpoint.storage.db = mongoshake_a
checkpoint.storage.collection = ckpt_default
checkpoint.start_position = 1970-01-01T00:00:00Z
transform.namespace =
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.collection_exist_drop = false
full_sync.create_index = background
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
incr_sync.mongo_fetch_method = oplog
incr_sync.oplog.gids =
incr_sync.shard_key = collection

incr_sync.worker = 8

incr_sync.worker.oplog_compressor = none

incr_sync.target_delay = 0

incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

incr_sync.executor.upsert = false

incr_sync.executor.insert_on_dup_update = false

incr_sync.conflict_write_to = none

incr_sync.executor.majority_enable = false

**Comment by vinllen** [comment]
https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E#35-%E5%85%B6%E4%BB%96

**Comment by wgq1134711420** [comment]
我好好的看了一便配置信息  发现没有什么出入   但是数据还是不对  我的配置是这样的
conf.version = 4
id = mongoshake_a
master_quorum = false

full_sync.http_port = 9201
incr_sync.http_port = 9200
system_profile_port = 9300
log.level = info
log.dir =
log.file = collector_a.log
log.flush = false
sync_mode = incr
tunnel = kafka
tunnel.address 
tunnel.message = bson
mongo_connect_mode = secondaryPreferred

filter.namespace.black =
filter.namespace.white =  ***.**
filter.pass.special.db =
filter.ddl_enable = false
checkpoint.storage.url =
checkpoint.storage.db = mongoshake_a
checkpoint.storage.collection = ckpt_default
checkpoint.start_position = 1970-01-01T00:00:00Z
transform.namespace =
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.collection_exist_drop = false
full_sync.create_index = background
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
incr_sync.mongo_fetch_method = oplog
incr_sync.oplog.gids =
incr_sync.shard_key = collection

incr_sync.worker = 8

incr_sync.worker.oplog_compressor = none

incr_sync.target_delay = 0


incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

incr_sync.executor.upsert = false

incr_sync.executor.insert_on_dup_update = false

incr_sync.conflict_write_to = none

incr_sync.executor.majority_enable = false

**Comment by wgq1134711420** [comment]
> 我好好的看了一堆便便配置信息发现没有什么出入但是数据还是不对我的配置是这样的的
conf.version = 4
id = mongoshake_a
master_quorum = false

full_sync.http_port = 9201
incr_sync.http_port = 9200
system_profile_port = 9300
log.level = info
log.dir =
log.file = collector_a.log
log.flush = false
sync_mode = incr
tunnel = kafka
tunnel.address
tunnel.message = bson
mongo_connect_mode =第二优先

filter.namespace.black =
filter.namespace.white = * 。
filter.pass.special.db =
filter.ddl_enable = false
checkpoint.storage.url =
checkpoint.storage.db = mongoshake_a
checkpoint.storage.collection = ckpt_default
checkpoint.start_position = 1970-01-01T00：00：00Z
transform.namespace =
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.collection_exist_drop =
否full_sync.create_index =背景
full_sync.executor.insert_on_dup_update =
否full_sync.executor.insert_on_dup_update =
否full_sync.syncutor.filter.orphan_document = = oplog
incr_sync.oplog.gids =
incr_sync.shard_key =集合

incr_sync.worker = 8

incr_sync.worker.oplog_compressor =无

incr_sync.target_delay = 0

incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

incr_sync.executor.upsert =否

incr_sync.executor.insert_on_dup_update =否

incr_sync.conflict_write_to =无

incr_sync.executor.majority_enable = false

**Comment by vinllen** [comment]
@wgq1134711420 这个是否可以解决你的问题？

**Comment by vinllen** [comment]
你看我给你发的链接的tag：incr_sync.change_stream.watch_full_document

**Comment by wgq1134711420** [comment]
@vinllen 您好 这个问题还是没解决 有好多重复数据   还有很多数据不全
--这是数据齐全的：
{'ts': Timestamp(1597443407, 128), 'h': -2641522000236506426, 'ns': 'ggdb.gg', 'op': 'i', 'v': 2, 'o': {'stock_name': '新力金融', 'ggsj': '2020-08-15', 'modify_time': datetime.datetime(2020, 8, 15, 6, 16, 47, 723000), 'seq': '20200815061647723618', 'stock_code': '600318', 'title': '新力金融：关于监事辞职及提名监事候选人的公告', 'create_time': datetime.datetime(2020, 8, 15, 6, 16, 47, 724000), '_id': ObjectId('5f370d4fc9fef8190232efdb'), 'item_type': 'gg', 'etl_time': '2020-08-15 06:16:47', 'url': 'http://www.cninfo.com.cn/finalpage/2020-08-15/1208177173.PDF', 'seq_id': 1575315}}
--这是数据不齐的：
{'ts': Timestamp(1597443761, 4), 'o2': {'_id': ObjectId('5f370d14c9fef818e53a6af6')}, 'h': -7304072416979315647, 'ns': 'ggdb.gg', 'op': 'u', 'v': 2, 'o': {'$set': {'is_index': [1]}}}

**Comment by wgq1134711420** [comment]
@vinllen  您好 谢谢您的答复    在2.4.6 中没有incr_sync.change_stream.watch_full_document 这个配置  加上的话  会直接报错

**Comment by vinllen** [comment]
更新下版本

**Comment by wgq1134711420** [comment]
@您好 有什么 推荐的版本吗  比较稳定的 谢谢

**Comment by wgq1134711420** [comment]
@vinllen 您好https://github.com/alibaba/MongoShake/releases 上下载的tar.gz
都没有这个参数

**Comment by wgq1134711420** [comment]
@vinllen 您好  跟新版本也还是不行  其中2.4.10中有两个incr_sync.change_stream.watch_full_document设置参数

**Comment by wgq1134711420** [comment]
@vinllen 版本2.4.8 也是不行 incr_sync.change_stream.watch_full_document 开启了

**Comment by vinllen** [comment]
@vinllen 您好 跟新版本也还是不行 其中2.4.10中有两个incr_sync.change_stream.watch_full_document设置参数
----------
2.4.10这里是配置文件弄错了，需要修改一下。下个版本进行修改。
2.4.8的版本应该可以的。设置了以后不应该会出现o2中$set的字段：
```{'ts': Timestamp(1597443761, 4), 'o2': {'_id': ObjectId('5f370d14c9fef818e53a6af6')}, 'h': -7304072416979315647, 'ns': 'ggdb.gg', 'op': 'u', 'v': 2, 'o': {'$set': {'is_index': [1]}}}```
是不是你消费到了kafka中老的数据？

**Comment by wgq1134711420** [comment]
@vinllen  谢谢  - 我把它过滤掉以后发现数据的数量是不缺的  - 不会是kafka的老数据  - 我直接消费的是最新数据没有处理偏移
但是发现可能是mongoshake同步过来了 一部分小于当前同步时间的数据  - 也正是这部分数据只有id -  $get 可能是更新 - 我发现同一个id回出现多次 - 出现多次的 会出现$get

**Comment by vinllen** [comment]
如果发现消费到重复数据（重复的_id），一般来说是MongoShake回退了同步的位点，通常来说，这个是Mongoshake发生了重启。
可以把完整的mongoshake日志发我一下：cvinllen@gmail.com

**Comment by wgq1134711420** [comment]
@vinllen 好的

**Comment by wgq1134711420** [comment]
@vinllen 好的
