### ISSUE TITLE
v2.4.10和v2.4.9_3 版本tunnel为kafka时无法正确连接kafka broker

### ISSUE THREAD

**Issue by SuperChrisliu** [alibaba/MongoShake#424]
v2.4.10和v2.4.9_3 版本tunnel为kafka时无法正确连接kafka broker
在执行collection filter之后 报错如下：
```start document replication failed: no reachable servers
[16:41:05 CST 2020/08/19] [CRIT] (mongoshake/common.NewMongoConn:48) Connect to mongosync@172.16.20.25:9092 failed. no reachable servers
[16:41:05 CST 2020/08/19] [CRIT] (main.startup:139) run replication failed: start document replication failed: no reachable servers
[2020/08/19 16:41:05 CST] [CRIT] Connect to mongosync@172.16.20.25:9092 failed. no reachable servers
[2020/08/19 16:41:05 CST] [CRIT] run replication failed: start document replication failed: no reachable servers```
collecter.conf配置如下：
```tunnel = kafka
tunnel.address = mongoshake@127.0.0.1:9092
tunnel.message = raw```

当tunnel = mock 时也出现和上面一样的报错


同样的配置 在v2.4.7版本不会报错

**Comment by vinllen** [comment]
Connect to mongosync@172.16.20.25:9092 failed
--------
这个应该是源端的库连接失败了，你确认是可以的吗？

**Comment by vinllen** [comment]
@SuperChrisliu 贴下完整的配置吧，连接串密码部分可以脱敏

**Comment by SuperChrisliu** [comment]
{
	"ConfVersion": 5,
	"Id": "mongoshake",
	"MasterQuorum": false,
	"FullSyncHTTPListenPort": 9101,
	"IncrSyncHTTPListenPort": 9100,
	"SystemProfilePort": 9200,
	"LogLevel": "debug",
	"LogDirectory": "",
	"LogFileName": "collector.log",
	"LogFlush": false,
	"SyncMode": "incr",
	"MongoUrls": ["mongodb://***:***@pub.mongodb.rds.aliyuncs.com:3717,pub.mongodb.rds.aliyuncs.com:3717"],
	"MongoCsUrl": "",
	"MongoSUrl": "",
	"MongoConnectMode": "secondaryPreferred",
	"Tunnel": "kafka",
	"TunnelAddress": ["mongosync@172.16.20.25:9092"],
	"TunnelMessage": "json",
	"FilterNamespaceBlack": null,
	"FilterNamespaceWhite": ["d2mongo.t_gps_info"],
	"FilterPassSpecialDb": null,
	"FilterDDLEnable": false,
	"CheckpointStorageUrl": "mongodb://***:***@-pub.mongodb.rds.aliyuncs.com:3717,pub.mongodb.rds.aliyuncs.com:3717",
	"CheckpointStorageDb": "mongoshake",
	"CheckpointStorageCollection": "ckpt_default",
	"CheckpointStartPosition": 1,
	"TransformNamespace": null,
	"FullSyncReaderCollectionParallel": 6,
	"FullSyncReaderWriteDocumentParallel": 8,
	"FullSyncReaderReadDocumentCount": 0,
	"FullSyncReaderDocumentBatchSize": 128,
	"FullSyncCollectionDrop": true,
	"FullSyncCreateIndex": "none",
	"FullSyncReaderOplogStoreDisk": false,
	"FullSyncReaderOplogStoreDiskMaxSize": 256000,
	"FullSyncExecutorInsertOnDupUpdate": false,
	"FullSyncExecutorFilterOrphanDocument": false,
	"FullSyncExecutorMajorityEnable": false,
	"IncrSyncMongoFetchMethod": "oplog",
	"IncrSyncChangeStreamWatchFullDocument": false,
	"IncrSyncOplogGIDS": null,
	"IncrSyncShardKey": "collection",
	"IncrSyncWorker": 8,
	"IncrSyncTargetDelay": 0,
	"IncrSyncWorkerOplogCompressor": "none",
	"IncrSyncWorkerBatchQueueSize": 64,
	"IncrSyncAdaptiveBatchingMaxSize": 1024,
	"IncrSyncFetcherBufferCapacity": 256,
	"IncrSyncExecutorUpsert": false,
	"IncrSyncExecutorInsertOnDupUpdate": false,
	"IncrSyncConflictWriteTo": "none",
	"IncrSyncExecutorMajorityEnable": false,
	"CheckpointStorage": "database",
	"CheckpointInterval": 5000,
	"FullSyncExecutorDebug": false,
	"IncrSyncDBRef": false,
	"IncrSyncExecutor": 1,
	"IncrSyncExecutorDebug": false,
	"IncrSyncReaderDebug": "",
	"IncrSyncCollisionEnable": false,
	"IncrSyncReaderBufferTime": 1,
	"Version": "feature-2.4,928466e9d255e184e4c0b722b0e59de033ee818f,release,go1.10.3,2020-08-07_14:33:47",
	"IncrSyncTunnel": "",
	"IncrSyncTunnelAddress": null,
	"IncrSyncTunnelMessage": "",
	"HTTPListenPort": 0,
	"SystemProfile": 0
}

**Comment by SuperChrisliu** [comment]
不可能是源库连不上，日志设为debug，打印出了源库的collection

**Comment by SuperChrisliu** [comment]
上面的配置是命令行输出的

**Comment by vinllen** [comment]
感谢反馈，是个bug，2.4.11版本进行修复

**Comment by vinllen** [comment]
修复版本已发布

**Comment by dengdongshan** [comment]
上个月我下载的v2.4.9_3也是同样的问题，连接测试库改了几次MONGOSHAKE的配置成功，但是切换到生产库又不行。

下一个新版本试一下。

**Comment by vinllen** [comment]
@dengdongshan 2.4.11修复的
