### ISSUE TITLE
full sync doesn't create all the source indexes

### ISSUE THREAD

**Issue by tanisdlj** [alibaba/MongoShake#425]
Mongoshake: v2.4.9_3
Source mongo: v4.0.10
Target mongo: v4.2.8
Mongo type: Replica set

After setting mongoshake in "all" mode and letting it run for two days, I run the comparison script that you provide:
`/opt/mongoshake/comparison.py --src=x.x.x.x:27017 --dest=y.y.y.y:27017 --excludeDbs=dbsToExclude --excludeCollections=system.profile`
```
ERROR [2020-08-19 17:30:25] DIFF => collection [XXXX] index number not equals: src[2], dst[1]
FAIL
```

Comparing the indexes myself with `db.collection.getIndexes()` I can see the differences also.

Apparently full sync doesn´t copy the indexes

**Comment by vinllen** [comment]
It depends on `full_sync.create_index` configuration:

* none: do not create index.
* foreground: create index by foreground after full sync stage finished.
* background: create index when starting.

**Comment by tanisdlj** [comment]
Yes! That fixed it, thanks a lot :)
