### ISSUE TITLE
Fetch master election info ObjectIdHex("5204af979955496907000001") failed. server returned error on SASL authentication step: Authentication failed

### ISSUE THREAD

**Issue by supanwoc** [alibaba/MongoShake#427]
这是啥意思，密码没有错的

**Comment by supanwoc** [comment]
应该有一个设置 authenticationDatabase  的位置吧？没找到

**Comment by vinllen** [comment]
https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E6%8A%A5%E9%94%99oplog-tailer-initialize-failed-no-reachable-servers
密码不能包含@

**Comment by supanwoc** [comment]
没有哦
