### ISSUE TITLE
After full replication the database and collection size differs

### ISSUE THREAD

**Issue by tanisdlj** [alibaba/MongoShake#429]
This is with mongoshake running for a long time and replication up to date.

Source db: 0.023GB
Target db: 0.017GB

Analyzing the collections, object count, average object size and collection size matches but not the storageSize.
Any idea why?

**Comment by vinllen** [comment]
Different mongod/replica may have different storage size based on the compress algorithm and disk fragmentation.

**Comment by tanisdlj** [comment]
Good to know. Thanks a lot!
