### ISSUE TITLE
内存溢出被kill怎么解决

### ISSUE THREAD

**Issue by wangweilinaiyaya** [alibaba/MongoShake#431]
我环境里sharding数量比较多，当我mongo_urls里随着sharding数量增多，内存占用明显增大，请问该怎么调优呢。
还有关于mongo_urls的配置有些困惑，比如说我有一个10个sharding的集群，要同步一个A库在sharding2上。我在mongo_urls只配置了sharding1好像也能完成同步，是否有必要在mongo_urls补全所有sharding

**Comment by vinllen** [comment]
2.4.4开始的版本全量和是从mongos上，增量拉取如果是change stream模式也是从mongos拉取，如果是oplog拉取是从各个shard拉取的。需要提供所有shard地址，第一是为了校验oplog的合法性，第二个如果是oplog拉取，那么如果源端配置10个shard，就会只拉取10个shard，但实际上你有11个shard，就有1个shard的数据丢失了。
关于内存的问题，目前应该主要是mgo driver的问题，最近考虑优化替换这个mgo的driver，减轻内存的压力。计划是2.4的后面版本会进行支持，请持续关注。

**Comment by wangweilinaiyaya** [comment]
我用的是2.4.8，看了一下配置文件，拉取模式是默认的oplog。那为什么可以拉取到没有配置的shard上的数据，按理说应该是change stream模式才从mongos读数据才对。

**Comment by vinllen** [comment]
拉取不到

**Comment by wangweilinaiyaya** [comment]
恩，做了一下测试，这样配置全量是可以拉去到的。但是增量不行。感谢
