### ISSUE TITLE
change_stream 同步数据慢

### ISSUE THREAD

**Issue by DEWUIW** [alibaba/MongoShake#437]
源库是阿里云分片集群4.2，目标库是单点4.2，使用的mongoshake做增量同步，使用的是change_stream模式，同步数据特别慢，每次只有几十条，服务器的负载，内存占用都不高。另外一个库使用的是oplogs方式就很快，请问是什么原因？

**Comment by vinllen** [comment]
2.4.10做了优化，升级到最新版本试下

**Comment by vinllen** [comment]
问题无反馈先关闭，有问题请重新打开
