### ISSUE TITLE
使用kafka + json 增量同步, 事务类型的oplog丢失

### ISSUE THREAD

**Issue by loda507** [alibaba/MongoShake#439]
使用kafka + json 增量同步, 事务类型的oplog丢失， 非事务类型的oplog正常

主要配置：
incr_sync.mongo_fetch_method = oplog
sync_mode = incr
tunnel = kafka
tunnel.message = json
filter.ddl_enable = true

mongoDB版本 v4.0 主从
mongoshake版本 v2.4.2

看代码怀疑是AutologousFilter把事务类型的oplog过滤掉了

**Comment by vinllen** [comment]
感谢反馈，副本集的确有这个问题，我修复一下，下个版本发布。你留个邮箱，我加你到contributor list中。

**Comment by loda507** [comment]
> 感谢反馈，副本集的确有这个问题，我修复一下，下个版本发布。你留个邮箱，我加你到contributor list中。

741536172@qq.com

**Comment by vinllen** [comment]
2.4.13版本已发布
