### ISSUE TITLE
同步开始后，很短时间内被killed

### ISSUE THREAD

**Issue by wwz801226** [alibaba/MongoShake#442]
![image](https://user-images.githubusercontent.com/4090874/92693126-c16c9d00-f377-11ea-93ba-800523dfd089.png)

源地址为 分片副本集的所有分片，目的地址为目标集群的mongos

日志最后是以下内容

![image](https://user-images.githubusercontent.com/4090874/92693173-d47f6d00-f377-11ea-93c9-c2b65b7d8ce2.png)

**Comment by wwz801226** [comment]
使用白名单，只开启一个test库貌似是没问题的，难道和数据量有关？
`filter.namespace.white = test1
`

**Comment by vinllen** [comment]
看下dmesg，是不是Oom掉了

**Comment by vinllen** [comment]
估计是oplog比较大，导致内存占用比较多，oom掉了
