### ISSUE TITLE
v2.4.12_2 关于字段：full_sync.collection_exist_drop 的疑惑

### ISSUE THREAD

**Issue by brzone** [alibaba/MongoShake#445]
在v2.2.1，有一个字段：replayer.collection_drop，在配置文件中的描述是：

// drop the same name of collection in dest mongodb in full synchronization
 //如果待同步表在目的端存在，是否先删除目的端的表再进行同步。
 //默认true，表示先删除目的端的表，再同步
// false，表示不删除目的端的表，如果目的端表存在，就不再同步表中的索引和表结构，只同步数据
replayer.collection_drop = false

默认为false，存在下面有个情形（均有做过测试）：
1   在目的库，如果A表不存在，同步的时候，会先开始同步数据，同步数据之后，就会同步索引，在目的库执行源库中A表中索引信息。
2  在目的库，存在A表（我是用db.createCollection('a') 来创建一个空表），同步的时候，会先开始同步数据，不会同步索引。

在v2.4.12_2中，有一个字段：full_sync.collection_exist_drop，在配置文件中的描述是：

// drop the same name of collection in dest mongodb in full synchronization
// 同步时如果目的库存在，是否先删除目的库再进行同步，true表示先删除再同步，false表示不删除。
full_sync.collection_exist_drop = false

默认值为true，如果修改值为false，是否也会上面的v2.2.1的相同逻辑（即：不存在表，同步数据和索引，存在表，仅仅同步数据）。

如果逻辑一样，可否把下面的一句话：
// false，表示不删除目的端的表，如果目的端表存在，就不再同步表中的索引和表结构，只同步数据
加在full_sync.collection_exist_drop配置字段的描述中，可能会更清楚一些。

在v2.4.12_2，
发现有一个full_sync.create_index字段来控制是否创建索引：
//全量期间数据同步完毕后，是否需要创建索引，none表示不创建，foreground表示创建前台索引，
//background表示创建后台索引。
full_sync.create_index = none

**Comment by vinllen** [comment]
感谢反馈，`full_sync.collection_exist_drop`的行为是刚启动进行判断的，如果置为true会删除相关的表，false表示不删除，然后再开始后续的数据同步。
你说的这个现象：
```
2 在目的库，存在A表（我是用db.createCollection('a') 来创建一个空表），同步的时候，会先开始同步数据，不会同步索引。
```
在2.4是不符合预期的，2.4里面是通过你下面说的`full_sync.create_index`来控制索引的创建与否，跟表是否存在没有关系。
