### ISSUE TITLE
增量同步副本集每条记录都有这样得警告，查看数据是同步成功。

### ISSUE THREAD

**Issue by pangqiqiang** [alibaba/MongoShake#446]
mongodb    v4.2.1
增量同步时日志没同步一条记录都会有这样一条警告日志记录，查看记录同步是成功的：
[WARN] CheckpointOperation updated is not suitable. lowest [0]. current [6872671328344735745[1600168489, 1]]. inputTs [0]. reason : smallest candidates is zero

同时用mongoshake-stat 监控提示HTTPError: HTTP Error 503: Service Unavailable

**Comment by vinllen** [comment]
这个是推进checkpoint失败了，通常发生在刚启动的时候。
端口报错503，这个详细mongoshake的日志可以发我一份：cvinllen@gmail.com
