### ISSUE TITLE
无法完成包依赖安装

### ISSUE THREAD

**Issue by occultskyrong** [alibaba/MongoShake#447]
https://github.com/alibaba/MongoShake/blob/2f31ff91b5aa5e548e88dfefcf8021e1eeb08aba/src/vendor/vendor.json#L91

```
govendor sync -v
```

以下两个库对应地址已失效
```
github.com/klauspost/compress/fse
github.com/klauspost/compress/huff0
```

**Comment by vinllen** [comment]
是不是网络的问题，govendor目前的确比较难拉，后面会考虑转到go.mod上去

**Comment by occultskyrong** [comment]
> 是不是网络的问题，govendor目前的确比较难拉，后面会考虑转到go.mod上去

不是吧，你直接访问这两个地址，对应的github仓库已经404了

**Comment by vinllen** [comment]
目录是存在的，你访问上级目录可以看到有fse和huff0的子目录
