### ISSUE TITLE
[Bug] 同步数据至新库时，新建的Collection配置与旧库不同

### ISSUE THREAD

**Issue by Angelo-Credo** [alibaba/MongoShake#448]
使用版本：2.4.10
MongoDB版本：3.0
通道模式：direct

源数据库里边的Collection是带有capped属性并限制了最大条数/文件大小的，同步到新库时，这些信息都丢失了。
由于源数据库流水很大才采用此设置的，结果同步到新库，丢失设置之后同步服务运行没一阵子磁盘空间就爆了。。。

这个bug修复应该比较容易。

**Comment by vinllen** [comment]
capped属性这个没有同步，对于表信息目前只会同步表内数据以及表的索引。
你说的这个属性同步我评估一下
