### ISSUE TITLE
[疑惑] sync_mode 为all时，只同步了增量数据。文档的描述分明是 全量 + 增量。

### ISSUE THREAD

**Issue by WantUzZ** [alibaba/MongoShake#449]

**Comment by WantUzZ** [comment]
...
sync_mode = all
...

以 A.diaries -> B.diaries 为例，A.diaries 数据最早有2018年创建。但是 sync_mode = all， 仅仅同步当前时间之后的日记数据。
![image](https://user-images.githubusercontent.com/29161909/93731441-897b1a80-fbff-11ea-98ed-a75ce3b5f326.png)

**Comment by vinllen** [comment]
先看下wiki里面给的文档，了解下基本的运行机制。估计是哪里配置不对，或者使用不当
