### ISSUE TITLE
Mongo shake 全量同步失败之后要怎么修复

### ISSUE THREAD

**Issue by xiaohuazi123** [alibaba/MongoShake#453]
- 看了提到全量同步失败的issue，都没有说失败之后要怎么修复，恢复全量同步   
- 比如我数据库有3个库，A库，B库，C库，我怎么实现只同步B库，是设置filter.namespace.white = B库 吗  
- 全量同步admin 库不成功，设置了filter.namespace.white = admin 和 filter.pass.special.db = admin都不行

**Comment by xiaohuazi123** [comment]
第一个问题，全量同步失败，貌似是会重新全量同步，把已经同步的表和库删了重新同步
>  
>
>

> https://mongoing.com/archives/75020
> Resumable Initial Sync
> 在 4.4 之前的版本中，如果备库在做全量同步，出现网络抖动而导致连接闪断，那么备库是需要重头开始全量同步的，把已经同步的表和库删了重新同步，导致之前的工作全部白费，这个情况在数据量比较大时，比如 TB 级别，更加让人崩溃。
> 而在 4.4 中，MongoDB 提供了，因网络异常导致全量同步中断情况下，从中断位置恢复全量同步的能力。在尝试恢复一段时间后，如果仍然不成功，那么会重新选择一个同步源进行新的全量同步。这个尝试的超时时间默认是 24 小时，可以通过 replication.initialSyncTransientErrorRetryPeriodSeconds 在进程启动时更改。
> 需要注意的是，对于全量同步过程中遇到的非网络异常导致的中断，仍然需要重新发起全量同步
> 
>

**Comment by vinllen** [comment]
全量同步需要手动删除目的库的数据，然后重启mongoshake。
你发现报错信息，看看如何处理。
admin库还需要设置一个命名转换`transform.namespace =`，我文档里面应该写了。

**Comment by vinllen** [comment]
https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E5%85%A8%E9%87%8F%E6%8A%A5%E9%94%99%E4%BB%A5%E5%90%8E%E5%A6%82%E4%BD%95%E6%81%A2%E5%A4%8D

**Comment by xiaohuazi123** [comment]
> 全量同步需要手动删除目的库的数据，然后重启mongoshake。
> 你发现报错信息，看看如何处理。
> admin库还需要设置一个命名转换`transform.namespace =`，我文档里面应该写了。

比如，我要全量同步B库，我需要先在目标端手动drop掉B库，才能启动mongoshake全量同步是吧？

**Comment by Jannchie** [comment]
> > 全量同步需要手动删除目的库的数据，然后重启mongoshake。
> > 你发现报错信息，看看如何处理。
> > admin库还需要设置一个命名转换`transform.namespace =`，我文档里面应该写了。
> 
> 比如，我要全量同步B库，我需要先在目标端手动drop掉B库，才能启动mongoshake全量同步是吧？

在配置中可以选择全量同步是否同步前先drop库。

`full_sync.collection_exist_drop = true`

**Comment by xiaohuazi123** [comment]
好，明白

**Comment by xiaohuazi123** [comment]
>比如我数据库有3个库，A库，B库，C库，我怎么实现只同步B库，是设置filter.namespace.white = B库 吗  
.  
  
 

  

这个问题还没说

还有，也就是说全量同步中途失败之后，mongo-shake或目标mongo起来之后，会重新删一次目标库，重新进行全量同步？  
因为我看到mongo4.4才有全量同步续传的功能

**Comment by Jannchie** [comment]
> > 比如我数据库有3个库，A库，B库，C库，我怎么实现只同步B库，是设置filter.namespace.white = B库 吗
> > .
> 
> 这个问题还没说
> 
> 还有，也就是说全量同步中途失败之后，mongo-shake或目标mongo起来之后，会重新删一次目标库，重新进行全量同步？
> 因为我看到mongo4.4才有全量同步续传的功能

虽然我没用过这个功能，但我觉得应该是这条配置：
```
# 黑白名单过滤，目前不支持正则，白名单表示通过的namespace，黑名单表示过滤的namespace，
# 不能同时指定。分号分割不同namespace，每个namespace可以是db，也可以是db.collection。
filter.namespace.black =
filter.namespace.white = 
```

**Comment by vinllen** [comment]
比如我数据库有3个库，A库，B库，C库，我怎么实现只同步B库，是设置filter.namespace.white = B库 吗
---
是的。

还有，也就是说全量同步中途失败之后，mongo-shake或目标mongo起来之后，会重新删一次目标库，重新进行全量同步？
---
默认配置下会删除进行重新同步，跟内核的断点续传机制没有关系，目前shake还都没有支持。

**Comment by xiaohuazi123** [comment]
> ## 比如我数据库有3个库，A库，B库，C库，我怎么实现只同步B库，是设置filter.namespace.white = B库 吗
> 是的。
> 
> ## 还有，也就是说全量同步中途失败之后，mongo-shake或目标mongo起来之后，会重新删一次目标库，重新进行全量同步？
> 默认配置下会删除进行重新同步，跟内核的断点续传机制没有关系，目前shake还都没有支持。

明白
