### ISSUE TITLE
增量同步存在偶发的"duplicate key"故障，导致增量卡住

### ISSUE THREAD

**Issue by bjbl2367** [alibaba/MongoShake#454]
mongoshake版本：improve-2.4.12,d42cf214e2611c12d8871252fbd0a3bfb32b89f9,release,go1.10.3,2020-09-01_21:09:51
mongodb版本：4.2
源端sharding，目的端单机
同步方式：全量+增量
增量拉取方式：change stream

经过多次测试，在源端、目的端、mongoshake全部没有调整的情况下，测试7次出现2次如下故障：
全量同步后，日志不断刷类似如下报错：
[2020/09/24 23:59:59 CST] [WARN] 6875935000978522121 6876071181506576446
[2020/09/24 23:59:59 CST] [WARN] detail error info with index[0] msg[E11000 duplicate key error collection: mydb.mycollection index: userId_1_appType_1 dup key: { myId: null, myType: null }] dup[true], isFullSyncStage[true], oplog[&{0xc420b927e0 <nil>}]
[2020/09/24 23:59:59 CST] [CRIT] Replayer-1, executor-1, oplog for namespace[mydb.mycollection] op[u] failed. error type[*errors.errorString] error[doUpdate[update] data[map[myId:osewR0uK2ImoCFJo3i1zXOJSZp5E _id:ObjectIdHex("5f6b04a5d10748ce2ea00bbe")]] not found], logs number[2], firstLog: {"ts":6875935018158391351,"op":"u","g":"","ns":"mydb.mycollection","o":null,"o2":{"_id":"5f6b32898928b0416d5b8d2a","myId":"osewR0jBdInPLLDr3U_D0etpFl4M"},"uk":null,"lsid":null,"fromMigrate":false,"txnNumber":0}
然后增量同步就停止了，重启mongoshake无效，drop库后重新全量+增量才能解决

FAQ里提到了此问题：“但通常，用户最好先检查一下这个原因，mongoshake同步不会产生这个问题”，但我测试这个问题是偶发的，不确定就是源端的问题。
解决方案提到“如果是增量期间报错，可以启用replayer.executor.upsert和replayer.executor.insert_on_dup_update。”，但源端sharding下可能会出现错误，那么有方法解决此问题吗？感谢！

**Comment by vinllen** [comment]
E11000 duplicate key error collection: mydb.mycollection index: userId_1_appType_1 dup key: `{ myId: null, myType: null }`
这个报错看起来是你的索引为空导致插入/修改失败，然后改为upsert发现`{"_id": ObjectOd(5f6b04a5d10748ce2ea00bbe)}`不存在，导致报错。这个检查过目的端对应的这个_id数据是否存在吗？
你这个是全量刚结束进入增量，但是增量位点还没有超过全量结束的位点。从源端拉取来说，change stream不会拉到重复的数据，唯一的可能是全量到增量这段时间的oplog重放是可能存在duplicate key的问题。
你找找源端各个shard中oplog里面，文档_id等于ObjectOd(5f6b04a5d10748ce2ea00bbe}的oplog拉出来看下。另外，给一下你的全量开始和结束的时间。

**Comment by bjbl2367** [comment]
> E11000 duplicate key error collection: mydb.mycollection index: userId_1_appType_1 dup key: `{ myId: null, myType: null }`
> 这个报错看起来是你的索引为空导致插入/修改失败，然后改为upsert发现`{"_id": ObjectOd(5f6b04a5d10748ce2ea00bbe)}`不存在，导致报错。这个检查过目的端对应的这个_id数据是否存在吗？
> 你这个是全量刚结束进入增量，但是增量位点还没有超过全量结束的位点。从源端拉取来说，change stream不会拉到重复的数据，唯一的可能是全量到增量这段时间的oplog重放是可能存在duplicate key的问题。
> 你找找源端各个shard中oplog里面，文档_id等于ObjectOd(5f6b04a5d10748ce2ea00bbe}的oplog拉出来看下。另外，给一下你的全量开始和结束的时间。

检查过目的端，find({ myId: null, myType: null })后能查到一条数据，但只有{"_id": ObjectOd(5f6b04a5d10748ce2ea00bbe)}这一个字段，别的啥也没有了

源端oplog这个我可能得过两天才能查出结果。

第一次全量开始时间：2020/09/24 14:15:52 CST
结束时间：2020/09/24 23:08:00 CST
第一次报错的时间：[2020/09/24 23:08:08 CST] [WARN] 和 [2020/09/24 23:08:20 CST] [CRIT]

另外还有个现象，我第一次全量后报错卡住后，我查find({ myId: null, myType: null })后只有一条结果，把结果那个文档删掉后，再查find({ myId: null, myType: null })，又会冒出来一条结果，再删一条就再出来一个结果，都是只有_id一个字段的文档。而且，我删的同时关注了集合的总文档数，发现删一条总文档数就少一条。会不会是源端的删除类操作在同步中出了问题，到目的端从删除变成了清除了所有字段，只留了_id一个字段？

感谢！

**Comment by vinllen** [comment]
估计你myId和myType是唯一索引，但是已经存在一个都为Null的数据，然后再插入这个数据就会导致duplicate key的报错。因为对于唯一索引来说，至多只允许存在1条为空的的数据。你后面捞到mongodb日志，带上mongoshake的日志一起发我看下，钉钉加我的时候备注一下（先加钉钉群，能找到我），我跟你一起看下。

**Comment by vinllen** [comment]
```
{"ts":6875935018158391351,"op":"u","g":"","ns":"mydb.mycollection","o":null,"o2":{"_id":"5f6b32898928b0416d5b8d2a","myId":"osewR0jBdInPLLDr3U_D0etpFl4M"},"uk":null,"lsid":null,"fromMigrate":false,"txnNumber":0}
```
这条oplog里面的o字段是null，这是不合法的。可能是哪里有问题导致的

**Comment by vinllen** [comment]
当采用change_stream拉取，且当设置incr_sync.change_stream.watch_full_document为true的时候，吐出的数据的o字段是为null的，导致存在bug。

**Comment by vinllen** [comment]
感谢反馈

**Comment by vinllen** [comment]
2.4.14版本已发布修复这个问题
