### ISSUE TITLE
mongodb中的不同collection同时进行操作，使用mongoshake将数据导入到kafka不同topic如何实现

### ISSUE THREAD

**Issue by ghost** [alibaba/MongoShake#457]
mongodb中的不同collection同时进行操作，使用mongoshake将数据导入到kafka不同topic如何实现

**Comment by DEWUIW** [comment]
你使用kafka增量同步oplogs，同步效率怎么样？

**Comment by vinllen** [comment]
目前不支持导入到不同topic，可以描述一下场景，什么情况下，需要推到不同的topic
