### ISSUE TITLE
请问什么时候可以支持go mod方式

### ISSUE THREAD

**Issue by python8384** [alibaba/MongoShake#458]
使用 go vendor 方式，编译过程很不方便，不知道有没有计划支持  go mod方式

**Comment by vinllen** [comment]
短期内暂无计划

**Comment by ZhuoSiChen** [comment]
你可以看下[我的分支](https://github.com/ZhuoSiChen/MongoShake/),
需要编译方式为
cd src/mongoshake
然后执行 go mod tidy
需要注意的是 mock 这个tunnel已经被用作其他用途了。
