### ISSUE TITLE
源库3.4 sharding集群同步到目的端4.0sharding集群报错：command insert requires authentication

### ISSUE THREAD

**Issue by sitoc** [alibaba/MongoShake#459]
在做数据同步时报如下错误**command insert requires authentication**，注：是在进行增量同步时发生的报错，全量同步可以正常进行；
源端：3.4 sharding集群
目的端：4.0.12 sharding 集群
![image](https://user-images.githubusercontent.com/17570029/95578758-006d3b80-0a67-11eb-8040-8e2837222eb2.png)
目的端的账号权限如下：
![image](https://user-images.githubusercontent.com/17570029/95579130-a3be5080-0a67-11eb-817b-9fc8c93386d1.png)

疑惑：我尝试测试3.4 sharding集群同步到 3.4 sharding集群时，却没有这样的报错
希望大佬有时间可以回复一下我的这个问题，非常感谢

**Comment by vinllen** [comment]
你这个是启用了SSL加密吗？这个报错看起来就是没有认证导致的，不过全量可以，增量理论上不应该有问题

**Comment by sitoc** [comment]
没有启用SSL，都是直接username+password登录的，并且模式为full都是可以的，只是走到增量同步的时候就有问题，我源端不变，把目的端换成一个3.4版本sharding也不会有问题，你那边方便的话，可以试一下我这个场景，看看有问题不，非常感谢您在百忙之中能抽出时间来看我的问题。

**Comment by vinllen** [comment]
这个问题我晚上看下

**Comment by vinllen** [comment]
用户连接串配置不正确：
`"TunnelAddress":["mongodb://dba:***@xx.xx.xx.xx:37559","yy.yy.yy.yy:37559","zz.zz.zz.zz:37559?authSource=admin\u0026authMechanism=SCRAM-SHA-256"]`
正确配置请参考：https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E6%8A%A5%E9%94%99oplog-tailer-initialize-failed-no-oplog-ns-in-mongo
`tunnel.address = mongodb://dba:***@xx.xx.xx.xx:37559?authSource=admin\u0026authMechanism=SCRAM-SHA-256;mongodb://dba:***@yy.yy.yy.yy:37559?authSource=admin\u0026authMechanism=SCRAM-SHA-256;mongodb://dba:***@zz.zz.zz.zz:37559?authSource=admin\u0026authMechanism=SCRAM-SHA-256;`

**Comment by sitoc** [comment]
实属自己文档没看仔细，导致这样的问题出现，非常感谢大佬的热心解答
