### ISSUE TITLE
High availabilty

### ISSUE THREAD

**Issue by raqqun** [alibaba/MongoShake#462]
Hi there,

I want to use mongoshake to sync two mongodb replica sets and i wanted to know if there is a possibility to run mongoshake in high availability by running multiple instances. 

I've already read this https://github.com/alibaba/MongoShake/wiki/MongoShake-Detailed-Documentation#32-high-availability which describes the possibility of saving the oplog position in the source database for fault tolerance.

Any information on how to implement multiple instances is welcome.

Best regards

**Comment by vinllen** [comment]
You can enable `master_quorum` option and then start two mongoshake instances to fulfill your goals. Once one instance crashed, the other will take over the sync job. One thing that should be mentioned that the HA only works when mongoshake runs in the increase-sync stage which means fetch and replay oplog, the HA switch will meet error in the full-sync stage(initial sync).
Generally speaking, you can also use `start.sh` script to start your mongoshake which uses hypervisor inner so once mongoshake crashed, the hypervisor will reboot the instance immediately.
