### ISSUE TITLE
“oplog各字段的解析”文档描述存在问题

### ISSUE THREAD

**Issue by zcyoop** [alibaba/MongoShake#464]
文档地址：https://github.com/alibaba/MongoShake/wiki/oplog%E5%90%84%E5%AD%97%E6%AE%B5%E7%9A%84%E8%A7%A3%E6%9E%90
问题：
MongoShake中对应的oplog格式-》示例一》ts描述应该是右移32位

**Comment by vinllen** [comment]
感谢反馈，已订正
