### ISSUE TITLE
能否设置延迟一周全量覆盖同步一次至目标的单mongo实例？

### ISSUE THREAD

**Issue by kuaiwenwu** [alibaba/MongoShake#468]
请问是否可以设置延迟一周全量同步到目标mongo服务实例,而且每次都是覆盖目标的示例数据呢。

**Comment by vinllen** [comment]
增量有延迟同步的功能，我理解你这里说的全量延迟同步没办法做到，除非存储全量数据一周。比如你定期搞一个中间库，启动一个mongoshake源库A->中间库B存储，然后过一周再启动一个mongoshake把B库全量写到C库。
覆盖这个已经设置`full_sync.executor.insert_on_dup_update `默认就是覆盖。
