### ISSUE TITLE
是否支持只同步部分表？

### ISSUE THREAD

**Issue by bishuilantian1** [alibaba/MongoShake#469]

**Comment by vinllen** [comment]
参见wiki，配置filter相关参数即可：https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E#16-%E8%BF%87%E6%BB%A4%E7%9B%B8%E5%85%B3
