### ISSUE TITLE
同一个数据库的不同DB之间，源库是DB A，目标库是DB B，这种是否可同步？

### ISSUE THREAD

**Issue by bishuilantian1** [alibaba/MongoShake#471]
如果可以的话如何配置？在配置文件中未发现这种场景的配置参数

**Comment by vinllen** [comment]
`transform.namespace`:
https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E#18-%E5%85%B6%E4%BB%96
