### ISSUE TITLE
 请教下在进行同步时，怎么样算完成全量同步呢，这取决于什么？ 如果全量同步完成的话，这时候的checkpoint应该是什么时间呢？

### ISSUE THREAD

**Issue by yuwei43** [alibaba/MongoShake#472]
请教下在进行同步时，怎么样算完成全量同步呢，这取决于什么？
如果全量同步完成的话，这时候的checkpoint应该是什么时间呢？

**Comment by vinllen** [comment]
全量完成：
https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-sync_modeall%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E5%85%A8%E9%87%8F%E9%98%B6%E6%AE%B5%E7%BB%93%E6%9D%9F%E8%BF%9B%E5%85%A5%E4%BA%86%E5%A2%9E%E9%87%8F
全量完成后，会记一次checkpoint，为全量开始的时间点。例如，从8点开始同步，10点完成全量同步并进入增量，则10点完成后，会记录一次checkpoint=8点

**Comment by yuwei43** [comment]
可以理解为，从八点开始(此时oplog的最后产生时间为8点)，只要把数据同步到oplog中记录的8点时的数据就代表全量同步完成了嘛？10点完成全量同步后(此时checkpoint=8点)再从8点开始进行增量同步

**Comment by vinllen** [comment]
你可以这么理解，不过全量同步不是基于oplog来同步的，而是基于一次全量扫表，此处跟mongodb主从同步initialSync原理基本一致。全量同步以后追的增量都是基于oplog来的，需要从8点开始拉取，此处便于你的理解，你可以认为mongodb的全量同步是基于8点的snapshot来实现的，虽然实际上并不是一个snapshot，而是一个不断变动的数据，所以8-10点的Oplog应用是可能会存在重复的，不过可以依赖oplog的幂等性来解决。

**Comment by yuwei43** [comment]
好的感谢。
