### ISSUE TITLE
mongoshark进行同步时总是报too many open file，已将其Limit改为1024000仍然会有这个报错的出现

### ISSUE THREAD

**Issue by meimeng1** [alibaba/MongoShake#481]

**Comment by vinllen** [comment]
确认是mongoshake自身打开的fd？

**Comment by meimeng1** [comment]
这个问题我解决了，之后我将limit改完后重启了服务,多谢回答




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vinllen Chen"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 晚上6:04
收件人: "alibaba/MongoShake"<MongoShake@noreply.github.com&gt;; 
抄送: "1443182787"<1443182787@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [alibaba/MongoShake] mongoshark进行同步时总是报too many open file，已将其Limit改为1024000仍然会有这个报错的出现 (#481)





 
确认是mongoshake自身打开的fd？

**Comment by meimeng1** [comment]
嗯嗯，这个确实是mongoshake那台服务器上的fd，改过后，重启服务得到恢复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vinllen Chen"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 晚上6:04
收件人: "alibaba/MongoShake"<MongoShake@noreply.github.com&gt;; 
抄送: "1443182787"<1443182787@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [alibaba/MongoShake] mongoshark进行同步时总是报too many open file，已将其Limit改为1024000仍然会有这个报错的出现 (#481)





 
确认是mongoshake自身打开的fd？
