### ISSUE TITLE
使用时大部分导致目标端OOM，需要调整哪些参数

### ISSUE THREAD

**Issue by meimeng1** [alibaba/MongoShake#482]

**Comment by vinllen** [comment]
如果是mongodb本身oom的，需要调整目的端的配置

**Comment by meimeng1** [comment]
好的，多谢回答



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vinllen Chen"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 晚上6:03
收件人: "alibaba/MongoShake"<MongoShake@noreply.github.com&gt;; 
抄送: "1443182787"<1443182787@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [alibaba/MongoShake] 使用时大部分导致目标端OOM，需要调整哪些参数 (#482)





 
如果是mongodb本身oom的，需要调整目的端的配置
