### ISSUE TITLE
全量同步的目标端data目录要小于源端的data目录,大概相差几个G，查看日志全量同步已经完成,请问之间有什么数据遗失情况嘛

### ISSUE THREAD

**Issue by meimeng1** [alibaba/MongoShake#483]

**Comment by vinllen** [comment]
你可以count看下差别，data目录可能跟压缩，分片率有关系

**Comment by meimeng1** [comment]
好的我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vinllen Chen"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 晚上6:02
收件人: "alibaba/MongoShake"<MongoShake@noreply.github.com&gt;; 
抄送: "1443182787"<1443182787@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/MongoShake] 全量同步的目标端data目录要小于源端的data目录,大概相差几个G，查看日志全量同步已经完成,请问之间有什么数据遗失情况嘛 (#483)





 
你可以count看下差别，data目录可能跟压缩，分片率有关系
