### ISSUE TITLE
源代码编译问题github.com/gugemichael/nimo4go

### ISSUE THREAD

**Issue by haochenhh** [alibaba/MongoShake#488]
![image](https://user-images.githubusercontent.com/22142365/100190403-22dcea80-2f29-11eb-97f2-4571dea80100.png)

![image](https://user-images.githubusercontent.com/22142365/100195088-caf6b180-2f31-11eb-91ee-42df1b530c43.png)
syscall.SIGUSR2\syscall.SIGUSR1是因为windows下没有，有什么替代吗？
另外nimo4go的三个函数，是因为版本问题么

PS：有交流群么，QQ\微信\钉钉。。。。

**Comment by vinllen** [comment]
打的二进制包里面直接有windows的包，应该可以执行

**Comment by vinllen** [comment]
钉钉群在readme最后有给出
