### ISSUE TITLE
CheckPoint和MongoShake对应问题。

### ISSUE THREAD

**Issue by cason0126** [alibaba/MongoShake#490]
问题：
  测试时发现。用同一个MongoShake，测试不同的任务；（只在白名单 更换一下 col）。但是此时CKPT是没有更新的。
是不是意味着，知道 目标源 和 目的地发生变化。 都需要每次去配置ckpt的name以区分？ 
展望：
后面会不会计划考虑增加这种 自动识别的方式？

**Comment by vinllen** [comment]
checkpoint标记目前同步的位点，如果你黑白名单发生变化，希望接着上次checkpoint的时间位点同步，则不需要调整，否则checkpoint需要调整。
