### ISSUE TITLE
全量+增量，进入增量后发现有一个shard停止同步了

### ISSUE THREAD

**Issue by bjbl2367** [alibaba/MongoShake#491]
mongoshake版本：improve-2.2.1,97bd6ffb1bb4ee7df2d5f95c021b2d6d6cc2f38f,release,go1.12.9,2020-05-27_20:06:22
mongodb版本：3.2.8
源端sharding，目的端单机

我以all模式启动的mongoshake，在全量同步完成进入增量后一段时间（今天），发现有部分数据在源端存在，目的端却查不到
访问127.0.0.1:9400/repl看到，其中一个shard（s18）已经停止同步了（lsn、lsn_ack、lsn_ckpt的time值都是11月1日的），而其他shard的同步均正常。

查看mongoshake日志发现，从缺少的部分数据在源端产生的时间一直到现在，都没有INFO和CRIT以外级别的日志，CRIT日志数量也不多
部分CRIT级别日志如下：

> [11:25:04 CST 2020/09/23] [CRIT] (mongoshake/collector.(*OplogSyncer).FlushByDoc:470) OplogSyncer flush checkpoint get ackTs of syncer s5 failed. candidates should follow up unack[6875233985006403593] ack[6875238194074353665]
> [15:32:16 CST 2020/09/24] [CRIT] (mongoshake/executor.(*Executor).execute:100) Replayer-18, executor-18, oplog for namespace[库.集合] op[u] failed. error type[*errors.errorString], error[doUpdate run upsert/update[false] failed[interrupted at shutdown]], logs number[1], firstLog: [{ts 6875953559532208132} {op u} {g } {ns 库.集合} {o [{$set [文档数据]}]} {o2 map[_id:ObjectIdHex("5a704bee5ed9a0429ff01b10")]} {uk map[]} {lsid <nil>} {fromMigrate false}]
> [11:31:32 CST 2020/11/24] [CRIT] (mongoshake/executor.(*Executor).execute:100) Replayer-6, executor-6, oplog for namespace[库.集合] op[i] failed. error type[*mgo.BulkError], error[read tcp 127.0.0.1:44886->127.0.0.1:27017: i/o timeout], logs number[3], firstLog: [{ts 6898522667779883012} {op i} {g } {ns 库.集合} {o [文档数据]} {o2 map[]} {uk map[]} {lsid <nil>} {fromMigrate false}]

请问这会是什么原因？如何解决？我们计划明天上午重启mongoshake试一下
感谢！

**Comment by bjbl2367** [comment]
重启mongoshake后，访问127.0.0.1:9400/repl，看到出问题的shard（s18）情况如下：

> {
>     "logs_get": 33536,
>     "logs_repl": 0,
>     "logs_success": 0,
>     "lsn": {
>         "time": "1970-01-01 08:00:00",
>         "ts": "0",
>         "unix": 0
>     },
>     "lsn_ack": {
>         "time": "1970-01-01 08:00:00",
>         "ts": "0",
>         "unix": 0
>     },
>     "lsn_ckpt": {
>         "time": "2020-11-01 07:37:41",
>         "ts": "6889932681648275459",
>         "unix": 1604187461
>     },
>     "now": {
>         "time": "2020-11-27 10:32:53",
>         "unix": 1606444373
>     },
>     "replset": "s18",
>     "tag": "improve-2.2.1,97bd6ffb1bb4ee7df2d5f95c021b2d6d6cc2f38f,release,go1.12.9,2020-05-27_20:06:22",
>     "tps": 0,
>     "who": "XXXX"
> },

lsn、lsn_ack的time变成1970-01-01 08:00:00了，并且lsn、lsn_ack、lsn_ckpt的time值仍然不再变化。

查看admin库下的ckpt_mvck_map表，发现很多类似这样的数据：
> { "_id" : ObjectId("5fc060f17fe1f17598c33a69"), "deleteItem" : {  }, "key" : { "docId" : ObjectId("5f8d8d047d57178c801cfcbf"), "namespace" : "库.集合" }, "insertMap" : { "s18" : Timestamp(1604178011, 60) } }

查看admin库下的ckpt_mvck_syncer表，发现正常的shard的barrierKey是空的，出问题的s18则有内容：
> { "_id" : ObjectId("5fc0612e7fe1f17598c36549"), "name" : "s13", "barrierKey" : {  } }
> { "_id" : ObjectId("5fc0612e7fe1f17598c3654a"), "name" : "s18", "barrierKey" : { "docId" : ObjectId("5f9ccb9c7d57178c803e5ed5"), "namespace" : "库.集合" } }

查看admin库下的ckpt_mvck_syncer表，发现出问题的s18的两个Timestamp落后很久，和之前看到的11月1日的日期相符：
> { "_id" : ObjectId("5fc0615f7fe1f17598c38786"), "name" : "s18", "ackTs" : Timestamp(1604187461, 3), "syncTs" : Timestamp(1604187461, 3) }

**Comment by vinllen** [comment]
2.2的版本有缺陷，已经下线掉了，你升2.4看下，2.0和2.4都是稳定版本，2.4会长期维护。

**Comment by bjbl2367** [comment]
好的，另外再请教下，如果我们正在运行的另一个2.4.14换成最新的2.4.16，能接着之前增量的点位继续增量吗？谢谢！

**Comment by vinllen** [comment]
可以的

**Comment by bjbl2367** [comment]
我从2.2.1换成了2.4.14，开始全量一段时间后报错"duplicate key"。
我按照FAQ里说的，启用了full_sync.executor.insert_on_dup_update和full_sync.executor.filter.orphan_document
又全量同步了一段时间（30分钟），报错：
> [14:17:11 CST 2020/11/30] [CRIT] (mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1:422) splitter reader[DocumentReader src[mongodb://地址] ns[{库 集合}] query[map[]]] get next document failed: Cursor not found (namespace: '库.集合', id: 1981226839477009723).
> [14:17:15 CST 2020/11/30] [CRIT] (mongoshake/collector/docsyncer.(*DocExecutor).start:157) DocExecutor[21] collectionExecutor[{库 集合}] sync failed: convert oplog[[{_id ObjectIdHex("5fc48e42479ee007e9f032c0")} {AAA BBB} {CCC DDD}]] from insert to update run failed[not found]（这一条不断重复）
两种情况都是还在全量同步的过程中发生的，重启mongoshake无效

我感觉和这个issue里的情况好像差不多：[https://github.com/alibaba/MongoShake/issues/451](url)
同步的表里也有上亿条数据的大表，也是30分钟准时报错，这个问题现在有进展吗？

**Comment by vinllen** [comment]
这个应该是cursor超时的问题，下个版本会修掉，之前noCursorTimeout设置了，但是有些版本不支持，就临时又给关掉了

**Comment by vinllen** [comment]
当前问题我先关闭，有问题在 #451 统一回复哈。

**Comment by vinllen** [comment]
@bjbl2367 方便的话钉钉联系我一下，可以加我的时候备注一下
