### ISSUE TITLE
增量获取oplog日志同步到kafka上时能否只过滤出insert变动日志

### ISSUE THREAD

**Issue by jonlen2012** [alibaba/MongoShake#493]
增量获取oplog日志同步到kafka上时能否只过滤出insert变动日志，对应的参数是什么？

**Comment by vinllen** [comment]
不能，你可以自己消费时候过滤

**Comment by jonlen2012** [comment]
> 不能，你可以自己消费时候过滤

如果同步的时候不过滤，一天的变更数据量就达到了100多个G。最终数据落到Kafka上时只会进入一个分区（mongoshake只会把数据同步到Kafka的partition 0中），这样对Kafka集群中的单台机器压力有点大。请问有没什么办法在变更数据上做处理？

**Comment by vinllen** [comment]
目前的确是1个partition0，后面会考虑分partition，不过考虑到有些用户可能需要1个partition保证数据的一致性，如何切分partition是个问题，不同用户可能有不同的需求，关于切分如果你有什么想法可以抛出来。

**Comment by vinllen** [comment]
过滤的确是没有的，只过滤insert这个需求也比较特定化，大部分都是至少关注所有的DML操作。
关于分partition我看你新建了一个issue，这个重复就先关掉了。
#496
