### ISSUE TITLE
关于raw格式数据解析

### ISSUE THREAD

**Issue by zcyoop** [alibaba/MongoShake#494]
你好，因为目前在使用json时，go会报出 year outside of range [0,9999]]，所以准备使用raw格式进行传输，自己来实现receiver，但是目前接受到raw格式，不知道如何解析（不太懂go），在wiki里面也无法找到详细的解析信息，只找到了https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8kafka-tcp-rpc-file%E7%AD%89%E5%BC%82%E6%AD%A5%E9%80%9A%E9%81%93%E8%BF%9B%E8%A1%8C%E6%95%B0%E6%8D%AE%E7%9A%84%E5%8F%91%E9%80%81%E5%92%8C%E6%B6%88%E8%B4%B9
，但是并没有告知该如何解析，劳烦告知一下应该如何解析raw信息 ORZ

**Comment by TIMPLIN** [comment]
麻烦问下老哥，最后是怎么解析raw中的信息的，这个receiver源码你是怎么改的呀
