### ISSUE TITLE
磁盘io很高

### ISSUE THREAD

**Issue by maxzhang2017** [alibaba/MongoShake#495]
开启mongoshake之后，磁盘io很高，而且mongo的io  read 最高达到30多M每秒，导致增量同步的差距越来越大

<img width="621" alt="图片" src="https://user-images.githubusercontent.com/13342261/100437751-2f557480-30dc-11eb-8bcb-518006fd16e0.png">

**Comment by vinllen** [comment]
你是增量还是全量，磁盘IO高在全量阶段是正常的，扫表操作导致，增量阶段会拉取oplog，如果刚启动是会比较高，后面追上了就不会这么大。
增量如果追不上，看下磁盘IO是不是到瓶颈了
