### ISSUE TITLE
连接错误：mongo url后边不加库名不报错，加上后报错，错误信息url ？号后边的不是自己写的

### ISSUE THREAD

**Issue by YaErHub** [alibaba/MongoShake#497]
(mongoshake/common.NewMongoConn:24) Connect to mongodb://root:***@d**-****58-pub.mongodb.rds.aliyuncs.com:20717/test?connect=direct failed. server returned error on SASL authentication step: Authentication failed.

**Comment by YaErHub** [comment]
这里配置文件里配置的是 增量到kafka

**Comment by jonlen2012** [comment]
权限问题，不加库名默认进入的test库

**Comment by YaErHub** [comment]
> 权限问题，不加库名默认进入的test库

感谢，所以我在后面追加了?authSource=admin，authSourceDatbase=admin分别试了下，都报错了，之前出现权限问题加了第一个参数就可以解决了，现在一直解决不了，有什么建议吗老哥
