### ISSUE TITLE
请问可以抽象一下全量同步的步骤吗？

### ISSUE THREAD

**Issue by ZhuoSiChen** [alibaba/MongoShake#500]

**Comment by vinllen** [comment]
全量同步就是一个源库扫表+目的端insert的过程，当然并发度是由配置参数里面进行控制的。
https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E

**Comment by ZhuoSiChen** [comment]
恩恩，感谢回复。
目的端不只有mongodb,我这边的需求是把数据同步到ES中去.
然而我发现只能通过是否是tuunel == direct 去分出我的代码逻辑,
不能很好的嵌入到原有的mongoshake的执行逻辑中去。

**Comment by vinllen** [comment]
你可以看下kafka_writer的逻辑，怎么写kafka的，改成写es，改动应该不大

**Comment by ZhuoSiChen** [comment]
嗯嗯，kafka的逻辑,我看只有增量同步的。
好像没有涉及全量的同步
