### ISSUE TITLE
增量同步数据的checkpoint问题

### ISSUE THREAD

**Issue by YaErHub** [alibaba/MongoShake#502]
mongoshake进行增量数据同步到kafka时，是不是首先以默认的1970的时间点进行同步？考虑到生产中mongo数据量较大，并且所处理的数据可能用不到较久之前的数据，如何去调整checkpoint这个参数，使得增量同步时从指定的checkpoint开始传输数据？

**Comment by YaErHub** [comment]
如果我从一个数据量很大的collection中进行增量获取，如何将checkpoint直接调整到当前的时间点呢

**Comment by vinllen** [comment]
如果第一次启动没有checkpoint，则会按照配置文件中的`checkpoint.start_position`进行启动拉取，调整这个参数就可以从指定时间拉取。

**Comment by vinllen** [comment]
checkpoint时间也是可以调整的，你直接登录库重写这个时间就行

**Comment by YaErHub** [comment]
> checkpoint时间也是可以调整的，你直接登录库重写这个时间就行

好的，感谢
