### ISSUE TITLE
如何配置kafka集群

### ISSUE THREAD

**Issue by wangymyy** [alibaba/MongoShake#503]

**Comment by vinllen** [comment]
先看下这个
https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E5%9C%BA%E6%99%AF%E9%85%8D%E7%BD%AE#5-%E4%BB%8Emongodb%E5%89%AF%E6%9C%AC%E9%9B%86%E5%90%8C%E6%AD%A5%E5%88%B0kafka%E9%80%9A%E9%81%93
