### ISSUE TITLE
oplog同步时数据可以过滤数据么

### ISSUE THREAD

**Issue by lijiawei6** [alibaba/MongoShake#505]
备份时删除操作过滤掉，只同步增加和修改操作可以么

**Comment by vinllen** [comment]
目前不支持，需要自己改代码编译。
编译流程参考：
https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E6%9E%9C%E6%88%91%E6%83%B3%E8%87%AA%E5%B7%B1%E7%BC%96%E8%AF%91%E4%BB%A3%E7%A0%81%EF%BC%8C%E6%88%91%E8%AF%A5%E5%A6%82%E4%BD%95%E6%93%8D%E4%BD%9C
过滤流程参考filter目录下面的实现
