### ISSUE TITLE
gid开启后，希望可同步  不支持gid的MongoDB  或者  支持gid但是没有开启gid的阿里云MongoDB

### ISSUE THREAD

**Issue by xzshinan** [alibaba/MongoShake#510]
场景：
1、使用阿里云MongoDB
2、开启了gid
3、使用以上配置的MongoDB作为源端  同步不支持gid的MongoDB  或者  同步支持gid但是没有开启gid的阿里云MongoDB

会报以下错误：
op[i] failed. error type[*mgo.LastError] error[BSON field 'insert.g' is an unknown field.]

希望：
通过配置文件，类似做filter namespace的操作  ，使用  开启了gid的阿里MongoDB作为源端  可同步  其他不支持gid的MongoDB 以及 支持gid但是没有开启gid的阿里云MongoDB

**Comment by vinllen** [comment]
2.4.17版本已发布
