### ISSUE TITLE
mongo-shake tunnel = file  生成的文件相关问题

### ISSUE THREAD

**Issue by donkeyForward** [alibaba/MongoShake#518]
tunnel = file 生成的文件，后续怎么使用，比如说，怎么样导入到mongo?  或者导入到kafka?   哪位大侠帮忙看看，谢谢。

**Comment by vinllen** [comment]
需要借助receiver，对接成本目前来说比较高，要自己写代码：https://github.com/alibaba/MongoShake/wiki/FAQ#q-how-to-connect-to-different-tunnel-except-direct
