### ISSUE TITLE
o使用bson.D数据结构时空对象和空数组都会转换成空数组

### ISSUE THREAD

**Issue by MorganYoung** [alibaba/MongoShake#523]
例如mongodb中这样的数据结构
{
"_id":"xxx",
"array1":[],
"obj1":{}
}
通过mongoshake发出kafka消息是这样的
{
...
"o":[
{"Name":"obj1","Value":[]},
{"Name":"array1","Value":[]}
]
...
}

是不是这样就没法通过json反序列化成原来的数据结构了。

**Comment by vinllen** [comment]
由于部分数据对顺序有要求，所以目前都是按照bson.D的转换，不是bson.M

**Comment by pan3793** [comment]
你好，我不是很熟悉 GoLong 和 MongoDB，想了解一下 bson.M 序列化成的 JSON 是一种标准的数据交换方式吗？换句话说，我能使用别的语言比如 Python Java 将这个 JSON 还原成 MongoDB Driver 库提供的 BSON 数据结构吗？
