### ISSUE TITLE
源端为多shared副本集群，目的端为集群模式，启动报错

### ISSUE THREAD

**Issue by zw-star** [alibaba/MongoShake#524]
配置：
# 分片集：mongodb://username1:password1@primaryA,secondaryB,secondaryC;mongodb://username2:password2@primaryX,secondaryY,secondaryZ
mongo_urls = mongodb://192.168.137.161:27001,192.168.137.162:27001,192.168.137.163:27001;mongodb://192.168.137.161:27002,192.168.137.162:27002,192.168.137.163:27002;mongodb://192.168.137.161:27003,192.168.137.162:27003,192.168.137.163:27003
# please fill the source config server url if source mongodb is sharding. 配置集地址
mongo_cs_url = mongodb://192.168.137.161:27018,192.168.137.162:27018,192.168.137.163:27018
# please give at least one mongos address if source is sharding.
# 如果源端采用change stream拉取，这里还需要配置至少一个mongos的地址，多个mongos地址以逗号（,）分割
mongo_s_url = mongodb://192.168.137.161:27017,192.168.137.162:27017,192.168.137.163:27017

启动报错
[root@dst mongo-shake-v2.4.17]# /opt/mongo-shake-v2.4.17/collector.linux  -conf=/opt/mongo-shake-v2.4.17/collector.conf
[17:34:32 HKT 2021/01/04] [CRIT] (mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1:422) splitter reader[DocumentReader src[mongodb://192.168.137.161:27017,192.168.137.162:27017,192.168.137.163:27017] ns[{calon user}] query[map[]]] get next document failed: (BadValue) maxTimeMS can only be used with getMore for tailable, awaitData cursors
panic: splitter reader[DocumentReader src[mongodb://192.168.137.161:27017,192.168.137.162:27017,192.168.137.163:27017] ns[{calon user}] query[map[]]] get next document failed: (BadValue) maxTimeMS can only be used with getMore for tailable, awaitData cursors

goroutine 626 [running]:
vendor/github.com/vinllen/log4go.Crashf(0xcd69f4, 0x2, 0xc4200b3f98, 0x1, 0x1)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:46 +0xf8
mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1(0xc420178a20, 0xc4200a0000, 0xc420228600, 0xc4201d6c20, 0xc42024ad10)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:422 +0xeb
created by mongoshake/collector/docsyncer.(*DBSyncer).collectionSync
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:414 +0x2cc

如何解决了

**Comment by vinllen** [comment]
提供一下副本集的版本号

**Comment by vinllen** [comment]
3.6以前的版本不能设置maxTimeMS，此处逻辑需要调整。

**Comment by vinllen** [comment]
2.4.18版本发布已修复
