### ISSUE TITLE
standalone模式启动失败

### ISSUE THREAD

**Issue by vinllen** [alibaba/MongoShake#526]
create connectMode[standalone] failed: unknown read preference standalone

**Comment by jdkcn** [comment]
一样的问题。

query[map[]]] get next document failed: create connectMode[standalone] failed: unknown read preference standalone
panic: send on closed channel

goroutine 436 [running]:
vendor/github.com/vinllen/log4go.(*ConsoleLogWriter).LogWrite(0xc42000c7c0, 0xc4204fa700)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/termlog.go:41 +0x43
vendor/github.com/vinllen/log4go.Logger.intLogf(0xc4200db800, 0x7, 0xcd616c, 0x2, 0xc4206c1f98, 0x1, 0x1)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/log4go.go:223 +0x289
vendor/github.com/vinllen/log4go.Crashf(0xcd616c, 0x2, 0xc4206c1f98, 0x1, 0x1)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:44 +0x6c
mongoshake/collector/docsyncer.(*DBSyncer).collectionSync.func1(0xc42045a960, 0xc42023e500, 0xc420118000, 0xc420223640, 0xc4203b0aa0)
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:422 +0xeb
created by mongoshake/collector/docsyncer.(*DBSyncer).collectionSync
	/home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_syncer.go:414 +0x2cc
