### ISSUE TITLE
增量同步存在某些表数据同步出现延迟，某些表不存在延迟的情况

### ISSUE THREAD

**Issue by yuwei43** [alibaba/MongoShake#530]
线上已经稳定运行几个月，昨天出现了这种情况：
例：表A与表B，时间为22点   表A已经成功同步到22点的数据了，但是表B的数据同步还停留在9点，我们可以看到源端B表是有数据的，但是出现了同步延迟的情况，一直到第二天才追上数据。
请问下出现这种情况是正常的嘛？是会基于oplog再进行分表读取写入嘛

**Comment by vinllen** [comment]
是会分表hash后同步写入，如果某些表的压力比较大，会造成表存在lag，但是正常情况下lag不会这么大，可能是表A写入很少，比如10多个小时没有写入过，而另外一个表一直有写入，这种情况是可能出现你说的这个lag。
