### ISSUE TITLE
mongoshake-stats in full sync

### ISSUE THREAD

**Issue by kinesra75** [alibaba/MongoShake#536]
Hi everyone,

I start mongoshake in full sync, but when Ii tried to connect stats with :

bin/mongoshake-stat --host=127.0.0.1 --port=9101

I got :

Traceback (most recent call last):
  File "bin/mongoshake-stat", line 78, in <module>
    if detail["tag"] is None:
KeyError: 'tag'

Thanks in advance !

**Comment by vinllen** [comment]
Currently, `mongoshake-stat` is only used to monitor the incr-sync stage. If you want to monitor the full-sync stage, you can curl the 9101 monitor directly: `curl 127.0.0.1:9101/progress`.

**Comment by kinesra75** [comment]
ok thanks !
