### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by twink7e** [alibaba/MongoShake#541]
[2021/01/21 20:54:06 CST] [INFO] [name=cdp_001, stage=full, get=346198792, write_success=346198792, tps=0]
[2021/01/21 20:54:11 CST] [INFO] [name=cdp_001, stage=full, get=346198792, write_success=346198792, tps=0]
[2021/01/21 20:54:16 CST] [INFO] [name=cdp_001, stage=full, get=346198792, write_success=346198792, tps=0]
panic: send on closed channel

goroutine 3291703 [running]:
vendor/github.com/vinllen/log4go.(*FileLogWriter).LogWrite(0xc420304000, 0xc4241f5280)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/filelog.go:45 +0x42
vendor/github.com/vinllen/log4go.Logger.intLogf(0xc4200ad800, 0x7, 0xce1cd4, 0x12, 0xc447943fa8, 0x2, 0x2)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/log4go.go:223 +0x289
vendor/github.com/vinllen/log4go.Crashf(0xce1cd4, 0x12, 0xc447943fa8, 0x2, 0x2)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/vendor/github.com/vinllen/log4go/wrapper.go:44 +0x6c
mongoshake/collector/docsyncer.(*DocExecutor).start(0xc42c534120)
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_executor.go:157 +0x16b
created by mongoshake/collector/docsyncer.(*CollectionExecutor).Start
        /home/zhuzhao.cx/mongo-shake/MongoShake/src/mongoshake/collector/docsyncer/doc_executor.go:75 +0x161

**Comment by vinllen** [comment]
https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&FAQ#q-%E6%8A%A5%E9%94%99panic-send-on-closed-channel
