### ISSUE TITLE
Support format Canonical Extended JSON Format

### ISSUE THREAD

**Issue by pan3793** [alibaba/MongoShake#542]
BSON is a Strict Defined Format which can be serde in many language, and BSON can be serialize as `Binary Format` or `Canonical Extended JSON Format`, see detail at [BSON Spec](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#conversion-table)

Currently, MongoShake support format `bson`, which actually is BSON Binary Format, in Java/Scala side, we can use lib `org.mongodb:bson:4.0.5` to deserialize it:
```
import org.bson._

val bson = new RawBsonDocument(bytes)
val ts = bson.getTimestamp("ts").getValue
val ns = bson.getString("ns").getValue
val op = bson.getString("op").getValue
```

And we can serialize BSON as `Canonical Extended JSON Format` and deserialize:
```
val json = bson.toJson
val bson = BsonDocument.parse(bson)
```

So, I'm here to request MongoShake to support new format `bson-json`, a more readable and cross language strict format which easier develop and debug. For example, we can mock data in unit test and use `kafka-console-consumer` to check data when something going wrong.

**Comment by vinllen** [comment]
2.4.21 version has released, please check it.

**Comment by pan3793** [comment]
Thanks, will try in next few days.

**Comment by vinllen** [comment]
Star v2.4.22, I modify the policy that adds a 'tunnel.json.format' in configuration, you can choose to use Canonical Extended Json Format if set 'tunnel.json.format = canonical_extended_json'. By default, mongoshake stills use the old policy.
