### ISSUE TITLE
全量同步过程中，mongoshake i/o timeout, 进程down了。有什么方法或配置能避免自动关闭吗？

### ISSUE THREAD

**Issue by yuwei43** [alibaba/MongoShake#547]
我的问题和这个有点相似：
https://github.com/alibaba/MongoShake/issues/335

请问下现在全量同步支持断点续传了嘛~ 我们也遇到了这个问题。
因为海外到国内的网络IO会出现问题，在全量同步的时候会报这个问题，就会自动停止当前进程，这就导致了同步无法进行，每同步一部分就timeout->进程down。有什么方法或配置能避免mongoShake down掉嘛？

**Comment by vinllen** [comment]
timeout导致进程down通常是：
1. 如果显示write timeout，则一般是目的端数据库的问题
2. 如果显示getNext源端拉取timeout，则一般是源库的问题。此外，2.4.18版本修过一个bug，也可能跟这个有关系
3. 当然也有可能是网络的问题。
你需要检查一下目的端数据库的日志，看看是不是压力过大或者别的原因导致没有响应连接断开了。
全量阶段的断点续传目前还没支持，后面即使支持的话也是4.4+的版本。
