### ISSUE TITLE
MongoShake HA 信息保存到集合名称能不能配置？

### ISSUE THREAD

**Issue by ghost** [alibaba/MongoShake#549]
utils.VarCheckpointStorageDbReplicaDefault = "mongoshake"
QUORUM_COLLECTION string = "election"

selectLeader() 方法：

quorum.UseElectionObjectId(bson.ObjectIdHex("5204af979955496907000001"))
go quorum.BecomeMaster(conf.Options.CheckpointStorageUrl, utils.VarCheckpointStorageDbReplicaDefault)

目前测试发现 HA 保存到 MongoDB 固定为： mongoshake 库的 election 集合，主键固定为：5204af979955496907000001。

如果想配置多个抽取不同实例的 MongoShake，CheckpointStorageUrl 指定为同一个实例时，不能同时做 MongoShake  HA，请问一下大佬有什么解决办法吗

**Comment by vinllen** [comment]
这里可以做一下，通过设置不同的表名来实现，表名考虑加入配置文件的id信息，比如id=shake1，id=shake2，对应的表名为election-shake1, election-shake2

**Comment by ghost** [comment]
好的，谢谢

**Comment by vinllen** [comment]
看了下代码，你这个直接修改checkpoint.storage.db参数就行，2个不同的拉取配置不同的参数即可。

**Comment by ghost** [comment]
试过配置不同的 checkpoint.storage.db 参数了，但是还是会保存到 mongoshake 库的 election 集合，我使用的版本是：mongo-shake-v2.4.19

**Comment by ghost** [comment]
> 看了下代码，你这个直接修改checkpoint.storage.db参数就行，2个不同的拉取配置不同的参数即可。

配置不同的 checkpoint.storage.db参数，还是会将 HA 信息保存到 mongoshake 库的 election 集合
