### ISSUE TITLE
最新版本mongoshake配置filter.pass.special.db = admin主从同步到副本集没有同步admin库

### ISSUE THREAD

**Issue by yangjiayu2437** [alibaba/MongoShake#551]
日志记录：
[2021/03/03 16:23:13 CST] [DEBG] Namespace is filtered. local.me
[2021/03/03 16:23:13 CST] [DEBG] Namespace is filtered. local.oplog.$main
[2021/03/03 16:23:13 CST] [DEBG] Namespace is filtered. local.sources
[2021/03/03 16:23:13 CST] [DEBG] Namespace is filtered. local.startup_log
 配置参数：
filter.pass.special.db = admin transform.namespace = admin.system.users:admin.system.users

**Comment by vinllen** [comment]
确认2.4.19源端为副本集没有问题，你再看下自己的环境

**Comment by yangjiayu2437** [comment]
其他版本副本集测试过来也是相同问题的

**Comment by vinllen** [comment]
即使开启了这个选项，系统库不会被同步，比如admin.system.xx，只有用户自己的库表才会同步

**Comment by jinchengsix** [comment]
@vinllen  你好，我在源集群的 ycsb01 库上创建了一个用户，没有同步到目标集群。 
<img width="300" alt="eca33fb6cd3888ee60cd920284fdb56" src="https://github.com/alibaba/MongoShake/assets/39333013/116d76b4-61f3-4e34-bd60-fc464c3c1674">
<img width="292" alt="0befa7393674c6f2fd930dc516ad14f" src="https://github.com/alibaba/MongoShake/assets/39333013/4217aca7-61fe-439f-9279-b14cdbf31b9c">

目前保持正常的增量同步，数据都是正常同步，就是用户信息过不来
![image](https://github.com/alibaba/MongoShake/assets/39333013/d8c23816-f652-4ff9-a35a-8195569d022c)

mongoshake 版本 2.8.4
mongodb 版本 4.0.3
