### ISSUE TITLE
mongoshake向kafka同步数据速率可以优化吗？

### ISSUE THREAD

**Issue by donkeyForward** [alibaba/MongoShake#553]
请问用mongoshake 向kafka 同步数据，设置哪些参数可以提高写入速率啊，目前我的写入速率为2.47M/s 左右，kafka 设置一个topic，一个partition 和一个副本。

**Comment by donkeyForward** [comment]
补充下，mongoshake 是增量同步模式。

**Comment by vinllen** [comment]
这个优化有几个方面：
1. 优化写入到多个partition，hash的方式按照配置文件中指定的`incr_sync.shard_key`决定。考虑向上兼容，需要多开放一个参数，否则默认还是写入1个partition。
2. 目前序列号是单线程的操作，序列化后再发送到kafka，这个可以优化为序列化和发送分离，序列化采用多线程保序，以解决序列化的瓶颈。开放多线程序列化参数，这里默认为1。

**Comment by vinllen** [comment]
2.4.21版本已经发布

**Comment by vinllen** [comment]
问题先关闭，后面如果还有问题可以重新回复或者打开
