### ISSUE TITLE
看日志有replay操作，但是数据为什么不同步呢？

### ISSUE THREAD

**Issue by Simpson877** [alibaba/MongoShake#555]
目前处于增量同步阶段
mongo-shake的日志：
![image](https://user-images.githubusercontent.com/67669408/110574381-f6777200-8197-11eb-8409-f0208208de9e.png)

mongoshake-stat状态
![image](https://user-images.githubusercontent.com/67669408/110574438-1018b980-8198-11eb-9bf5-3393140ace7f.png)
lsn时间始终与当前时间相隔1个小时以上
我自己在源端测试写入一条带时间的数据，即使lsn的时间超过测试数据中的时间，目标端的测试数据仍然不存在。目标端机器压力小，系统5负载在1以下，请问，这是什么问题？

mongo-shake增量同步相关配置文件：
![image](https://user-images.githubusercontent.com/67669408/110574742-b1a00b00-8198-11eb-86d3-41ce25b7f3ef.png)
![image](https://user-images.githubusercontent.com/67669408/110574815-cb415280-8198-11eb-86e5-8da73fd819f5.png)

**Comment by vinllen** [comment]
从日志看应该是正常的，你确定日志文件配的mongodb地址没问题吗？

**Comment by Simpson877** [comment]
> 从日志看应该是正常的，你确定日志文件配的mongodb地址没问题吗？

地址没有问题，我是选择了all模式，如果有问题，全量同步也不会成功的

**Comment by vinllen** [comment]
提供一下mongodb和mongoshake的版本。你确认推进的位点不包括写入的数据？不包括你的延迟。比如现在11点，checkpoint推进到10点，你确定10点前的数据都没有同步？

**Comment by Simpson877** [comment]
源端和目标端的版本都是3.4，mongo-shake是2.4.19.我现在看数据还是没有写入到目标库的，而且目标库并未设置过滤或者白名单的

**Comment by vinllen** [comment]
可以加钉钉群沟通一下，群里可以找到我

**Comment by Simpson877** [comment]
已申请入群

**Comment by vinllen** [comment]
已定位：用户自己查找不当导致
