### ISSUE TITLE
写oplog到kafka中时，oplog中的_id字段对应的值出现乱码，有遇到这种情况的吗

### ISSUE THREAD

**Issue by helloshenzhen** [alibaba/MongoShake#559]
[{"name":"_id","value":"_1\ufffd+)T\ufffd\u0000\u0001\u003c\ufffd\ufffd"},{"name":"name","value":"transceiver"} 类似这种

**Comment by helloshenzhen** [comment]
`[{"name":"_id","value":"_1\ufffd+)T\ufffd\u0000\u0001\u003c\ufffd\ufffd"},{"name":"name","value":"transceiver"}`

**Comment by vinllen** [comment]
使用的哪个版本？另外，是全部都这样了还是部分？

**Comment by helloshenzhen** [comment]
> 使用的哪个版本？另外，是全部都这样了还是部分？

最新的release-v2.4.21-20210309这个，是全部都这样，只要是 _id字段对应的值都这样，其他字段是正常的，中文也是正常的
[{"name":"_id","value":"`Q\ufffd\ufffdD0)\u0000\u0001\ufffd\ufffd\ufffd"}]
[{"name":"_id","value":"`Q\ufffd\ufffdD0)\u0000\u0001\ufffd\ufffd\ufffd"}]
"o":[{"name":"_id","value":"_Юe\ufffd\ufffd\ufffdo\ufffd\ufffd0k"}]
会出现这些情况，都是_id字段，这个值是一个 "_id" : ObjectId("5fd0ae858df45a000123c339")  在源数据库中是ObjectId类型

**Comment by vinllen** [comment]
这个应该是ObjectId对应的字节流模式，你是想要字符串吗？

**Comment by helloshenzhen** [comment]
> 这个应该是ObjectId对应的字节流模式，你是想要字符串吗？
是的，我就想要字符串，不能准确获取ObjectId("5fd0ae858df45a000123c339") 我没办法准确定位是在操作数据库的哪条记录

**Comment by helloshenzhen** [comment]
> 这个应该是ObjectId对应的字节流模式，你是想要字符串吗？

**Comment by vinllen** [comment]
这个需求我考虑一下

**Comment by helloshenzhen** [comment]
> 这个需求我考虑一下
你好，我给你发了一份邮件，关于这个问题的，你有空回一下我，谢谢！或者指导下我们怎么修改也可以

**Comment by vinllen** [comment]
你如果用Java的话，可以用json转bson解析试一下，格式是统一的[Canonical Extended JSON Format](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#conversion-table)，本身格式是文档内嵌一个大端的string：
```
{"$oid": <ObjectId bytes as 24-character, big-endian hex string>}
```
可以参考一下 #542

**Comment by helloshenzhen** [comment]
> 你如果用Java的话，可以用json转bson解析试一下，格式是统一的[Canonical Extended JSON Format](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#conversion-table)，本身格式是文档内嵌一个大端的string：
> 
> ```
> {"$oid": <ObjectId bytes as 24-character, big-endian hex string>}
> ```
> 
> 可以参考一下 #542
试了下各种方式，都不行，我可以在本地运行起来mongoshake吗，我想自己修改源代码

**Comment by vinllen** [comment]
今天我会发个版本，增加一个版本字段，默认还是老版本，开启配置选项后可以启用Canonical Extended JSON Format

**Comment by helloshenzhen** [comment]
> 今天我会发个版本，增加一个版本字段，默认还是老版本，开启配置选项后可以启用Canonical Extended JSON Format

非常感谢您抽空指导这个问题，谢谢！

**Comment by vinllen** [comment]
v2.4.22版本发布了，你试一下

**Comment by helloshenzhen** [comment]
> v2.4.22版本发布了，你试一下

好的，谢谢！

**Comment by vinllen** [comment]
@helloshenzhen 使用怎么样？恢复了吧？

**Comment by helloshenzhen** [comment]
> @helloshenzhen 使用怎么样？恢复了吧？

我们试了v2.4.22版本，增加了这个tunnel.json.format = canonical_extended_json配置，但是还是一样的问题；不过我们改成tunnel.message = bson格式接收，然后在kafka消费端配置       
value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer 然后用 BSONDecoder 读取kafka中的内容可以获取到正常的ObjectId对象及其他数据，如果mongoshake中配置的是 tunnel.json.format = canonical_extended_json格式则还是不行，不过我们的问题已经解决了，谢谢哈！

**Comment by vinllen** [comment]
你不用指定`tunnel.json.format =`，留空就行。

**Comment by helloshenzhen** [comment]
> 你不用指定`tunnel.json.format =`，留空就行。

可以了，可以获取正常的 _id 对应的值了，太棒了，谢谢哈！

**Comment by lzy6664** [comment]
2.4.21 
 tunnel.message = json 
读取ObjectId 乱码   ，不升级版本的情况可以解决么

**Comment by lzy6664** [comment]
> 2.4.21
> tunnel.message = json
> 读取ObjectId 乱码 ，不升级版本的情况可以解决么

我已经升级到 2.6.3版本了。  已经不乱码了
