### ISSUE TITLE
incr_sync.conflict_write_to的使用

### ISSUE THREAD

**Issue by hope1234567hope** [alibaba/MongoShake#564]
第一次用
测试环境：是副本集到单机
设置了
incr_sync.executor.insert_on_dup_update = false
incr_sync.executor.upsert = false
incr_sync.conflict_write_to = db
但是副本集插入db.hello.insert({"_id":4,"item":"e4","qty":44})，副本集之前此单机环境已经有了此数据，看文档说：mongoshake碰到同步出错的情况，会停止，但是我的mongoshake，不会停止，后续的数据还是会同步，这种情况不算出错么？

有这种情况，我还是希望能停止，请问改怎么做？
关于master_quorum怎么设置，我在两台台机器上安装2个MongoShake，还有其它参数怎么设置才能成主备?

**Comment by vinllen** [comment]
1. 你是哪个版本的shake，这个正常情况如果不设置upsert以及insert_on_dup_update，是会报错的。log是否有报错信息
2. 这个2个MongoShake配置相同的checkpoint地址即可，master_quorum设置为true
