### ISSUE TITLE
目的端是kafka的时候，为什么会从Topic一次性读取到多行重复数据呢

### ISSUE THREAD

**Issue by pandework** [alibaba/MongoShake#568]
tunnel = kafka
tunnel.address = mongoshake@hadoop01:9092,hadoop02:9092,hadoop03:9092
实际上只操作了一次update，但从topic内却获取到连续三行更新操作，ts相同，更改的数据也完全相同

**Comment by pandework** [comment]
> tunnel = kafka
> tunnel.address = mongoshake@hadoop01:9092,hadoop02:9092,hadoop03:9092

如上配置后，发现每次从kafka读取到的log日志都是三行

**Comment by vinllen** [comment]
你这个update是更新的多条文档吧？或者是一个事务，你可以发出来看一下

**Comment by pandework** [comment]
发现后台启动了多个进程导致的
