### ISSUE TITLE
incr_sync.worker.oplog_compressor option移除原因

### ISSUE THREAD

**Issue by calvin1717** [alibaba/MongoShake#572]
为什么在最新版的shake，将压缩方法的用户选项给移除了呢？考虑的原因是什么呢？

**Comment by vinllen** [comment]
目前是配置项里面移除了，实际还是可以使用的，可以直接配置。
主要考虑到对接的成本，接收端拿到以后需要自己解压缩，然后解析格式。你是什么使用场景，需要这个压缩选项？
