### ISSUE TITLE
全量同步后，显示-full sync done! 但是两个数据库的大小不一致

### ISSUE THREAD

**Issue by alianrock** [alibaba/MongoShake#573]
感谢你们维护这个库，很好用！
最近用mongoshake做迁移，使用mode=all模式同步后显示全量同步完成，但是两个数据库大小却不一样，一个0.079GB， 一个0.066GB， 检查了下各个collections的数量确是一致的，查了几个数据似乎数据也没丢失，请问这个是什么原因呢？非常感谢！

**Comment by vinllen** [comment]
你要看的是逻辑大小，逻辑大小一致即可。物理大小受压缩算法，物理磁盘碎片等多个因素影响

**Comment by alianrock** [comment]
> 你要看的是逻辑大小，逻辑大小一致即可。物理大小受压缩算法，物理磁盘碎片等多个因素影响
了解了，感谢！

**Comment by alianrock** [comment]
@vinllen 了解了，感谢
