### ISSUE TITLE
[2.4.22]transform.namespace情况下full同步，DDL在namespace层面报错

### ISSUE THREAD

**Issue by Steloj-shaw** [alibaba/MongoShake#574]
使用版本：发行版v2.4.22

collection级同步
源端： online.trans.sp 
目标端： hd2_online.trans.sp   

配置文件如下：
sync_mode = full
transform.namespace = online:hd2_online
filter.namespace.white = ^online.trans$;^online.trans.sp$

数据同步正常，并且正确转换到新的namespace、但是DDL同步报错，报错如下：
[2021/04/01 11:05:27 CST] [WARN] Create indexes for ns {online trans.sp} of dest mongodb failed. (BadValue) The value of the field 'ns' (online.trans.sp) doesn't match the namespace 'hd2_online.trans.sp'

但是在目标端，表已经正确存在并含有数据
data:PRIMARY> show dbs
admin       0.000GB
hd2_online  1.303GB
local       2.255GB
data:PRIMARY> show tables
trans
trans.sp
data:PRIMARY> db.trans.sp.getIndexes()
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "hd2_online.trans.sp"
        }
]

请问是什么原因导致的？ 目前我们暂时是关闭ddl同步使用状态。 谢谢。

**Comment by Steloj-shaw** [comment]
full_sync.create_index = foreground

**Comment by vinllen** [comment]
看起来是协议转换的问题，MongoDB版本是什么？

**Comment by Steloj-shaw** [comment]
hi,vinllen：
源端： mongo 3.4.23 社区版
目标端 mongo 3.4.24 社区版

**Comment by Steloj-shaw** [comment]
hi：
filter.ddl_enable = true  
这个参数在transform.namespace后，索引可以正常入库，目前只有full阶段的create_index有问题。

**Comment by vinllen** [comment]
full阶段这个索引转换的确存在问题
