### ISSUE TITLE
全量同步无法同步ttl索引，expireAfterSeconds丢失。

### ISSUE THREAD

**Issue by Jack-Jiang** [alibaba/MongoShake#575]
使用版本：2.4.6
配置：
sync_mode = all
incr_sync.mongo_fetch_method = oplog

执行全量同步，目标库被清空，全量同步完成后，发现ttl索引丢失：
源库索引有expireAfterSeconds标识，目标库此ttl标识丢失。
请问是当前mongoshake有配置我未配置正确，还是当前工具丢失了ttl索引的同步。

**Comment by vinllen** [comment]
这个问题的确是存在的，目前没有识别ttl的信息，这个问题需要改进一下。

**Comment by zhangst** [comment]
已解决，待2.7.1版本发布
