### ISSUE TITLE
filter.namespace.white 長度過長導致無效

### ISSUE THREAD

**Issue by IceCastill** [alibaba/MongoShake#582]
版本：**2.6.2**
描述：

`filter.namespace.white` 設定超過一定長度，mongoshake 啟動後 api conf 回應 FilterNamespaceWhite 是 null，造成全量同步階段同步了所有表，增量同步階段同步了不在 `filter.namespace.white` 上列出的表。

![image](https://user-images.githubusercontent.com/29156434/114483916-d1b16700-9c3b-11eb-9ac1-18396765eb5f.png)

如上圖，`filter.namespace.white` 設定由 `demo.Table1` 至 `demo.Table300` 共 300 個表，但是啟動後 conf api 回應顯示 `FilterNamespaceWhite` 值是 null。

![image](https://user-images.githubusercontent.com/29156434/114484073-20f79780-9c3c-11eb-9554-42ea6d06a3c3.png)

上面是來源 mongodb；下面是目標 mongodb，執行的步驟如下。

1. 確認來源及目標 demo 資料庫為空
2. 在來源 `demo.Test1` 新增一筆紀錄並確認內容被同步到目標（設定檔案上是設定同步 `demo#Table1` 至 `demo#Table300`）
3. 在來源 `demo.Test2` 新增一筆紀錄並確認內容被同步到目標
4. 切換到 demo2 資料庫
5. 在來源 `demo2.Test1` 新增一筆紀錄並確認內容被同步到目標（設定檔案上沒有同步 `demo2` 相關資料庫的設定）

**Comment by vinllen** [comment]
问题的根因是目前配置文件解析是有整行4096的长度限制

**Comment by IceCastill** [comment]
測試了 `2.6.4` 版本正常了。
