### ISSUE TITLE
全量同步+增量同步完成后 目的库比源库 小了很多

### ISSUE THREAD

**Issue by yinghongliang** [alibaba/MongoShake#587]
源库数据有340多G 到目的库以后只有240G.
如题 请问一下这个可能是什么导致的？以下是我正使用的配置文件，求大佬帮忙看看。

conf.version = 9
id = mongoshake
master_quorum = false
full_sync.http_port = 9101
incr_sync.http_port = 9100
system_profile_port = 9200
log.level = info
log.dir =
log.file = collector.log
log.flush = false
sync_mode = all
mongo_urls = mongodb://xxxxxxxxx
mongo_cs_url =
mongo_s_url = 
tunnel = direct
tunnel.address = mongodb://xxxxxxxx
tunnel.message = raw
tunnel.kafka.partition_number = 1
mongo_connect_mode = secondaryPreferred
filter.namespace.black =
filter.namespace.white =
filter.pass.special.db =
filter.ddl_enable = false
filter.oplog.gids = false
checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.start_position = 1970-01-01T00:00:00Z
transform.namespace =
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.read_document_count = 0
full_sync.collection_exist_drop = true
full_sync.create_index = none
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false
incr_sync.mongo_fetch_method = oplog
incr_sync.change_stream.watch_full_document = false
incr_sync.oplog.gids =
incr_sync.shard_key = collection
incr_sync.shard_by_object_id_whitelist = 
incr_sync.worker = 8
incr_sync.tunnel.write_thread = 32
incr_sync.target_delay = 0
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256
incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false
special.source.db.flag =

**Comment by vinllen** [comment]
看逻辑大小，物理大小受磁盘碎片压缩率多个因素影响

**Comment by yinghongliang** [comment]
> 看逻辑大小，物理大小受磁盘碎片压缩率多个因素影响

你好请问逻辑大小怎么看呢？我这个大小是 进入到mongo里面show dbs 出来的。

**Comment by vinllen** [comment]
count一下表大小对比一下
