### ISSUE TITLE
applyOps with "d" op is not applied

### ISSUE THREAD

**Issue by Juhi22** [alibaba/MongoShake#588]
Hi, have encountered an issue when syncronizing. The deleted Document is not removed in target database, but it is logged by mongoshake when the **fetch method is set to oplog:**
`oplog is filtered. {"ts":6955802069626257499,"v":2,"op":"c","ns":"admin.$cmd","o":[{"Name":"applyOps","Value":[[{"Name":"op","Value":"d"},...`
Tried the **fetching method change stream** as well, the result:
`panic: interface conversion: interface {} is []bson.M, not []bson.D`
Tried versions: **2.4.19** and **2.6.4**

**Comment by zhangst** [comment]
Have you set filter.ddl_enable to true
