### ISSUE TITLE
增量同步出现开启配置后出现doUpdate runs upsert but lack documentKey问题

### ISSUE THREAD

**Issue by Lazy-Yang** [alibaba/MongoShake#592]
# oplog changes to Insert while Update found non-exist (_id or unique-index)
# 如果_id不存在在目的库，是否将update语句修改为insert语句。
incr_sync.executor.upsert = true
# oplog changes to Update while Insert found duplicated key (_id or unique-index)
# 如果_id存在在目的库，是否将insert语句修改为update语句。
incr_sync.executor.insert_on_dup_update = true

[2021/05/08 01:17:57 CST] [WARN] doUpdate runs upsert but lack documentKey: {"ts":*,"h":*,"v":*,"op":"*","ns":"*","o":[{"Name":"$set","Value":[{"Name":"*","Value":*},{"Name":"updateDate","Value":"2021-05-07T17:17:53.463Z"}]}],"o2":{"_id":"*"}}

**Comment by Lazy-Yang** [comment]
我目前使用的是2.6.4版本

**Comment by Lazy-Yang** [comment]
且同步过程中会出现目标源比原有源数据多的情况

**Comment by vinllen** [comment]
还有别的EROR或者CRIT的日志吗？

**Comment by Lazy-Yang** [comment]
upsert _id[ObjectIdHex("607928417c2f0b7b9ee5f320")] with data[[{_id ObjectIdHex("")} {answerData <elements><element id=""><answers><![CDATA[Dear Henry, I'm Li Hua, the leader of the papercutting club in our school. Last time you told me you looked forward to learning more about traditional Chinese culture. Now I'm glad to tell you there will be a Chinese paper-cutting exhibition held by our school. I sincerely hope you can set aside some time for the art feast. The exhibition, the theme of which is "beauty of China", will take place in the school hall from 2 to 5 on the afternoon of June 21. Not only will our club's works be displayed, but we also have a valuable set of paper-cutting created by a famous artist of this field. Besides, there will be a lot of useful and interesting activities, from which you can have a clearer picture of Chinese culture. I would appreciate it if you accept my invitation. I'm sure it can leave a wonderful impression on you! I'm looking forward to your reply. Best wishes! Yours, Li Hua]]></answers><pictures><pic><url>.....</url><size>undefined</size></pic></pictures></element><element id=""><answers><![CDATA[Dear Henry, I'm Li Hua, the leader of the papercutting club in our school. Last time you told me you looked forward to learning more about traditional Chinese culture. Now I'm glad to tell you there will be a Chinese paper-cutting exhibition held by our school. I sincerely hope you can set aside some time for the art feast. The exhibition, the theme of which is "beauty of China", will take place in the school hall from 2 to 5 on the afternoon of June 21. Not only will our club's works be displayed, but we also have a valuable set of paper-cutting created by a famous artist of this field. Besides, there will be a lot of useful and interesting activities, from which you can have a clearer picture of Chinese culture. I would appreciate it if you accept my invitation. I'm sure it can leave a wonderful impression on you! I'm looking forward to your reply. Best wishes! Yours, Li Hua]]></answers><pictures><pic><url>......</url><size>undefined</size></pic></pictures></element><element id=""><answers><![CDATA[ccccc]]></answers></element></elements>} {qstTimes <nil>} {markDataS } {testScoreO 0} {markDataO } {answerScore 0} {playData <nil>} {updateTime 2021-04-16 06:01:37.978 +0000 UTC} {percent 0} {spid 1} {duration 23} {insertTime 2021-04-16 06:01:37.978 +0000 UTC} {testGrade 0} {uid 3562479} {testStatus 2} {testScoreS 0} {testId } {beginTime 2021-01-19 03:34:18 +0000 UTC} {....}//略

**Comment by Lazy-Yang** [comment]
[2021/04/16 14:38:56 CST] [EROR] upsert _id[ObjectIdHex("")] with data[[{_id ObjectIdHex("607928427c2f0b7b9ee5f327")} {answerData <elements><element id="1d1ec54ac5813049b11022786072566c"><answers><![CDATA[qwertyuiloi]]></answers></element></elements>} {qstTimes <nil>} {markDataS <element id=""><><result>2</result><score>0.0</score><score_ai>0.0</score_ai><comment_ai/></mark_data></element>} {testScoreO 0} {markDataO } {answerScore 0} {playData <nil>} {updateTime 2021-04-16 06:01:38.73 +0000 UTC} {percent 0} {spid 1} {duration 5} {.....}//略]] failed[E11000 duplicate key error collection: {.....}//略 ]
./collector.log.31:[2021/04/16 14:38:57 CST] [EROR] detail error info with index[0] msg[E11000 duplicate key error collection: {.....}//略 ] dup[true]

**Comment by Lazy-Yang** [comment]
有这种报错信息

**Comment by Lazy-Yang** [comment]
请问是代码方面的问题，还是我这边配置问题？
