### ISSUE TITLE
[容灾切换场景]源端故障，切换到目的端后，待源端恢复，如何同步目的端的增量数据

### ISSUE THREAD

**Issue by andyyuano** [alibaba/MongoShake#593]
主站点故障，切到备站点，待主站点修复，怎么把备站点的变化数据同步回主站点，是只能修改源和目的端通过全量+增量方式重新建立同步关系，还是可以做到增量同步回主站点？

**Comment by vinllen** [comment]
可以从备到主进行增量同步，指定需要开始同步的时间点就行

**Comment by andyyuano** [comment]
好的
