### ISSUE TITLE
mongoshake 如何连接带认证的 kafka？

### ISSUE THREAD

**Issue by shuosiw** [alibaba/MongoShake#595]
查看了[帮助文档](https://github.com/alibaba/MongoShake/wiki/%E5%B8%B8%E8%A7%81%E5%9C%BA%E6%99%AF%E9%85%8D%E7%BD%AE#5-%E4%BB%8Emongodb%E5%89%AF%E6%9C%AC%E9%9B%86%E5%90%8C%E6%AD%A5%E5%88%B0kafka%E9%80%9A%E9%81%93)，发现给的案例都是连接不带认证鉴权的 kafka：

```
sync_mode = incr # 如果目的端不是mongodb，仅支持增量同步模式
incr_sync.tunnel = kafka
incr_sync.tunnel.address = test@50.1.1.1:6379
```

请问一下，如果是带用户密码认证的 kafka，这个 tunnel.address 应该怎么写呢？

**Comment by shuosiw** [comment]
ps: 有看到另外一个 issue 是说还不支持 SSL kafka #236 ，不知道现在支不支持 username:password 认证的 kafka

**Comment by zemul** [comment]
可以看下我的仓库，兼容了kafka ssl

> ps: 有看到另外一个 issue 是说还不支持 SSL kafka #236 ，不知道现在支不支持 username:password 认证的 kafka

**Comment by shuosiw** [comment]
> 可以看下我的仓库，兼容了kafka ssl

核心还是想要用户名密码认证的功能..

**Comment by zhangst** [comment]
> 可以看下我的仓库，兼容了kafka ssl
> 
> > ps: 有看到另外一个 issue 是说还不支持 SSL kafka #236 ，不知道现在支不支持 username:password 认证的 kafka

欢迎提patch
