### ISSUE TITLE
全量+增量同步完成后，目标库中的其中一个表数据量多了几十万

### ISSUE THREAD

**Issue by wilean** [alibaba/MongoShake#599]
环境及版本：

MongoDB server version: 4.0.11
mongo-shake-v2.4.21
源端和目的端都是shard cluster

操作说明：
目标库中清除了脏数据
mongos> use dm
switched to db dm
mongos> db.dropDatabase()

然后源端也清除了同步点
mongos> use mongoshake
mongos> db.ckpt_default.drop()

说明：以上的同步操作已经尝试过几次，数据均正常。

现象：
全量同步+增量同步完成几个小时后发现目标库其他几个表的数据量一致，但是其中一个表的数据多了96万，请问一下，这种情况，应该怎么排查呢？

**Comment by zhangst** [comment]
是ChangeStream方式同步吗？建议用这个方式对比下
