### ISSUE TITLE
checkpoint设置了但无效（已删除mongodb中mongoshake库）

### ISSUE THREAD

**Issue by ChenShuofeng** [alibaba/MongoShake#601]
我想让mongoshake从我设置的checkpoint开始。我先将mongodb中的mongoshake库删除了，然后修改mongoshake的配置文件为：
![image](https://user-images.githubusercontent.com/52701746/119344214-fd5b4e80-bcc9-11eb-94c7-c3147ee9a508.png)
接着从其mongoshake，但是没有生效，我修改集合数据mongoshake也没有反应，始终输出如下日志：
![image](https://user-images.githubusercontent.com/52701746/119344394-33003780-bcca-11eb-82e2-25f7c65f9d58.png)

**Comment by ChenShuofeng** [comment]
mongoshake版本为2.4.19

**Comment by ChenShuofeng** [comment]
然后我等了一晚，第二天早上再看，mongodb中就出现了新的mongoshake库，以及其中的checkpoint。
![image](https://user-images.githubusercontent.com/52701746/119426173-52837880-bd3b-11eb-88d6-417b6fb7b689.png)

**Comment by ChenShuofeng** [comment]
所以我删除原来的checkpoint，修改start_position，再重启mongoshake。没有实现预期中的立即从我设置的时间处理。
请问这是咋回事？

**Comment by zhangst** [comment]
请参考：https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E#17-checkpoint%E7%9B%B8%E5%85%B3%E9%87%8D%E8%A6%81
