### ISSUE TITLE
黑白名单能否支持下正则？

### ISSUE THREAD

**Issue by ChenShuofeng** [alibaba/MongoShake#603]
黑白名单能否支持下正则？因为有的业务表是需要经常增加的，且有特定格式的。

**Comment by zhangst** [comment]
欢迎给shake提patch :)

**Comment by tian-zhihui** [comment]
@zhangst 
我这边简单实现了一下黑白名单的正则。顺便用go fmt把代码也格式化了一下。
能否麻烦您过目一下，看看我还需要做哪些东西才能提PR。
核心代码如下：
https://github.com/alibaba/MongoShake/compare/develop...tian-zhihui:MongoShake:develop#diff-554c4ef10f5db52726b6b2ae8a15fa8d8031c833eb9ec6c63f64b088ef59b864R135

**Comment by zhangst** [comment]
> @zhangst 我这边简单实现了一下黑白名单的正则。顺便用go fmt把代码也格式化了一下。 能否麻烦您过目一下，看看我还需要做哪些东西才能提PR。 核心代码如下： [develop...tian-zhihui:MongoShake:develop#diff-554c4ef10f5db52726b6b2ae8a15fa8d8031c833eb9ec6c63f64b088ef59b864R135](https://github.com/alibaba/MongoShake/compare/develop...tian-zhihui:MongoShake:develop#diff-554c4ef10f5db52726b6b2ae8a15fa8d8031c833eb9ec6c63f64b088ef59b864R135)

直接提PR就可以，有问题可以在PR中沟通。谢谢
