### ISSUE TITLE
incr模式读取ChangeStream为什么CheckPoint会有三个checkpoint

### ISSUE THREAD

**Issue by wolgy** [alibaba/MongoShake#611]
ChangeStream是从mongos读出来的。
难道不是应该只有一个checkpoint吗。因为mongos对oplog做了聚合。
我的理解有误吗？期待得到回应。万分感谢🙏

**Comment by zhangst** [comment]
分片集群是有三个分片吗？

**Comment by wolgy** [comment]
> 分片集群是有三个分片吗？

是的。三个分片。并且做了replica。
