### ISSUE TITLE
连接出错时日志会暴露连接密码

### ISSUE THREAD

**Issue by LuoHaibin** [alibaba/MongoShake#612]
https://github.com/alibaba/MongoShake/blob/749331152a0601458b388d3fbac246bc32832642/cmd/collector/sanitize.go#L265

**Comment by LuoHaibin** [comment]
https://github.com/alibaba/MongoShake/blob/749331152a0601458b388d3fbac246bc32832642/cmd/collector/sanitize.go#L287

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/commit/49a7afb4b27b594ae0ae8962e66ef74b95b5ddf5
