### ISSUE TITLE
[FEATURE REQUEST] Support Kafka message compression

### ISSUE THREAD

**Issue by pan3793** [alibaba/MongoShake#613]
Currently, MongoShake sends the raw bytes to Kafka w/o any compression, which may be a quite expensive behavior. 

https://github.com/alibaba/MongoShake/blob/749331152a0601458b388d3fbac246bc32832642/tunnel/kafka/sync_writer.go#L58

Use gzip/lz4/zstd/snappy algorithm to compress the bytes could significantly reduce bandwidth usage.

**Comment by itsgodzilla** [comment]
以前有过，现在他们废弃了。
---
`[incr_sync.worker.oplog_compressor。2.4.21废弃。仅用于非direct通道跨网络传输的情况，用户可以配置gzip, zlib或者deflate三种压缩方式，发送前数据将会进行压缩，以减少网络带宽的使用。默认none。](https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E#:~:text=incr_sync.worker.oplog_compressor)`

**Comment by pan3793** [comment]
Thanks for your answers, but I don't think there are the same thing.

According to https://github.com/alibaba/MongoShake/issues/572#issuecomment-809830685, the compression of `incr_sync.worker.oplog_compressor` is not transparent to consumers, but Kafka compression should be transparent, the Kafka consumer client can auto-detect the compression algorithm of record and do decompression, i.e. in Kafka Java Client, the user always gets the same `ConsumerRecord<K, V>` object whether the record is compressed or not.

**Comment by zhangst** [comment]
Code contributions are welcome.
