### ISSUE TITLE
BSON field 'saslContinue.mechanism' is an unknown field.

### ISSUE THREAD

**Issue by kedizhou** [alibaba/MongoShake#618]
我的场景是从一个stand alone的mongodb同步数据到另一个集群副本集，现在源和目的的版本是5..0.0，源端的认证是：
> db.system.version.find()
{ "_id" : "featureCompatibilityVersion", "version" : "5.0" }
{ "_id" : "authSchema", "currentVersion" : 5 }

源数据库配置：mongo_urls = mongodb://MyAdmin:My**************d@10.10.10.9:20000 

现在运行./collector.linux -conf=collector.conf -verbose 1 报错如下：
[17:06:20 CST 2021/08/10] [CRIT] (github.com/alibaba/MongoShake/v2/common.NewMongoConn:49) Connect to mongodb://MyAdmin:***@10.10.10.9:20000 failed.
server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field.

谢谢！

**Comment by kedizhou** [comment]
在我的场景中，在loginSASL方法，删除第四步登录认证中去掉Mechanism头就可以了。

**Comment by MagicCode-byte** [comment]
@kedizhou 请教一下，如何解决这问题
