### ISSUE TITLE
出现“move chunk oplog found”错误，mongoshake启动不了

### ISSUE THREAD

**Issue by xxrt** [alibaba/MongoShake#619]
[11:38:28 CST 2021/08/14] [CRIT] (mongoshake/collector.(*Batcher).filter:127) move chunk oplog found

请教，出了这个错误后，mongoshake启动不了，请教解决思路

**Comment by zhangst** [comment]
这个是rebalancer在运行，详见：https://github.com/alibaba/MongoShake/wiki/%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8%EF%BC%8C%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE%EF%BC%9F#31-%E5%A6%82%E6%9E%9C%E6%98%AF%E5%88%86%E7%89%87sharding%E8%AF%A5%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE

建议使用ChangeStream迁移
