### ISSUE TITLE
Kafka服务停止以后MongoShake写入异常数据

### ISSUE THREAD

**Issue by zcyoop** [alibaba/MongoShake#622]
问题现象：今天早上Kafka因为阿里云物理机故障切换到另一个节点导致Kafka服务停止，MongoShake服务也开始报错。然后重启了Kafka服务，Kafka服务恢复正常。从这个时候开始MongoShake开始不断往Kafka里面写重复的数据，写的数据的**数据时间**一直都是MongoShake停止之间的几分钟的数据，一直写了几个小时直到Kafka磁盘告警才发现该问题。然后发现MongoShake从早上停止后到现在一直在报错。下面是几张数据和MongoShake截图

_MongoShake停止时间截图_
![lALPDhYBQ7AHr-XNATTNAjI_562_308](https://user-images.githubusercontent.com/39327876/130194815-ed8cddb3-7264-4b88-9d9b-fdf08f68d889.png)
_Kafka内重复数据截图（数据时间为7点多，Kafka消费时间起点为11点）_
![image](https://user-images.githubusercontent.com/39327876/130194984-9e41cb62-54df-4ebd-8616-f96f14bfa3bd.png)

**Comment by sannyqin** [comment]
你好，请问这个问题怎么解决的
