### ISSUE TITLE
为什么不直接使用原生的oplog中的o字段,反而转换成了Name,Value这种格式

### ISSUE THREAD

**Issue by yusenyi123** [alibaba/MongoShake#625]
Name和Value这种格式还需要单独写程序再翻译一遍，为什么要搞的复杂，可以直接采集原生oplog吗不进行修改

**Comment by vinllen** [comment]
这个主要是考虑到DDL的兼容性，对于op=c的命令，是需要对o字段保序的，所以做法是翻译成bson.D，而不是bson.M
