### ISSUE TITLE
云主机流量带宽10M，同步经常出现丢包的现象 ，导致全量同步失败，请问这如何解决

### ISSUE THREAD

**Issue by sunqintao** [alibaba/MongoShake#627]
`IP:27017: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.], index[0] dup[false]
`
云主机流量带宽10M，同步经常出现丢包的现象 ，导致全量同步失败，请问这如何解决

**Comment by sunqintao** [comment]
insert docs with length[5] into ns[{RMS_MogoFileDb uploadfile.chunks}] of dest mongo failed[index[0], msg[read tcp 192.168.1.11:57597->192.168.1.13:27017: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.], dup[false]]

**Comment by zhangst** [comment]
可以尝试降低同步worker线程的数量，或者开启限速开关，来间接减低带宽。

限速资料：https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E4%BD%95%E7%9B%91%E6%8E%A7%E5%92%8C%E7%AE%A1%E7%90%86MongoShake%E7%9A%84%E8%BF%90%E8%A1%8C%E7%8A%B6%E6%80%81%EF%BC%9F
