### ISSUE TITLE
[v2.6.4]对于连接到ssl加密的mongodb数据库，all&&full模式报错，但是incr同步正常。

### ISSUE THREAD

**Issue by Steloj-shaw** [alibaba/MongoShake#628]
源端：mongodb v3.2.22 社区版
同步软件： mongoshake v2.6.4
目标端： mongodb v3.4.23 社区版

源端mongodb加密配置：
  ssl:
    mode: requireSSL
    PEMKeyFile: /mongodb/data_32/tls/server.pem
    CAFile: /mongodb/data_32/tls/cafile.pem
    allowConnectionsWithoutCertificates : true

mongoshake相关ssl配置
# enable source ssl 
mongo_ssl_root_ca_file = /mongoshake/tls/cafile.pem

目标端mongodb无加密

=========================================================================
mongoshake以all，或者fall模式启动，启动命令：/mongoshake/mongoshake/264/collector.linux -conf=/mongoshake/conf/mongoshake.conf
运行一分钟左右后终端页面报错，并指令终止：
start document replication failed: ping to mongodb://mongoshake_reader:***@mongodbtest01:23636/admin failed: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodbtest01:23636, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : connection(mongodbtest01:23636[-64]) incomplete read of message header: EOF }, ] }
[21:07:38 CST 2021/09/16] [CRIT] (main.startup:140) run replication failed: start document replication failed: ping to mongodb://mongoshake_reader:***@mongodbtest01:23636/admin failed: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodbtest01:23636, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : connection(mongodbtest01:23636[-64]) incomplete read of message header: EOF }, ] }

连接期间源端加密数据库日志报错：
Thu Sep 16 21:16:33.932 I NETWORK  [initandlisten] connection accepted from 192.168.1.41:50412 #2865 (3 connections now open)
Thu Sep 16 21:16:33.932 I NETWORK  [conn2865] AssertionException handling request, closing client connection: 17189 The server is configured to only allow SSL connections
Thu Sep 16 21:16:34.432 I NETWORK  [initandlisten] connection accepted from 192.168.1.41:50414 #2866 (3 connections now open)
Thu Sep 16 21:16:34.433 I NETWORK  [conn2866] AssertionException handling request, closing client connection: 17189 The server is configured to only allow SSL connections

=========================================================================
mongoshake以incr模式启动
数据同步、DDL同步一切正常。

**Comment by zhangst** [comment]
这个应该是全量同步建立分析集合名称的时候，没有支持SSL。
我在下一个版本中补上这点。

**Comment by zhangst** [comment]
It's not work now. There is a problem in the version, we will fix it in the next version

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/commit/e2b7a0853f7cb14ec07806883502048ce642aa93

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/commit/e2b7a0853f7cb14ec07806883502048ce642aa93
