### ISSUE TITLE
[v2.6.5]副本集ssl加密的mongodb数据库，报ping to mongodb://xxx:***@xx failed: server selection error: server selection timeout

### ISSUE THREAD

**Issue by zhangxianaa** [alibaba/MongoShake#668]
报错如下
[CRIT] run replication failed: start document replication failed: ping to mongodb://root:***@192.169.2.87:50012,192.169.2.87:50013,192.169.2.87:50014 failed: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: 192.169.2.87:50012, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : connection(192.169.2.87:50012[-189]) incomplete read of message header: EOF }, { Addr: 192.169.2.87:50013, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : connection(192.169.2.87:50013[-190]) incomplete read of message header: EOF }, { Addr: 192.169.2.87:50014, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : connection(192.169.2.87:50014[-188]) incomplete read of message header: EOF }, ] }
使用mongo shell连接是可以访问的，如下：
mongo --host 192.169.2.87 --port 50013 --tls --tlsCAFile /mongo/ssl/ca.pem -u user -p passwd --sslAllowInvalidHostnames
mongod.conf如下
net:
  port: 50012
  bindIp: 192.169.2.87
  tls:
   mode: requireTLS
   certificateKeyFile:  /mongo/ssl/server.pem
   CAFile: /mongo/ssl/ca.pem
   allowInvalidHostnames: true
   allowConnectionsWithoutCertificates: true

security:
  authorization: enabled
  clusterAuthMode: x509

**Comment by zhangst** [comment]
下个版本中解决，请稍等

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/commit/e2b7a0853f7cb14ec07806883502048ce642aa93
