### ISSUE TITLE
全量同步，同步索引无法保证顺序

### ISSUE THREAD

**Issue by momopluto** [alibaba/MongoShake#670]
看代码，处理索引时用的是 bson.M{} 处理 key 数组（顺序matter）

> // M is an unordered representation of a BSON document. This type should be used when the order of the elements does not
// matter. This type is handled as a regular map[string]interface{} when encoding and decoding. Elements will be
// serialized in an undefined, random order. If the order of the elements matters, a D should be used instead.
//
// Example usage:
//
// 		bson.M{"foo": "bar", "hello": "world", "pi": 3.14159}
type M = primitive.M

---

改了下 doc_syncer_test.go 里面的案例，test 能 pass，但是最终结果不能保证正确

TestStartIndexSync 案例

> // 新增的案例
 		{
			"unique": true,
			"key": bson2.M{
				"id_type": int32(1),
				"did":     int32(1),
				"uid":     int32(1),
				"msg_id":  int32(1),
			},
			"name":       "id_type_1_did_1_uid_1_msg_id_1",
			"ns":         "test_db.test_coll",
			"background": true,
		}

`
func TestStartIndexSync(t *testing.T) {
	// test StartIndexSync

	var nr int

	utils.InitialLogger("", "", "info", true, 1)

	// test drop
	{
		fmt.Printf("TestStartIndexSync case %d.\n", nr)
		nr++

		conf.Options.FullSyncReaderCollectionParallel = 4

		conn, err := utils.NewMongoCommunityConn(testMongoAddress, utils.VarMongoConnectModeSecondaryPreferred, true,
			utils.ReadWriteConcernLocal, utils.ReadWriteConcernDefault)
		assert.Equal(t, nil, err, "should be equal")

		// drop old db
		err = conn.Client.Database("test_db").Drop(nil)
		assert.Equal(t, nil, err, "should be equal")

		indexInput := []bson2.M{
			{
				"key": bson2.M{
					"_id": int32(1),
				},
				"name": "_id_",
				"ns":   "test_db.test_coll",
			},
			{
				"key": bson2.M{
					"hello": "hashed",
				},
				"name": "hello_hashed",
				"ns":   "test_db.test_coll",
			},
			{
				"key": bson2.M{
					"x": int32(1),
					"y": int32(1),
				},
				"name": "x_1_y_1",
				"ns":   "test_db.test_coll",
			},
			{
				"key": bson2.M{
					"z": int32(1),
				},
				"name": "z_1",
				"ns":   "test_db.test_coll",
			},
			{
				"unique": true,
				"key": bson2.M{
					"id_type": int32(1),
					"did":     int32(1),
					"uid":     int32(1),
					"msg_id":  int32(1),
				},
				"name":       "id_type_1_did_1_uid_1_msg_id_1",
				"ns":         "test_db.test_coll",
				"background": true,
			},
		}
		indexMap := map[utils.NS][]bson2.M{
			utils.NS{"test_db", "test_coll"}: indexInput,
		}
		err = StartIndexSync(indexMap, testMongoAddress, nil, true)
		assert.Equal(t, nil, err, "should be equal")

		cursor, err := conn.Client.Database("test_db").Collection("test_coll").Indexes().List(nil)
		assert.Equal(t, nil, err, "should be equal")

		indexes := make([]bson2.M, 0)

		cursor.All(nil, &indexes)
		assert.Equal(t, nil, err, "should be equal")
		assert.Equal(t, len(indexes), len(indexInput), "should be equal")
		assert.Equal(t, isEqual(indexInput, indexes), true, "should be equal")
	}

	// serverless
	{
		fmt.Printf("TestStartIndexSync case %d.\n", nr)
		nr++

		conf.Options.FullSyncReaderCollectionParallel = 4

		conn, err := utils.NewMongoCommunityConn(testMongoAddressServerless, utils.VarMongoConnectModePrimary, true,
			utils.ReadWriteConcernLocal, utils.ReadWriteConcernDefault)
		assert.Equal(t, nil, err, "should be equal")

		// drop old db
		err = conn.Client.Database("test_db").Drop(nil)
		assert.Equal(t, nil, err, "should be equal")

		indexInput := []bson2.M{
			{
				"key": bson2.M{
					"_id": int32(1),
				},
				"name": "_id_",
				//"ns":   "test_db.test_coll",
			},
			{
				"key": bson2.M{
					"hello": "hashed",
				},
				"name": "hello_hashed",
				//"ns":   "test_db.test_coll",
			},
			{
				"key": bson2.M{
					"x": int32(1),
					"y": int32(1),
				},
				"name": "x_1_y_1",
				//"ns":   "test_db.test_coll",
			},
			{
				"key": bson2.M{
					"z": int32(1),
				},
				"name": "z_1",
				//"ns":   "test_db.test_coll",
			},
			{
				"unique": true,
				"key": bson2.M{
					"id_type": int32(1),
					"did":     int32(1),
					"uid":     int32(1),
					"msg_id":  int32(1),
				},
				"name": "id_type_1_did_1_uid_1_msg_id_1",
				//"ns":         "test_db.test_coll",
				//"background": true,
			},
		}
		indexMap := map[utils.NS][]bson2.M{
			utils.NS{"test_db", "test_coll"}: indexInput,
		}
		err = StartIndexSync(indexMap, testMongoAddressServerless, nil, true)
		assert.Equal(t, nil, err, "should be equal")

		cursor, err := conn.Client.Database("test_db").Collection("test_coll").Indexes().List(nil)
		assert.Equal(t, nil, err, "should be equal")

		indexes := make([]bson2.M, 0)

		cursor.All(nil, &indexes)
		assert.Equal(t, nil, err, "should be equal")
		assert.Equal(t, len(indexes), len(indexInput), "should be equal")
		assert.Equal(t, isEqual(indexInput, indexes), true, "should be equal")
	}
}
`

---

test 结果

> === RUN   TestStartIndexSync
TestStartIndexSync case 0.
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] start writing index with background[true], indexMap length[1]
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] Close client with mongodb://xx.xx.xx.xx:27017
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] Close client with mongodb://xx.xx.xx.xx:27017
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] Close client with mongodb://xx.xx.xx.xx:27017
[2021/10/20 11:00:54 CST] [INFO] Create indexes for ns {test_db test_coll} of dest mongodb finish
[2021/10/20 11:00:54 CST] [INFO] Close client with mongodb://xx.xx.xx.xx:27017
[2021/10/20 11:00:54 CST] [INFO] finish writing index
[map[key:map[_id:1] name:_id_] map[background:true key:map[hello:hashed] name:hello_hashed] map[background:true key:map[did:1 id_type:1 msg_id:1 uid:1] name:id_type_1_did_1_uid_1_msg_id_1 unique:true] map[background:true key:map[x:1 y:1] name:x_1_y_1] map[background:true key:map[z:1] name:z_1]]
[map[key:map[_id:1] name:_id_] map[background:true key:map[hello:hashed] name:hello_hashed] map[background:true key:map[did:1 id_type:1 msg_id:1 uid:1] name:id_type_1_did_1_uid_1_msg_id_1 unique:true] map[background:true key:map[x:1 y:1] name:x_1_y_1] map[background:true key:map[z:1] name:z_1]]
TestStartIndexSync case 1.
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] start writing index with background[true], indexMap length[1]
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] Close client with mongodb://xx.xx.xx.xx:27017
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] Close client with mongodb://xx.xx.xx.xx:27017
[2021/10/20 11:00:54 CST] [INFO] New session to mongodb://xx.xx.xx.xx:27017 successfully
[2021/10/20 11:00:54 CST] [INFO] Close client with mongodb://xx.xx.xx.xx:27017
[2021/10/20 11:00:55 CST] [INFO] Create indexes for ns {test_db test_coll} of dest mongodb finish
[2021/10/20 11:00:55 CST] [INFO] Close client with mongodb://xx.xx.xx.xx:27017
[2021/10/20 11:00:55 CST] [INFO] finish writing index
[map[key:map[_id:1] name:_id_] map[background:true key:map[hello:hashed] name:hello_hashed] map[background:true key:map[did:1 id_type:1 msg_id:1 uid:1] name:id_type_1_did_1_uid_1_msg_id_1 unique:true] map[background:true key:map[x:1 y:1] name:x_1_y_1] map[background:true key:map[z:1] name:z_1]]
[map[key:map[_id:1] name:_id_] map[background:true key:map[hello:hashed] name:hello_hashed] map[background:true key:map[did:1 id_type:1 msg_id:1 uid:1] name:id_type_1_did_1_uid_1_msg_id_1 unique:true] map[background:true key:map[x:1 y:1] name:x_1_y_1] map[background:true key:map[z:1] name:z_1]]
--- PASS: TestStartIndexSync (0.38s)
PASS

---

实际db内索引

> [
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "test_db.test_coll"
	},
	{
		"v" : 1,
		"key" : {
			"hello" : "hashed"
		},
		"name" : "hello_hashed",
		"ns" : "test_db.test_coll",
		"background" : true
	},
	{
		"v" : 1,
		"key" : {
			"x" : 1,
			"y" : 1
		},
		"name" : "x_1_y_1",
		"ns" : "test_db.test_coll",
		"background" : true
	},
	{
		"v" : 1,
		"key" : {
			"z" : 1
		},
		"name" : "z_1",
		"ns" : "test_db.test_coll",
		"background" : true
	},
	{
		"v" : 1,
		"unique" : true,
		"key" : {
			"uid" : 1,
			"msg_id" : 1,
			"id_type" : 1,
			"did" : 1
		},
		"name" : "id_type_1_did_1_uid_1_msg_id_1",
		"ns" : "test_db.test_coll",
		"background" : true
	}
]

**Comment by zhangst** [comment]
看文章，没有弄明白是索引的什么顺序不对？请补充下

**Comment by momopluto** [comment]
> 看文章，没有弄明白是索引的什么顺序不对？请补充下

"name" : "id_type_1_did_1_uid_1_msg_id_1" 这个索引的 key 顺序，

期望是：
	{
		"key" : {
			"id_type" : 1,
			"did" : 1,
			"uid" : 1,
			"msg_id" : 1
		},
	},

实际是：
	{
		"key" : {
			"uid" : 1,
			"msg_id" : 1,
			"id_type" : 1,
			"did" : 1
		},
	}

**Comment by momopluto** [comment]
大概看了下要修改的点，

同步索引时，使用 Indexes() 方法获取保持顺序的索引

重放时，目前使用的是 []bson.M，改用 []Index，取 Index.Key 保持顺序

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/commit/e2b7a0853f7cb14ec07806883502048ce642aa93

**Comment by momopluto** [comment]
这个改动提交不是解决这个问题？

**Comment by zhangst** [comment]
>

**Comment by lzpsqzr** [comment]
你好，我们在同步过程中也碰到了类似问题，请问现在有哪个版本修复了么？

**Comment by zhangst** [comment]
> 

还没有

**Comment by momopluto** [comment]
> 你好，我们在同步过程中也碰到了类似问题，请问现在有哪个版本修复了么？

我这边目前的应对方案，比较接近于 full_sync.create_index = foreground 
（并不完全准确，因为 foreground 是全量完就创建，而我下面的方案是增量同步到最新了才创建索引）

---

如果是线上在跑的源数据库（整个database，多个db）进行同步，为了保证全量同步能正常完成（避免，因业务上有对数据进行remove后insert的操作，而导致_id变了但又受唯一索引限制，而无法写入数据），

就 "不得不" 在同步数据过程中忽略掉索引，让数据冗余同步，直到增量同步都完成（按oplog重放，将remove后insert的操作也都同步完）

最后用脚本在目标数据库批量重建索引（目标数据库都未启用，建索引费时就费时了）

---

以上是近期整库多db迁移踩过的坑及经验，供参考

**Comment by momopluto** [comment]
另外，在修复了此issue的问题（索引顺序维持）的前提下，

我建议提供一个全局的 all.create_index = xxx 方式，支持在 全量+增量 同步完后，再创建索引，以应对业务中有对数据进行remove后insert操作，改变了 _id 的情况

**适用场景：整库迁移，包含多个db（不好改变 full_sync.reader.parallel_index = _id 配置的情况）**

**Comment by zzh0106** [comment]
小白尝试对此进行了修复，请各位大佬看下可行
![screen_2022-02-12_15-16-06](https://user-images.githubusercontent.com/40262383/153701401-dcaa8251-5b65-4d79-a323-dd1b56156700.png)
![screen_2022-02-12_15-16-58](https://user-images.githubusercontent.com/40262383/153701420-77c685ed-d02c-4dfc-bd7a-ce5fbf2da83d.png)
![2](https://user-images.githubusercontent.com/40262383/153701421-48e34bed-5e29-473d-8f02-74153665674d.png)

**Comment by momopluto** [comment]
> 小白尝试对此进行了修复，请各位大佬看下可行 ![screen_2022-02-12_15-16-06](https://user-images.githubusercontent.com/40262383/153701401-dcaa8251-5b65-4d79-a323-dd1b56156700.png) ![screen_2022-02-12_15-16-58](https://user-images.githubusercontent.com/40262383/153701420-77c685ed-d02c-4dfc-bd7a-ce5fbf2da83d.png) ![2](https://user-images.githubusercontent.com/40262383/153701421-48e34bed-5e29-473d-8f02-74153665674d.png)


type D []E

// Map creates a map from the elements of the D.
func (d D) Map() M {
	m := make(M, len(d))
	for _, e := range d {
		m[e.Key] = e.Value
	}
	return m
}

bson.D{}.Map() 还是转成了 bson.M ，解决不了这个问题。

解决思路我上面其实提到了，

> 同步索引时，使用 Indexes() 方法获取保持顺序的索引
重放时，目前使用的是 []bson.M，改用 []Index，取 Index.Key 保持顺序

**Comment by chaigang0** [comment]
版本号：release-v2.6.5-20210723-1
我们今天迁移测试环境数据也遇到了索引顺序打乱的问题，幸好及时发现，如果在线上可能会有查询变慢的问题，希望可以在下下个版本中修复这个问题~

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/commit/16732d1d99994fa09aacb5b23c6f30efbe00d397
已修改，会在2.7.1版本发布
