### ISSUE TITLE
mongoshake同步分片集群，源端开启平衡的问题

### ISSUE THREAD

**Issue by kwenzh** [alibaba/MongoShake#671]
我们在使用shake同步分片集群的时候遇到一个问题，由于同步分片集群需要关闭源端的banlance，导致源端mongo集群分片不均匀，源端分片集群是mongodSrv27031 和mongodSrv27032，其中mongodSrv27031数据磁盘占用很多，不够均衡

目前最新版的shake是否支持 同步分片集群源端开启balance？

**Comment by zhangst** [comment]
ChangeStream方式支持开启balance

**Comment by kwenzh** [comment]
> ChangeStream方式支持开启balance

我们目前是 oplog的拉取，incr_sync.mongo_fetch_method = oplog
您的意思是说改为：incr_sync.mongo_fetch_method = change_stream，这样源端就可以正常开启balance了吗

**Comment by kwenzh** [comment]
> ChangeStream方式支持开启balance

从当前的oplog方式改到change_stream，ckpt可以保证数据断点继续同步吗

**Comment by zhangst** [comment]
> > ChangeStream方式支持开启balance
> 
> 从当前的oplog方式改到change_stream，ckpt可以保证数据断点继续同步吗

改为change_stream，源就可以balance。这个方式增量同步也支持断点续传的

**Comment by kwenzh** [comment]
> > > ChangeStream方式支持开启balance
> > 
> > 
> > 从当前的oplog方式改到change_stream，ckpt可以保证数据断点继续同步吗
> 
> 改为change_stream，源就可以balance。这个方式增量同步也支持断点续传的

好的 谢谢
