### ISSUE TITLE
全量同步 full模式结束之后，没有自动退出，又重新拉起任务重复执行

### ISSUE THREAD

**Issue by kwenzh** [alibaba/MongoShake#673]
全量同步 full模式结束之后，没有自动退出，又重新拉起任务重复执行全量同步，这个问题有遇到过吗
sync_mode = full

**Comment by zhangst** [comment]
直接用命令行启动试一下：./collector --conf=

**Comment by kwenzh** [comment]
> 直接用命令行启动试一下：./collector --conf=

这样确实可以自动退出，请问这是为什么呢，./hypervisor --daemon --exec 执行是拉起了什么自动机制吗？

**Comment by zhangst** [comment]
hypervisor本身是自动重启程序。给需要一直长期运行的增量同步使用。全量同步只运行一次，不需要使用hypervisor

**Comment by hlz5857475** [comment]
> hypervisor本身是自动重启程序。给需要一直长期运行的增量同步使用。全量同步只运行一次，不需要使用hypervisor

使用hypervisor启动， 后期想彻底关掉mongoshake服务，怎么干掉hypervisor呢
