### ISSUE TITLE
syncer_inner_queue队列满，worker队列空，如何提升性能

### ISSUE THREAD

**Issue by DrgZong** [alibaba/MongoShake#675]
![image](https://user-images.githubusercontent.com/19589495/141228083-01539fbe-fb9a-4700-a769-61fa504a84bc.png)
![image](https://user-images.githubusercontent.com/19589495/141228166-8df0d752-bd8c-4898-9e24-eebe89c27b26.png)

**Comment by DrgZong** [comment]
lsn_ckpt.time与now.time时差在oplog过多时会越来越大’服务器、端库都没有性能压力

**Comment by zhangst** [comment]
参考下面排查下：
https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E4%BD%95%E7%9B%91%E6%8E%A7%E5%92%8C%E7%AE%A1%E7%90%86MongoShake%E7%9A%84%E8%BF%90%E8%A1%8C%E7%8A%B6%E6%80%81%EF%BC%9F

**Comment by DrgZong** [comment]
我们是增量同步，上面的信息就是从看监控得来的。。这边也没做限速。为了提高效率，加了很多worker，然而性能并没有提升，因为瓶颈不在woeker这儿，它的队列都是空的

**Comment by DrgZong** [comment]
mongoshake拿到oplog后需要分发到worker，感觉瓶颈在分发这儿。。

**Comment by zhangst** [comment]
麻烦上传下日志和完成的监控信息：
curl -s http://127.0.0.1:9100/repl | python -m json.tool
curl -s http://127.0.0.1:9100/queue | python -m json.tool
curl -s http://127.0.0.1:9100/worker | python -m json.tool
