### ISSUE TITLE
Conf.Options check failed: connect source mongodb[mongodb://root:123456@****] failed[server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field.]

### ISSUE THREAD

**Issue by zhangxianaa** [alibaba/MongoShake#677]
Conf.Options check failed: connect source mongodb[mongodb://root:123456@192.169.7.82:50000,192.169.7.82:50001,192.169.7.82:50002] failed[server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field.]
[19:07:10 CST 2021/11/11] [CRIT] (github.com/alibaba/MongoShake/v2/common.NewMongoConn:49) Connect to mongodb://root:***@192.169.7.82:50000,192.169.7.82:50001,192.169.7.82:50002 failed. server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field.
mongdb版本是5.0.3
mongoshake版本是 2.6.5

**Comment by zhangst** [comment]
确认下账号和DB能否对应上，用mongoshell连接试下
如果账号在admin库中，连接串最后加下admin

**Comment by zhangxianaa** [comment]
> mongoshell可以连接，之前用的mongdb版本是4.2.15，一直没问题
现在改成这样 mongo_urls = mongodb://root:123456@192.169.7.82:50000,192.169.7.82:50001,192.169.7.82:50002/?replicaSet=rs0&authSource=admin 也不行，之前是不带选项直接都可以。
加账号是下面的命令加的：
use admin
db.createUser({user:"root",pwd:"123456",roles:[{role:"root",db:"admin"}]})

**Comment by zhangst** [comment]
未发布2.6.7版本会支持MongoDB5.0，发布可使用新版本测试

**Comment by whaike** [comment]
> 未发布2.6.7版本会支持MongoDB5.0，发布可使用新版本测试

你好 问下2.6.7大概什么时候会发布？
