### ISSUE TITLE
配置文件单行最大只支持4096字节

### ISSUE THREAD

**Issue by LuoHaibin** [alibaba/MongoShake#680]
https://github.com/alibaba/MongoShake/blob/a4ec5ced86d147e317ee04767666113b53f0978c/go.mod#L8

此依赖的版本存在此问题，后续提交已修复问题
https://github.com/gugemichael/nimo4go/commit/ff2f84828620cc40f5d7eb4fa737478a14d89b44#diff-0e426a43248661127a0c0ee115aef7a1093b635f8993b3f7ebb1dd9f05b8f249

**Comment by zhangst** [comment]
什么场景需要单行大于4096？

**Comment by LuoHaibin** [comment]
在配置数据源，我们这边统一用的是集合白名单，需要迁移的集合多了，就会超过4096字节。

读取配置时，单行超限后，会放弃读取剩下的配置直接返回已读的配置，而不是报错，这也是不合理的。

**Comment by zhangst** [comment]
也可以直接指定DB的名称，不需要指定每一个集合。这样可以缩短长度，这样能解决你的问题吗？
你这个用法很少

**Comment by LuoHaibin** [comment]
之前是通过指定数据库的方式解决了，但实际，集合粒度的白名单 是不能完全被 数据库粒度的白名单 或 其他黑名单所取代的。
