### ISSUE TITLE
mongo-shake 2.6.5版本，限速命令报错的问题

### ISSUE THREAD

**Issue by sunqintao** [alibaba/MongoShake#682]
windows下，同步本地局域网到阿里云
由于云主机带宽的限制，在同步mongoGridfs过程中，30M的带宽超限，被云主机断了请求，因此需要限速。
执行如下命令
`curl -X POST --data '{"TPS": 1000}' 127.0.0.1:9100/sentinel/options`

`curl -X POST -d '{"TPS":1000}'  http://127.0.0.1:9820/sentinel/options`
报错
`{"sentinel":"request json options wrong format"}`

请教下限速命令的问题?

**Comment by sunqintao** [comment]
curl -H "Content-Type:application/json"  -X POST --data '{"TPS":1000}' http://127.0.0.1:9820/sentinel/options这个命令也试过了，也报同样的错误

**Comment by sunqintao** [comment]
logs
`Register set options wrong format : invalid character '\'' looking for beginning of value`

**Comment by zhangst** [comment]
请用linux系统访问试一下，对比下是不是window的shell把字符转义了
