### ISSUE TITLE
MongoShake的数据同步，日志在报了一段时间这个错误后，任务就挂了

### ISSUE THREAD

**Issue by YaoAndYang** [alibaba/MongoShake#683]
Collector-worker-7 transfer retransmit:false send [50] logs. reply_acked [7039641033835027384[1639044153, 7096]], list_unack [0]

**Comment by zhangst** [comment]
这个是一个常规日志，不会让shake退出的。
1. 补充下shake版本信息
2. 用debug级别的日志运行下
