### ISSUE TITLE
Syncer deserializer panic

### ISSUE THREAD

**Issue by zemul** [alibaba/MongoShake#689]
插入这样一条数据时候，bson.unmashal报错直接panic
```
db.col.insert({"progress" : BinData(2,"CgM3NzcQAhgCIgQIAhACKgQIAhACMgQIAhACOgQIAhACQgQIAhACWgA=")})
```

panic: Syncer[rs0] deserializer parse data failed[Document is corrupted]

似乎跟2这个subtype有关系，另外,bson.Unmarshal解析失败直接Crash是不是不太合适呢？

**Comment by zhangst** [comment]
略过有问题的语句，这样问题就不可现了，会导致目的数据库缺少数据，这是数据迁移不能接受的。
这个unmarshal的错误，在2.6.7版本中会更换底层mgo库，到时候请使用新的版本。

**Comment by zhangst** [comment]
略过有问题的语句，这样问题就不可现了，会导致目的数据库缺少数据，这是数据迁移不能接受的。
这个unmarshal的错误，在2.6.7版本中会更换底层mgo库，到时候请使用新的版本。

**Comment by zemul** [comment]
> 略过有问题的语句，这样问题就不可现了，会导致目的数据库缺少数据，这是数据迁移不能接受的。 这个unmarshal的错误，在2.6.7版本中会更换底层mgo库，到时候请使用新的版本。

找到锅了，这个问题与库无关 https://jira.mongodb.org/browse/SERVER-41994
