### ISSUE TITLE
两个副本集增量同步时，lsn不更新，同步卡住

### ISSUE THREAD

**Issue by minggaodong** [alibaba/MongoShake#690]
我是两个副本集，通过公网进行同步，运行的过程中，发现经常跑了20分钟，会出现lsn.time完全卡住不再增加的情况，l进程状态也正常，只是数据不再同步了，有如下日志告警：”doUpdateOnInsert runs upsert but lack documentKey“

队列监控：
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 256,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 0
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 1
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 2
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 3
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 4
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 5
        }
    ],
    "syncer_replica_set_name": "gzrs"
}

副本集监控返回：
{
    "log_size_avg": "778.00B",
    "log_size_max": "3.83MB",
    "logs_get": 8905728,
    "logs_repl": 7715132,
    "logs_success": 7715132,
    "lsn": {
        "time": "2022-01-17 17:37:22",
        "ts": "7054106865940045187",
        "unix": 1642412242
    },
    "lsn_ack": {
        "time": "2022-01-17 17:37:22",
        "ts": "7054106865940045088",
        "unix": 1642412242
    },
    "lsn_ckpt": {
        "time": "2022-01-17 17:37:17",
        "ts": "7054106844465216309",
        "unix": 1642412237
    },
    "now": {
        "time": "2022-01-17 20:16:18",
        "unix": 1642421778
    },
    "replset": "default-0",
    "tag": "$",
    "tps": 1027,
    "who": "mongoshake"
}

**Comment by zhangst** [comment]
请看下目的的MongoDB的oplog中有没有数据操作，这个日志提醒表示原有的insert语句因为目的库数据已存在，改为update执行。
