### ISSUE TITLE
change_stream模式下mongshake.ckpt_default collection中ckpt在无数据同步时没有实时更新

### ISSUE THREAD

**Issue by longwallstreet** [alibaba/MongoShake#696]
背景: 想要监控mongoshake的运行状态，根据wiki中的指引通过curl -s http://127.0.0.1:9100/repl可以获取到lsn_ckpt信息，如果lsn_ckpt长期没有更新，跟now的时间越来越大，那么通常证明同步有异常了，要么是写流量过大导致差距变大，要么是同步中断了。对于3.4以后的版本，即使没有写入，也会定期产生noop oplog推动lsn_ckpt，但对于3.4以前，如果长期没写入，这个差距越来越大是正常现象。

问题：但是在实际的使用过程中，发现mongoshake.ckpt_default里面的时间停留在source mongo最新一次有数据写入时的时间，http://127.0.0.1:9100/repl拿到的lsn_ckpt并没有实时在变化。 但local.oplog.rs中确实是定时有noop的document产生。
请问老师是需要更改哪些配置能让mongoshake.ckpt_default表里面的时间定时更新？

环境：
mongo的版本是4.4.X
mongoshake版本是2.6.5
使用change_stream增量同步

**Comment by zhangst** [comment]
Noop oplog不需要写入目的Mongo，在shake上的过滤节点被丢弃了。
lsn_chpt取所有的work线程中完成目的写入的最小的oplog时间，实际写入的oplog中并没有Noop oplog。
目前的增量更新机制是这样，还不支持用Noop来更新lsn_ckpt
