### ISSUE TITLE
怎么重新全量同步

### ISSUE THREAD

**Issue by zlee520** [alibaba/MongoShake#698]
第一次全量同步后，把目标集合的数据都删除了（测试）
想要再一次全量同步要怎么配置？

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/wiki/%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8%EF%BC%8C%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE%EF%BC%9F
看下文档啊，重新运行一次

**Comment by zlee520** [comment]
thanks
