### ISSUE TITLE
mongoshake与源mongodb网络断开后，内存持续增加，网络恢复后内存未释放并且有很多个TCP连接

### ISSUE THREAD

**Issue by longwallstreet** [alibaba/MongoShake#702]
现象：
mongoshake与mongodb之间是vpn连接，周末vpn断开后，mongoshake不断自动重连，内存持续增加
网络恢复后，内存并未释放，并且观测到有很多个tcp连接(ESTABLISTED)存在。
![5133FE53-E844-4cb5-93A5-9A1AB1BF4C78](https://user-images.githubusercontent.com/34297812/160315000-06d755d3-c68f-46d5-9dbe-e0c67dca92d5.png)
![lALPJxuMP_2eqwfNBDjNB4A_1920_1080](https://user-images.githubusercontent.com/34297812/160315009-0fce5c4d-d7de-4f99-b3a4-58ddba698f94.png)
![lQLPDhtHAbRwqMfNA23NA0awCCRi3wOoelcCRQKwxIBfAA_838_877](https://user-images.githubusercontent.com/34297812/160315016-9b420240-18b5-4fb1-98f2-ebf8cadfafae.png)

环境
mongoshake：2.6.5
mongodb: 4.4.X
同步方式: change_stream

**Comment by zhangst** [comment]
请尝试下2.6.6版本，这个版本有解决这个问题。

**Comment by longwallstreet** [comment]
好的，谢谢，回复的很及时哈  @zhangst
