### ISSUE TITLE
mongoshake与源mongodb网络断开后，网络恢复后内存未释放并且有很多个TCP连接

### ISSUE THREAD

**Issue by longwallstreet** [alibaba/MongoShake#703]
前几天提了这个issue: https://github.com/alibaba/MongoShake/issues/702
升级了2.6.6版本以后，mongoshake与源mongodb网络断开后，网络恢复后并没有内存泄漏的现象，但是仍然存在很多个TCP连接，麻烦老师有空看一下，我们即将准备在生产环境大规模使用了。

环境
mongoshake: 2.6.6
mongodb: 4.4.X
同步方式: change_stream

**Comment by zhangst** [comment]
TCP连接方便截个图吗？连接是什么状态？如果是TIME_WAIT，那是正常的

**Comment by longwallstreet** [comment]
运行了一个月左右，没出现这个问题，当时可能是没更新吧。。。 先关闭吧 @zhangst
