### ISSUE TITLE
mongoshake应用事务数据报错

### ISSUE THREAD

**Issue by Jinle1234** [alibaba/MongoShake#705]
hi：我在使用mongoshake同步数据的时候，发现开了session之后写的oplog是以下格式的
![image](https://user-images.githubusercontent.com/102858979/161380828-95dd0a81-97d1-4ade-8662-fd570ce34033.png)
但是在开启filter.ddl_enable = true的情况下，同步还是失败的，报错如下：
![image](https://user-images.githubusercontent.com/102858979/161380878-7a1dd911-315e-405e-abff-4b909219d515.png)

之前看到有个issue---https://github.com/alibaba/MongoShake/issues/544 说开启filter.ddl_enable = true之后可以成功应用事务日志，但好像并不是如此，不知道是否还有哪里需要配置，请帮忙看下，谢谢~

我是用的mongoshake版本是：mongo-shake-v2.6.5

**Comment by zhangst** [comment]
现在不支持事务oplog的应用
