### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by paul-mesnilgrente** [alibaba/MongoShake#711]
Hi,

I'm having an issue setting the `tunnel.address`. When I launch `./collector.linux -conf=collector.conf` I get this:

> Conf.Options check failed: connect target tunnel mongodb[mongodb://user:password@127.0.0.1:27017] failed[server returned error on SASL authentication step: Authentication failed.]
> [21:21:17 UTC 2022/04/13] [CRIT] (github.com/alibaba/MongoShake/v2/common.NewMongoConn:24) Connect to mongodb://user:***@127.0.0.1:27017 failed. server returned error on SASL authentication step: Authentication failed.

Although, when I run `mongo mongodb://user:password@127.0.0.1:27017` it works and I have a root access to Mongo. Does Mongo need an extra setup?

I'm using the MongoShake 2.6.6 with Mongo 4.2.17.

**Comment by zhangst** [comment]
src & dst version is 4.2.17?

**Comment by paul-mesnilgrente** [comment]
That's the source, installed with bitnami/mongodb helm chart, that's the version:

```
MongoDB shell version v4.2.17
git version: be089838c55d33b6f6039c4219896ee4a3cd704f
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
allocator: tcmalloc
modules: none
build environment:
    distmod: debian10
    distarch: x86_64
    target_arch: x86_64
```

That's the docker image of the destination: docker.io/mongo:4.2.17. Installed with the mongodb-helm-charts/community-operator helm chart.

**Comment by zhangst** [comment]
shake do not support mongo5.0 authentication method, but 4.2 is ok before, 4.2.17 maybe introduce new authentication method.

**Comment by paul-mesnilgrente** [comment]
I found the problem in the mongo logs:

```
2022-04-19T10:52:22.934+0000 I  NETWORK  [listener] connection accepted from 172.34.90.193:34878 #6445 (33 connections now open)
2022-04-19T10:52:22.935+0000 I  NETWORK  [conn6445] received client metadata from 172.34.90.193:34878 conn6445: { driver: { name: "mgo", version: "vinllen" }, os: { type: "linux", architecture: "amd64" } }
2022-04-19T10:52:22.936+0000 I  ACCESS   [conn6445] SASL SCRAM-SHA-1 authentication failed for user on admin from client 172.34.90.193:34878 ; BadValue: SCRAM-SHA-1 authentication is disabled
2022-04-19T10:52:22.942+0000 I  NETWORK  [conn6445] end connection 172.34.90.193:34878 (32 connections now open)
```

Is there any ways to use `SCRAM-SHA-256` instead of `SCRAM-SHA-1`? I guess I could enable it.

**Comment by zhangst** [comment]
Sorry, there is no such configuration

**Comment by paul-mesnilgrente** [comment]
That's all good, I managed to set it up so that it supports both.

**Comment by ws-liutl1** [comment]
> That's all good, I managed to set it up so that it supports both.

How did you set it up? I am also facing the same issue.

**Comment by bfun123** [comment]
> That's all good, I managed to set it up so that it supports both.

Hi, how do u solve the problem.
