### ISSUE TITLE
mongo 数据库主从切换后为什么会重建索引，可以通过什么方式避免重建索引？（源4.0.11，目的4.2.8，shake 2.0.7）

### ISSUE THREAD

**Issue by jianghancheng** [alibaba/MongoShake#712]
我们搭建了一个主库和灾备库，我们进行灾备切换后，灾备库变成主库，然后会有大量的表索引重建操作（索引重建会导致库不可用），导致生产应用连接出现问题，请问这种重建索引是正常的？如何设置可以不让重建索引。
![0263fdb1cdd8fb0d769c7930f66e3d3](https://user-images.githubusercontent.com/14351843/163547143-429e7404-67d9-4fd0-b5d5-5d1e7a24acfc.jpg)
![9601d85bd0588fa3cffde800843f5e3](https://user-images.githubusercontent.com/14351843/163547199-2960a8bd-7e03-4dec-96b6-dbba95d65f72.jpg)
![2e584240766918bd7ca917fb653a59c](https://user-images.githubusercontent.com/14351843/163547226-d381b065-a196-4eb5-9520-b5a2be3e6b03.jpg)

**Comment by zhangst** [comment]
这个要看下是谁触发的索引重建，通过搜索conn连接串可以找到。这个是mongo的问题，可以在mongo官网文档上看看索引相关的内容
