### ISSUE TITLE
源端分片集群事务删除同步目标端分片集群报错

### ISSUE THREAD

**Issue by wl4879066** [alibaba/MongoShake#723]
mongo部署：源端和目标端均为分片集群，版本4.4
mongoshake版本;2.6.5
源端事务删除多个文档，mongoshake同步一直卡住重试，报错如下：
collector.log.2022-02-18.001:[2022/02/18 16:09:47 CST] [INFO] Replay-0 run DDL with metadata[admin] in db[map[]], firstLog: {"ts":7065940673366589443,"op":"c","ns":"admin.$cmd","o":[{"Name":"applyOps","Value":[{"ns":"test-db.t_test","o":[{"Name":"_id","Value":"620f433c1002000332de4e88"}],"o2":{},"op":"d"},{"ns":"test-db.t_test","o":[{"Name":"_id","Value":"620f433c1002000332de4e8b"}],"o2":{},"op":"d"}]}],"o2":null,"lsid":{"id":{"Kind":4,"Data":"1BHJ4ZMmRE2RvVESGFykxA=="},"uid":"9MyaWelB7KMfAyEzDbP8oBq0H31abhJi/ZkhUAGJ8QA="}}
collector.log.2022-02-18.001:[2022/02/18 16:09:47 CST] [INFO] RunCommand run DDL with type[applyOps]
collector.log.2022-02-18.001:[2022/02/18 16:09:47 CST] [DEBG] RunCommand run DDL: [{ts 7065940673366589443} {h 0} {v 0} {op c} {g } {ns admin.$cmd} {o [{applyOps [map[ns:test-db.t_test o:[{_id ObjectIdHex("620f433c1002000332de4e88")}] o2:map[] op:d] map[ns:test-db.t_test o:[{_id ObjectIdHex("620f433c1002000332de4e8b")}] o2:map[] op:d]]}]} {o2 map[]} {uk map[]} {lsid map[id:{4 [212 17 201 225 147 38 68 77 145 189 81 18 24 92 164 196]} uid:[244 204 154 89 233 65 236 163 31 3 33 51 13 179 252 160 26 180 31 125 90 110 18 98 253 153 33 80 1 137 241 0]]} {fromMigrate false} {txnNumber 0} {documentKey map[]}]
collector.log.2022-02-18.001:[2022/02/18 16:09:47 CST] [INFO] Execute command (op==c) oplog, operation [applyOps]
collector.log.2022-02-18.001:[2022/02/18 16:09:47 CST] [DEBG] writer: command {"ts":7065940673366589443,"op":"c","ns":"admin.$cmd","o":[{"Name":"applyOps","Value":[{"ns":"test-db.t_test","o":[{"Name":"_id","Value":"620f433c1002000332de4e88"}],"o2":{},"op":"d"},{"ns":"test-db.t_test","o":[{"Name":"_id","Value":"620f433c1002000332de4e8b"}],"o2":{},"op":"d"}]}],"o2":null,"lsid":{"id":{"Kind":4,"Data":"1BHJ4ZMmRE2RvVESGFykxA=="},"uid":"9MyaWelB7KMfAyEzDbP8oBq0H31abhJi/ZkhUAGJ8QA="}}

**Comment by wl4879066** [comment]
谢谢

**Comment by zhangst** [comment]
请试下2.7.4版本
