### ISSUE TITLE
增量同步的oplog速率qps瓶颈

### ISSUE THREAD

**Issue by JienYang94** [alibaba/MongoShake#724]
1. MongoShake的版本：v2.4.16

2. 源和目的MongoDB的版本: MongoDB shell version v3.6.23

3. 脱敏后的配置文件和日志

每一天会执行一个删除语句，删除大约1700百万笔记录。
在进行观察监控的复制信息时，耗费了6个小时完成，导致严重的延迟

提问：想请问目前新或旧的mongoshake版本只的tps上限只是到1000吗？还是其它配置因素而导致呢？

    "lsn": { // 已经拉取的checkpoint位点（不一定写入）
        "time": "2022-05-26 05:37:29", // 这个时间点是初始时间，表示还没有数据写入
        "unix": 1653514649
    },
    "lsn_ack": { // 已经成功写入目的端的checkpoint位点（已经成功写入，但是不一定持久化）
        "time": "2022-05-26 05:37:15",
        "unix": 1653514635
    },
    "lsn_ckpt": { // 已经成功持久化的checkpoint位点
        "time": "2022-05-26 05:37:14",
        "unix": 1653514634
    },
    "now": { // 当前的时间
        "time": "2022-05-26 08:59:22",
        "unix": 1653526762
    },
    "tps": 1000, // 同步的oplog速率qps

[collector_shard2.log.gz](https://github.com/alibaba/MongoShake/files/8778099/collector_shard2.log.gz)
[collector_shard2.conf.gz](https://github.com/alibaba/MongoShake/files/8778101/collector_shard2.conf.gz)

**Comment by zhangst** [comment]
如果是有测试环境，建议做最新版本2.7.x版试一下。

日志中的tps=256，表示每秒的写入量，现在是256。建议调大下面的两个参数，比如先翻一倍看下有没有效果
[2022/05/26 00:17:55 HKT] [INFO] [name=default-0, stage=incr, get=1839077678, filter=973451, success=1838103947, tps=256, ckpt_times=829010, lsn_ckpt={7101708967734149399[1653495470, 279], 2022-05-26 00:17:50}, lsn_ack={7101708984914018368[1653495474, 64], 2022-05-26 00:17:54}]]

incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

**Comment by JienYang94** [comment]
你好，

我的测试环境无法复制数据量和流量 ，目前是在正式环境修改以下的配置进行翻一倍。
incr_sync.adaptive.batching_max_size = 2048
incr_sync.fetcher.buffer_capacity = 512

可能也可以问问，tps量怎么断断续续的

**Comment by JienYang94** [comment]
你好，

我的测试环境无法复制数据量和流量 ，目前是在正式环境修改以下的配置进行翻一倍。
incr_sync.adaptive.batching_max_size = 2048
incr_sync.fetcher.buffer_capacity = 512

翻倍配置之后，tps总是0 / 512 / 2048

翻倍前，0 / 256 / 1024tps量怎么断断续续的

**Comment by JienYang94** [comment]
你好，

我的测试环境无法复制数据量和流量 ，目前是在正式环境修改以下的配置进行翻一倍。
incr_sync.adaptive.batching_max_size = 2048
incr_sync.fetcher.buffer_capacity = 512

在日志和我自制的监控板都能看到tps值确实有增加，可是有个疑问的是为什么tps量断断续续呢？目前这数据表每一秒都有操作。
翻倍配置前，tps是0 / 256 / 1024
翻倍配置后，tps是0 / 512 / 2048

在这三天的观察下，同样的删除量和配置/tps都翻倍了，可是却没有在延迟上看到任何的效果。

我上传了日志和监控图供您参考。
监控图

**Comment by JienYang94** [comment]
你好，

我的测试环境无法复制数据量和流量 ，目前是在正式环境修改以下的配置进行翻一倍。
incr_sync.adaptive.batching_max_size = 2048
incr_sync.fetcher.buffer_capacity = 512

在日志和我自制的监控板都能看到tps值确实有增加，可是有个疑问的是为什么tps量断断续续呢？目前这数据表每一秒都有操作。
翻倍配置前，tps是0 / 256 / 1024
翻倍配置后，tps是0 / 512 / 2048

在这三天的观察下，同样的删除量和配置/tps都翻倍了，可是却没有在延迟上看到任何的效果。

我上传了日志和监控图供您参考。

- ”图一“监控了repl复制信息的”lsn_ack - now“

- ”图二“监控了repl复制信息的”tps“

<img width="1242" alt="图一" src="https://user-images.githubusercontent.com/106303450/170908137-fec03a57-837d-4172-a0ee-a7445b716965.png">
<img width="1229" alt="图二" src="https://user-images.githubusercontent.com/106303450/170908160-88307a4d-4852-45eb-9bcc-1da0e4f8ebea.png">


[collector_shard2.log.2022-05-29.001.gz](https://github.com/alibaba/MongoShake/files/8795068/collector_shard2.log.2022-05-29.001.gz)

**Comment by zhangst** [comment]
除了上面的参数，incr_sync.worker = 16 也可以尝试调整。
进一步分析，你再观察下内部队列的参数情况，参考连接：https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E4%BD%95%E7%9B%91%E6%8E%A7%E5%92%8C%E7%AE%A1%E7%90%86MongoShake%E7%9A%84%E8%BF%90%E8%A1%8C%E7%8A%B6%E6%80%81%EF%BC%9F

**Comment by JienYang94** [comment]
你好，

已依据你的建议调整至如以下，在观察每一天执行删除语句时，并没有看见改善。
incr_sync.worker = 24
incr_sync.tunnel.write_thread = 48
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 2048
incr_sync.fetcher.buffer_capacity = 512

在观察下内部队列的参数的时候发现这删除语句进行时，参数结果如下，
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 512,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 0
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 1
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 2
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 3
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 4
        },
        {
            "logs_queue_used": 64,
            "pending_queue_used": 64,
            "queue_id": 5
        }
    ],
    "syncer_replica_set_name": "default-0"
}

能看见"logs_queue_used"和"pending_queue_used": 都处于64，直到结束后才归0。

persister_buffer_used的也在这段时间维持512
<img width="1242" alt="图三" src="https://user-images.githubusercontent.com/106303450/171808723-c5f9dc21-bded-4e21-bc68-47060f52b8bf.png">

想问看以上这几个参数代表着什么呢？增加这些或其它哪些配置能够改善现状吗？

**Comment by zhangst** [comment]
这个可以看到写入积压的哪个队列中，在看下worker的队列情况，这个也有监控命令。

**Comment by JienYang94** [comment]
你好，

我这是观察下来的worker内部的使用情况。

"count": 0, // 当前worker已经同步了多少条数据
<img width="1228" alt="worker_count" src="https://user-images.githubusercontent.com/106303450/173511891-6b503f78-95c5-458f-899e-1359cffd5d3e.png">

"jobs_in_queue": 0, // 目前worker queue里面存在的个数
<img width="1222" alt="worker_job_in_queue" src="https://user-images.githubusercontent.com/106303450/173511970-190c7caf-af4b-4b93-9aca-a19300225736.png">

"last_ack": "0", // 已经ack的最后一条oplog的ts
<img width="1229" alt="worker_last_ack" src="https://user-images.githubusercontent.com/106303450/173512070-e6772e29-73b6-49cd-b9ee-4e7985036465.png">

"last_unack": "0", // 上一个未ack的oplog的ts
<img width="1219" alt="worker_last_unack" src="https://user-images.githubusercontent.com/106303450/173512165-c1d19a42-6eb8-498a-9281-388166bf17c0.png">

在图看见语句是在4.30am到10.30am，但是能看见worker设置了24个可是在运行的只有两个worker_id=1和6。
请问这是什么配置的原因导致吗？

**Comment by zhangst** [comment]
incr_sync.shard_key = collection
改为 
incr_sync.shard_key = auto

做下修改试试，你的增量只有两个表吗?

**Comment by JienYang94** [comment]
好的，会进行修改和观察。

是的。这是分片集群，目前只针对这一个表进行备份。

**Comment by Echo-19** [comment]
我这边也遇到了类似的情况，增量同步的延迟越来越大，导致一直追不上源集群，以下参数做了加大调整，incr_sync.adaptive.batching_max_size第一次从1024调到2048 tps有一定增加，从2048调整到4096tps没有增长了，调整之后延迟依旧在增大。incr_sync.shard_key = auto 这个也已经改成auto，同步的表中存在唯一索引，可能这个改善不大，请问下还有其他方式优化提升写入QPS吗？
incr_sync.worker = 8
incr_sync.tunnel.write_thread = 16
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 2048/4096
incr_sync.fetcher.buffer_capacity = 512/1024
{
    "logs_queue_size": 128,
    "pending_queue_size": 128,
    "persister_buffer_used": 1024,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 0
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 1
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 2
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 3
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 4
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 5
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 6
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 7
        }
    ],
    "syncer_replica_set_name": "x'x'x"
}

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/issues/700
pending_queue_used都满了，表示oplog拉取过来了，但是在worker处理中堆积了，就是写入目的慢了。
不知道你使用的版本信息，建议用最新的版本试一下，如果还是不行，参考上面提供下信息。

**Comment by Echo-19** [comment]
补充信息：
mongoshake版本：improve-2.8.0,12c59eaf1eaec312a51e29b3d05dea7a2b46d2dc,release,go1.15.10,2022-07-20_17:25:03
源端版本：3.6.13 目标端版本：3.6.10

[collector.conf.docx](https://github.com/alibaba/MongoShake/files/9671646/collector.conf.docx)
[collector.log.2022-09-28.log1.gz](https://github.com/alibaba/MongoShake/files/9672132/collector.log.2022-09-28.log1.gz)

**Comment by zhangst** [comment]
您好，看日志没有确定问题点，感觉是目的MongoDB的写入太慢了，请在目的MongoDB上看下来自shake的写入耗时大概都是多少？
另外请收集下如下的信息：
curl -s http://127.0.0.1:9100/queue | python -m json.tool
curl -s http://127.0.0.1:9100/worker | python -m json.tool
curl -s http://127.0.0.1:9100/executor | python -m json.tool

**Comment by Echo-19** [comment]
好的，写入只有来自shake，我这边用mongotop观察了下，时延大概如下图：
![image](https://user-images.githubusercontent.com/69190440/195582366-cadfa537-ef6f-4080-ac31-68f682e17b11.png)
curl -s http://127.0.0.1:9100/queue | python -m json.tool信息：

**Comment by Echo-19** [comment]
curl -s http://127.0.0.1:9100/queue | python -m json.tool信息：
{
    "logs_queue_size": 128,
    "pending_queue_size": 128,
    "persister_buffer_used": 512,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 0
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 1
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 2
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 3
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 4
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 5
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 6
        },
        {
            "logs_queue_used": 128,
            "pending_queue_used": 128,
            "queue_id": 7
        }
    ],
    "syncer_replica_set_name": ""
}
curl -s http://127.0.0.1:9100/worker | python -m json.tool
[
    {
        "count": 0,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "0",
        "last_unack": "0",
        "worker_id": 0
    },
    {
        "count": 48898,
        "jobs_in_queue": 64,
        "jobs_unack_buffer": 0,
        "last_ack": "7153897884146991459",
        "last_unack": "7153900864854294531",
        "worker_id": 1
    },
    {
        "count": 0,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "0",
        "last_unack": "0",
        "worker_id": 2
    },
    {
        "count": 0,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "0",
        "last_unack": "0",
        "worker_id": 3
    },
    {
        "count": 0,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "0",
        "last_unack": "0",
        "worker_id": 4
    },
    {
        "count": 0,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "0",
        "last_unack": "0",
        "worker_id": 5
    },
    {
        "count": 51282,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "7153900796134817799",
        "last_unack": "7153900796134817799",
        "worker_id": 6
    },
    {
        "count": 673,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "7153900787544883764",
        "last_unack": "7153900787544883764",
        "worker_id": 7
    }
]
curl -s http://127.0.0.1:9100/executor | python -m json.tool
[
    {
        "ddl": 0,
        "ddl_ns_top_3": [],
        "delete": 0,
        "delete_ns_top_3": [],
        "error": 0,
        "error_ns_top_3": [],
        "id": 0,
        "insert": 0,
        "insert_ns_top_3": [],
        "unknown": 0,
        "unknown_ns_top_3": [],
        "update": 0,
        "update_ns_top_3": []
    },
    {
        "ddl": 0,
        "ddl_ns_top_3": [],
        "delete": 37643,
        "delete_ns_top_3": [
            {
                "Key": " ",
                "Val": 37643
            }
        ],
        "error": 0,
        "error_ns_top_3": [],
        "id": 1,
        "insert": 37851,
        "insert_ns_top_3": [
            {
                "Key": " ",
                "Val": 37851
            }
        ],
        "unknown": 0,
        "unknown_ns_top_3": [],
        "update": 0,
        "update_ns_top_3": []
    },
    {
        "ddl": 0,
        "ddl_ns_top_3": [],
        "delete": 0,
        "delete_ns_top_3": [],
        "error": 0,
        "error_ns_top_3": [],
        "id": 2,
        "insert": 0,
        "insert_ns_top_3": [],
        "unknown": 0,
        "unknown_ns_top_3": [],
        "update": 0,
        "update_ns_top_3": []
    },
    {
        "ddl": 0,
        "ddl_ns_top_3": [],
        "delete": 0,
        "delete_ns_top_3": [],
        "error": 0,
        "error_ns_top_3": [],
        "id": 3,
        "insert": 0,
        "insert_ns_top_3": [],
        "unknown": 0,
        "unknown_ns_top_3": [],
        "update": 0,
        "update_ns_top_3": []
    },
    {
        "ddl": 0,
        "ddl_ns_top_3": [],
        "delete": 0,
        "delete_ns_top_3": [],
        "error": 0,
        "error_ns_top_3": [],
        "id": 4,
        "insert": 0,
        "insert_ns_top_3": [],
        "unknown": 0,
        "unknown_ns_top_3": [],
        "update": 0,
        "update_ns_top_3": []
    },
    {
        "ddl": 0,
        "ddl_ns_top_3": [],
        "delete": 0,
        "delete_ns_top_3": [],
        "error": 0,
        "error_ns_top_3": [],
        "id": 5,
        "insert": 0,
        "insert_ns_top_3": [],
        "unknown": 0,
        "unknown_ns_top_3": [],
        "update": 0,
        "update_ns_top_3": []
    },
    {
        "ddl": 0,
        "ddl_ns_top_3": [],
        "delete": 3,
        "delete_ns_top_3": [
            {
                "Key": " ",
                "Val": 3
            }
        ],
        "error": 0,
        "error_ns_top_3": [],
        "id": 6,
        "insert": 2120,
        "insert_ns_top_3": [
            {
                "Key": " ",
                "Val": 1171
            },
            {
                "Key": " ",
                "Val": 949
            }
        ],
        "unknown": 0,
        "unknown_ns_top_3": [],
        "update": 67713,
        "update_ns_top_3": [
            {
                "Key": " ",
                "Val": 65236
            },
            {
                "Key": " ",
                "Val": 2477
            }
        ]
    },
    {
        "ddl": 0,
        "ddl_ns_top_3": [],
        "delete": 0,
        "delete_ns_top_3": [],
        "error": 0,
        "error_ns_top_3": [],
        "id": 7,
        "insert": 967,
        "insert_ns_top_3": [
            {
                "Key": " ",
                "Val": 967
            }
        ],
        "unknown": 0,
        "unknown_ns_top_3": [],
        "update": 0,
        "update_ns_top_3": []
    }
]

**Comment by zhangst** [comment]
同步实例有唯一索引，增量只能采用的collection hash的方式把oplog分发给worker，创建的8个worker只有3个在工作，所以增量中的表不多，只有限几个?
其中一个wokrer的jobs_in_queue队列已经满了，这个一般是写入目的DB慢导致的阻塞，因为oplog的写入有顺序要求，只要有一个worker慢就会拖累整体oplog的回放速度。

从你的截图看，有的都快到1秒了，不知道是什么维度统计的，可以要想办法对目的DB做个调优，让目的DB的写入变快，看下效果。

**Comment by Echo-19** [comment]
是的，只有几个表有更新。
截图里面是用mongotop统计的，1s内花在这个表上某个操作的总耗时，看到主要第一个表更新最频繁，时延通过db.serverStatus()，看opcounters字段各个操作的均值在700us左右，节点上慢查询是100ms，目前目标主节点上没有慢查询。从目标实例上看写入时延不高。
![image](https://user-images.githubusercontent.com/69190440/196426800-13f44ce9-4a0d-41fa-ad1c-edd472a31b58.png)

请教一下，单个worker上的队列满了，是由于单表有唯一索引并且存在增量流量倾斜导致的吗？

**Comment by zhangst** [comment]
是的，有唯一索引时，会采用collection name的方式来做hash，没有唯一索引时会用_id来做hash。
这里的hash是指，把oplog路由到哪个worker队列中。
相同collection的oplog都会路由到一个worker队列中

**Comment by Echo-19** [comment]
好的，感谢。后面尝试将流量倾斜的表分片看看效果。
