### ISSUE TITLE
checkpoint.storage.url 配置失效

### ISSUE THREAD

**Issue by loulech** [alibaba/MongoShake#727]
mongoshake.version: 2.6.6
src.mongo.version: 4.2.17
conf: `conf.version = 10
id = mongoshake-a
master_quorum = false
full_sync.http_port = 9301
incr_sync.http_port = 9300
system_profile_port = 9302
log.level = error
log.dir = /data/logs
log.file = collector-a.log
log.flush = false
sync_mode = incr
mongo_urls = mongodb://abc:abc@shard.201:27017/?authSource=admin;mongodb://abc:abc@shard.202:27017/?authSource=admin;mongodb://abc:abc@shard.203:27017/?authSource=admin;
mongo_cs_url = mongodb://abc:abc@shard.200:4001/?authSource=admin
mongo_s_url = mongodb://abc:abc@master.200:27017/?authSource=admin
mongo_ssl_root_ca_file = 
tunnel = kafka
tunnel.address = topic@kafka:port
tunnel.message = bson
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =
mongo_connect_mode = secondaryPreferred
filter.namespace.black =
filter.namespace.white = a.item
filter.pass.special.db =
filter.ddl_enable = false
filter.oplog.gids = false
checkpoint.storage.url = mongodb://abc:abc@ckpt:27017/?authSource=admin
checkpoint.storage.db = stg_mongoshake_kafka
checkpoint.storage.collection = stg_omdmain_mongo_kafka
checkpoint.storage.url.mongo_ssl_root_ca_file = 
checkpoint.start_position = 2022-05-25T00:00:00Z
transform.namespace =
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.parallel_thread = 1
full_sync.reader.parallel_index = _id
full_sync.collection_exist_drop = true
full_sync.create_index = none
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false
incr_sync.mongo_fetch_method = change_stream
incr_sync.change_stream.watch_full_document = false
incr_sync.oplog.gids =
incr_sync.shard_key = id
incr_sync.shard_by_object_id_whitelist = 
incr_sync.worker = 8
incr_sync.tunnel.write_thread = 0
incr_sync.target_delay = 0
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256
incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false
special.source.db.flag =
`
checkpoint.storage.url 运行后数据如下, ckpt未更新:
![image](https://user-images.githubusercontent.com/9553099/172088754-96d7a7c2-e2a5-4a9e-9174-ab0487726822.png)

mongo_s_url中ckpt更新:
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/9553099/172088846-cf4f024f-c46f-4cb2-b42b-c31f42a9aa7b.png">

**Comment by zhangst** [comment]
请使用2.7.X版本试一下

**Comment by loulech** [comment]
收到, 暂时不需要这个feature了, 多谢
