### ISSUE TITLE
增量同步一些历史数据时程序卡住

### ISSUE THREAD

**Issue by MartinPeng01** [alibaba/MongoShake#728]
mongoshake version 2.6.6
mongodb version 4.4.12
现象：
1. 正常同步n天
2. 由于网络原因同步停止1天
3. 重新启动同步程序卡住merge部分
4. 重启后恢复正常
PS：重新启动后同步会占用大量内存及cpu，同步完成之后不会释放，重启后正常。
![lQLPJxZibA9UW4x1zQiusM1VK7QF84KqAqJSMtPA-AA_2222_117](https://user-images.githubusercontent.com/107113673/172749396-db6056ed-585b-4b8a-bbcc-2cb52b28ec8f.png)

**Comment by zhangst** [comment]
只有一张截图看不出来问题。网络问题是源MongoDB还是目的MongoDB的网络有问题？

**Comment by MartinPeng01** [comment]
> 只有一张截图看不出来问题。网络问题是源MongoDB还是目的MongoDB的网络有问题？

目的mongoDB的问题，2是预期中的，和mongoshake没有关系。

**Comment by lenovore** [comment]
> > 只有一张截图看不出来问题。网络问题是源MongoDB还是目的MongoDB的网络有问题？
> 
> 目的mongoDB的问题，2是预期中的，和mongoshake没有关系。

能说明下是目的mongodb的什么原因导致的嘛，也遇到这个情况？
