### ISSUE TITLE
docker启动mongoshake,偶尔程序会hang住

### ISSUE THREAD

**Issue by q102137601** [alibaba/MongoShake#731]
我们在一台机器上使用docker启动了多个mongoshake容器，有时docker重启时，原有的docker不能被正常的stop，kill -9都不能杀死进程。
只能杀死父进程使其成为僵尸进程，最终只能重启宿主机解决。

mongoshake版本2.6.6
原mongo库与目标mongo库 皆为4.4.12

具体现象：
![image](https://user-images.githubusercontent.com/43600528/174222501-e587b4a2-26a4-451e-901b-76c706490751.png)
![image](https://user-images.githubusercontent.com/43600528/174222590-96c549ac-2b8b-48d4-bc72-6ae580268a2b.png)

mongoshake配置如下：
![image](https://user-images.githubusercontent.com/43600528/174222076-35a4f2f6-0cec-47a1-b482-461dfddb059c.png)

单个容器的配置为：
![image](https://user-images.githubusercontent.com/43600528/174222296-9c7117c2-e714-40b1-b90a-02c8b64ee954.png)

该问题有可能是因为docker做了资源限制，应用本身还在不断的申请资源，导致程序僵住
![image](https://user-images.githubusercontent.com/43600528/174223351-90a12b9b-be85-4895-818b-3458b1884d29.png)

**Comment by zhangst** [comment]
这个要排查docker环境的问题。
