### ISSUE TITLE
2.7.4 don't support ExitPoint bug

### ISSUE THREAD

**Issue by happysheep1** [alibaba/MongoShake#733]
post data like curl -X POST --data '{"ExitPoint": 1655782500,"TPS":5000} 127.0.0.1:9111/sentinel/options

stdout will show like these
exitPoint[{0 1655782500}] < lastOplog.Timestamp[{1654560905 1}]
exitPoint[{0 1655782500}] < current.Timestamp[{1654555400 10}]

it will need to change batcher.go:50 to utils.TimeToTimestamp

**Comment by zhangst** [comment]
ExitPoint is full formate primitive.Timestamp, which is combine by {T uint32,I uint32}, so  try to use 1655782500 << 32 + i, i means ordinal in oplog.ts
