### ISSUE TITLE
源mongodb mongodb.opcounters.getmore飙升

### ISSUE THREAD

**Issue by tangbing2014** [alibaba/MongoShake#734]
mongoshake版本为2.7.4
源数据为副本集mongo
qps直接涨了1200

**Comment by zhangst** [comment]
请详细描述下问题是什么

**Comment by tangbing2014** [comment]
mongoshake版本为2.7.4
源mongo版本4.0.0 副本集
启动mongoshake后源mongo的secondary QPS提升，公司物联系统重度依赖mongodb数据，导致数据无法从mongodb中查出，数据插入正常（primary节点正常），其它指标例如内存、cpu等都正常。
截图为secondary节点
![Image_20220627103823](https://user-images.githubusercontent.com/8262388/175849718-bb3ff963-a266-4043-a53d-2961b5a195a4.png)

**Comment by zhangst** [comment]
全量同步是要全表扫描拉取全量数据的，这个his必要的。建议把业务和shake的访问的mongo节点独立分开。
另外shake可以调整表的并行个数，来减少并发度。
