### ISSUE TITLE
mongoshake tries to sync views and fails

### ISSUE THREAD

**Issue by deveshk0** [alibaba/MongoShake#735]
After changes to mongo drivers, mongoshake tries to  sync view and fails, I guess we need to update list collection to 
`ListCollectionNames(nil, bson.M{"type": "collection"})`

**Comment by zhangst** [comment]
Are you referring to the "view" in this link? mongodb.com/docs/manual/core/views/

**Comment by deveshk0** [comment]
yes, if we don't pass `bson.M{"type": "collection"}` to listCollectionNames, view will be listed in output. We should add this filter to restrict to collectionNames only
