### ISSUE TITLE
mongodb4.0版本集群同步到kafka问题[EROR] Syncer[mongos] change_stream internal error: client[mongodb://xxx:xxx@xxx:8635,xxx:8635,xxx:8635] create change stream handler failed[(ReadConcernMajorityNotEnabled) Storage engine does not support read concern: { readConcern: { level: "majority" } }]

### ISSUE THREAD

**Issue by zj198456** [alibaba/MongoShake#736]
mongoshake源端为mongo集群，目的地端为kafka，fetch方式为incr_sync.mongo_fetch_method = change_stream
启动mongoshake报这个错，帮看下
[EROR] Syncer[mongos] change_stream internal error: client[mongodb://xxx:xxx@xxx:8635,xxx:8635,xxx:8635] create change stream handler failed[(ReadConcernMajorityNotEnabled) Storage engine does not support read concern: { readConcern: { level: "majority" } }]

**Comment by zhangst** [comment]
这报错提示很明白，源mongo的ReadConcernMajority没有开启
[(ReadConcernMajorityNotEnabled) Storage engine does not support read concern: { readConcern: { level: "majority" } }]

**Comment by zj198456** [comment]
好的。但是因为限制，如果源端没发更改readConcern时，请问mongoshake的change_stream方式是否支持指定readConcern为local呢？
