### ISSUE TITLE
在没有开启gid的mongodb里，可否用文档内的一个属性充当gid的作用？

### ISSUE THREAD

**Issue by cwt9562** [alibaba/MongoShake#737]
比如我往json里添加一个叫gid的属性
```
{
    "_id" : ObjectId("61e918e2e138237349ece23b"),
    "@timestamp" : "\"2022-01-20T08:10:08.008Z\"",
    "gid" : "123",
    ...
}
```
然后可以在mongoshake里添加一个配置，将这个gid当做你们原先在mongo内核里添加的gid那样来使用么？

**Comment by zhangst** [comment]
不可以的，gid不是一个业务字段，这样加是业务字段

**Comment by cwt9562** [comment]
我想法的gid，不是一个业务字段
它和_id、@timestamp一样，是固有字段
并不是可以随意设定值的

**Comment by cwt9562** [comment]
比如，现在有A、B两个mongodb库
程序往A库里insert或update数据时，gid固定为“A”
程序往B库里insert或update数据时，gid固定为“B”
效果和改mongo内核达到的效果是一样的

**Comment by cwt9562** [comment]
如果需要，这个字段也可以叫 “_gid”

**Comment by zhangst** [comment]
你可以试一下
