### ISSUE TITLE
MongoShake gridfs utility

### ISSUE THREAD

**Issue by vineelyalamarthy** [alibaba/MongoShake#744]
Gridfs lets us use files in MongoDB. Files meta data stored in files collection and corresponding data in chunks collection. So moving files from one Mongo deployment to another should be done very carefully otherwise we lose integrity of data. I mean lets say

1. one of the chunks is missed while transferring. 
OR 
2. Chunks got transferred but their corresponding file record didn't get transferred leaving orphaned chunks. 

What extra care does MongoShake take to ensure data integrity?

**Comment by zhangst** [comment]
Hi,
We have a script which can do something in data integrity. And if MongoShake can't handle some situation, it will exit with an error.
https://github.com/alibaba/MongoShake/blob/develop/scripts/comparison.py
