### ISSUE TITLE
增量报错checkpoint failed

### ISSUE THREAD

**Issue by MrGYuan** [alibaba/MongoShake#748]
MongoDB 3.2 分片集群到5.0.9分片集群，用root账号全部同步完成后，执行增量报错run replication failed: select sync mode failed: get mongod[7405] checkpoint failed: get by checkpoint manager[] failed  版本2.7.1

logs:
[2022/08/22 10:24:27 CST] [WARN] 7405 Reload ckpt find context fail. Majority read concern requested, but server was not started with --enableMajorityReadConcern.
[2022/08/22 10:24:27 CST] [CRIT] run replication failed: select sync mode failed: get mongod[7405] checkpoint failed: get by checkpoint manager[] failed
[2022/08/22 10:24:27 CST] [WARN]
                ##### | #####
Oh we finish ? # _ _ #|# _ _ #
               #      |      #
         |       ############
                     # #
  |                  # #
                    #   #
         |     |    #   #      |        |
  |  |             #     #               |
         | |   |   # .-. #         |
                   #( O )#    |    |     |
  |  ################. .###############  |
   ##  _ _|____|     ###     |_ __| _  ##
  #  |                                |  #
  #  |    |    |    |   |    |    |   |  #
   ######################################
                   #     #
                    #####

**Comment by zhangst** [comment]
参考下面连接补充下内容：https://github.com/alibaba/MongoShake/issues/700

**Comment by MrGYuan** [comment]
1

**Comment by woshiyigeshuaige** [comment]
你好，我也遇到同样的问题了，请问一下怎么解决的，我的mongshake版本是2.8.2  4.3的分片——>>4.0的副本集

**Comment by zhangst** [comment]
checkpoint.storage.url = 
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default

这三个参数配置上试试

**Comment by woshiyigeshuaige** [comment]
> 
mongshake2.8.2版本中这三个参数已经自带了，3.4.24的分片集群——全量+增量同步到>>4.0的副本集
分片配置文件如下：
dbpath=/data/mongo1/db_shard1
logpath=/data/mongo1/logs/shard1_27017.log
pidfilepath=/data/mongo1/db_shard1/shard1.pid
directoryperdb=true
port=27017
logappend=true
noprealloc=true
fork=true
maxConns=20000
oplogSize=10240
wiredTigerCacheSizeGB=5
shardsvr=true
replSet=shard1
bind_ip=x.x.x.x
 auth=true
 keyFile=/usr/local/mongodb34/KeyFile.file
# 分片集群和副本集用的同一个KeyFile.file

**Comment by zhangst** [comment]
checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
这个三个参数有配置值吗？完成的配置文件发一下

**Comment by woshiyigeshuaige** [comment]
> checkpoint.storage.url = checkpoint.storage.db = mongoshake checkpoint.storage.collection = ckpt_default 这个三个参数有配置值吗？完成的配置文件发一下
这个就是mongoshake的配置文件，这是在测试环境同一台上搭建的，跟生产一样的配置，一样的报错，
conf.version = 10
id = mongoshake
master_quorum = false
full_sync.http_port = 9101
incr_sync.http_port = 9100
system_profile_port = 9200
log.level = info
log.dir =
log.file = collector.log
log.flush = false
sync_mode = all
mongo_urls = mongodb://mongoshake:123456@192.168.00.60:27017,192.168.00.60:28017;mongodb://mongoshake:123456@192.168.00.60:27018,192.168.00.60:28018
mongo_cs_url =mongodb://mongoshake:123456@192.168.00.60:27100,192.168.00.60:27200,192.168.00.60:27300
mongo_s_url = mongodb://mongoshake:123456@192.168.00.60:28100,192.168.00.60:28200,192.168.00.60:28300
mongo_ssl_root_ca_file = 
tunnel = direct
tunnel.address = mongodb://mongoshake:123456@192.168.00.40:27017,192.168.00.40:27018,192.168.00.40:27019
tunnel.message = raw
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =
mongo_connect_mode = secondaryPreferred
filter.namespace.black =
filter.namespace.white = data.renzhengji;data.zips02
filter.pass.special.db =
filter.ddl_enable = false
filter.oplog.gids = false
checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.storage.url.mongo_ssl_root_ca_file = 
checkpoint.start_position = 1970-01-01T00:00:00Z
transform.namespace =
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.fetch_batch_size = 8192
full_sync.reader.parallel_thread = 1
full_sync.reader.parallel_index = _id
full_sync.collection_exist_drop = true
full_sync.create_index = none
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false
incr_sync.mongo_fetch_method = oplog
incr_sync.change_stream.watch_full_document = false
incr_sync.oplog.gids =
incr_sync.shard_key = collection
incr_sync.shard_by_object_id_whitelist = 
incr_sync.worker = 8
incr_sync.tunnel.write_thread = 8
incr_sync.target_delay = 0
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256
incr_sync.reader.fetch_batch_size = 8192
incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false
special.source.db.flag =


###配置分片的时候，分片节点的制裁节点没有加到分片里：
  shards:
        {  "_id" : "shard1",  "host" : "shard1/192.168.00.60:27017,192.168.00.60:28017",  "state" : 1 }
        {  "_id" : "shard2",  "host" : "shard2/192.168.00.60:27018,192.168.00.60:28018",  "state" : 1 }




麻烦大佬帮忙看看了，感谢感谢

**Comment by zhangst** [comment]
checkpoint.storage.url =
这个是空的，这里需要配置一个mongodb的地址。复用tunnel.address的地址试一下。

**Comment by woshiyigeshuaige** [comment]
> checkpoint.storage.url = 这个是空的，这里需要配置一个mongodb的地址。复用tunnel.address的地址试一下。

将tunnel.address的地址复制到checkpoint.storage.url = 后，启动都没反应了，日志也没有输出了。

**Comment by woshiyigeshuaige** [comment]
> checkpoint.storage.url = 这个是空的，这里需要配置一个mongodb的地址。复用tunnel.address的地址试一下。

将tunnel.address的地址复制到checkpoint.storage.url = 后，启动都没反应了，日志也没有输出了。

**Comment by zhangst** [comment]
> > checkpoint.storage.url = 这个是空的，这里需要配置一个mongodb的地址。复用tunnel.address的地址试一下。
> 
> 将tunnel.address的地址复制到checkpoint.storage.url = 后，启动都没反应了，日志也没有输出了。

目的是一个分片集群。有没有测试的副本集，把这个副本集的地址填到checkpoint.storage.url = 试试，要保证有写入的权限

**Comment by woshiyigeshuaige** [comment]
意思是将现在的3.4分片>副本集，变为3.4副本集>副本集吗？

**Comment by zhangst** [comment]
> 
不是的，迁移源和目的保留原来的。
checkpoint.storage.url = 这个地址是用来存储位点信息的，需要一个副本集的地址

**Comment by woshiyigeshuaige** [comment]
# 源端分片
mongodb://mongoshake:123456@192.168.00.60:27017,192.168.00.60:28017;mongodb://mongoshake:123456@192.168.00.60:27018,192.168.00.60:28018
mongo_cs_url =mongodb://mongoshake:123456@192.168.00.60:27100,192.168.00.60:27200,192.168.00.60:27300
mongo_s_url = mongodb://mongoshake:123456@192.168.00.60:28100,192.168.00.60:28200,192.168.00.60:28300

# 目标段副本集
tunnel.address = mongodb://mongoshake:123456@192.168.00.40:27017,192.168.00.40:27018,192.168.00.40:27019

# 同步指定的集合
filter.namespace.white = data.zips01;data.zips02

# 用目标端来存储位点信息
checkpoint.storage.url = mongodb://mongoshake:123456@192.168.00.40:27017,192.168.00.40:27018,192.168.00.40:27019  

刚刚就是这样，启动了没反应，日志都没输出

**Comment by zhangst** [comment]
如果是这样，可能是地址连不上。建议用mongoshell测试下上面的地址，看能否正常连上，是否有写入的权限。

**Comment by woshiyigeshuaige** [comment]
可以了，跑起来了，暂时看着没问题了，谢谢大佬。
