### ISSUE TITLE
2.8版本，分片集群all同步只会同步数据结构不同步数据

### ISSUE THREAD

**Issue by MrGYuan** [alibaba/MongoShake#749]
MongoDB 3.2 分片集群到5.0.9分片集群，账号密码已验证没有问题，coller配置在版本2.7.1可进行全量同步，2.8版本只能同步库表结构，并无任何异常报错信息

logs:
[2022/08/18 17:17:13 CST] [INFO] metric[name[mongos] stage[full]] exit
[2022/08/18 17:17:13 CST] [INFO] document syncer sync end
[2022/08/18 17:17:13 CST] [INFO] Close client with mongodb://root:***@*****************************
[2022/08/18 17:17:13 CST] [WARN]
                ##### | #####
Oh we finish ? # _ _ #|# _ _ #
               #      |      #
         |       ############
                     # #
  |                  # #
                    #   #
         |     |    #   #      |        |
  |  |             #     #               |
         | |   |   # .-. #         |
                   #( O )#    |    |     |
  |  ################. .###############  |
   ##  _ _|____|     ###     |_ __| _  ##
  #  |                                |  #
  #  |    |    |    |   |    |    |   |  #
   ######################################
                   #     #
                    #####

**Comment by zhangst** [comment]
参考下面连接补充下内容：https://github.com/alibaba/MongoShake/issues/700
