### ISSUE TITLE
Mongoshake全量同步正常进入增量模式，正常运行2个月后，源端数据库增加索引和源端实例增加新库不能同步到目的端，需要做什么操作

### ISSUE THREAD

**Issue by uilmas** [alibaba/MongoShake#751]
1 Mongoshake版本为：develop,2f31ff91b5aa5e548e88dfefcf8021e1eeb08aba,release,go1.11.5,2020-06-06_06:26:50

2 源MongoDB版本:
MongoDB shell version v4.4.1
Build Info: {
"version": "4.4.1",
"gitVersion": "ad91a93a5a31e175f5cbf8c69561e788bbc55ce1",
"openSSLVersion": "OpenSSL 1.1.1 11 Sep 2018",
"modules": [],
"allocator": "tcmalloc",
"environment": {
"distmod": "ubuntu1804",
"distarch": "x86_64",
"target_arch": "x86_64"
}
}
3 目的MongoDB版本：
MongoDB shell version v4.0.28-rc0
git version: af1a9dc12adcfa83cc19571cb3faba26eeddac92
OpenSSL version: OpenSSL 1.0.2g 1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
distmod: ubuntu1604
distarch: x86_64
target_arch: x86_64

4 Mongoshake全量同步正常进入增量模式，正常运行2个月后，源端数据库增加索引和源端实例增加新库不能同步到目的端，需要做什么操作

**Comment by zhangst** [comment]
请用最新的2.8.0版本尝试下

**Comment by uilmas** [comment]
请用最新的2.8.0版本尝试下---- 更换版本时，需要重新再全量同步所有数据吗？

**Comment by uilmas** [comment]
我用全新的2.8.0版本确认已经全量同步完成所有数据后，目的端主机保持了9101,9100,9200三个端口的开启状态，但是我在源端实例主机上新增一个库 或 新增一些索引，发现并不能同步到目的端实例上，请您指教，是需要做什么操作吗？ 还是并未开发这个功能？源端和目的端都是MongoDB shell version v4.4.3，Mongoshake用最新的2.8版本

**Comment by zhangst** [comment]
filter.ddl_enable = true 确认下这个配置项是否已经开启，如果已开启未同步，打开debug日志看下是什么错误。
