### ISSUE TITLE
全量同步到一半，报错

### ISSUE THREAD

**Issue by xiaohuazi123** [alibaba/MongoShake#753]
MongoShake的版本 ：  2.8.0
源和目的MongoDB的版本： mongodb4.0
脱敏后的配置文件和日志
`[2022/09/07 17:22:13 CST] [INFO] Close client with mongodb://root:***@192.168.0.69:7888,192.168.0.63:7888,192.168.0.62:7888
[2022/09/07 17:22:13 CST] [INFO] Close client with mongodb://root:***@192.168.0.69:7888,192.168.0.63:7888,192.168.0.62:7888
[2022/09/07 17:22:13 CST] [INFO] Close client with mongodb://root:***@192.168.0.69:7888,192.168.0.63:7888,192.168.0.62:7888
[2022/09/07 17:22:13 CST] [INFO] Close client with mongodb://root:***@192.168.0.69:7888,192.168.0.63:7888,192.168.0.62:7888
panic: runtime error: index out of range [0] with length 0

goroutine 23942751 [running]:
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).doSync(0xc0005c8b70, 0xc002487000, 0x80, 0x80, 0x0, 0x0)
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:225 +0x16cd
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc0005c8b70)
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:169 +0xe6
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda
[root@mongodb-69 mongoshake]#
[root@mongodb-69 mongoshake]#

`

**Comment by zhangst** [comment]
这个是写入失败了，要在目的MongoDB上排查，看下目的MongoDb的CPU、写入压力之类的

**Comment by xiaohuazi123** [comment]
源库是mongo3.6，目标库是mongo4.0

**Comment by xiaohuazi123** [comment]
目的MongoDb的CPU、写入压力，都很正常，没有压力

**Comment by xiaohuazi123** [comment]
今天又重新同步了一次，这次报这个错误
`2022/09/08 13:05:47 CST] [INFO] [name=rpl, stage=full, get=1256837287, write_success=1256836605, tps=0]
[2022/09/08 13:05:47 CST] [INFO] Close client with mongodb://root:***@192.168.0.69:7888,192.168.0.63:7888,192.168.0.62:7888
panic: interface conversion: error is mongo.CommandError, not mongo.BulkWriteException

goroutine 18994390 [running]:
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).doSync(0xc000293710, 0xc00156a000, 0x80, 0x80, 0x0, 0x0)
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:225 +0x16ee
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc000293710)
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:169 +0xe6
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda
[root@dc-web1 mongoshake]# 
`

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/issues/700
参考这个提供下提供下配置文件和日志文件
