### ISSUE TITLE
2.8.0 全量同步时发生错误 panic: interface conversion: error is mongo.CommandError, not mongo.BulkWriteException

### ISSUE THREAD

**Issue by tank39133** [alibaba/MongoShake#754]
源版本：4.4.14  目标：4.4.10

Mongoshake 2.8.0

Logs:

[2022/09/07 23:46:06 CST] [INFO] [name=rs, stage=full, get=45587, write_success=45071, tps=0]                                        
[2022/09/07 23:46:11 CST] [INFO] [name=rs, stage=full, get=45587, write_success=45071, tps=0]
[2022/09/07 23:46:16 CST] [INFO] [name=rs, stage=full, get=45715, write_success=45199, tps=128]                                      
panic: interface conversion: error is mongo.CommandError, not mongo.BulkWriteException                                               
                                                                                                                                     
goroutine 5246 [running]:                                                                                                            
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).doSync(0xc00bb6dad0, 0xc000876000, 0x80, 0x80, 0xf22a00, 0xc0000a3300)
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:225 +0x16ee                       
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DocExecutor).start(0xc00bb6dad0)
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:169 +0xe6                                          
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*CollectionExecutor).Start
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_executor.go:84 +0xda                     

Config:

conf.version = 10
id = mongoshake
master_quorum = false
full_sync.http_port = 19101
incr_sync.http_port = 19100
system_profile_port = 19201

log.level = info
log.dir =
log.file = collector.log
log.flush = false
sync_mode = all

mongo_urls = mongodb://127.0.0.1:27017
mongo_cs_url =
mongo_s_url = 
mongo_ssl_root_ca_file = 

tunnel = direct
tunnel.address = mongodb://127.0.0.1:37017/admin?connect=direct
tunnel.message = raw
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =

mongo_connect_mode = standalone

filter.namespace.black =
filter.namespace.white =
filter.pass.special.db =
filter.ddl_enable = false
filter.oplog.gids = false

checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.storage.url.mongo_ssl_root_ca_file = 
checkpoint.start_position = 1970-01-01T00:00:00Z

transform.namespace =

full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.parallel_thread = 1
full_sync.reader.parallel_index = _id

full_sync.collection_exist_drop = true

full_sync.create_index = background

full_sync.executor.insert_on_dup_update = true
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false

incr_sync.mongo_fetch_method = oplog

incr_sync.change_stream.watch_full_document = false

incr_sync.oplog.gids =

incr_sync.shard_key = collection
incr_sync.shard_by_object_id_whitelist = 

incr_sync.worker = 8

incr_sync.tunnel.write_thread = 8

incr_sync.target_delay = 0

incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

incr_sync.executor.upsert = true
incr_sync.executor.insert_on_dup_update = true
incr_sync.conflict_write_to = none

incr_sync.executor.majority_enable = false

special.source.db.flag =

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/issues/700
参考提供下对应的日志和配置文件

**Comment by xiaohuazi123** [comment]
跟我的报错一样！

**Comment by yangxianjungree** [comment]
> 跟我的报错一样！

请问这个文档序列化有问题吗，咋解决的哈？

**Comment by xiaohuazi123** [comment]
> > 跟我的报错一样！
> 
> 请问这个文档序列化有问题吗，咋解决的哈？

最后没解决，这个问题解决不了，而且mongodb7.0官方已经推出了同步工具，可以单实例，副本集，分片集群之间同步，感觉mongoshake要淘汰了

**Comment by yangxianjungree** [comment]
> > > 跟我的报错一样！
> > 
> > 
> > 请问这个文档序列化有问题吗，咋解决的哈？
> 
> 最后没解决，这个问题解决不了，而且mongodb7.0官方已经推出了同步工具，可以单实例，副本集，分片集群之间同步，感觉mongoshake要淘汰了

可能是其他问题，要把错误打印出来具体分析。
我在mongoshake panic之前，加了一个错误类型判断，并把错误信息打印了出来，发现是目的端网络问题导致的
![image](https://github.com/alibaba/MongoShake/assets/28832754/0f0653fb-107d-4f40-aa75-6c5436052e59)
![image](https://github.com/alibaba/MongoShake/assets/28832754/da91a603-d8b7-411e-93f7-2a6420c9f994)

**Comment by xiaohuazi123** [comment]
> > > > 跟我的报错一样！
> > > 
> > > 
> > > 请问这个文档序列化有问题吗，咋解决的哈？
> > 
> > 
> > 最后没解决，这个问题解决不了，而且mongodb7.0官方已经推出了同步工具，可以单实例，副本集，分片集群之间同步，感觉mongoshake要淘汰了
> 
> 可能是其他问题，要把错误打印出来具体分析。 我在mongoshake panic之前，加了一个错误类型判断，并把错误信息打印了出来，发现是目的端网络问题导致的 ![image](https://private-user-images.githubusercontent.com/28832754/301378049-0f0653fb-107d-4f40-aa75-6c5436052e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzgwNDktMGYwNjUzZmItMTA3ZC00ZjQwLWFhNzUtNmM1NDM2MDUyZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNzJkYWMzMTg1MzE3ZTYwMDZmNDA5ZmE2NWU0ZjE2MTFlM2JiZDEzNGFiYjUwY2JlNWVkMjI4OTcxMjQzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPYSHSpaYDBuOMavoJyscCRdt43DhRU8tpsnMKJGce8) ![image](https://private-user-images.githubusercontent.com/28832754/301378460-da91a603-d8b7-411e-93f7-2a6420c9f994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzg0NjAtZGE5MWE2MDMtZDhiNy00MTFlLTkzZjctMmE2NDIwYzlmOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNmI0N2EzYThiNTdiZGU3MjE4ZThhOWU5ZjQ0YjQ2NDdjOGQ1OGNiMzJhOTA3ZDRmZWM5MDljYTI1M2MxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0tvjaz-r4NytQWQl0hnaXV3DUbSG4a_Lo_8J5eGoDI)

自己修改  mongoshake的源代码吗

**Comment by yangxianjungree** [comment]
> > > > > 跟我的报错一样！
> > > > 
> > > > 
> > > > 请问这个文档序列化有问题吗，咋解决的哈？
> > > 
> > > 
> > > 最后没解决，这个问题解决不了，而且mongodb7.0官方已经推出了同步工具，可以单实例，副本集，分片集群之间同步，感觉mongoshake要淘汰了
> > 
> > 
> > 可能是其他问题，要把错误打印出来具体分析。 我在mongoshake panic之前，加了一个错误类型判断，并把错误信息打印了出来，发现是目的端网络问题导致的 ![image](https://private-user-images.githubusercontent.com/28832754/301378049-0f0653fb-107d-4f40-aa75-6c5436052e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzgwNDktMGYwNjUzZmItMTA3ZC00ZjQwLWFhNzUtNmM1NDM2MDUyZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNzJkYWMzMTg1MzE3ZTYwMDZmNDA5ZmE2NWU0ZjE2MTFlM2JiZDEzNGFiYjUwY2JlNWVkMjI4OTcxMjQzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPYSHSpaYDBuOMavoJyscCRdt43DhRU8tpsnMKJGce8) ![image](https://private-user-images.githubusercontent.com/28832754/301378460-da91a603-d8b7-411e-93f7-2a6420c9f994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzg0NjAtZGE5MWE2MDMtZDhiNy00MTFlLTkzZjctMmE2NDIwYzlmOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNmI0N2EzYThiNTdiZGU3MjE4ZThhOWU5ZjQ0YjQ2NDdjOGQ1OGNiMzJhOTA3ZDRmZWM5MDljYTI1M2MxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0tvjaz-r4NytQWQl0hnaXV3DUbSG4a_Lo_8J5eGoDI)
> 
> 自己修改 mongoshake的源代码吗

嗯嗯。定位一下原因

**Comment by xiaohuazi123** [comment]
> > > > > > 跟我的报错一样！
> > > > > 
> > > > > 
> > > > > 请问这个文档序列化有问题吗，咋解决的哈？
> > > > 
> > > > 
> > > > 最后没解决，这个问题解决不了，而且mongodb7.0官方已经推出了同步工具，可以单实例，副本集，分片集群之间同步，感觉mongoshake要淘汰了
> > > 
> > > 
> > > 可能是其他问题，要把错误打印出来具体分析。 我在mongoshake panic之前，加了一个错误类型判断，并把错误信息打印了出来，发现是目的端网络问题导致的 ![image](https://private-user-images.githubusercontent.com/28832754/301378049-0f0653fb-107d-4f40-aa75-6c5436052e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzgwNDktMGYwNjUzZmItMTA3ZC00ZjQwLWFhNzUtNmM1NDM2MDUyZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNzJkYWMzMTg1MzE3ZTYwMDZmNDA5ZmE2NWU0ZjE2MTFlM2JiZDEzNGFiYjUwY2JlNWVkMjI4OTcxMjQzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPYSHSpaYDBuOMavoJyscCRdt43DhRU8tpsnMKJGce8) ![image](https://private-user-images.githubusercontent.com/28832754/301378460-da91a603-d8b7-411e-93f7-2a6420c9f994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzg0NjAtZGE5MWE2MDMtZDhiNy00MTFlLTkzZjctMmE2NDIwYzlmOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNmI0N2EzYThiNTdiZGU3MjE4ZThhOWU5ZjQ0YjQ2NDdjOGQ1OGNiMzJhOTA3ZDRmZWM5MDljYTI1M2MxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0tvjaz-r4NytQWQl0hnaXV3DUbSG4a_Lo_8J5eGoDI)
> > 
> > 
> > 自己修改 mongoshake的源代码吗
> 
> 嗯嗯。定位一下原因

可以，不过官方在mongo7.0推出同步工具了，感觉自己修补mongoshake代码意义也不大了

**Comment by yangxianjungree** [comment]
> > > > > > > 跟我的报错一样！
> > > > > > 
> > > > > > 
> > > > > > 请问这个文档序列化有问题吗，咋解决的哈？
> > > > > 
> > > > > 
> > > > > 最后没解决，这个问题解决不了，而且mongodb7.0官方已经推出了同步工具，可以单实例，副本集，分片集群之间同步，感觉mongoshake要淘汰了
> > > > 
> > > > 
> > > > 可能是其他问题，要把错误打印出来具体分析。 我在mongoshake panic之前，加了一个错误类型判断，并把错误信息打印了出来，发现是目的端网络问题导致的 ![image](https://private-user-images.githubusercontent.com/28832754/301378049-0f0653fb-107d-4f40-aa75-6c5436052e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzgwNDktMGYwNjUzZmItMTA3ZC00ZjQwLWFhNzUtNmM1NDM2MDUyZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNzJkYWMzMTg1MzE3ZTYwMDZmNDA5ZmE2NWU0ZjE2MTFlM2JiZDEzNGFiYjUwY2JlNWVkMjI4OTcxMjQzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPYSHSpaYDBuOMavoJyscCRdt43DhRU8tpsnMKJGce8) ![image](https://private-user-images.githubusercontent.com/28832754/301378460-da91a603-d8b7-411e-93f7-2a6420c9f994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzg0NjAtZGE5MWE2MDMtZDhiNy00MTFlLTkzZjctMmE2NDIwYzlmOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNmI0N2EzYThiNTdiZGU3MjE4ZThhOWU5ZjQ0YjQ2NDdjOGQ1OGNiMzJhOTA3ZDRmZWM5MDljYTI1M2MxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0tvjaz-r4NytQWQl0hnaXV3DUbSG4a_Lo_8J5eGoDI)
> > > 
> > > 
> > > 自己修改 mongoshake的源代码吗
> > 
> > 
> > 嗯嗯。定位一下原因
> 
> 可以，不过官方在mongo7.0推出同步工具了，感觉自己修补mongoshake代码意义也不大了

只看到二进制啊，代码没有开源吧，没找到。这样出问题都只能干等着

**Comment by xiaohuazi123** [comment]
> > > > > > > > 跟我的报错一样！
> > > > > > > 
> > > > > > > 
> > > > > > > 请问这个文档序列化有问题吗，咋解决的哈？
> > > > > > 
> > > > > > 
> > > > > > 最后没解决，这个问题解决不了，而且mongodb7.0官方已经推出了同步工具，可以单实例，副本集，分片集群之间同步，感觉mongoshake要淘汰了
> > > > > 
> > > > > 
> > > > > 可能是其他问题，要把错误打印出来具体分析。 我在mongoshake panic之前，加了一个错误类型判断，并把错误信息打印了出来，发现是目的端网络问题导致的 ![image](https://private-user-images.githubusercontent.com/28832754/301378049-0f0653fb-107d-4f40-aa75-6c5436052e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzgwNDktMGYwNjUzZmItMTA3ZC00ZjQwLWFhNzUtNmM1NDM2MDUyZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNzJkYWMzMTg1MzE3ZTYwMDZmNDA5ZmE2NWU0ZjE2MTFlM2JiZDEzNGFiYjUwY2JlNWVkMjI4OTcxMjQzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPYSHSpaYDBuOMavoJyscCRdt43DhRU8tpsnMKJGce8) ![image](https://private-user-images.githubusercontent.com/28832754/301378460-da91a603-d8b7-411e-93f7-2a6420c9f994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjAxOTgsIm5iZiI6MTcwNjc1OTg5OCwicGF0aCI6Ii8yODgzMjc1NC8zMDEzNzg0NjAtZGE5MWE2MDMtZDhiNy00MTFlLTkzZjctMmE2NDIwYzlmOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAzNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNmI0N2EzYThiNTdiZGU3MjE4ZThhOWU5ZjQ0YjQ2NDdjOGQ1OGNiMzJhOTA3ZDRmZWM5MDljYTI1M2MxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0tvjaz-r4NytQWQl0hnaXV3DUbSG4a_Lo_8J5eGoDI)
> > > > 
> > > > 
> > > > 自己修改 mongoshake的源代码吗
> > > 
> > > 
> > > 嗯嗯。定位一下原因
> > 
> > 
> > 可以，不过官方在mongo7.0推出同步工具了，感觉自己修补mongoshake代码意义也不大了
> 
> 只看到二进制啊，代码没有开源吧，没找到。这样出问题都只能干等着

可能暂时没开源吧，毕竟官方出品必属正品/精品
