### ISSUE TITLE
mongoshake是否支持单个集合一次性全量抽取发送到kafka？

### ISSUE THREAD

**Issue by dbcmp** [alibaba/MongoShake#756]
mongoshake2.8.0
源：mongodb4.2.15分片集群
目标：kafka
您好，目前有场景需要实现单个集合全量一次性同步到kafka（oplog增量同步另外起进程同步），当前mongoshake版本是否支持，如何配置？不支持的话后续可否支持？

**Comment by zhangst** [comment]
目前还不支持
