### ISSUE TITLE
v2.8.0跳过全量阶段直接进入增量阶段

### ISSUE THREAD

**Issue by xiaohuazi123** [alibaba/MongoShake#759]
MongoShake的版本：v2.8.0
源和目的MongoDB的版本：源是MongoDB  v3.6.21 ； 目的是MongoDB  v4.0.28
配置文件的模式是：all
```
cat /root/mongoshake/collector.conf |grep mode
# sync mode: all/full/incr. default is incr.
sync_mode = all
```
整个mongo实例是200GB大小
![QQ截图20220920154455](https://user-images.githubusercontent.com/45115671/191199976-7b9fd39d-6b9b-46a0-9e8d-cd52e43db9e1.png)

看日志，一开始就是增量阶段
![QQ截图20220920154326](https://user-images.githubusercontent.com/45115671/191200467-39945603-41a1-4c1f-a5bf-4ad13a10e8eb.png)

目标是全新安装的mongo实例，请确定是否是bug
![QQ截图20220920155630](https://user-images.githubusercontent.com/45115671/191200671-90655980-153d-4972-96f9-0138d929d211.png)

**Comment by xiaohuazi123** [comment]
还有一个，日志里是没有这句话的
[INFO] (mongoshake/collector.(*ReplicationCoordinator).Run:80) finish full sync, start incr sync with timestamp:

**Comment by xiaohuazi123** [comment]
要指定 sync_mode =full才行
![Uploading QQ截图20220920163640.png…]()

**Comment by xiaohuazi123** [comment]
bug真他吗多，阿里妈妈
![Uploading QQ截图20220920164209.png…]()

**Comment by zhangst** [comment]
建议别用了，白嫖还没口德
