### ISSUE TITLE
请问MongoShake是否能够使用代理（proxy）

### ISSUE THREAD

**Issue by tinkertian** [alibaba/MongoShake#760]
`export ALL_PROXY=socks5://127.0.0.1:1080`

像上面这个系统代理配置，MongoShake会如何处理？
如果希望MongoShake通过代理连接一个目标数据库该如何做呢？

**Comment by zhangst** [comment]
通过standalone的方式试一下，shake不识别网络的，应用程序怎么连，shake使用相同的机制。

**Comment by tinkertian** [comment]
好的，感谢解答！
