### ISSUE TITLE
v2.8.1 全量同步后目标端会自动分片

### ISSUE THREAD

**Issue by xanawang** [alibaba/MongoShake#761]
源端4.2.10分片集群 目的端4.4.16分片集群
sync_mode = all 且 full_sync.create_index = none执行后发现目的端同步的库自动生成了分片片键和启用分片，请问这个是新特性吗，目的端提前设置分片片键则会导致shake无法创建片键而退出
附上配置文件
[collector.txt](https://github.com/alibaba/MongoShake/files/9670310/collector.txt)

**Comment by zhangst** [comment]
对，这是一个特性，这个特性目前还不支持开关。建议使用shake创建的分片键，如果要手工设置，可以这这段这注释掉，自己改一个版本
