### ISSUE TITLE
comparison脚本使用问题

### ISSUE THREAD

**Issue by xyshanren** [alibaba/MongoShake#762]
文档中并没有comparison脚本的使用说明，在使用脚本时发现有对象无法调用，具体情况如下；

mongoshake版本：release-v2.8.0-20220720，release-v2.8.1-20220922
Python版本：Python 3.10.6

报错信息：
root@30aec69a20b8:~/mongoshake# python3 ./comparison.py --src="dds-xxxxx.mongodb.rds.aliyuncs.com:3717" --dest="dds-xxxxx.mongodb.rds.aliyuncs.com:3717" --count=10000 --excludeDbs=admin --excludeCollections=system.profile --comparisonMode=sample                                               sample
INFO  [2022-10-11 05:02:10] Configuration [sample=True, count=10000, excludeDbs=['admin', 'admin', 'local'], excludeColls=['system.profile', 'system.profile']]
[src = dds-xxxxxx.mongodb.rds.aliyuncs.com:3717]
[dst = dds-xxxxx.mongodb.rds.aliyuncs.com:3717]
Traceback (most recent call last):
  File "/root/mongoshake/./comparison.py", line 250, in <module>
    if check(src, dst):
  File "/root/mongoshake/./comparison.py", line 59, in check
    srcDbNames = src.conn.database_names()
TypeError: 'Database' object is not callable

root@30aec69a20b8:~/mongoshake# python3 ./comparison.py --src="dds-xxxxx.mongodb.rds.aliyuncs.com:3717" --dest="dds-xxxxx.mongodb.rds.aliyuncs.com:3717" --count=10000 --excludeDbs=lsd --excludeCollections=lsd.lsd1 --comparisonMode=sample
sample
INFO  [2022-10-11 05:23:22] Configuration [sample=True, count=10000, excludeDbs=['lsd', 'admin', 'local'], excludeColls=['lsd.lsd1', 'system.profile']]
[src = dds-xxxxx.mongodb.rds.aliyuncs.com:3717]
[dst = dds-xxxxxx.mongodb.rds.aliyuncs.com:3717]
Traceback (most recent call last):
  File "/root/mongoshake/./comparison.py", line 250, in <module>
    if check(src, dst):
  File "/root/mongoshake/./comparison.py", line 59, in check
    srcDbNames = src.conn.database_names()
TypeError: 'Database' object is not callable

**Comment by zhangst** [comment]
用mongoshell在这台机器上试下，能否正确的访问这两个dds-开头的mongo地址。这个看上去是访问Mongo失败了

**Comment by xyshanren** [comment]
> 用mongoshell在这台机器上试下，能否正确的访问这两个dds-开头的mongo地址。这个看上去是访问Mongo失败了

在做校验前在这个机器上做过全量迁移，相同的ecs、源和目标；

**Comment by xyshanren** [comment]
![lQLPJxbEh23iTanNAq_NBjCwd1xJOCSZUZYDQw834sD7AA_1584_687](https://user-images.githubusercontent.com/49270615/195197266-3a0e19da-9553-423e-985c-be38b8d84d84.png)

补充截图

**Comment by zhangst** [comment]
用户名和密码加上试一下？

**Comment by xyshanren** [comment]
> 用户名和密码加上试一下？

可以给个例子吗？
这种传入user pwd的方法应该是无法识别，是传入格式有问题还是Python版本有问题导致无法识别？：
--src="user:pwd@dds-xxxxx.mongodb.rds.aliyuncs.com:3717" --dest="user:pwd@dds-xxxxx.mongodb.rds.aliyuncs.com:3717"

报错如图：
![image](https://user-images.githubusercontent.com/49270615/195505235-27d60ffc-0e05-45de-85ee-387b142e1429.png)

**Comment by zhangst** [comment]
./comparison.py --src="mongodb://root:123@dds-xxx.mongodb.rds.aliyuncs.com:3717/admin" --dest=""  --count=1000  --excludeDbs="admin,local,config,mongoshake" --excludeCollections="system.profile" --comparisonMode=sample

**Comment by xyshanren** [comment]
> ./comparison.py --src="mongodb://root:[123@dds-xxx.mongodb.rds.aliyuncs.com](mailto:123@dds-xxx.mongodb.rds.aliyuncs.com):3717/admin" --dest="" --count=1000 --excludeDbs="admin,local,config,mongoshake" --excludeCollections="system.profile" --comparisonMode=sample

抱歉，按这个还是报：TypeError: 'Database' object is not callable

确认源和目标端都能连接，如图；
![image](https://user-images.githubusercontent.com/49270615/195739379-3d363f5c-9f8f-4c9e-84d7-9eadaaf6566e.png)
![image](https://user-images.githubusercontent.com/49270615/195739518-11b36d94-1b16-476d-b6fc-4cf4059987f0.png)
![image](https://user-images.githubusercontent.com/49270615/195739619-9ac05a2a-d385-4a90-b656-09bab4e4673c.png)

**Comment by zhangst** [comment]
mongo "mongodb://root:[123@dds-xxx.mongodb.rds.aliyuncs.com](mailto:123@dds-xxx.mongodb.rds.aliyuncs.com):3717/admin"
试下这样的shell命令行可以连上吗？

**Comment by xyshanren** [comment]
> mongo "mongodb://root:[123@dds-xxx.mongodb.rds.aliyuncs.com](mailto:123@dds-xxx.mongodb.rds.aliyuncs.com):3717/admin"

可以的，源和目标端，如图：
![image](https://user-images.githubusercontent.com/49270615/195977396-a1bf4ffd-c7f2-43ed-9125-c5682d9e84aa.png)
![image](https://user-images.githubusercontent.com/49270615/195977476-15c7be9c-608f-4d44-9abe-e1e3f4ba6b48.png)

**Comment by zhangst** [comment]
这个有点诡异了，我试过是没有问题的。
你用python 2.7试一下？其它感觉也么有区别了。

**Comment by xmabul** [comment]
pymongo版本问题，新版没有这个方法了，版本差异的还有其它collection和count。
需将database_names改成list_database_names，collection_names改成list_collection_names，count()改成count_documents({})
