### ISSUE TITLE
怎么搭建Mongoshake集群

### ISSUE THREAD

**Issue by BcnJcaicai** [alibaba/MongoShake#763]
请问是否有wiki描述如何搭建mongoshake集群的，以及mongoshake集群的同步机制

**Comment by zhangst** [comment]
master_quorum。是否启动主备模式。false表示只能启动1个mongoshake。配置true的话，用户可以启动2个mongoshake，拉取同一个源MongoDB，mongoshake将会自动选主，备在监测到主挂掉后，会接管过同步服务。注意，如果主是在全量同步阶段挂掉，那么备接管过服务是不会进行断点续传，而是会从头开始同步，而且如果配置项不当，可能还会有报错。主备模式主要用于在增量环节的HA容错切换。默认false
https://github.com/alibaba/MongoShake/wiki/%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E

没有集群，只有冷备模式

**Comment by BcnJcaicai** [comment]
您好，开启master_quorum后，开启两个mongoshake拉同一个源，内部如何判断哪个是master的？  
如果想开启第二个mongoshake，我这边是调整了全量，增量，监听端口，同时把pid改了，然后启动后就自动找到主节点了。 
那如果我这个机器上面还有一个源端同端口的mongoshake但是目标端口不一样 ，这个后起来的slave如何判断哪个是要同步的主呢？是拿配置文件中的源端和目标端口和机器上面的另外的mongoshake的源端和目标端口对比的么

**Comment by zhangst** [comment]
shake的主备通过数据库中的锁来决定的，使用checkpoint.storage.url这个配置对应的数据库。
具体哪个在工作，可以通过内部监控查看：https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E4%BD%95%E7%9B%91%E6%8E%A7%E5%92%8C%E7%AE%A1%E7%90%86MongoShake%E7%9A%84%E8%BF%90%E8%A1%8C%E7%8A%B6%E6%80%81%EF%BC%9F
