### ISSUE TITLE
mongoshake启动同步任务报错Reload ckpt find context fail. (ReadConcernMajorityNotEnabled) 

### ISSUE THREAD

**Issue by bozai111** [alibaba/MongoShake#765]
mongo版本 
源端: mongo分片，MongoDB server version: 3.4.7
目标端：mongo分片 MongoDB server version: 3.4.10

mongoshake版本 v2.8.1

报错日志：
[EROR] shard1 Reload ckpt find context fail. (ReadConcernMajorityNotEnabled) Majority read concern requested, but server was not started with --enableMajorityReadConcern.
[2022/10/31 10:30:47 CST] [CRIT] run replication failed: select sync mode failed: get mongod[shard1] checkpoint failed: get by checkpoint info from db or api failed, please see err log
[2022/10/31 10:30:47 CST] [WARN]

**Comment by bozai111** [comment]
开启 ReadConcernMajority参数后，mongoshake不报错了，建议把这个加到常见问题里面；

另外mongoshake同步任务启动，需要mongodb开启ReadConcernMajority这个参数，是在什么场景下？

**Comment by zhangst** [comment]
MongoDB 3.6 开始，enableMajorityReadConcern这个参数默认是true的，你用的MongoDB的版本是比较老的版本了。

**Comment by humingfeng** [comment]
> 
enableMajorityReadConcern这个参数我设置成true，Mongo3.4 -> 3.6还是报这个错
