### ISSUE TITLE
deserializer 性能瓶颈如何突破

### ISSUE THREAD

**Issue by dongkun-nb** [alibaba/MongoShake#766]
MongoShake 版本为最新的 2.8.1.

我们 mongo 集群的 oplog 很大，平均单个 oplog 的大小 300K，最大的 oplog 超过 2M。
同步的模式，source 为 replication set，tunnel 为 file，file 的 路径为 /dev/null. 使用 mongoshake 同步的时候，发现 mongoshake 在增量阶段同步的 lsn 不断增加，无法同步成功。

在同步的过程中，通过 curl -s 127.0.0.1:9702/worker | python -m json.tool  观察 worker 的 jobs_in_queue 和 jobs_unack_buffer 都为 0 。
通过 curl -s 127.0.0.1:9702/queue | python -m json.tool 观察 logs_queue_used 一般在 4 以内，而 pending_queue_used  一般在 10 以上。
buffer_capercity 配置为 128。 logs_queue_size 和 pending_queue_size 为 16。
通过 curl -s 127.0.0.1:9702/repl | python -m json.tool 观察 logs_get 和 logs_repl 的增加速率为 800/S.

我做的测试和结论：
1 增加 logs_queue_size 和 pending_queue_size 可以提高 logs_get 的速率到 3100/S，但是 logs_repl 的速率为 1200/S. 在这个过程中 mongoshake 的内存使用量不断的增加，直到系统内存耗尽时被杀死。通过分析，我认为 deserializer 的性能到了瓶颈，这个结论对么？
2 buffer_capercity 配置为 128，logs_queue_size 和 pending_queue_size 为 16。在这个条件下，我修改源代码的 PipelineQueueMaxNr, PipelineQueueMiddleNr, PipelineQueueMinNr 将 deserialize 的数量增加，在 1 - 4 时候 logs_get 和 logs_repl 的速率按照线性增加，但是大于 4 以后，logs_get 和 logs_repl 一直处于 900/S 不再增加啦。增加 deserializer 而 logs_get 和 logs_repl 的速率不再继续增肌的原因是什么哪？

**Comment by zhangst** [comment]
logs_get是从源DB拉取速率的统计，在写入pending之前统计
logs_repl 是worker中写入batchBlock的统计，可以理解为写入目的DB的速率在logsQueue之后。
增加 deserializer 数据没有增长，要看下shake所在机器的CPU是否够用。
排查思路没有错的。

**Comment by dongkun-nb** [comment]
我执行了一次测试。
mongoshake 版本为 2.8.1.
测试的机器 的 CPU 信息 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz， 24 个物理核。
修改 collector/syncer.go 中的变量为如下：
        PipelineQueueMaxNr    = 8
        PipelineQueueMiddleNr = 8
        PipelineQueueMinNr    = 8
        PipelineQueueLen      = 64

测试过程中使用 top 发现 collector 进程的 CPU 利用率在 800% - 1100% 之间波动。
logs_get 和 logs_repl 的速率还是 1100/S，相比 deserializer 的数量配置 为 4 时候 增加了 200/S。而 deserializer 的数量从 8 继续增加到 16， logs_get 和 logs_repl 的速率还是 1100/S。我期望 logs_repl 的速率能达到 3000/S。

**我现在怀疑是 go channel 机制的性能瓶颈，这个推测是否对？如果对，如何解决哪？**

**测试过程中配置文件如下，仅贴出关键配置：**
master_quorum = false

full_sync.http_port = 9701
incr_sync.http_port = 9702
system_profile_port = 9700

sync_mode = incr

mongo_urls = mongodb://127.0.0.1:27017/?readPreference=primary
mongo_cs_url =
mongo_ssl_root_ca_file = 

tunnel = file
tunnel.address = /dev/null
tunnel.message = raw
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =

mongo_connect_mode = primary

filter.namespace.black =
filter.namespace.white =
filter.pass.special.db =
filter.ddl_enable = false
filter.oplog.gids = false

checkpoint.storage.url = mongodb://xxxx:27017/?replicaSet=shake
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = xxx
checkpoint.storage.url.mongo_ssl_root_ca_file = 
checkpoint.start_position = 2022-11-01T00:00:00Z

transform.namespace =

incr_sync.mongo_fetch_method = oplog
incr_sync.change_stream.watch_full_document = false
incr_sync.oplog.gids =
incr_sync.shard_key = collection
incr_sync.shard_by_object_id_whitelist = 
incr_sync.worker = 8
incr_sync.tunnel.write_thread = 8
incr_sync.target_delay = 0
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 128
incr_sync.reader.fetch_batch_size = 8192
incr_sync.executor.upsert = true
incr_sync.executor.insert_on_dup_update = true
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false

下面是测试过程中的，监控数据：
**while true; do date; curl -s 127.0.0.1:9702/persist  | python -m json.tool ; sleep 1; done**
Tue Nov  1 08:15:38 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 128,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}
Tue Nov  1 08:15:39 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 65,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}
Tue Nov  1 08:15:40 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 6,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}
Tue Nov  1 08:15:41 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 128,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}
Tue Nov  1 08:15:42 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 128,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}
Tue Nov  1 08:15:43 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 128,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}
Tue Nov  1 08:15:44 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 4,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}
Tue Nov  1 08:15:45 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 128,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}
Tue Nov  1 08:15:46 UTC 2022
{
    "buffer_size": 128,
    "buffer_used": 7,
    "disk_read_count": 0,
    "disk_write_count": 0,
    "enable_disk_persist": false,
    "fetch_stage": "store memory and apply"
}

**while true; do date; curl -s 127.0.0.1:9702/queue  | python -m json.tool ; sleep 1; done**                   
Tue Nov  1 08:16:44 UTC 2022
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 128,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 5,
            "pending_queue_used": 59,
            "queue_id": 0
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 1
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 64,
            "queue_id": 2
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 3
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 4
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 5
        },
        {
            "logs_queue_used": 2,
            "pending_queue_used": 62,
            "queue_id": 6
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 7
        }
    ],
    "syncer_replica_set_name": "viewhistory-shard5"
}
Tue Nov  1 08:16:45 UTC 2022
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 128,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 5,
            "pending_queue_used": 59,
            "queue_id": 0
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 1
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 64,
            "queue_id": 2
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 3
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 4
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 5
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 6
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 7
        }
    ],
    "syncer_replica_set_name": "viewhistory-shard5"
}
Tue Nov  1 08:16:46 UTC 2022
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 128,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 5,
            "pending_queue_used": 59,
            "queue_id": 0
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 1
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 64,
            "queue_id": 2
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 3
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 4
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 5
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 6
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 7
        }
    ],
    "syncer_replica_set_name": "viewhistory-shard5"
}
Tue Nov  1 08:16:47 UTC 2022
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 128,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 5,
            "pending_queue_used": 59,
            "queue_id": 0
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 1
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 64,
            "queue_id": 2
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 3
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 4
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 5
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 6
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 7
        }
    ],
    "syncer_replica_set_name": "viewhistory-shard5"
}
Tue Nov  1 08:16:48 UTC 2022
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 128,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 5,
            "pending_queue_used": 59,
            "queue_id": 0
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 1
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 64,
            "queue_id": 2
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 3
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 4
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 61,
            "queue_id": 5
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 63,
            "queue_id": 6
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 7
        }
    ],
    "syncer_replica_set_name": "viewhistory-shard5"
}

**while true; do date; curl -s 127.0.0.1:9702/repl  | python -m json.tool ; sleep 1; done**
Tue Nov  1 08:19:57 UTC 2022
{
    "log_size_avg": "161.56KB",
    "log_size_max": "602.80KB",
    "logs_get": 470400,
    "logs_repl": 402998,
    "logs_success": 402998,
    "lsn": {
        "time": "2022-11-01 01:03:07",
        "ts": "7160846874943951149",
        "unix": 1667264587
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:07",
        "ts": "7160846874943951149",
        "unix": 1667264587
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:07",
        "ts": "7160846874943948028",
        "unix": 1667264587
    },
    "now": {
        "time": "2022-11-01 08:19:57",
        "unix": 1667290797
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 1024,
    "who": "mongoshake"
}
Tue Nov  1 08:19:58 UTC 2022
{
    "log_size_avg": "81.40KB",
    "log_size_max": "602.80KB",
    "logs_get": 471424,
    "logs_repl": 404022,
    "logs_success": 404022,
    "lsn": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238914247",
        "unix": 1667264588
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238914247",
        "unix": 1667264588
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:07",
        "ts": "7160846874943948028",
        "unix": 1667264587
    },
    "now": {
        "time": "2022-11-01 08:19:58",
        "unix": 1667290798
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 0,
    "who": "mongoshake"
}
Tue Nov  1 08:19:59 UTC 2022
{
    "log_size_avg": "69.98KB",
    "log_size_max": "602.80KB",
    "logs_get": 472448,
    "logs_repl": 405046,
    "logs_success": 405046,
    "lsn": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238915271",
        "unix": 1667264588
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238915271",
        "unix": 1667264588
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:07",
        "ts": "7160846874943948028",
        "unix": 1667264587
    },
    "now": {
        "time": "2022-11-01 08:19:59",
        "unix": 1667290799
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 1024,
    "who": "mongoshake"
}
Tue Nov  1 08:20:00 UTC 2022
{
    "log_size_avg": "146.23KB",
    "log_size_max": "602.80KB",
    "logs_get": 473472,
    "logs_repl": 406070,
    "logs_success": 406070,
    "lsn": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238916295",
        "unix": 1667264588
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238916295",
        "unix": 1667264588
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238915139",
        "unix": 1667264588
    },
    "now": {
        "time": "2022-11-01 08:20:00",
        "unix": 1667290800
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 1024,
    "who": "mongoshake"
}
Tue Nov  1 08:20:02 UTC 2022
{
    "log_size_avg": "129.43KB",
    "log_size_max": "602.80KB",
    "logs_get": 474254,
    "logs_repl": 407094,
    "logs_success": 407094,
    "lsn": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238917320",
        "unix": 1667264588
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238917320",
        "unix": 1667264588
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238915139",
        "unix": 1667264588
    },
    "now": {
        "time": "2022-11-01 08:20:02",
        "unix": 1667290802
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 1024,
    "who": "mongoshake"
}
Tue Nov  1 08:20:03 UTC 2022
{
    "log_size_avg": "68.30KB",
    "log_size_max": "602.80KB",
    "logs_get": 474496,
    "logs_repl": 407094,
    "logs_success": 407094,
    "lsn": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238917320",
        "unix": 1667264588
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238917320",
        "unix": 1667264588
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238915139",
        "unix": 1667264588
    },
    "now": {
        "time": "2022-11-01 08:20:03",
        "unix": 1667290803
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 1024,
    "who": "mongoshake"
}
Tue Nov  1 08:20:04 UTC 2022
{
    "log_size_avg": "18.48KB",
    "log_size_max": "602.80KB",
    "logs_get": 475520,
    "logs_repl": 408118,
    "logs_success": 408118,
    "lsn": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238918344",
        "unix": 1667264588
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238918344",
        "unix": 1667264588
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238915139",
        "unix": 1667264588
    },
    "now": {
        "time": "2022-11-01 08:20:04",
        "unix": 1667290804
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 77,
    "who": "mongoshake"
}
Tue Nov  1 08:20:05 UTC 2022
{
    "log_size_avg": "73.89KB",
    "log_size_max": "602.80KB",
    "logs_get": 476544,
    "logs_repl": 409142,
    "logs_success": 409142,
    "lsn": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238919369",
        "unix": 1667264588
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238919369",
        "unix": 1667264588
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238915139",
        "unix": 1667264588
    },
    "now": {
        "time": "2022-11-01 08:20:05",
        "unix": 1667290805
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 947,
    "who": "mongoshake"
}
Tue Nov  1 08:20:06 UTC 2022
{
    "log_size_avg": "48.18KB",
    "log_size_max": "602.80KB",
    "logs_get": 477568,
    "logs_repl": 410166,
    "logs_success": 410166,
    "lsn": {
        "time": "2022-11-01 01:03:09",
        "ts": "7160846883533882364",
        "unix": 1667264589
    },
    "lsn_ack": {
        "time": "2022-11-01 01:03:09",
        "ts": "7160846883533882364",
        "unix": 1667264589
    },
    "lsn_ckpt": {
        "time": "2022-11-01 01:03:08",
        "ts": "7160846879238919087",
        "unix": 1667264588
    },
    "now": {
        "time": "2022-11-01 08:20:06",
        "unix": 1667290806
    },
    "replset": "viewhistory-shard5",
    "tag": "unknown,0.0,release,go1.13.8,2022-11-01_04:12:12",
    "tps": 1024,
    "who": "mongoshake"
}
**while true; do date; curl -s 127.0.0.1:9702/worker  | python -m json.tool ; sleep 1; done**                  
Tue Nov  1 08:24:49 UTC 2022
[
    {
        "count": 19020,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "7160847149821857048",
        "last_unack": "7160847149821857048",
        "worker_id": 0
    },
    {
        "count": 6650,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "7160847149821857037",
        "last_unack": "7160847149821857037",
        "worker_id": 1
    },
    {
        "count": 0,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "0",
        "last_unack": "0",
        "worker_id": 2
    },
    {
        "count": 0,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "0",
        "last_unack": "0",
        "worker_id": 3
    },
    {
        "count": 601835,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "7160847149821857055",
        "last_unack": "7160847149821857055",
        "worker_id": 4
    },
    {
        "count": 0,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "0",
        "last_unack": "0",
        "worker_id": 5
    },
    {
        "count": 47,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "7160847051037609364",
        "last_unack": "7160847051037609364",
        "worker_id": 6
    },
    {
        "count": 30250,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "7160847149821857044",
        "last_unack": "7160847149821857044",
        "worker_id": 7
    }
]

**Comment by zhangst** [comment]
PipelineQueueMaxNr = 8
PipelineQueueMiddleNr = 8
PipelineQueueMinNr = 8

当上面三个参数都调整为16时，下面的queue监控中pending_queue_used还都是60多，基本写满的状态吗？

while true; do date; curl -s 127.0.0.1:9702/queue | python -m json.tool ; sleep 1; done

**Comment by dongkun-nb** [comment]
这个问题可以先 close 掉了，我们减少了一个 collection 的 update 。oplog 的 avg size 从 150KB，降低到 50KB。现在 logs_repl 可以提高到了 2400/S 以上，可以满足我们的需求啦。

**Comment by dongkun-nb** [comment]
我z再次执行了一次测试。
mongoshake 版本为 2.8.1.
测试的机器 的 CPU 信息 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz， 24 个物理核，启动超线程。
修改 collector/syncer.go 中的变量为如下：
PipelineQueueMaxNr = 16
PipelineQueueMiddleNr = 16
PipelineQueueMinNr = 16
PipelineQueueLen = 64
配置文件的各个配置项和上一次测试的配置文件相同。
测试结果为 logs_repl 的

下面是本次测试的监控数据：
**while true; do curl -s 127.0.0.1:9702/repl | python -m json.tool | grep logs; sleep 10; date; done;**
    "logs_get": 352768,
    "logs_repl": 218512,
    "logs_success": 218512,
Thu Nov  3 13:40:25 UTC 2022
    "logs_get": 363008,
    "logs_repl": 228749,
    "logs_success": 228749,
Thu Nov  3 13:40:35 UTC 2022
    "logs_get": 373248,
    "logs_repl": 238989,
    "logs_success": 238989,
Thu Nov  3 13:40:45 UTC 2022
    "logs_get": 385536,
    "logs_repl": 251277,
    "logs_success": 251277,
Thu Nov  3 13:40:55 UTC 2022
    "logs_get": 393728,
    "logs_repl": 259469,
    "logs_success": 259469,

**curl -s 127.0.0.1:9702/queue | python -m json.tool**
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 15,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 6,
            "pending_queue_used": 57,
            "queue_id": 0
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 59,
            "queue_id": 1
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 60,
            "queue_id": 2
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 64,
            "queue_id": 3
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 4
        },
        {
            "logs_queue_used": 6,
            "pending_queue_used": 58,
            "queue_id": 5
        },
        {
            "logs_queue_used": 10,
            "pending_queue_used": 54,
            "queue_id": 6
        },
        {
            "logs_queue_used": 8,
            "pending_queue_used": 56,
            "queue_id": 7
        },
        {
            "logs_queue_used": 7,
            "pending_queue_used": 57,
            "queue_id": 8
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 59,
            "queue_id": 9
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 60,
            "queue_id": 10
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 63,
            "queue_id": 11
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 62,
            "queue_id": 12
        },
        {
            "logs_queue_used": 6,
            "pending_queue_used": 57,
            "queue_id": 13
        },
        {
            "logs_queue_used": 9,
            "pending_queue_used": 54,
            "queue_id": 14
        },
        {
            "logs_queue_used": 7,
            "pending_queue_used": 56,
            "queue_id": 15
        }
    ],
    "syncer_replica_set_name": "viewhistory-shard5"
}

**Comment by dongkun-nb** [comment]
我再次执行了一次测试。
mongoshake 版本为 2.8.1.
测试的机器 的 CPU 信息 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz， 24 个物理核，启动超线程。
修改 collector/syncer.go 中的变量为如下：
PipelineQueueMaxNr = 16
PipelineQueueMiddleNr = 16
PipelineQueueMinNr = 16
PipelineQueueLen = 64
配置文件的各个配置项和上一次测试的配置文件相同。
**测试结果为 logs_repl 的速率为 1000/S, 而 pending_queue_used 的 queue 几乎为满的情况。**

下面是本次测试的监控数据：
**while true; do curl -s 127.0.0.1:9702/repl | python -m json.tool | grep logs; sleep 10; date; done;**
    "logs_get": 352768,
    "logs_repl": 218512,
    "logs_success": 218512,
Thu Nov  3 13:40:25 UTC 2022
    "logs_get": 363008,
    "logs_repl": 228749,
    "logs_success": 228749,
Thu Nov  3 13:40:35 UTC 2022
    "logs_get": 373248,
    "logs_repl": 238989,
    "logs_success": 238989,
Thu Nov  3 13:40:45 UTC 2022
    "logs_get": 385536,
    "logs_repl": 251277,
    "logs_success": 251277,
Thu Nov  3 13:40:55 UTC 2022
    "logs_get": 393728,
    "logs_repl": 259469,
    "logs_success": 259469,

**curl -s 127.0.0.1:9702/queue | python -m json.tool**
{
    "logs_queue_size": 64,
    "pending_queue_size": 64,
    "persister_buffer_used": 15,
    "syncer_inner_queue": [
        {
            "logs_queue_used": 6,
            "pending_queue_used": 57,
            "queue_id": 0
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 59,
            "queue_id": 1
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 60,
            "queue_id": 2
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 64,
            "queue_id": 3
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 60,
            "queue_id": 4
        },
        {
            "logs_queue_used": 6,
            "pending_queue_used": 58,
            "queue_id": 5
        },
        {
            "logs_queue_used": 10,
            "pending_queue_used": 54,
            "queue_id": 6
        },
        {
            "logs_queue_used": 8,
            "pending_queue_used": 56,
            "queue_id": 7
        },
        {
            "logs_queue_used": 7,
            "pending_queue_used": 57,
            "queue_id": 8
        },
        {
            "logs_queue_used": 4,
            "pending_queue_used": 59,
            "queue_id": 9
        },
        {
            "logs_queue_used": 3,
            "pending_queue_used": 60,
            "queue_id": 10
        },
        {
            "logs_queue_used": 0,
            "pending_queue_used": 63,
            "queue_id": 11
        },
        {
            "logs_queue_used": 1,
            "pending_queue_used": 62,
            "queue_id": 12
        },
        {
            "logs_queue_used": 6,
            "pending_queue_used": 57,
            "queue_id": 13
        },
        {
            "logs_queue_used": 9,
            "pending_queue_used": 54,
            "queue_id": 14
        },
        {
            "logs_queue_used": 7,
            "pending_queue_used": 56,
            "queue_id": 15
        }
    ],
    "syncer_replica_set_name": "viewhistory-shard5"
}

**Comment by zhangst** [comment]
16个pending_queue_used基本都是满的，说明还是deserializer处理慢了，但是这个Routine很简单，只是调用Unmarshal函数，理论上增加个数就可以消耗更多CPU处理更多任务。
增加pending_queue_used个数后，对应消耗的CPU有上升吗？

**Comment by dongkun-nb** [comment]
在上面 deserializer 配置 16 的测试中，collector 的 CPU 利用率已经为 1600% 以上了。继续增加 deserializer 数量到 32 个，collector 的 CPU 利用率可以提高到 3200% 以上，但是 logs_repl 的速率不会增加。

**Comment by zhangst** [comment]
> 在上面 deserializer 配置 16 的测试中，collector 的 CPU 利用率已经为 1600% 以上了。继续增加 deserializer 数量到 32 个，collector 的 CPU 利用率可以提高到 3200% 以上，但是 logs_repl 的速率不会增加。

这时，如果队列pending_queue_used还是高负荷，而logs_queue_used是低负荷，那还是deserializer为瓶颈。有条件换一台配置更高的机器试一下吗？

**Comment by dongkun-nb** [comment]
使用更高配置的机器做了测试，collector 的 CPU 利用率会增加，但是 logs_repl 的速率不会增加啦。
我们开发了一个新的程序，可以多进程并发读取 oplog 并解析 oplog 然后写入到目标集群解决了该问题。
