### ISSUE TITLE
全量同步问题

### ISSUE THREAD

**Issue by longer3281** [alibaba/MongoShake#769]
mongoshake 在做全量同步时，会突然断掉，报以下错误信息：
[lilongqian@MGD_DBSTORE01 shake]$ [11:36:13 CST 2022/11/16] [CRIT] (github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DBSyncer).collectionSync.func1:468) splitter reader[DocumentReader id[0], 
src[mongodb://mgsync:***@10.14.10.13:27017,10.14.10.12:27017,10.14.10.11:27017,10.14.10.14:27017] ns[{fast platform_base_doc_202104}] query[map[]]] get next document failed: (CursorNotFound) cursor id 7621574038415 not found
goroutine 4438 [running]:
github.com/vinllen/log4go.(*ConsoleLogWriter).LogWrite(0xc00000e240, 0xc003120e80)
        /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/termlog.go:41 +0x45
github.com/vinllen/log4go.Logger.intLogf(0xc0001006f0, 0x7, 0xd7a47f, 0x2, 0xc00063bf88, 0x1, 0x1)
        /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/log4go.go:223 +0x277
github.com/vinllen/log4go.Crashf(0xd7a47f, 0x2, 0xc00063bf88, 0x1, 0x1)
        /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:44 +0x6c
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DBSyncer).collectionSync.func1(0xc00031ee00, 0xc000328620, 0xc00031c120, 0xc0000b70e0, 0xc0004301a0)
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_syncer.go:468 +0x115
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DBSyncer).collectionSync
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_syncer.go:459 +0x328
请问这是什么原因造成的啊？

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/issues/700
参考上面补充下信息。
表象看是cursor失效了，有可能是mongoDB的bug

**Comment by longer3281** [comment]
我的mongodb版本是 3.6.4

**Comment by longer3281** [comment]
mongoshake版本 improve-2.8.1,9f2515bbe508b2d86fab2ed87f01f3121efc6920,release,go1.15.10,2022-09-22_11:49:22
源端，目的端 mongo数据库版本 3.6.4-1.2

**Comment by longer3281** [comment]
配置文件如下：
conf.version = 10
id = mongoshake

tunnel = direct
sync_mode = full

mongo_urls = mongodb://username:password@SRC_IP1:27017,SRC_IP2:27017,SRC_IP3:27017
tunnel.address = mongodb://username:password@DST_IP1:27017,DST_IP2:27017,DST_IP3:27017


#context.storage = database
checkpoint.storage.url= mongodb://username:password@DST_IP1:27017
checkpoint.storage.db = chkpdb
checkpoint.storage.collection = ckpt_default_2022
checkpoint.start_position = 2022-11-16T11:00:00Z

incr_sync.worker = 8
incr_sync.tunnel.write_thread = 8
full_sync.create_index = background
full_sync.http_port = 9101
incr_sync.http_port = 9100

#warning, info, debug
log.level=info
log.dir=./logs/
log.file=collector.log
log.flush=false

tunnel.message = raw
#mongo_connect_mode = standalone
mongo_connect_mode = secondaryPreferred

filter.namespace.white=fast.platform_base_doc_202104

full_sync.executor.insert_on_dup_update=true
full_sync.collection_exist_drop = true
incr_sync.executor.insert_on_dup_update = true
incr_sync.executor.upsert = true
filter.ddl_enable = true


full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 80
full_sync.reader.parallel_index = _id

incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256

**Comment by zhangst** [comment]
> mongoshake版本 improve-2.8.1,9f2515bbe508b2d86fab2ed87f01f3121efc6920,release,go1.15.10,2022-09-22_11:49:22
> 源端，目的端 mongo数据库版本 3.6.4-1.2

沟通效率太低了，源和目的分别是什么版本？源DB是3.6.4版本，目的DB是1.2版本？

**Comment by zhangst** [comment]
另外日志还是没有提供，只能盲猜下，可能如下两种情况：
1. 源DB中的bug，bug连接：https://jira.mongodb.org/browse/SERVER-34810
2. 目的DB写入过慢，导致shake数据堆积，队列写满，从长时间没有从源DB拉取数据，导致cursor超时被kill。
请根据 jira中的资料 和 shake的wiki中内部监控相关的资料判断下。

**Comment by longer3281** [comment]
源端，目的端 mongo数据库版本都是 3.6.4-1.2，是同一版本之间的数据库节点同步

**Comment by longer3281** [comment]
有没有什么好发解决方法？
wod mongodb 连接时长已经设置为20分钟了，可是每次跑3分钟左右就挂了。
go语言无法设置连接时长吗?

**Comment by longer3281** [comment]
为什么不搞一个心跳检测，以及重连机制呢？

**Comment by zhangst** [comment]
如果是MongoDB的bug，不是心跳可以解决的。
目前全量同步确实也不支持断点续传，这个是一个待补充的能力

**Comment by Little-Tiny** [comment]
源端目标端都是3.6.3，mongoshake尝试了2.7.5、2.8.1、2.4.22都是报相同的问题，源端日志查不到报错信息，总共10GB的数据，每次还没传几分钟就直接停掉了

**Comment by zhangst** [comment]
建议参考jira连接把源DB的版本升级试一下，问题是在3.6.6版本中解决的。目前cursor被清理的情况下，shake是没有办法正常拉数据的

**Comment by Little-Tiny** [comment]
> 建议参考jira连接把源DB的版本升级试一下，问题是在3.6.6版本中解决的。目前cursor被清理的情况下，shake是没有办法正常拉数据的

整了1GB的数据进行测试，将3.6.3版本升级到3.6.23版本后，同步可以正常进行，后期计划对生产进行小版本升级，然后再同步，感谢大佬支持

**Comment by longer3281** [comment]
> > 建议参考jira连接把源DB的版本升级试一下，问题是在3.6.6版本中解决的。目前cursor被清理的情况下，shake是没有办法正常拉数据的
> 
> 整了1GB的数据进行测试，将3.6.3版本升级到3.6.23版本后，同步可以正常进行，后期计划对生产进行小版本升级，然后再同步，感谢大佬支持

非常感谢您的解答。
