### ISSUE TITLE
mongoshake 同步游标问题

### ISSUE THREAD

**Issue by longer3281** [alibaba/MongoShake#770]
[19:36:55 CST 2022/11/16] [CRIT] (github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DBSyncer).collectionSync.func1:468) splitter reader[DocumentReader id[0], src[mongodb://mgsync:***@10.14.10.13:27017,10.14.10.14:27017] ns[{ticketdb flight_logs_202007}] query[map[]]] get next document failed: (CursorNotFound) cursor id 3037596471419 not found
panic: splitter reader[DocumentReader id[0], src[mongodb://mgsync:***@10.14.10.13:27017,10.14.10.14:27017] ns[{ticketdb flight_logs_202007}] query[map[]]] get next document failed: (CursorNotFound) cursor id 3037596471419 not found

goroutine 1405 [running]:
github.com/vinllen/log4go.Crashf(0xd7a47f, 0x2, 0xc000707f88, 0x1, 0x1)
        /u02/shuntong.zhang/local_bin/go1_15_10/go_modcache/github.com/vinllen/log4go@v0.0.0-20180514124125-3848a366df9d/wrapper.go:46 +0xe5
github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DBSyncer).collectionSync.func1(0xc00025f300, 0xc00026e000, 0xc00052a5a0, 0xc00042e000, 0xc0004640e0)
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_syncer.go:468 +0x115
created by github.com/alibaba/MongoShake/v2/collector/docsyncer.(*DBSyncer).collectionSync
        /u02/shuntong.zhang/db_src/MongoShake/collector/docsyncer/doc_syncer.go:459 +0x328
 全量同步一张大表，总是报cursor有问题，不知道是什么原因？

**Comment by longer3281** [comment]
日志错误定位在 https://github.com/alibaba/MongoShake/blob/develop/collector/docsyncer/doc_syncer.go 的第468行错误，不懂 go语言，看不明白。

**Comment by zhangst** [comment]
duplicate: https://github.com/alibaba/MongoShake/issues/769
