### ISSUE TITLE
全量同步完后增量资源占用异常

### ISSUE THREAD

**Issue by lenovore** [alibaba/MongoShake#772]
source：阿里云mongodb副本集v3.4
mongoshake：v2.8.1
target：ECS自建mongodb单实例 v4.4.18

全量同步耗时6小时，全量完成后进入增量后就导致mongoshake资源占用飙升
![1](https://user-images.githubusercontent.com/29646774/204256818-992ec479-3865-4f88-af8e-3704d972f1fe.jpg)
期间有大量的重复键警告信息
![2](https://user-images.githubusercontent.com/29646774/204256839-3b34f1b5-57c9-4580-b6db-a48de85c83b0.jpg)
ECS资源监控图
![3](https://user-images.githubusercontent.com/29646774/204256858-92c151e0-4b70-4652-a009-6dd05125c07d.jpg)
下图是快恢复的时候，mongoshake内存资源占用
![image](https://user-images.githubusercontent.com/29646774/204257082-9a0dc245-3622-4073-83d4-a8f517437862.png)

增量同步为什么会突然资源占用徒增，和数据冲突处理有关还是其他什么原因呢

**Comment by zhangst** [comment]
有时间我本地复现一下，请补充过一下脱敏后的配置文件

**Comment by lenovore** [comment]
配置
[collector.txt](https://github.com/alibaba/MongoShake/files/10109174/collector.txt)

**Comment by lenovore** [comment]
通过调低下面2个参数解决了，还是机器资源不够
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256
