### ISSUE TITLE
同步DDL报错

### ISSUE THREAD

**Issue by lenovore** [alibaba/MongoShake#773]
source：阿里云mongodb副本集v3.4
mongoshake：v2.8.1
target：ECS自建mongodb单实例 v4.4.18

目标库账号权限
![image](https://user-images.githubusercontent.com/29646774/204421922-3bca198f-a131-4cff-bc9c-eb5bac19f6b2.png)
mongoshake日志
![image](https://user-images.githubusercontent.com/29646774/204422029-252f4d37-b1e2-4b09-9208-933defa3f64b.png)

**Comment by lenovore** [comment]
配置
[collector.txt](https://github.com/alibaba/MongoShake/files/10109170/collector.txt)

**Comment by zhangst** [comment]
这是MongoDB版本不同带来的问题，3.4的索引是库内的system.index集合，新版本中机制变了。建议关掉DDL，手工创建下索引。

**Comment by lenovore** [comment]
全量同步索引的机制和增量是有不同嘛，这边全量是没问题的

**Comment by zhangst** [comment]
不一样，全量是主动去源实例获取所有的索引，获取的方法没有变化，所以可以正确创建。增量中会反映创建索引的内部细节，比如3.4的版本是一个insert，之后的版本就是createIndex命令了。

**Comment by lenovore** [comment]
了解了
