### ISSUE TITLE
源库关闭balancer全量同步遥遥无期

### ISSUE THREAD

**Issue by solemnpending** [alibaba/MongoShake#774]
1.MongoShake的版本：2.6.5

2.源和目的MongoDB的版本：源3.6.23-13,  目的3.6.23-13

3.shake配置：
conf.version = 10
id = mongoshake
master_quorum = false
full_sync.http_port = 9101
incr_sync.http_port = 9100
system_profile_port = 9200
log.level = info
log.dir =
log.file = collector.log
log.flush = false
sync_mode = all
mongo_urls = mongodb://xxx:xxx@10.101.100.49:27017,10.101.100.89:27017,10.101.100.93:27017;mongodb://xxx:xxx@10.101.100.21:27020,10.101.100.237:27020,10.101.100.92:27020;mongodb://xxx:xxx@10.101.100.89:27018,10.101.100.49:27018,10.101.100.93:27018;mongodb://xxx:xxx@10.101.100.92:27021,10.101.100.237:27021,10.101.100.21:27021;mongodb://xxx:xxx@10.101.100.93:27019,10.101.100.89:27019,10.101.100.49:27019;mongodb://xxx:xxx@10.101.100.237:27022,10.101.100.21:27022,10.101.100.92:27022;
mongo_cs_url = mongodb://xxx:xxx@10.101.100.49:21000,10.101.100.89:21000,10.101.100.93:21000
mongo_s_url = mongodb://xxx:xxx@10.101.100.49:20000,10.101.100.89:20000,10.101.100.93:20000,10.101.100.21:20000,10.101.100.237:20000,10.101.100.92:20000
mongo_ssl_root_ca_file =
tunnel = direct
tunnel.address = mongodb://xxx:xxx@10.103.10.10:20000,10.103.10.11:20000,10.103.10.12:20000,10.103.10.13:20000,10.103.10.14:20000,10.103.10.15:20000
tunnel.message = raw
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =
mongo_connect_mode = secondaryPreferred
filter.namespace.black =
filter.namespace.white = adtrace
filter.pass.special.db =
filter.ddl_enable = false
filter.oplog.gids = false
checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.storage.url.mongo_ssl_root_ca_file =
checkpoint.start_position = 1970-01-01T00:00:00Z
transform.namespace =
full_sync.reader.collection_parallel =6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.parallel_thread = 0
full_sync.collection_exist_drop = false
full_sync.create_index = none
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false
incr_sync.mongo_fetch_method = oplog
incr_sync.change_stream.watch_full_document = false
incr_sync.oplog.gids =
incr_sync.shard_key = collection
incr_sync.shard_by_object_id_whitelist =
incr_sync.worker = 8
incr_sync.tunnel.write_thread = 8
incr_sync.target_delay = 0
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256
incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false
special.source.db.flag =

4.问题描述
关闭balancer后，全量同步完成目前已经过了18个小时还在同步。

开启balancer，设置时间窗口，避开全量和增量同步：
12个小时完成全量同步，但是增量过程中会遇到move chunk oplog found问题。

**Comment by zhangst** [comment]
1. 请使用最新的2.8.1版本
2. 请参考下面连接自查下，看下阻塞在哪里：https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E4%BD%95%E7%9B%91%E6%8E%A7%E5%92%8C%E7%AE%A1%E7%90%86MongoShake%E7%9A%84%E8%BF%90%E8%A1%8C%E7%8A%B6%E6%80%81%EF%BC%9F 
3. 如果还没有找到问题，提供下日志和第二条命令中返回的内容

**Comment by solemnpending** [comment]
好的，谢谢

**Comment by solemnpending** [comment]
已经解决了，就是表太大导致，至于为什么开了balancer会快，可能是正好当时那个表的document数量少点儿，当时没有curl获取到这个表的process的文档数。

**Comment by solemnpending** [comment]
还有个问题：就是我们的balancer关闭后，有部分表在全量同步的时候完全没有同步过来，但是全量同步显示已经完成了，curl http://127.0.0.1:9101/progress 也显示进度100%了

这是我们progress拉出来的数据：
<img width="568" alt="image" src="https://user-images.githubusercontent.com/20881795/204772924-1060c02c-66f2-49cd-bbed-9d8281270161.png">


这是我们用diff脚本对比源库和目的库的数据：
<img width="532" alt="image" src="https://user-images.githubusercontent.com/20881795/204772129-d3115adc-8b95-4d89-945a-935aa9a7209e.png">
