### ISSUE TITLE
2.4.18版本mongoshake增量同步mongodb-sharding同步至mongodb-replica 4.0版本每天延迟半小时左右

### ISSUE THREAD

**Issue by Lili123456** [alibaba/MongoShake#776]
环境如题
每天特定时间会有200w级别的大表delete数据动作，使用mongoshake的延迟监控，会发现每天都会有延迟20分钟左右的，稳定增长后直线掉下去，目标端io、cpu等资源充足，想咨询mongoshake是否有限制目标端delete速度的行为呢或者是否有相关参数可以调整？另外对延迟曲线的直线掉0不太理解

目标端Profile 日志如下：
COMMAND $cmd command: delete locks:{ Global: { acquireCount: { r: 1002, w: 1002 } }, Database: { acquireCount: { w: 1002 } }, Collection: { acquireCount: { w: 1002 } } }

**Comment by zhangst** [comment]
1. 请使用最新的2.8.1试一下
2. 监控曲线具体是指什么
3. 新版本如果没有改善，参考 https://github.com/alibaba/MongoShake/issues/700 补充下资料

**Comment by Lili123456** [comment]
1. 2.8.1 在这一块有什么具体的改进呢？ 想了解下，升级后好有关注点
2. curl -s http://127.0.0.1:9100/repl | python -m json.tool  // 取下面两个time的差值
  "now": { // 当前的时间
        "time": "2020-04-03 18:32:28",
        "unix": 1585909948
    },
    "lsn_ack": { // 已经成功写入目的端的checkpoint位点（已经成功写入，但是不一定持久化）
        "time": "1970-01-01 08:00:00",
        "ts": "0",
        "unix": 0
    }
<img width="420" alt="image" src="https://user-images.githubusercontent.com/19341689/205193844-ae7a934c-0cae-4b79-9fbe-51f16be240c3.png">

**Comment by Lili123456** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/19341689/205193755-16388dd9-9dbd-48dd-a445-74473b2c2b76.png">

**Comment by zhangst** [comment]
修改点可以看ChangeLog，里面都有
