### ISSUE TITLE
如何通过公网端口映射连接mongoDB的副本集?

### ISSUE THREAD

**Issue by secondwifelikemytalent** [alibaba/MongoShake#780]
# the target is sharding, this should be the mongos address.
# direct模式用于直接写入MongoDB，其余模式用于一些分析，或者远距离传输场景，
# 注意，如果是非direct模式，需要通过receiver进行解析，具体参考FAQ文档。
# 此处配置通道的地址，格式与mongo_urls对齐。
tunnel.address = mongodb://root:******@110.***.***.***:28017,110.***.***.***:28018,110.***.***.***:28016/admin?replicaSet=r***
# the message format in the tunnel, used when tunnel is kafka.
# "raw": batched raw data format which has good performance but encoded so that users
# should parse it by receiver.
# "json": single oplog format by json.

我通过路由器的NAT分别映射了三台内网服务器的地址和端口到公网IP上，但是不能访问一直报错，如果改成单独的一台就可以连接 。 应该怎么配置目标地址？是不支持这样吗？还是需要别的特殊配置？用的mongoshake_v2.8.2，mongo的版本是5.0.6

连接总是报错:
Conf.Options check failed: connect target tunnel mongodb[mongodb://root:***@110.***.***.***:28017,110.***.***.***:28018,110.***.***.***:28016/admin?replicaSet=***] failed[ping to mongodb://root:***@110.***.***.***:28017,110.***.***.***:28018,110.***.***.***:28016/admin?replicaSet=*** failed: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: 192.168.2.177:27017, Type: Unknown }, { Addr: 192.168.2.178:27017, Type: Unknown }, { Addr: 192.168.2.26:27017, Type: Unknown }, ] }
If Mongo Server is standalone(single node) Or conn address is different with mongo server address try atandalone mode by mongodb://ip:port/admin?connect=direct

**Comment by zhangst** [comment]
5.0版本的mongodb有自己独有的服务发现机制，因为你的公网地址在mongoDB侧并没有配置，所以只能使用单节点的直连方式。也就是?connect=direct方式，不能使用? replicaSet服务发现的方式。
