### ISSUE TITLE
v2.8.2 解析ckpt_default报错

### ISSUE THREAD

**Issue by jsbxyyx** [alibaba/MongoShake#781]
[2022/12/30 19:27:41 CST] [EROR] rs0 Reload ckpt find context fail. error decoding key ckpt: cannot decode timestamp into an int
eger type

1. mongoshake升级前版本：2.6.5，升级后的版本2.8.2

配置：
conf.version = 10
id = mongoshake
master_quorum = false
full_sync.http_port = 9101
incr_sync.http_port = 9100
system_profile_port = 9201
log.level = info
log.dir =
log.file = collector.log
log.flush = false
sync_mode = incr
mongo_urls = 
mongo_cs_url =
mongo_s_url = 
mongo_ssl_root_ca_file = 
tunnel = kafka
tunnel.address = mongodbTopic@kafka:9092
tunnel.message = json
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =
mongo_connect_mode = secondaryPreferred
filter.namespace.black =
filter.namespace.white = 
filter.pass.special.db =
filter.ddl_enable = false
filter.oplog.gids = false
checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.storage.url.mongo_ssl_root_ca_file = 
checkpoint.start_position = 1970-01-01T00:00:00Z
transform.namespace =
full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.fetch_batch_size = 8192
full_sync.reader.parallel_thread = 1
full_sync.reader.parallel_index = _id
full_sync.collection_exist_drop = true
full_sync.create_index = none
full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false
full_sync.executor.majority_enable = false
incr_sync.mongo_fetch_method = oplog
incr_sync.change_stream.watch_full_document = false
incr_sync.oplog.gids =
incr_sync.shard_key = collection
incr_sync.shard_by_object_id_whitelist = 
incr_sync.worker = 8
incr_sync.tunnel.write_thread = 8
incr_sync.target_delay = 0
incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256
incr_sync.reader.fetch_batch_size = 8192
incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false
special.source.db.flag =

新版本的数据 ckpt_default：
{
    "_id" : ObjectId("63aecdb2d0f0066272c90c92"),
    "name" : "rs0",
    "ckpt" : NumberLong(7182904607205490689),
    "version" : 2,
    "fetch_method" : "oplog",
    "oplog_disk_queue" : "",
    "oplog_disk_queue_apply_finish_ts" : NumberLong(1672399255)
}

老版本格式 ckpt_default：
{
    "_id" : ObjectId("61658626dfc43eff9d09bc9a"),
    "name" : "rs0",
    "ckpt" : Timestamp(1661972437, 17),
    "version" : 2,
    "fetch_method" : "oplog",
    "oplog_disk_queue" : "",
    "oplog_disk_queue_apply_finish_ts" : Timestamp(1672399255, 1)
}

**Comment by zhangst** [comment]
新版本因为替换了SDK，存储的ckpt格式也变化了。版本升级后，请手工更新下数据库，转换方式如下：
package main

import "fmt"

func main() {
   fmt.Println(int64(1661972437)<<32 + int64(17))
}

可以在线运行：https://c.runoob.com/compile/21/

**Comment by jsbxyyx** [comment]
[2023/01/03 18:10:57 CST] [INFO] rs0 ts.Oldest[7182900930713485313] >= ckptRemote.Timestamp[7138117263768420369], need full sync
[2023/01/03 18:10:57 CST] [CRIT] run replication failed: select sync mode failed: start time illegal, can't run incr sync

无法启动

**Comment by zhangst** [comment]
这个表示shake中存储的位点在源mongoDB中已经失效了，需要重新做一次全量同步
