### ISSUE TITLE
> Hi,

### ISSUE THREAD

**Issue by sannithisubbarao** [alibaba/MongoShake#782]
> Hi,
> 
> We are able to migrate mongo 4.4 version and however we are having issues with 5.0 using mongoshake. we do not have any logs generated when we start migrating 5.0.

which version do you use, please try ver2.8.1.

we tried re-deploy with ver 2.8.2 and still having issues

_Originally posted by @zhangst in https://github.com/alibaba/MongoShake/issues/777#issuecomment-1352398707_

**Comment by zhangst** [comment]
Hi sannithisubbarao,

the problem is not solved yet. Will solve it in next version. 
please upload error logs which 2.8.2 print.

**Comment by sannithisubbarao** [comment]
Stopping migration process with  "exit status 251"

**Comment by zhangst** [comment]
please try ver 2.8.3 which fix this bug
