### ISSUE TITLE
What is stored in mongo collection as ckpt

### ISSUE THREAD

**Issue by harishsambasivam** [alibaba/MongoShake#785]
Im trying to understand what is stored under the ckpt collection as ckpt field. Is it a time stamp (but 19 digits?) or is it some sort of hash?

When switching the dest as source and source as dest, can we use same collection for ckpt if that's time based!

**Comment by zhangst** [comment]
Hi 
```
Im trying to understand what is stored under the ckpt collection as ckpt field. Is it a time stamp (but 19 digits?) or is it some sort of hash?
```
It's MognoDB type Timestamp, https://www.mongodb.com/docs/manual/reference/bson-types/

```
When switching the dest as source and source as dest, can we use same collection for ckpt if that's time based!
```
Not available for reuse, should use a new collection.

**Comment by harishsambasivam** [comment]
Thanks @zhangst
