### ISSUE TITLE
Mongoshake direct tunnel for production

### ISSUE THREAD

**Issue by harishsambasivam** [alibaba/MongoShake#786]
We are trying to use the direct tunnel to sync data between two clusters for our production environment. 

1. Do you think we could use / rely on direct tunnel for production?
2. Will mongoshake handle crashes and provide data integrity when used with hypervisor? 
3. Data integrity is our priority
4. how to identify replication lags and scale up the workers

**Comment by zhangst** [comment]
MongoShake is designed for one-time data migration, not for long-term data synchronization.
In incr sync phase, shake will record ckpt which will guaranteed resuming, not lost data.
For performance tuning, you can refer to https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E4%BD%95%E7%9B%91%E6%8E%A7%E5%92%8C%E7%AE%A1%E7%90%86MongoShake%E7%9A%84%E8%BF%90%E8%A1%8C%E7%8A%B6%E6%80%81%EF%BC%9F
