### ISSUE TITLE
副本集同步到副本集时报CheckpointOperation updated is not suitable. lowest [0]. current [7162100966739693991[1667556578, 20903]]. inputTs [0]. reason : smallest candidates is zero

### ISSUE THREAD

**Issue by gyb-uinnova** [alibaba/MongoShake#788]
mongoshake同步数据时：
[2023/02/11 17:30:09 CST] [WARN] CheckpointOperation updated is not suitable. lowest [0]. current [7162100966739693991[1667556578, 20903]]. inputTs [0]. reason : smallest candidates is zero

mongoshake库中：
> db.ckpt_default.find().pretty()
{
        "_id" : ObjectId("63e74688b247d1597b0bff57"),
        "name" : "smv",
        "ckpt" : NumberLong("7162100966739693991"),
        "fetch_method" : "oplog",
        "oplog_disk_queue" : "",
        "oplog_disk_queue_apply_finish_ts" : NumberLong(0),
        "version" : 2
}

**Comment by zhangst** [comment]
https://github.com/alibaba/MongoShake/issues/700
参考连接提供下必须内容。什么情况下使用报这个错误，

**Comment by gyb-uinnova** [comment]
mongoshake：2.8.2
mongodb：4.2.17

**Comment by gyb-uinnova** [comment]
conf.version = 10
id = mongoshake
master_quorum = false
full_sync.http_port = 9101
incr_sync.http_port = 9100
system_profile_port = 10300
log.level = info
log.dir =
log.file = collector.log
log.flush = false
sync_mode = incr
mongo_urls = mongodb://USER:PASS@IP1:28017,IP2:28017,IP3:28017

mongo_cs_url =
mongo_s_url =

mongo_ssl_root_ca_file =
tunnel = direct

tunnel.address = mongodb://IP1:28017,IP2:28017,IP3:28017
tunnel.message = raw
tunnel.kafka.partition_number = 1
tunnel.json.format =
tunnel.mongo_ssl_root_ca_file =

mongo_connect_mode = secondaryPreferred
filter.namespace.black = admin
filter.namespace.white =
filter.pass.special.db =
filter.ddl_enable = true
filter.oplog.gids = false

checkpoint.storage.url =
checkpoint.storage.db = mongoshake
checkpoint.storage.collection = ckpt_default
checkpoint.storage.url.mongo_ssl_root_ca_file =
checkpoint.start_position = 1970-01-01T00:00:00Z

transform.namespace =

full_sync.reader.collection_parallel = 6
full_sync.reader.write_document_parallel = 8
full_sync.reader.document_batch_size = 128
full_sync.reader.fetch_batch_size = 8192
full_sync.reader.parallel_thread = 1
full_sync.reader.parallel_index = _id

full_sync.collection_exist_drop = true

full_sync.create_index = none

full_sync.executor.insert_on_dup_update = false
full_sync.executor.filter.orphan_document = false

full_sync.executor.majority_enable = false

incr_sync.mongo_fetch_method = oplog
incr_sync.change_stream.watch_full_document = false

incr_sync.oplog.gids =
incr_sync.shard_key = collection
incr_sync.shard_by_object_id_whitelist =
incr_sync.worker = 8
incr_sync.tunnel.write_thread = 8
incr_sync.target_delay = 0

incr_sync.worker.batch_queue_size = 64
incr_sync.adaptive.batching_max_size = 1024
incr_sync.fetcher.buffer_capacity = 256
incr_sync.reader.fetch_batch_size = 8192

incr_sync.executor.upsert = false
incr_sync.executor.insert_on_dup_update = false
incr_sync.conflict_write_to = none
incr_sync.executor.majority_enable = false

special.source.db.flag =_

**Comment by gyb-uinnova** [comment]
> use mongoshake
switched to db mongoshake
> db.ckpt_default.find().pretty()
{
        "_id" : ObjectId("63e74688b247d1597b0bff57"),
        "name" : "smv",
        "ckpt" : NumberLong("7199457136286367745"),
        "fetch_method" : "oplog",
        "oplog_disk_queue" : "",
        "oplog_disk_queue_apply_finish_ts" : NumberLong(0),
        "version" : 2
}

**Comment by zhangst** [comment]
如果shake进程刚重启后，还没有新的增量产生，报这个错误是正常的。

**Comment by gyb-uinnova** [comment]
收到 谢谢



优锘科技  郭瑜波
***@***.***
Tel： 15001262782
Add：北京市朝阳区酒仙桥路10号恒通国际商务园B23
 
发件人： zhangst
发送时间： 2023-03-10 15:01
收件人： alibaba/MongoShake
抄送： guoyb; Author
主题： Re: [alibaba/MongoShake] 副本集同步到副本集时报CheckpointOperation updated is not suitable. lowest [0]. current [7162100966739693991[1667556578, 20903]]. inputTs [0]. reason : smallest candidates is zero (Issue #788)
如果shake进程刚重启后，还没有新的增量产生，报这个错误是正常的。
