### ISSUE TITLE
关于 “全量同步是否会同步索引中-none：表示不创建所以。”的错误问题。

### ISSUE THREAD

**Issue by xiaozhimengmengda** [alibaba/MongoShake#791]
“Q: 全量同步是否会同步索引？
A: 2.1以下版本，目前会同步索引，先是全量同步，全量同步完毕后会建前台索引；2.4版本开始提供索引配置项full_sync.create_index：

none：表示不创建所以。
background：全量同步前创建后台索引。
foreground: 全量同步完毕后创建前台索引“
这段里面 “none：表示不创建所以” 是表示不创建索引吧？
麻烦修正下

**Comment by zhangst** [comment]
已订正，感谢反馈。
