### ISSUE TITLE
lsn and lsn_ack both are "1970-01-01 00:00:00" while in incr stage

### ISSUE THREAD

**Issue by coltisa** [alibaba/MongoShake#800]
到达增量同步之后，LSN和LSN_ACK始终是“1970-01-01 00:00:00“，日志中出现”CheckpointOperation updated is not suitable.“，源集群的OPLOG都是正常的

1.MongoShake的版本：2.8.2
2.源和目的MongoDB的版本：源和目的都是4.0.27
3.脱敏后的配置文件和日志文件以及其它信息
增量同步的信息：
{"who":"mongoshake","tag":"improve-2.8.2,78d0e913a561b651af2b6310183a8eb881555782,release,go1.15.10,2022-12-15_23:03:06","replset":"default-0","logs_get":750,"logs_repl":0,"logs_success":0,"tps":0,"lsn":{"unix":0,"time":"1970-01-01 00:00:00","ts":"0"},"lsn_ack":{"unix":0,"time":"1970-01-01 00:00:00","ts":"0"},"lsn_ckpt":{"unix":1677818293,"time":"2023-03-03 04:38:13","ts":"7206174697065545729"},"now":{"unix":1677823155,"time":"2023-03-03 05:59:15"},"log_size_avg":"110.00B","log_size_max":"271.00B"}

主节点的OPLOG信息：
myReplicaSet:PRIMARY> rs.printReplicationInfo()
configured oplog size:   102400MB
log length start to end: 11750581secs (3264.05hrs)
oplog first event time:  Tue Oct 18 2022 06:37:45 GMT+0000 (UTC)
oplog last event time:   Fri Mar 03 2023 06:40:46 GMT+0000 (UTC)
now:                     Fri Mar 03 2023 06:40:48 GMT+0000 (UTC)

备节点的OPLOG信息：
myReplicaSet:SECONDARY> rs.printReplicationInfo()
configured oplog size:   102400MB
log length start to end: 11750643secs (3264.07hrs)
oplog first event time:  Tue Oct 18 2022 06:37:30 GMT+0000 (UTC)
oplog last event time:   Fri Mar 03 2023 06:41:33 GMT+0000 (UTC)
now:                     Fri Mar 03 2023 06:41:41 GMT+0000 (UTC)

**Comment by zhangst** [comment]
配置文件和日志请发下脱密后的文件。另外lsn_ckpt在增长不？实际的数据复制有发现问题吗?

**Comment by coltisa** [comment]
> 配置文件和日志请发下脱密后的文件。另外lsn_ckpt在增长不？实际的数据复制有发现问题吗?

我刚才手动INSERT数据之后lsn_ckpt更新了，然后lsn和lsn_ack也更新了，所以可能是因为我这套MongoDB没有数据更新的缘故是吧。因为这个库开启Mongo Shake之后没有关心业务那边是否有数据写入。如果没有数据写入可能造成这个问题吗

**Comment by zhangst** [comment]
> 

是的，没有数据写入ckpt是不更新的
