### ISSUE TITLE
增量同步卡主问题

### ISSUE THREAD

**Issue by mcat1997** [alibaba/MongoShake#802]
1. mongoShake: 2.8.2
2. 源mongod副本集 3.6
3. 目标mongod副本集 5.0
4. 脱密后的配置文件
[mongo.txt](https://github.com/alibaba/MongoShake/files/10893604/mongo.txt)
5. 监控
<img width="1752" alt="image" src="https://user-images.githubusercontent.com/16068202/223000124-38375233-1bbe-4207-8db0-6dbc430882d6.png">
6. 部分日志
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/16068202/223000186-e97c48df-4f5d-4bc4-95ca-c299a2f8d3ea.png">

7. 在进行完全量同步之后，增量同步能立马接上，但是在运行一天之后，第二天9点检查checkpoint在凌晨4点。重试几天都能复现这个现象。

**Comment by zhangst** [comment]
增量复制并没有停止，而是变慢了，shake的复制追不上源节点增量产生的量，时间就会变晚。
请看下增联同步过程中一共有几张表在产生增量，表是否有唯一索引。

incr_sync.shard_key = collection
当前使用的是collection分发的方式，一个表的增量数据都分发到一个增量worker线程来工作。

请改为auto试一下，如果还不行，提供下完整的日志（脱敏后）和内部监控数据（参考下面连接）
https://github.com/alibaba/MongoShake/wiki/%E5%A6%82%E4%BD%95%E7%9B%91%E6%8E%A7%E5%92%8C%E7%AE%A1%E7%90%86MongoShake%E7%9A%84%E8%BF%90%E8%A1%8C%E7%8A%B6%E6%80%81%EF%BC%9F
