### ISSUE TITLE
使用分片的mongodb同步到kafka报错

### ISSUE THREAD

**Issue by jiyis** [alibaba/MongoShake#804]
问题：从mongodb同步消息到kafka，按照文档中 [从只暴露mongos地址的MongoDB分片集群版同步到MongoDB分片集群版](https://github.com/alibaba/MongoShake/wiki/%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8%EF%BC%8C%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE%EF%BC%9F#5-%E4%BB%8Emongodb%E9%9B%86%E7%BE%A4%E7%89%88%E5%90%8C%E6%AD%A5%E5%88%B0mongodb%E5%89%AF%E6%9C%AC%E9%9B%86)的方法启动报错。

报错信息：`[2023/03/10 22:39:29 CST] [CRIT] run replication failed: replia[mongos] not exists on startTsMap[map[]]`

mongoShake版本：最新的develop分支或者v2.8.2
mongodb版本:4.2 分片集群版

配置文件：

```
sync_mode = incr
mongo_urls = 
mongo_cs_url = 
mongo_s_url = mongodb://name:password@1.1.1.1:20000,1.1.1.1:20001,1.1.1.1:20002

mongo_ssl_root_ca_file = 
# 通道模式。
tunnel = kafka
tunnel.address = mongoshake@1.1.1.2:9092
tunnel.message = json

# fetch method:
incr_sync.mongo_fetch_method = change_stream
```
看了下源码跟`oplogStartPosition`的值有关，如果只配置了 `mongos`的地址，`startTsMap`的值就是nil，执行到`startOplogReplication`一定报错。把下面代码跳过发现也可以正常运行。
```
//  MongoShake/collector/coordinator/incr.go:23
	for i, src := range coordinator.RealSourceIncrSync {
		var syncerTs interface{}
		if val, ok := oplogStartPosition.(int64); ok && val == 0 {
                         // 重点在这里，我的mongodb是分片集群的，但是又拿不到config地址，所以只能使用mongos方式，但是追踪代码发现只有mongos的地址时候，startTsMap的值是nil
			if v, ok := startTsMap[src.ReplicaName]; !ok {
				return fmt.Errorf("replia[%v] not exists on startTsMap[%v]", src.ReplicaName, startTsMap)
			} else {
				syncerTs = v
			}
		} else {
			syncerTs = oplogStartPosition
		}
            ..............
        }
```

想请教下这段代码判断逻辑目的是什么，另外看起来如果想用mongos的连接方式从mongodb同步数据到kafka，还必须设置拉取方式为stream才可以，默认的oplog也会报错。 `incr_sync.mongo_fetch_method = change_stream`

**Comment by zhangst** [comment]
mongos拉取增量只能通过changestream的方式。这里的处理有点问题，当使用通过mongos拉取增量时，不应该做这个判断了

**Comment by zhangst** [comment]
develop中代码已提交，下个版本中解决
