### ISSUE TITLE
虽然但是，还是想问一下多活双向同步问题

### ISSUE THREAD

**Issue by YeLuoSC** [alibaba/MongoShake#805]
你好，我在本地搭建环境测试，使用2个mongoshake最新版本，mongodb4.2版本的2个复制集进行测试，本来我是打算在kafka用consumer解决环形复制问题，本着测试的心态，想凑热闹试一下环形复制的场面，结果没想到没触发，这个和文档描述不一致，具体现象是：
1.新增，出现a复制集到b复制集，再b到a，此时报错重复主键，虽然不优雅，但是没问题；
2.删除，出现环形复制时，a中的文档已经被删除，所以什么也删除不了，正好终结；
3.更新，更奇怪，我尝试使用各种条件，包括id主键，其他查询字段进行更新，a到b正常，b到a没有任何异常～
所以我想问，是后来版本有修改吗？

我们要做双活，开源版本mongodb，自己用kfk做处理还是就直接用direct模式合适呢？

**Comment by zhangst** [comment]
版本没有修改，上面举得的这些例子其实已经形成了环形复制，A复制到B，B在复制到A，只是MongoDB自身的约束机制，让B复制到A的动作没有成功执行。
也有一些复杂的场景要考虑，比如在更新的场景中，有一条_id=1,a=1的记录，在A实例上连续执行update a=2，update a=3，这时就会有一个条件竞争，因为a=2这条增量oplog会通过环形复制回来（A->B->A），某一个时间内a的值是不正确的，这样其实是有一些问题的。
如果业务自己实现，可以通过业务上增加默认的字段，通过这个字段来做增量oplog的过滤。
