### ISSUE TITLE
get by checkpoint info from db or api failed

### ISSUE THREAD

**Issue by regin0-cpu** [alibaba/MongoShake#806]
使用MongoShake 2.8.2 全量+增量同步时遇到一个问题，完整的报错信息如下：

**Comment by regin0-cpu** [comment]
select sync mode failed: get mongod[rs] checkpoint failed: get by checkpoint info from db or api failed, please see err log
[18:24:49 CST 2023/03/14] [CRIT] (main.startup:145) run replication failed: select sync mode failed: get mongod[rs] checkpoint failed: get by checkpoint info from db or api failed, please see err log

**Comment by regin0-cpu** [comment]
麻烦帮忙看看，这个是什么原因造成的，谢谢！

**Comment by zhangst** [comment]
参考 https://github.com/alibaba/MongoShake/issues/700  提供下必要信息

**Comment by regin0-cpu** [comment]
> 参考#700 提供下必要信息

谢谢，我找到问题的所在了，已经得到了解决！

**Comment by lddlww** [comment]
请问是什么问题，怎么解决的？
