### ISSUE TITLE
关于同步合库合表，想问。。。

### ISSUE THREAD

**Issue by yuemingyuan1412** [alibaba/MongoShake#807]
你好，我们现在的mongo源业务表是分库分表的，我能通过direct模式（默写配置），进行把这些表合到一个大表么？感谢解答

**Comment by zhangst** [comment]
可以尝试下transform.namespace =功能。如果字段内容有冲突，则需要手工解决了

**Comment by yuemingyuan1412** [comment]
> 可以尝试下transform.namespace =功能。如果字段内容有冲突，则需要手工解决了

经过测试只是库合并了,但是表级别还是没有合并,配置如下(我想把所有的库表数据都合并到一张大表(hebing库hebing表)下)
# transform from source db or collection namespace to dest db or collection namespace.
# at most one of these two parameters can be given.
# transform: fromDbName1.fromCollectionName1:toDbName1.toCollectionName1;fromDbName2:toDbName2
# 转换命名空间，比如a.b同步后变成c.d，谨慎建议开启，比较耗性能。
transform.namespace = *.*:hebing.hebing

结果有意思的是源库的test表,在目标hebing库下的呈现类型表名是 hebing.test
<img width="187" alt="image" src="https://user-images.githubusercontent.com/32667945/226563651-77e864d3-6399-46f6-a9b5-213b5fcd41f6.png">
现在是还不支持表级的合并吗?版本:mongo-shake-v2.8.2

**Comment by yuemingyuan1412** [comment]
> 可以尝试下transform.namespace =功能。如果字段内容有冲突，则需要手工解决了

经过测试只是库合并了,但是表级别还是没有合并,配置如下(我想把所有的库表数据都合并到一张大表(hebing库hebing表)下)

转换命名空间，比如a.b同步后变成c.d，谨慎建议开启，比较耗性能。
transform.namespace = *.*:hebing.hebing

结果有意思的是源库的test表,在目标hebing库下的呈现类型表名是 hebing.test
<img width="168" alt="image" src="https://user-images.githubusercontent.com/32667945/226566294-d3eca83f-3891-4473-92be-52cbc6b7eec2.png">

现在是还不支持表级的合并吗?版本:mongo-shake-v2.8.2

**Comment by yuemingyuan1412** [comment]
> > 可以尝试下transform.namespace =功能。如果字段内容有冲突，则需要手工解决了
> 
> 经过测试只是库合并了,但是表级别还是没有合并,配置如下(我想把所有的库表数据都合并到一张大表(hebing库hebing表)下)
> 
> 转换命名空间，比如a.b同步后变成c.d，谨慎建议开启，比较耗性能。 transform.namespace = _._:hebing.hebing
> 
> 结果有意思的是源库的test表,在目标hebing库下的呈现类型表名是 hebing.test <img alt="image" width="168" src="https://user-images.githubusercontent.com/32667945/226566294-d3eca83f-3891-4473-92be-52cbc6b7eec2.png">
> 
> 现在是还不支持表级的合并吗?版本:mongo-shake-v2.8.2

更正transform.namespace = *.*:hebing.hebing

**Comment by yuemingyuan1412** [comment]
经过测试只是库合并了,但是表级别还是没有合并,配置如下(我想把所有的库表数据都合并到一张大表(hebing库hebing表)下)
<img width="645" alt="image" src="https://user-images.githubusercontent.com/32667945/226567054-c60c339a-d09e-4823-95b0-910297ad8538.png">


结果有意思的是源库的test表,在目标hebing库下的呈现类型表名是 hebing.test
<img width="188" alt="image" src="https://user-images.githubusercontent.com/32667945/226566973-3182a862-4a99-4476-a04f-4f55fe9a1e5f.png">


现在是还不支持表级的合并吗?版本:mongo-shake-v2.8.2


> 可以尝试下transform.namespace =功能。如果字段内容有冲突，则需要手工解决了

**Comment by zhangst** [comment]
不支持*类似的转义符。要每个表名的对应关系都写

**Comment by yuemingyuan1412** [comment]
> 不支持*类似的转义符。要每个表名的对应关系都写

我的库表是根据业务不断增加的,不是固定的,这种业务的话,有解吗?

**Comment by zhangst** [comment]
这种不支持
