### ISSUE TITLE
关于mongoshake同步kafka,第一次全量拉取问题

### ISSUE THREAD

**Issue by yuemingyuan1412** [alibaba/MongoShake#810]
(mongoshake版本2.8.2)你好,我想确认个问题,在第一次启动mongoshake,kafka模式下,kafka支持全量+增量模式吗?

**Comment by zhangst** [comment]
同步到kafka支持增量，不支持全量

**Comment by yuemingyuan1412** [comment]
> 同步到kafka支持增量，不支持全量

但就我本地测试来看，第一次启动把库的全量都一次性推到kafka了。这是什么原理

**Comment by zhangst** [comment]
> 

shake的配置文件脱密后贴一下，我本地试一试

**Comment by yuemingyuan1412** [comment]
> > 
> 
> shake的配置文件脱密后贴一下，我本地试一试

sync_mode = incr
mongo_urls = mongodb://localhost:28020
tunnel = kafka
tunnel.address = syncpool@***:9092
tunnel.message = json
其他都是默认

**Comment by zhangst** [comment]
sync_mode = incr
mode用的incr，你是怎么判断把全量也同步了的？

**Comment by yuemingyuan1412** [comment]
> sync_mode = incr mode用的incr，你是怎么判断把全量也同步了的？

我推测，因为是首次启动，源库还没有存断点续传信息，所以从最初oplog开始推送kafka了

**Comment by zhangst** [comment]
没有断点信息，也没有指定开始时间时，是从最初的oplog开始同步的。但最初的oplog也属于增量信息，不是全量信息的。

**Comment by yuemingyuan1412** [comment]
> 没有断点信息，也没有指定开始时间时，是从最初的oplog开始同步的。但最初的oplog也属于增量信息，不是全量信息的。

了解，kafka支持账号密码配置吗？配置参数是。。请教一下

**Comment by zhangst** [comment]
不支持
