### ISSUE TITLE
实时同步数据遇到错误,同步模式为增量

### ISSUE THREAD

**Issue by xiang-coco** [alibaba/MongoShake#813]
1.mongoshake版本:mongo-shake-v2.8.2
2.源端MongoDB server version: 4.2.17
目标端 :MongoDB server version: 4.2.17

mongoshake 日志中报错如下：
 [CRIT] Replayer-0, executor-0, oplog for namespace[admin.$cmd] op[c] failed. error type[*mgo.QueryError] 
error[not authorized on admin to execute command { applyOps: [ { op: "d", ns: "ouser.sequenceAlloc", o: { _id: ObjectId('6440b3cd197370ef20f5c4b9') } } ], $db: "admin" }], logs number[1], firstLog: {"ts":7225076895379881985,"v":2,"op":"c","ns":"admin.$cmd","o":[{"Name":"applyOps","Value":[[{"Name":"op","Value":"d"},{"Name":"ns","Value":"ouser.sequenceAlloc"},{"Name":"o","Value":[{"Name":"_id","Value":"6440b3cd197370ef20f5c4b9"}]}]]}],"o2":null,"lsid":{"id":{"Kind":4,"Data":"CGErSx42Rimh2knq2RFPtQ=="},"uid":"RbbEVjpOI3uyc50x3P+rzrwiFoHxKhSauWjk1mNngq4="},"txnNumber":195}
[2023/04/23 11:08:25 CST] [INFO] worker offset [7225076255429754881] use lowest 7225076255429754881[1682219155, 1]

**Comment by xiang-coco** [comment]
1.mongoshake版本:mongo-shake-v2.8.2 
2.源端MongoDB server version: 4.2.17
目标端 :MongoDB server version: 4.2.17

**Comment by zhangst** [comment]
{ applyOps: [ { op: "d", ns: "ouser.sequenceAlloc", o: { _id: ObjectId('6440b3cd197370ef20f5c4b9') } } ]
这一个oplog是在删除admin库中表ouser.sequenceAlloc中的 _id: ObjectId('6440b3cd197370ef20f5c4b9')的记录。问题是shake中配置的账号没有删除的权限。

**Comment by xiang-coco** [comment]
> { applyOps: [ { op: "d", ns: "ouser.sequenceAlloc", o: { _id: ObjectId('6440b3cd197370ef20f5c4b9') } } ] 这一个oplog是在删除admin库中表ouser.sequenceAlloc中的 _id: ObjectId('6440b3cd197370ef20f5c4b9')的记录。问题是shake中配置的账号没有删除的权限。

请问这个应该是源端账户的权限问题，还是目标端的账号权限问题吖

**Comment by zhangst** [comment]
目标端

**Comment by xiang-coco** [comment]
> 目标端

给目标端的账号授权后问题解决了，感谢感谢~~

use admin;
db.createRole(
   {
     role: "interalUseOnlyOplogRestore",
     privileges: [
       { resource: { anyResource: true }, actions: [ "anyAction" ] }
     ],
     roles: []
   }
);
