### ISSUE TITLE
能否支持arm架构

### ISSUE THREAD

**Issue by bearyue** [alibaba/MongoShake#835]
可否编译出支持arm架构的版本？

**Comment by bearyue** [comment]
再arm平台编译成功了，但是运行出现以下提示：
./collector.linux: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./collector.linux)

./collector.linux: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./collector.linux)

**Comment by bearyue** [comment]
解决了，在打包命令上加上CGO_ENABLED=0 ，可以避免上述报错，测试可以正常运行。

**Comment by HZ-zhoujun** [comment]
> 再arm平台编译成功了，但是运行出现以下提示： ./collector.linux: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./collector.linux)
> 
> ./collector.linux: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./collector.linux)

arm环境下编码是否有遇到该问题
mongoshake/collector/docsyncer
# vendor/github.com/DataDog/zstd
/bin/sh: warning: shell level (1000) too high, resetting to 1
/bin/sh: warning: shell level (1000) too high, resetting to 1
/bin/sh: warning: shell level (1000) too high, resetting to 1
/bin/sh: warning: shell level (1000) too high, resetting to 1
/bin/sh: warning: shell level (1000) too high, resetting to 1
/bin/sh: warning: shell level (1000) too high, resetting to 1
/bin/sh: warning: shell level (1000) too high, resetting to 1
/bin/sh: warning: shell level (1000) too high, resetting to 1
/usr/bin/gcc-arm: xmalloc: cannot allocate 27 bytes
